### PR TITLE
2.0 demo and doc updates

### LINKED ISSUE #677: Revise code examples and documentation
- Goal is to run DX test successfully with just the API docs and code examples.
- See also #587

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #677

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/762)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 21 of 21 files at r1.
Review status: 19 of 21 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIWHlA4ZuxZFZyt4FC:-KeIWHlA4ZuxZFZyt4FD:b-4nfehn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/vaadin-grid.html#L13)):*
> ```HTML
> ### Quick Start
> 
>  - Use the <a href="#vaadin-grid-column">vaadin-grid-column</a> element to configure the grid columns.
> ```

This one and the other element and prop references could have been highlighted more, like: ```<a href="...">`<vaadin-grid-column>`</a>```

---

*[vaadin-grid.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIXLBcwivr1J4GxAE-:-KeIXLBcwivr1J4GxAE0:bucp7a5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/vaadin-grid.html#L15)):*
> ```HTML
>  - Use the <a href="#vaadin-grid-column">vaadin-grid-column</a> element to configure the grid columns.
> 
>  - Then assign an array to the <a href="#vaadin-grid:property-items">items</a> property to visualize your data.
> ```

Maybe also mention `dataProvider` here or somewhere below with a link to live demos?

---

*[demo/columns.html, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIUQ4YyQnQX-LwM8q7:-KeIUQ4YyQnQX-LwM8q8:b-wk387b) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/demo/columns.html#L46)):*
> ```HTML
>             /* Define explicit bounds for images */
>             iron-image {
>               --iron-image-height: 30px;
> ```

This makes me wonder what these CSS properties do.

On the other hand, `<iron-image width="30" height="30" sizing="cover" src="..."></iron-image>` is immediately obvious, it looks like a regular `` tag.

Maybe use `width` and `height` attributes in the template? We mostly care about the element size here, not the image size inside. Not only easier to set this with attributes, but also would look more familiar for the readers.

---

*[demo/data.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIXZYNPafAMZoJjCg2:-KeIXZYNPafAMZoJjCg3:byjpyvf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/demo/data.html#L242)):*
> ```HTML
>                 this.dataProvider = function(opts, callback) {
>                   var xhttp = new XMLHttpRequest();
>                   xhttp.onreadystatechange = function() {
> ```

Maybe use `xhr.onload` here and everywhere else in the grid docs? It should be supported in every relevant browser already.

---

*[demo/index.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIXnJEipnQqPhf_I83:-KeIXnJFXHZo7nXRIq86:b2rm7v0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/demo/index.html#L84)):*
> ```HTML
>           }
>         </style>
>         <iron-ajax auto url="http://demo.vaadin.com/demo-data/1.0/people?count=200" handle-as="json" last-response={{users}}></iron-ajax>
> ```

Missing quotes arond `{{users}}`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762)*

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762)*

**Comment by tomivirkki** [comment]
Review status: 16 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIWHlA4ZuxZFZyt4FC:-KeJXK08yKykj9ZQy0I3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/vaadin-grid.html#L13)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This one and the other element and prop references could have been highlighted more, like: ```<a href="...">`<vaadin-grid-column>`</a>```
</blockquote></details>

Done.

---

*[vaadin-grid.html, line 15 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIXLBcwivr1J4GxAE-:-KeJTIdmnoRA17mtjHkT:bdes1cu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/vaadin-grid.html#L15)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe also mention `dataProvider` here or somewhere below with a link to live demos?
</blockquote></details>

Since this is a "quick start" guide, `items` should be enough. `dataProvider` is an advanced topic.

---

*[demo/columns.html, line 46 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIUQ4YyQnQX-LwM8q7:-KeJV8BcsjMseze0fzVA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/demo/columns.html#L46)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This makes me wonder what these CSS properties do.

On the other hand, `<iron-image width="30" height="30" sizing="cover" src="..."></iron-image>` is immediately obvious, it looks like a regular `` tag.

Maybe use `width` and `height` attributes in the template? We mostly care about the element size here, not the image size inside. Not only easier to set this with attributes, but also would look more familiar for the readers.
</blockquote></details>

Done.

---

*[demo/data.html, line 242 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIXZYNPafAMZoJjCg2:-KeJX3RA0xm-An4J77Kb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/demo/data.html#L242)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe use `xhr.onload` here and everywhere else in the grid docs? It should be supported in every relevant browser already.
</blockquote></details>

Done.

---

*[demo/index.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-KeIXnJEipnQqPhf_I83:-KeJXH1AHYCqmLVxZPF-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b66ecb1fd449254d2b1743b26baabd337ecc34c9/demo/index.html#L84)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Missing quotes arond `{{users}}`.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 15 of 21 files at r1, 1 of 2 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-:-KeXkNLEG6FTS5DAUAUu:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 15 of 21 files at r1, 1 of 2 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-:-KeXw-F_m2jvaaYNbyvf:b-uwkowd)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/762#-:-KeXxuxQT4HFIT9phqZk:bnfp4nl)*

**Pull request merged**
