### PR TITLE
API documentation rewrite

### PR DESCRIPTION
**Pull request by jounik**
- Added some missing documentation
- Updated some docs based on recent API changes
- Renamed and re-ordered the objects in vaadin-grid-doc.html
(alphabetical order and human-readable names)

This probably breaks something in the gwt-api-generator process (I renamed some of the object annotations, which are probably used by the generator). If that’s the case, then perhaps we need to revert parts of the changes.

So. this needs to be tested using the gwt-api-generator.

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/257)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[vaadin-grid-doc.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-5RDcwVH9z98746ve)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L7)):</sup>
Typo – "it's" should be "its".


---

<sup>**[vaadin-grid-doc.html, line 78 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-6QYx4Pxv8e-p6V3F)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L78)):</sup>
How about actually adding an example of this (like `<col flex>`)? This could be confused with omitting the whole attribute and thinking the default is 1.


---

<sup>**[vaadin-grid-doc.html, line 238 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-7X-uQfvBiMkNOMI8)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L238)):</sup>
Should probably be "declaratively"?


---

<sup>**[vaadin-grid-doc.html, line 470 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-7ysinlZeoXvRfWwi)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L470)):</sup>
Typo – "it's" should be "its".


---

<sup>**[vaadin-grid-doc.html, line 518 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-8HL-DlMAY5pO4rUy)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L518)):</sup>
Should this be "passed as a parameter **to** the row class generator"?


---

<sup>**[vaadin-grid-doc.html, line 522 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-8QMs8q6y8WV3P6HV)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L522)):</sup>
Should this be "passed as a parameter **to** column renderer"?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257)

**Comment by jounik** [comment]
Thanks @tehapo, I wasn’t really expecting anyone to really read through all the docs :smile: But another 🏅 for you that you did, thanks!

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

<sup>**[vaadin-grid-doc.html, line 106 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3JgC438ztQojUBeQWl)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L106)):</sup>
Changing this to an Object is kind of a tradeoff. setHeaderContent want's a JavaScriptObject as the parameter after this so we can't provide a String header easily. However this enables us to add an element as content.


---

<sup>**[vaadin-grid-doc.html, line 337 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3Jfb7Pk4fvH-8Rwha3)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L337)):</sup>
footer-cell and header-cell aren't defined types. Gwt api generator produces interfaces that return general JavaScriptObjects from getcell, so we lose the Cell apis.


---

<sup>**[vaadin-grid-doc.html, line 646 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3Jgt1A12MFx03Qd1Z7)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L646)):</sup>
Listing the parameters here makes the generated gwt api to also require them. Since the indexes are numbers, they translate as "double" to the apis and thus can't be omitted with null values.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257)

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

_[vaadin-grid-doc.html, line 7 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-5RDcwVH9z98746ve:-K3QC46JnGh2RAjAmMwq:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L7)):_
done

---

_[vaadin-grid-doc.html, line 78 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-6QYx4Pxv8e-p6V3F:-K3QCrrHDUZouoXBUc1F:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L78)):_
done

---

_[vaadin-grid-doc.html, line 106 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3JgC438ztQojUBeQWl:-K3QDoAbiauOgvtVlaeh:1031723591) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L106)):_
adding the jsdoc annotation @type {(object|string)} should clarify the issue

---

_[vaadin-grid-doc.html, line 238 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-7X-uQfvBiMkNOMI8:-K3QE0tXPj-FWiy1Cfv4:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L238)):_
done

---

_[vaadin-grid-doc.html, line 337 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3Jfb7Pk4fvH-8Rwha3:-K3QaSU_18P3nSR30vDZ:-839233820) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L337)):_
there is a header-and-footer-cell  behavior which is the correct option for this

---

_[vaadin-grid-doc.html, line 470 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-7ysinlZeoXvRfWwi:-K3QaejQ6-ddkaK2l4-z:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L470)):_
done

---

_[vaadin-grid-doc.html, line 518 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-8HL-DlMAY5pO4rUy:-K3Qb2dChg-4M0g6cv_M:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L518)):_
done

---

_[vaadin-grid-doc.html, line 522 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3-8QMs8q6y8WV3P6HV:-K3Qb3XFPsw4xpIQ5irN:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L522)):_
done

---

_[vaadin-grid-doc.html, line 646 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3Jgt1A12MFx03Qd1Z7:-K3QbMNfG2iA4fxjQ8kl:155820164) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c24fa2a8a297976b8c42145aa765eea4252a538e/vaadin-grid-doc.html#L646)):_
That is a caveat we have to leave with. Right now there is no plans for overloaded method in JsInterop. The only option we can do is to add more functions in the API with different names (for instance selectedWithIndexes)

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257)_

**Comment by manolo** [comment]
@jounik  @tomivirkki @tehapo : this is ready for merging. Api generator works ok and I committed your suggestions as well.

---

Review status: 1 of 2 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-:-K3QedcUj65wNcPuE1sJ:-2002383167)_

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257)_

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

_[vaadin-grid.html, line 709 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-K3Rh-b5obQzYqgohJ75:-K3Rh-b5obQzYqgohJ76:-544987345) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c19df19f236f516e2254ee7b181a66a3ad1a87d/vaadin-grid.html#L709)):_
hydrolysis needs @property and @type be set in order that we can know in api-generator the type of a property.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257)_

**Comment by tomivirkki** [comment]
Some conflicts still. Can't be merged

**Comment by manolo** [comment]
This is very hard to merge. We should avoid modifying a file when a big commit/re-factor like this is pending.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257#-:-K3WGmH8cTZHNiDd8IAO:1929900172)_

**Comment by manolo** [comment]
Reviewed 35 of 37 files at r6.
Review status: 35 of 37 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/257)_

**Comment by manolo** [comment]
Closing this and continuing the PR in #266

**Pull request closed without merging**
