### PR TITLE
Feature/ng2

### LINKED ISSUE #352: Grid Issues with Angular2

### PR DESCRIPTION
**Pull request by manolo**
Fixes #352 #331 #296 #220 #356

Adding Angular2 directives.

Fixes many issues found during the ng2 process, as well as updated grid to use latest gwt and vaadin dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/354)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[directives/README.md, line 58 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt2iGTJFY5EtCBMtP3:-KFt2iGTJFY5EtCBMtP4:-1862721106) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/directives/README.md#L58)):*
Should this say <colgroup><col></colgroup> instead of <columns>

---

*[docs/vaadin-grid-angular2.adoc, line 1 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt3DgOx45Hj1Xq6r5k:-KFt3DgOx45Hj1Xq6r5l:571545059) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/docs/vaadin-grid-angular2.adoc#L1)):*
Just wondering if the docs build task still works after we have documentation under both /demo and /docs. There wasn't a /docs folder in grid before.

---

*[docs/vaadin-grid-angular2.adoc, line 3 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt3Tu9-0jw7R-oCTlB:-KFt3Tu9-0jw7R-oCTlC:-704196893) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/docs/vaadin-grid-angular2.adoc#L3)):*
order: 3 ?

---

*[java/src/main/java/com/vaadin/VaadinMin.gwt.xml, line 1 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt4dKmun4dNfhaX54o:-KFt4dKmun4dNfhaX54p:-893229536) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/java/src/main/java/com/vaadin/VaadinMin.gwt.xml#L1)):*
Is this still necessary now that we're using our own Overlay impl anyway

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by manolo** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[directives/README.md, line 58 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt2iGTJFY5EtCBMtP3:-KFutsuMbCDlbFE3EUXQ:-1149981980) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/directives/README.md#L58)):*
What do you mean

---

*[docs/vaadin-grid-angular2.adoc, line 1 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt3DgOx45Hj1Xq6r5k:-KFut1DyY0-fpp5nJbqN:1844739454) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/docs/vaadin-grid-angular2.adoc#L1)):*
Probably we should remove this. I wrote this in order to finish doc task in spread sheet, but once this doc/examples are moved to core-components, we can remove this. Should be before merging this PR.

---

*[docs/vaadin-grid-angular2.adoc, line 3 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt3Tu9-0jw7R-oCTlB:-KFusef0pPnjj8XYjgBS:351600812) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/docs/vaadin-grid-angular2.adoc#L3)):*
I left that because it was the same order in the component I copied from.
Since we don't have what would be the order until all vaadin-grid doc is in adoc  I don't know what would be the correct order.

---

*[java/src/main/java/com/vaadin/VaadinMin.gwt.xml, line 1 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt4dKmun4dNfhaX54o:-KFutNUd-6_hiqeDD5nx:-432142257) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/java/src/main/java/com/vaadin/VaadinMin.gwt.xml#L1)):*
This simplifies vaadin dependency tree,  removing a lot of complexity. In fact Vaadin-widgets should have a simpler vaadin.gwt.xml like this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by tomivirkki** [comment]
*[directives/README.md, line 58 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt2iGTJFY5EtCBMtP3:-KFwCk7XXhYHC9G_nRmP:1443297074) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/directives/README.md#L58)):*
Damn, always forget that tags don't work here. Meant `<columns>` -> `<colgroup><col></colgroup>`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by manolo** [comment]
Review status: 0 of 23 files reviewed at latest revision, 4 unresolved discussions.

---

*[directives/README.md, line 58 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt2iGTJFY5EtCBMtP3:-KFwbcaRpT5uzakMs8tN:-1364769531) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/directives/README.md#L58)):*
Yup, it's colgroup

---

*[docs/vaadin-grid-angular2.adoc, line 3 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KFt3Tu9-0jw7R-oCTlB:-KFwbVVPhHkkBQSlc8Va:-1022775975) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d0289b0de632e295194be7cf81b411239abd9f80/docs/vaadin-grid-angular2.adoc#L3)):*
Will set this order to 1, so as it's the only document in the grid so far.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by manolo** [comment]
Reviewed 7 of 13 files at r3, 1 of 7 files at r4, 2 of 3 files at r6, 3 of 8 files at r7, 1 of 3 files at r8, 4 of 4 files at r9, 1 of 2 files at r10, 1 of 1 files at r11.
Review status: 20 of 23 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by manolo** [comment]
LGTM

---

Review status: 20 of 23 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-:-KFxsP82o6uQBNq8vzt7:676834233)*

**Comment by manolo** [comment]
Reviewed 3 of 7 files at r4, 3 of 3 files at r12, 2 of 2 files at r13.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by tomivirkki** [comment]
Review status: 14 of 25 files reviewed at latest revision, 6 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 249 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHQgVgYkCEL8ujcUYZ:-KGHQgVgYkCEL8ujcUY_:-2015864282) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L249)):*
Why no ScrollDestination.START.name() ?

---

*[java/src/main/java/com/vaadin/elements/grid/ViolatedGrid.java, line 39 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHPTsAloMXSXanbEH0:-KGHPTsAloMXSXanbEH1:847679224) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/java/src/main/java/com/vaadin/elements/grid/ViolatedGrid.java#L39)):*
This logic with computed body positioning determination and having body in the calculation altogether feels flaky. All you really should need is the overlay and partner bounding rects right? Or am I missing something here?

         p.style.margin ='0';
         
         var overlayRect = p.getBoundingClientRect();
         var partnerRect = r.getBoundingClientRect();
         
         p.style.left = (partnerRect.right - overlayRect.left - overlayRect.width) + 'px';
         p.style.top = (partnerRect.top - overlayRect.top + partnerRect.height) + 'px';

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by tomivirkki** [comment]
*[package.json, line 39 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHR_jJfF_ipzrB4tBm:-KGHR_jJfF_ipzrB4tBn:1540776203) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/package.json#L39)):*
Shouldn't have fixed beta 14 here...same with all the other Ang2-related dependencies

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by manolo** [comment]
Review status: 14 of 25 files reviewed at latest revision, 7 unresolved discussions.

---

*[package.json, line 39 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHR_jJfF_ipzrB4tBm:-KGHcEJRK7jJ-kYFShmR:-292493751) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/package.json#L39)):*
That came copied from other elements, what is the correct value then?

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 249 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHQgVgYkCEL8ujcUYZ:-KGHavA5eUKqGpYVAW9T:-1486050298) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L249)):*
Just to be coherent with the arguments we accept from js, but you are right, better to have that so as if for some reason the Enum changes our code does not compile.

---

*[java/src/main/java/com/vaadin/elements/grid/ViolatedGrid.java, line 39 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHPTsAloMXSXanbEH0:-KGHbLKsPC1iL_ltqqcI:-1589130675) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/java/src/main/java/com/vaadin/elements/grid/ViolatedGrid.java#L39)):*
Actually rects top/left refer to the view port, we need scrolling values to position the popup refered with the body (absolute). We could use position fixed, but then the popup does not move when scrolling.
The only thing not covered is window resizing here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by tomivirkki** [comment]
*[java/src/main/java/com/vaadin/elements/grid/ViolatedGrid.java, line 39 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHPTsAloMXSXanbEH0:-KGHd-n6TM9pb--Na4j5:-1825775748) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/java/src/main/java/com/vaadin/elements/grid/ViolatedGrid.java#L39)):*
We don't need the scrolling values for anything. That's why you shouldn't have body in the calculation logic at all.

You logically only need the difference between the overlay position and partner position and then add that difference to the overlay position to have them at the same position.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Comment by tomivirkki** [comment]
*[package.json, line 39 \[r15\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354#-KGHR_jJfF_ipzrB4tBm:-KGHe-9SliEd7Bp-wclR:21317361) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c8907d013b3c5470300c1f4356c976a6ed36c274/package.json#L39)):*
See here for example https://github.com/vaadin/vaadin-combo-box/blob/feature/ng2/package.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/354)*

**Pull request merged**
