### PR TITLE
Don’t normalize values into strings

### LINKED ISSUE #796: Sorting non-string values doesn't work properly
See: 
https://gitter.im/vaadin/vaadin-core-elements?at=58c1fef21465c46a560f338d

grid-sorting

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #796

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/827)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-:-KgJ2g9FDOEUVT-gDrdI:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-array-data-provider-behavior.html, line 97 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-KgJaFrL4A2cMz3kLHFS:-KgJaFrL4A2cMz3kLHFT:bupewkl) ([raw file](https://github.com/vaadin/vaadin-grid/blob/84ab2af834448daa9a98679a2058cbc4329542d5/vaadin-grid-array-data-provider-behavior.html#L97)):*
> ```HTML
> 
>     _normalizeEmptyValue: function(value) {
>       if ([undefined, null].indexOf(value) >= 0) {
> ```

I guess this approach won't work when sorting `Date` objects? I would just leave the `_normalizeEmptyValue` as it was and change `value.toString()` -> `value` 

---

*[test/sorting.html, line 374 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-KgJaxikqVU34nceP-GI:-KgJaxikqVU34nceP-GJ:b61gk8o) ([raw file](https://github.com/vaadin/vaadin-grid/blob/84ab2af834448daa9a98679a2058cbc4329542d5/test/sorting.html#L374)):*
> ```HTML
>           });
> 
>           it('should sort numbers correctly', function() {
> ```

A similar test using `Date` would be great

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-array-data-provider-behavior.html, line 97 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-KgJaFrL4A2cMz3kLHFS:-KgJeLU2sYiG7KcXG4Jp:b6qfe8m) ([raw file](https://github.com/vaadin/vaadin-grid/blob/84ab2af834448daa9a98679a2058cbc4329542d5/vaadin-grid-array-data-provider-behavior.html#L97)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I guess this approach won't work when sorting `Date` objects? I would just leave the `_normalizeEmptyValue` as it was and change `value.toString()` -> `value` 
</blockquote></details>

That wouldn't work when sorting `NaN` values. The suggested approach sorts `Date` objects fine, added a test for it.

---

*[test/sorting.html, line 374 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-KgJaxikqVU34nceP-GI:-KgJeEiq769AXS3L3cXx:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/84ab2af834448daa9a98679a2058cbc4329542d5/test/sorting.html#L374)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

A similar test using `Date` would be great
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827)*

**Comment by Saulis** [comment]
:lgtm: ready to :shipit: after build passes.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-array-data-provider-behavior.html, line 97 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-KgJaFrL4A2cMz3kLHFS:-KgNiEPkhVrQ50BiE5WY:bk0wkmv) ([raw file](https://github.com/vaadin/vaadin-grid/blob/84ab2af834448daa9a98679a2058cbc4329542d5/vaadin-grid-array-data-provider-behavior.html#L97)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

That wouldn't work when sorting `NaN` values. The suggested approach sorts `Date` objects fine, added a test for it.
</blockquote></details>

OK excellent

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/827#-:-KgNiTj5SB1i6-L0UHNW:b-6bkvkl)*

**Pull request merged**
