### PR TITLE
Fix typo in mixin docs

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/903)

### CODE REVIEW

**Comment by jouni** [comment]
I think there kinds of fixes could go in without review. Not sure how the rest of the team feels.

**Comment by samiheikki** [comment]
I felt that too, but was not 100% sure :)

**Comment by tomivirkki** [comment]
Yes, no need for a PR in cases like these.

**Comment by samiheikki** [comment]
Thanks!

**Pull request merged**
