### PR TITLE
Make sure header/footer height are included in sizer's vertical position

### LINKED ISSUE #537: Can't scroll to the last item in Safari with scroll handle
If there's a footer in the grid, the user can't scroll to the last item by dragging the scroll handle on the right. Last item can be revealed with wheel.

Footer height doesn't seem to be included in the vertical sizer height.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #537

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/548)

### CODE REVIEW

**Comment by samiheikki** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table.html, line 42 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkDWM-swor5r4XK06e:-KXkDWM0hhV9RSx9uGH_:b-3qcv44) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-table.html#L42)):*
> ```HTML
>       #items,
>       #fixedsizer,
>       #outersizer {
> ```

Can `#items`, `#fixedsizer` and `#outersizer` have one  common class to use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548)*

**Comment by platosha** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-sizer.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkYzZsPE9tUS6cxAy5:-KXkYzZtKShdPMRfgIuC:b-3er27l) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-sizer.html#L11)):*
> ```HTML
>         width: 100%;
>         visibility: hidden;
>         line-height: 0;
> ```

Why is that? Can’t we just remove the `&nbsp;` form the content below?

---

*[vaadin-grid-sizer.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkZ8F2QbMQGpbWToME:-KXkZ8F2QbMQGpbWToMF:b-8vop9s) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-sizer.html#L29)):*
> ```HTML
>       is: 'vaadin-grid-sizer',
> 
>       extends: 'div',
> ```

BTW this is out of the scope, I’m just curious. Do we really need to extend `div` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-sizer.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkYzZsPE9tUS6cxAy5:-KXkbEyI5utkxBvkMpIq:b-c1ic7m) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-sizer.html#L11)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Why is that? Can’t we just remove the `&nbsp;` form the content below?
</blockquote></details>

If you remove the content, the sizer-cell don't take space properly

---

*[vaadin-grid-sizer.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkZ8F2QbMQGpbWToME:-KXkae97FHuDoVke_BBR:bjuzorn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-sizer.html#L29)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW this is out of the scope, I’m just curious. Do we really need to extend `div` here?
</blockquote></details>

No, we guessed it would be cleaner to add a div inside a table caption than a custom element. Probably doesn't matter so we don't need to worry about it while switching to Polymer 2.

---

*[vaadin-grid-table.html, line 42 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkDWM-swor5r4XK06e:-KXkd-bPzONxc6RJafv_:b-pkbb5x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-table.html#L42)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary><blockquote>

Can `#items`, `#fixedsizer` and `#outersizer` have one  common class to use?
</blockquote></details>

Maybe, I did consider that during implementation but ended up with this since I couldn't come up with a common class name that makes sense for this case. Suggestions? :)

Rather than cluttering the template with unnecessary class attributes that are only needed for this one case I'd still add the two extra lines here and keep the template clean.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548)*

**Comment by samiheikki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-:-KXnxhERwd292ynjIlLB:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-sizer.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-KXkZ8F2QbMQGpbWToME:-KXon38rX_bmQFNytggz:b-u1zuj5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b4856fbe2b11029f7b9b1c9ae58e4d9a9341f18b/vaadin-grid-sizer.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No, we guessed it would be cleaner to add a div inside a table caption than a custom element. Probably doesn't matter so we don't need to worry about it while switching to Polymer 2.
</blockquote></details>

AFAIK custom elements are allowed in `<caption>` by the HTML spec now. Checked yesterday.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/548#-:-KXonKyG224vGdvnqHWX:bnfp4nl)*

**Pull request merged**
