### PR TITLE
Add "auto-select" to selection column

### LINKED ISSUE #616: Add "auto-select" shortcut to selection column
We should add a "auto-select" boolean flag to `<vaadin-grid-selection-column>` which, when set to `true` will make the column listen to changes on `activeItem` and toggle it's presence in the `selectedItems` array.

### PR DESCRIPTION
**Pull request by limonte**
Fixes #616

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/631)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-active-item-behavior.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_SxcdeQ1eH8cueTZ71:-K_Sxcdf7iYiDpFEWPiS:b-15xhuo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/09fce6e9f3ce012d30c48997d8ba4c5a364b6704/vaadin-grid-active-item-behavior.html#L35)):*
> ```HTML
>        * previousActiveItem will have an Object with just unselected activeItem
>        */
>       previousActiveItem: Object
> ```

I would make this private for now and if possible, move it to the selection column itself where it's needed.

---

*[test/selecting.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_Sxnt-81q6kobQV6sA:-K_Sxnt-81q6kobQV6sB:bpxu0gk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/09fce6e9f3ce012d30c48997d8ba4c5a364b6704/test/selecting.html#L164)):*
> ```HTML
>       });
> 
>       it('should select item when row is clicked and select-active-item is enabled', function() {
> ```

Maybe also add a test for deselecting.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-selection-behavior.html, line 80 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_ToJmwbu8SK-h_Mzwl:-K_ToJmwbu8SK-h_Mzwm:bpmbd49) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f514823f261ade18c22254857d4ca1a125641539/vaadin-grid-selection-behavior.html#L80)):*
> ```HTML
>      * @param {number|Object} item The item index or the item object
>      */
>     toggleItem: function(item) {
> ```

I would actually make this private also and maybe call it `toggleSelection`. Or did you have a specific  use case in mind to make this public?

---

*[vaadin-grid-selection-column.html, line 63 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_TnG_dApLw4LswpwPZ:-K_TnG_dApLw4LswpwP_:b-h3fup4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f514823f261ade18c22254857d4ca1a125641539/vaadin-grid-selection-column.html#L63)):*
> ```HTML
> 
>       /**
>        * When true it adds ab active item to selectedItem.
> ```

ab -> the, selectedItem -> selectedItems

---

*[test/selecting.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_Sxnt-81q6kobQV6sA:-K_TnX9ag760Wwh1Popr:byrf0fd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/09fce6e9f3ce012d30c48997d8ba4c5a364b6704/test/selecting.html#L164)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was thinking a separate test maybe – one test testing that clicking adds an item to selectedItems, one test testing that clicking on a previously selected item deselects it, and a third test where clicking the same item twice in  a row will deselect it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631)*

**Comment by limonte** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-selection-behavior.html, line 80 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_ToJmwbu8SK-h_Mzwl:-K_TqtiBpl6rDZQK7Z5c:beky3uh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f514823f261ade18c22254857d4ca1a125641539/vaadin-grid-selection-behavior.html#L80)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I would actually make this private also and maybe call it `toggleSelection`. Or did you have a specific  use case in mind to make this public?
</blockquote></details>

It's private now.

---

*[vaadin-grid-selection-column.html, line 63 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_TnG_dApLw4LswpwPZ:-K_UNuAigBb3Z9vGe-6r:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f514823f261ade18c22254857d4ca1a125641539/vaadin-grid-selection-column.html#L63)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

ab -> the, selectedItem -> selectedItems
</blockquote></details>

Done.

---

*[test/selecting.html, line 164 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-K_Sxnt-81q6kobQV6sA:-K_UPvSKvV7WQeVzDf3_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/09fce6e9f3ce012d30c48997d8ba4c5a364b6704/test/selecting.html#L164)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I was thinking a separate test maybe – one test testing that clicking adds an item to selectedItems, one test testing that clicking on a previously selected item deselects it, and a third test where clicking the same item twice in  a row will deselect it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/631#-:-K_Y5EPgAalAP29G7h1M:bnfp4nl)*

**Pull request merged**
