### PR TITLE
Optimize table-row _updateCells 

### PR DESCRIPTION
**Pull request by manolo**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/471)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Don't add asynchronicity to the component. As you see, many tests would require async with this change (same would be required from anyone using the Grid), which is not something we want.

Rather find the reason the API is called so often and fix the original issue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-:-KSjpIY4TUoYg_kvG6_S:b-8j5cju)*

**Comment by tomivirkki** [comment]
Furthermore, this isn't probably the best time to do optimization since the internals are still subject to heavy change; "premature optimization is the root of all evil".

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-:-KSjpvSiDtYivamUOvk8:b-vh4qzk)*

**Comment by Saulis** [comment]
In this case there are two places where `_updateCells` is called. The other one is the `colspan` listener for each `cell`, which we might either add a default value or remove altogether during #441 and the other place is here: https://github.com/vaadin/vaadin-grid/blob/2.0-dev/vaadin-grid-table-row.html#L155. As you can see, there's already a mention about optimization, but that should be taken care of separately.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-:-KSjpijGYAhKvv_KSa-s:bbvcdp7)*

**Comment by manolo** [comment]
@tomivirkki for instance when the grid is being configured, adding all columns, each single configuration step produces a call to this

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-:-KSju4tvz_1A7YdTdlNP:bat5pr7)*

**Comment by tomivirkki** [comment]
@manolo For sure. The bottom line is that the tests should pass unchanged. We don't want to require async() from the tests and especially from the users.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-:-KSjv-rs74HHnbdpiKyo:b-2gyshf)*

**Comment by manolo** [comment]
Removed the debounce. 
The PR is more a refactoring than an optimisation, it makes easier to understand what the code does (at least to me).
Also a fix when number of columns and cells are different.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-:-KSkCJViwuHOdC1NxTmG:b-vfe89q)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkIu_l5mxMrVTFGLIM:b12hmir) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
> ```HTML
>       _updateCells: function() {
>         // columns > cells means that there is an extra col for multiselection
>         var multiSel = this.columns.length > this.cells.length ? 1 : 0;
> ```

Looks a lot better now. The hierarchy support will add another extra column so could this be reformatted to
`var extraColumns = this.columns.length - this.cells.length;`
to make this future proof. The variable would also be agnostic to a specific feature.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkMm1q0qQLC_YIXRKi:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Looks a lot better now. The hierarchy support will add another extra column so could this be reformatted to
> `var extraColumns = this.columns.length - this.cells.length;`
> to make this future proof. The variable would also be agnostic to a specific feature.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkOvW_jg4J26iu1wfb:bbng7iu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Done.
</details>
Actually it seems that the variable isn't needed at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkR6kGbfx48R4UbipI:bin6qcj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Actually it seems that the variable isn't needed at all.
</details>
what do you mean ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkRCCssuPICDzsSy18:bjs459x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> what do you mean ?
</details>
There's a moment between adding extra columns and changing the row.cells property when the extraColumns isn't 0 but that changes soon after related observers are invoked. This is another issue and not critical to fix now.

So practically the extraColumns can always be 0 -> it may as well be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkSeOPTm7WyEmnlBow:b-5fak7y) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> There's a moment between adding extra columns and changing the row.cells property when the extraColumns isn't 0 but that changes soon after related observers are invoked. This is another issue and not critical to fix now.
> 
> So practically the extraColumns can always be 0 -> it may as well be removed.
> 
</details>
The problem is that sometimes we are setting erroneous properties to the wrong cell.
When debugging is quite confusing, and it works by chance, because always happens that the correct configuration comes the last.
I would do either: return when both arrays have not the same size, or leave the code with the offset check. But would not set erroneous css properties (that could have subtle rendering performance hits)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkUAKN1zpbAkB-b83E:bk37ip5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> The problem is that sometimes we are setting erroneous properties to the wrong cell.
> When debugging is quite confusing, and it works by chance, because always happens that the correct configuration comes the last.
> I would do either: return when both arrays have not the same size, or leave the code with the offset check. But would not set erroneous css properties (that could have subtle rendering performance hits)
> 
</details>
Well, as I said, "this is another issue and not critical to fix now". But sure you can return if the lengths don't match.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table-row.html, line 103 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkIu_l5mxMrVTFGLIL:-KSkk3IvL9QAhmRRCTLs:b-9u299q) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9262dc0c2b272a5134e78d305a7edbc7efd94052/vaadin-grid-table-row.html#L103)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Well, as I said, "this is another issue and not critical to fix now". But sure you can return if the lengths don't match.
</details>
Done, not doing anything when length does not match

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSkpnTgnUvFIXsR6HHd:b-tsh0f4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
> ```HTML
> 
>             // Visit colspanned cells to hide them, and increase parent width and flex.
>             for (var j = 1; j < colspan && i + j < l; j++) {
> ```

Could this be `var j =  i + 1; j < i + colspan && j < l; j++` ? All the consequent `i + j` could then be changed to just `j` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSkqXA83C63cy50Taxu:bqa5wku) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Could this be `var j =  i + 1; j < i + colspan && j < l; j++` ? All the consequent `i + j` could then be changed to just `j` 
</details>
Could also remove the l variable. colspan property will not be changeable by the developer. Column-groups are in control of the colspan value internally so there's no need for the check for invalid (overflowing) value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoZVvcLHOjasAzwmf7:b8r0n0v) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Could also remove the l variable. colspan property will not be changeable by the developer. Column-groups are in control of the colspan value internally so there's no need for the check for invalid (overflowing) value.
</details>
I know that it does not mutate, but the l variable is for simplicity, it's used in a couple of places, and leaving the l by the long  this.cells.length in the second condition does not simplifies the readability,  I think

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSocR9MLCjFkLLv1fky:b-1ngw3x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I know that it does not mutate, but the l variable is for simplicity, it's used in a couple of places, and leaving the l by the long  this.cells.length in the second condition does not simplifies the readability,  I think
</details>
Sorry, I misunderstood. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoc4KpsWU-m81hueqc:bs932c6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I know that it does not mutate, but the l variable is for simplicity, it's used in a couple of places, and leaving the l by the long  this.cells.length in the second condition does not simplifies the readability,  I think
</details>
I really don't think that the current approach is simpler than removing the variable. Take a look https://www.dropbox.com/s/g6vx6grmgyxhdf2/Screenshot%202016-09-29%2009.24.56.png?dl=0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSocXrtlslJK3dsh0aq:b-4jtorm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> I really don't think that the current approach is simpler than removing the variable. Take a look https://www.dropbox.com/s/g6vx6grmgyxhdf2/Screenshot%202016-09-29%2009.24.56.png?dl=0
</details>
Ok, will take a look

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSod1cDLbZYiUbHURIZ:bfcjfp6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Ok, will take a look
</details>
We cannot remove the check, if the user sets a big colspan, say 5 in a 4 columns grid, it breaks

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSodKnLaFK75CkMyRyR:b-7nwgqx) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> We cannot remove the check, if the user sets a big colspan, say 5 in a 4 columns grid, it breaks
</details>
User isn't in control of the colspan. It's column-group's job.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSodYpgNC_nxkkDAfM4:b2b6rha) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> User isn't in control of the colspan. It's column-group's job.
</details>
I don't follow, this breaks the grid:

```
         <vaadin-grid-column >
            <template>
              <div>baz-[[index]]</div>
            </template>
            <template is="header">
              baz-h1
            </template>
            <template is="header" colspan="5">
              baz-h2
            </template>
          </vaadin-grid-column>

```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSodfUWhoxtLDvut1r3:bnezcze) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I don't follow, this breaks the grid:
> 
> ```
>          <vaadin-grid-column >
>             <template>
>               <div>baz-[[index]]</div>
>             </template>
>             <template is="header">
>               baz-h1
>             </template>
>             <template is="header" colspan="5">
>               baz-h2
>             </template>
>           </vaadin-grid-column>
> 
> ```
</details>
`colspan` is temporary dev-time property. It will be removed when column-groups are introduced.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSodqj_8rgRfHa5EFbk:bnaq0bz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> `colspan` is temporary dev-time property. It will be removed when column-groups are introduced.
</details>
Meaning that it can never have an erroneous value since user cannot change it himself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSodr0m4cCvJyrnpzzh:b-8se1gk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> `colspan` is temporary dev-time property. It will be removed when column-groups are introduced.
</details>
But it's out of the scope of this PR when it will be removed. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoe0eQNhXh8ChPpFoL:b-2gcnz3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> But it's out of the scope of this PR when it will be removed. 
</details>
So is adding the check. It wasn't in the previous implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoe798oyU3sLzcb6cc:bmee4tf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> So is adding the check. It wasn't in the previous implementation.
</details>
Previous implementation was failing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoeHobxi5DOhlsvzAp:b-lbut5x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Previous implementation was failing
</details>
What do you mean?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoeMwTSH3SqdfSyvjN:bwthpcp) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> What do you mean?
</details>
In current 2.0-dev if user sets a colspan of 5 in the demo.html, the code breaks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSofGETZiurquG9PyYI:bu2xc4g) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> In current 2.0-dev if user sets a colspan of 5 in the demo.html, the code breaks.
</details>
Ok, if you're going to add this check then please add tests for it also.

Also check that the colspan cannot overflow the frozen column border (1 frozen column with colspan of 2 for example) because that's illegal also and "was failing" in the previous implementation. It also needs tests.

Then the colspan can also be set to -1 by the user which fails too...

To be honest, I don't see a point in adding these checks for a temporary implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSogo_2miqbm_y8dBrI:b-hjs3gy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Ok, if you're going to add this check then please add tests for it also.
> 
> Also check that the colspan cannot overflow the frozen column border (1 frozen column with colspan of 2 for example) because that's illegal also and "was failing" in the previous implementation. It also needs tests.
> 
> Then the colspan can also be set to -1 by the user which fails too...
> 
> To be honest, I don't see a point in adding these checks for a temporary implementation.
</details>
Well, I need this for the grouping prototyping I'm doing.
Introducing small changes and refactoring is not as bad ;-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoi8A5sl0a2VcSgP4N:bi9z0py) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Well, I need this for the grouping prototyping I'm doing.
> Introducing small changes and refactoring is not as bad ;-)
</details>
Well then it should be in your prototyping branch, not in 2.0-dev

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSoiaqAdc3SBlDqovKF:b-xfptd0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Well then it should be in your prototyping branch, not in 2.0-dev
</details>
This is related to what @saulis  asked when I started with this story : `The first goal to get done is to modify https://github.com/vaadin/vaadin-grid/blob/2.0-dev/vaadin-grid-table-row.html#L101 to just get the group header cell width calculated more simpler`

I did the PR in order that he could take a look to my findings and refactoring.

I don't think this is the definitive implementation, as everything I do. I still believe in agile development, that means refactor whenever something could be improved.

To be honest, If your thoughts were that this wasn't never to be merged, it could be said at the beginning.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSokgB-YpFZwaZGcbpi:bv55u6g) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> This is related to what @saulis  asked when I started with this story : `The first goal to get done is to modify https://github.com/vaadin/vaadin-grid/blob/2.0-dev/vaadin-grid-table-row.html#L101 to just get the group header cell width calculated more simpler`
> 
> I did the PR in order that he could take a look to my findings and refactoring.
> 
> I don't think this is the definitive implementation, as everything I do. I still believe in agile development, that means refactor whenever something could be improved.
> 
> To be honest, If your thoughts were that this wasn't never to be merged, it could be said at the beginning.
> 
> 
</details>
@tomivirkki isn't against this refactoring, he's just stating that if you're going to change the behavior, it's not refactoring anymore and you should add tests for the changed behavior. In this case, there hasn't been a check for overflowing colspan by the user, and at this point we probably shouldn't add one since the grouping feature will drop that from the API. So I agree in that sense that it might be better to leave the whole check out at this point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-row.html, line 110 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471#-KSkpnTgnUvFIXsR6HHc:-KSolLRzohXJHj_PLpnd:b4p9b4k) ([raw file](https://github.com/vaadin/vaadin-grid/blob/00aed5e8a2657f9a2d6288eb6b971c852280d3bb/vaadin-grid-table-row.html#L110)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> @tomivirkki isn't against this refactoring, he's just stating that if you're going to change the behavior, it's not refactoring anymore and you should add tests for the changed behavior. In this case, there hasn't been a check for overflowing colspan by the user, and at this point we probably shouldn't add one since the grouping feature will drop that from the API. So I agree in that sense that it might be better to leave the whole check out at this point.
</details>
The branch look really good to me. It simplifies the code a lot and I want to merge it but as @saulis stated, the check is unnecessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/471)*

**Pull request merged**
