### PR TITLE
Use generic directive from angular2-polymer

### PR DESCRIPTION
**Pull request by Saulis**
Connects to https://github.com/vaadin/components-team-tasks/issues/133

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/365)

### CODE REVIEW

**Comment by manolo** [comment]
:lgtm:

<details><summary><i>Previously, CLAassistant wrote…</i></summary>
> [CLA assistant check](https://cla-assistant.io/vaadin/vaadin-grid?pullRequest=365) <br/>All committers have signed the CLA.</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/365#-:-KH_GczjZ4nxKYzGbIo7:1417088721)*

**Comment by manolo** [comment]
Tests are broken in travis though

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> :lgtm:</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/365#-:-KH_H0ZDqb5sc1DVKp6N:1785777406)*

**Comment by Saulis** [comment]
Tests are fixed now

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Tests are broken in travis though</details>


---

Review status: 2 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/365#-:-KHsF1Q1J-JMBUpY9Rss:579240026)*

**Comment by manolo** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/365)*

**Comment by tomivirkki** [comment]
:lgtm: 

<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Tests are fixed now</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/365#-:-KHt20dRawh2y6wr6mB7:980077423)*

**Pull request merged**
