### PR TITLE
2.0 feature/observe light dom

### LINKED ISSUE #503: Observe light DOM for column tree changes
- Reset `columns` property whenever `<vaadin-grid-column>` or `<vaadin-grid-column-group>` is added or removed directly under `<vaadin-grid>` or inside any `<vaadin-grid-column-group>`
- Make sure `<template is="dom-repeat">` with some columns works nicely.
- Make sure columns can also be passed through a `<content>` element from a parent?

### PR DESCRIPTION
**Pull request by Saulis**
Fix #503

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/532)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 183 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KWlEAbawmNrWw4bJ5uY:-KWlEAbco_EIx8CL6QKS:baqar1v) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d2a65946971fc31d57213887a19a453d8760e9dc/vaadin-grid-column.html#L183)):*
> ```HTML
>       attached: function() {
>         this._updateFlexAndWidth(this._visibleChildColumns);
>         this._addNodeObserver();
> ```

I don't see code to remove this on detached. What happens if the user detaches / reattaches the component several times?

---

*[vaadin-grid-column.html, line 247 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KWlB0Dwad3vKwnV63Kl:-KWlB0Dy_jbhj9GwS9eA:biq8xm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d2a65946971fc31d57213887a19a453d8760e9dc/vaadin-grid-column.html#L247)):*
> ```HTML
>         this._observer = Polymer.dom(this).observeNodes(function(info) {
>           var columns = function(node) {
>             return (node.nodeType === Node.ELEMENT_NODE && node.localName.indexOf('vaadin-grid-column') === 0);
> ```

use equal when possible node.localName == 'vaadin-grid-column'

---

*[vaadin-grid.html, line 178 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KWlBeWohUFLHrTimPLk:-KWlBeWpBkRvEoP1Dj4U:b47lfrr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d2a65946971fc31d57213887a19a453d8760e9dc/vaadin-grid.html#L178)):*
> ```HTML
>       if (arr1.length !== arr2.length) {
>         return false;
>       }
> ```

join all the conditions in one:
if (!arr1 || !arr2 || arr1.length != arr2.length)

Note that you don't need to use !== and force the js check the type in runtime, since length returns the correct type

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532)*

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 183 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KWlEAbawmNrWw4bJ5uY:-KWrgInp8zGgOIyK04Hd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d2a65946971fc31d57213887a19a453d8760e9dc/vaadin-grid-column.html#L183)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I don't see code to remove this on detached. What happens if the user detaches / reattaches the component several times?
</details>
Done.

---

*[vaadin-grid-column.html, line 247 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KWlB0Dwad3vKwnV63Kl:-KWrfODKQL22Lym7gM8i:bt4eeqm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d2a65946971fc31d57213887a19a453d8760e9dc/vaadin-grid-column.html#L247)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> use equal when possible node.localName == 'vaadin-grid-column'
</details>
In this case we want to match both with `vaadin-grid-column` and `vaadin-grid-column-group`

---

*[vaadin-grid.html, line 178 at r7](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KWlBeWohUFLHrTimPLk:-KWrgZCo2h9Y71T8lttj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d2a65946971fc31d57213887a19a453d8760e9dc/vaadin-grid.html#L178)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> join all the conditions in one:
> if (!arr1 || !arr2 || arr1.length != arr2.length)
> 
> Note that you don't need to use !== and force the js check the type in runtime, since length returns the correct type
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532)*

**Comment by tomivirkki** [comment]
There's a lot of new functionality added directly to vaadin-grid.html in this PR. Should this feature also be added as a new behavior (like most of the bigger features added on top of vaadin-grid)?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-:-KX5fPttDdF9lHfJ6vp3:b-hor6q2)*

**Comment by tomivirkki** [comment]
In the dev.html demo's case, the column structure generates around 500 cell-content wrappers. Whenever the DOM-structure changes, it disposes of the existing wrappers and creates 500 new ones, resulting in bad performance. Would probably make a difference if the existing wrappers were re-used instead.
Don't know if this kind of optimization should be handled in a separate PR though...

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-:-KX5l9X3R3WXZd5Ft2AK:beo2hyc)*

**Comment by Saulis** [comment]
We discussed the possibility of extracting the functionality to a behavior, but decided to leave it as it now. Now that I look at the code, I would and could extract it.

The reusing of elements could be something to think about in the future, we can see the performance hit also on the tests, but as columns don't change that frequently in normal use cases, I think we can do the optimization later.

---

Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-:-KX5tTzmx38yfBaWxmAm:b-y3bu7x)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-cell.html, line 67 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KX5px5o4Bnof71T3tj0:-KX5px5pVjYEr0VDv4f2:b6p7uvw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f5fefe0e73f2385c17c1f5dc762334988347fb1f/vaadin-grid-table-cell.html#L67)):*
> ```HTML
>       detached: function() {
>         if (this.column) {
>           this.unlisten(this.column, 'property-changed', '_columnPropChanged');
> ```

Cells get detached/reattached occasionally due to row reordering (performed after scrolling stops). The cells on reordered rows no longer adapt to column changes if this isn't re-listened on attach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532)*

**Comment by Saulis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-table-cell.html, line 67 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KX5px5o4Bnof71T3tj0:-KX7Z2Fz4oNwVq4LxyUa:b-dwt9qi) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f5fefe0e73f2385c17c1f5dc762334988347fb1f/vaadin-grid-table-cell.html#L67)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Cells get detached/reattached occasionally due to row reordering (performed after scrolling stops). The cells on reordered rows no longer adapt to column changes if this isn't re-listened on attach.
</details>
Nice catch. Will fix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532)*

**Comment by samiheikki** [comment]
Reviewed 2 of 4 files at r4, 1 of 3 files at r5, 3 of 4 files at r6, 1 of 1 files at r7, 1 of 2 files at r8, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-dynamic-columns-behavior.html, line 47 at r9](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KX9lX2QLsc5yHQFTZZc:-KX9lX2QLsc5yHQFTZZd:b-9pcr57) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c0c73680600364beca3c1bc04747f28efd1451cf/vaadin-grid-dynamic-columns-behavior.html#L47)):*
> ```HTML
>           return [col];
>         }
>       }.bind(this)).reduce(function(prev, curr) {
> ```

Does this need `bind(this)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532)*

**Comment by Saulis** [comment]
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-dynamic-columns-behavior.html, line 47 at r9](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KX9lX2QLsc5yHQFTZZc:-KXA3KJCKwedvt_3qh0P:bu2j3sr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c0c73680600364beca3c1bc04747f28efd1451cf/vaadin-grid-dynamic-columns-behavior.html#L47)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Does this need `bind(this)`?
</details>
Nope. Removed.

---

*[vaadin-grid-table-cell.html, line 67 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-KX5px5o4Bnof71T3tj0:-KXA2iEdYU30Iq7cu4KX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f5fefe0e73f2385c17c1f5dc762334988347fb1f/vaadin-grid-table-cell.html#L67)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Nice catch. Will fix
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532)*

**Comment by samiheikki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r10.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-:-KXABEcx6xhDh6CvS8K_:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-:-KXAIERYWhYT8g51iFKa:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/532#-:-KXAIKo9cVCo6JbAFyaw:bnfp4nl)*

**Pull request merged**
