### PR TITLE
Feature/2.0 column resizing

### LINKED ISSUE #661: Column Resizing for 2.0
MVP:
- Add `resizable` property to `<vaadin-grid-column>`
- Only columns (not group headers) support resizing
- `width` should notify changes
- Column width should be changed to "fixed" when user is resizing (flex goes to 0)
- the handle should look like the one in 1.x with a large touch area
- Should work also on touch devices

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #661

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/672)

### CODE REVIEW

**Comment by limonte** [comment]
I'd like to see the progress graph after today's mergy-day :D :lgtm: 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-:-KbPvFPUnY3bCUzBOgic:b-ielqwo)*

**Comment by manolo** [comment]
Reviewed 10 of 10 files at r2.
Review status: 9 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbPzFmLtV7JVDgbGAAu:b-j574ew) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
> ```HTML
>               --vaadin-grid-focused-cell: {
>                 box-shadow: inset 0 0 0 2px rgba(27, 135, 227, 1);
>               };
> ```

I miss an example using the css mixin for the handle. 

---

*[test/index.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPyesHEW-SkeyFkUVf:-KbPyesHEW-SkeyFkUVg:b-2op18h) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/test/index.html#L25)):*
> ```HTML
>       'column-group.html',
>       'column-groups.html',
>       'column-resizing.html',
> ```

do you mind, at the same time to move the column reordering in this block ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by tomivirkki** [comment]
Review status: 8 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQ0T984SQvR49VH5Ws:b-ive75x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I miss an example using the css mixin for the handle. 
</blockquote></details>

It's no longer needed since we dropped the hover color & mixin. All mixins don't need to be demoed either, there's documentation for each of them already.

---

*[test/index.html, line 25 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPyesHEW-SkeyFkUVf:-KbQ0n4cZGZjZVb53XU_:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/test/index.html#L25)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

do you mind, at the same time to move the column reordering in this block ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by manolo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQ75fr94ua_nq2tDKX:b9xjm29) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's no longer needed since we dropped the hover color & mixin. All mixins don't need to be demoed either, there's documentation for each of them already.
</blockquote></details>

I don't follow, the mixin `--vaadin-grid-column-resize-handle` is still applied, so what is dropped.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by tomivirkki** [comment]
*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQ81MQdS28ih0m58fm:bjjhrbn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I don't follow, the mixin `--vaadin-grid-column-resize-handle` is still applied, so what is dropped.
</blockquote></details>

See revision 1 for this file (in this PR)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by manolo** [comment]
Review status: 8 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQ8_EZ8mMVQV5MghTz:b-e3mkg1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

See revision 1 for this file (in this PR)
</blockquote></details>

I was referring to the `--vaadin-grid-column-resize-handle` the user might want to see a customised handle.  For instance in the transparent demo, the handle is almost invisible. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by tomivirkki** [comment]
*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQAx_L77spVupL8j_S:b-mh83d2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I was referring to the `--vaadin-grid-column-resize-handle` the user might want to see a customised handle.  For instance in the transparent demo, the handle is almost invisible. 
</blockquote></details>

There are no handles in the "transparent header" demo. Those borders are included in the demo styles.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by tomivirkki** [comment]
*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQC471-h_uagjHVIiv:bodf2u2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

There are no handles in the "transparent header" demo. Those borders are included in the demo styles.
</blockquote></details>

Added the handles and used the mixin to hide them :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by manolo** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 241 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbPzFmLtV7JVDgbGAAt:-KbQCt2tFnp8zcCQgnCO:bb70w76) ([raw file](https://github.com/vaadin/vaadin-grid/blob/04643d08a1d846d4a4507928d0e28b8a412a2a61/demo/styling.html#L241)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Added the handles and used the mixin to hide them :+1: 
</blockquote></details>

Nice

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-:-KbQD3qQbllRzdG-dSbA:bg7igkv)*

**Comment by manolo** [comment]
Review status: 9 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/styling.html, line 493 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbQFd2qMJUamhQFCfbx:-KbQFd2rgE-QYdJzORLs:b3ciadk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ca1759efad39f9661715e042109fa066d579444e/demo/styling.html#L493)):*
> ```HTML
>               </template>
> 
>               <vaadin-grid-column width="45px" flex-grow="0">
> ```

Absolutly unrelated with this PR, but realised that there is no docs apart from a small reference in API  about sizing columns with with and flex-grow.  Users not familiar with flex model could need some explanation. For the resizing it could be a reference in the doc saying that in addition to set the resizable prop, the user might need to adjust the flex-grow ratio. :not-blocker: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[vaadin-grid-column.html, line 73 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbTw_eu4UiuNr9-ac0H:-KbTw_evavMb3b6n0Nd_:b-nqomk0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ca1759efad39f9661715e042109fa066d579444e/vaadin-grid-column.html#L73)):*
> ```HTML
>        * When set to true, the column is user-resizable.
>        */
>       resizable: {
> ```

When `resizable` is applied on a `<vaadin-grid-column-group>` I think it should set `resizable` to `true` on all of its child columns. In the current revision, the "Valo" styling demo has weird behavior where for example the "Last Name" column can be resized only from the middle header row.

---

*[vaadin-grid-table-cell.html, line 249 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbP7QIi9mUHRm1BaBb9:-KbP7QIjASuUFmfn0cTs:b-bb8vqn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5d53aa26be4d25caffa3de1f244494a3a54c8ea/vaadin-grid-table-cell.html#L249)):*
> ```HTML
>         if (this.columnResizing && e.detail.state === 'end') {
>           this.columnResizing = false;
>           this.column.fire('resized');
> ```

Not sure if this is necessary, `width-changed` should suffice?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-column.html, line 73 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbTw_eu4UiuNr9-ac0H:-KbTxL5jiILzk3coaCPz:b-uk65gp) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ca1759efad39f9661715e042109fa066d579444e/vaadin-grid-column.html#L73)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

When `resizable` is applied on a `<vaadin-grid-column-group>` I think it should set `resizable` to `true` on all of its child columns. In the current revision, the "Valo" styling demo has weird behavior where for example the "Last Name" column can be resized only from the middle header row.
</blockquote></details>

This gives the developer a possibility to select the row on which he places the resizers. Check out the original Valo demo: http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features

---

*[vaadin-grid-table-cell.html, line 249 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbP7QIi9mUHRm1BaBb9:-KbTy0oioLvwwIybGGQn:b-19z9ac) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5d53aa26be4d25caffa3de1f244494a3a54c8ea/vaadin-grid-table-cell.html#L249)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Not sure if this is necessary, `width-changed` should suffice?
</blockquote></details>

Hmm...you are probably looking at some older revision. We discussed this in person yesterday and decided to drop firing a dedicated event. This was fixed already.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-column.html, line 73 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbTw_eu4UiuNr9-ac0H:-KbV9wc39gu3bhW27YfA:b-d7265c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ca1759efad39f9661715e042109fa066d579444e/vaadin-grid-column.html#L73)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This gives the developer a possibility to select the row on which he places the resizers. Check out the original Valo demo: http://demo.vaadin.com/sampler/#ui/grids-and-trees/grid/features
</blockquote></details>

I'm not sure if that's a real use-case? Why wouldn't you allow resizing on each row?

---

*[vaadin-grid-table-cell.html, line 249 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbP7QIi9mUHRm1BaBb9:-KbV9lxeoSC4028GElAb:bbbmzel) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5d53aa26be4d25caffa3de1f244494a3a54c8ea/vaadin-grid-table-cell.html#L249)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm...you are probably looking at some older revision. We discussed this in person yesterday and decided to drop firing a dedicated event. This was fixed already.
</blockquote></details>

Yeah that comment was apparently something I wrote but didn't submit earlier – now it did :-) 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by jouni** [comment]
> I'm not sure if that's a real use-case? Why wouldn't you allow resizing on each row?

This way, the developer can let the end user resize the last frozen column from any level of headers, for instance. As there is a divider line there by default, it gives a strong visual indication that the end users should be able to resize from there also.

**Comment by tomivirkki** [comment]
Each row on the last frozen column can already be marked resizable by the developer. I guess what Sauli is asking that should all rows below a row that's marked resizable be automatically be marked resizable also. My point was that this would disallow developer from placing the handles like they currently are in the original valo demo (only the middle row).

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-:-KbVTDJJ4h-UmnG9Wa_2:b-d3vj0q)*

**Comment by tomivirkki** [comment]
Review status: 5 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column.html, line 73 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-KbTw_eu4UiuNr9-ac0H:-KbirkEtSf3cCg5jlZOF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ca1759efad39f9661715e042109fa066d579444e/vaadin-grid-column.html#L73)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I'm not sure if that's a real use-case? Why wouldn't you allow resizing on each row?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by manolo** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 4 of 10 files at r2, 1 of 3 files at r3, 5 of 5 files at r6.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/672#-:-KbjZwOoN9_rum0AFzVD:bnfp4nl)*

**Pull request merged**
