### PR TITLE
1058: Respect null and undefined when sorting columns

### LINKED ISSUE #1058: Sorting with empty data cells does not work correctly under version 1.2
Currently the grid contains as data for empty cells the 'value' undefined. Internally vaadin-grid compares two cells a and b with the < and > operator. One problem is that some value > undefined and some value < undefined is always false. This could lead to missorting of the grid.
One possible workaround is to store an empty string as value instead of undefined. So it applies:
some value > ''  => true     and
some value < '' => false

A better solution would be to modify the [compare function used in the method '_sortOrderChanged'](https://github.com/vaadin/vaadin-grid/blob/1.x/vaadin-grid.html#L1246) to something like this:
```
      function _compare(a, b) {
        if(a===undefined && b !== undefined){
          return 1;
        }
        if(b===undefined && a !== undefined){
          return -1;
        }
        if(a===undefined && b===undefined){
          return 0;
        }
        return (a < b ? -1 : a > b ? 1 : 0);
      }
```
Note additionally that Array.sort which is used from vaadin-grid is not stable: 
https://en.wikipedia.org/wiki/Sorting_algorithm#Stability
So vaadin-grid does not keep the other columns sorting while sorting one column multiple times.

### PR DESCRIPTION
**Pull request by newlukai**
Fixes #1058

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1122)

### CODE REVIEW

**Comment by newlukai** [comment]
Seems that the Travis build is fine, but the tests fail due to missing Sauce credentials. How could I fix that?

**Comment by web-padawan** [comment]
@newlukai Currently, our team is inclined not to introduce features to the 1.x branch.
Would it be an option for you to use 3.x instead, which is a hybrid version? 
If not, we might consider this fix, but please add tests for it.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1122#-:-KzTI9WTCqx9ALWPTC8Z:b-hpwnzm)*

**Comment by newlukai** [comment]
@web-padawan: You make a good point, I didn't find any information about which vaadin-grid version is compatible to which Polymer version. Vaadin-grid 2.x already includes the change I proposed here, but is it able to run with Polymer 1.x (we still didn't manage to migrate)?
If yes, I would consider to update.

**Comment by web-padawan** [comment]
@newlukai you're right, this definitely needs to be documented. We will take care of that, but as for now, here is the short description:

- 1.x is the Polymer 1.x version based on extending native elements (like `td`), which is no longer an option in Polymer 2
- 2.x is the Polymer 1.x version which dropped internal table structure in favor of being more flexible 
- 3.x is the hybrid version (both 1.x and 2.x) having mostly the same implementation
- 4.x is the pure Polymer 2.x class-based version, having table structure re-implemented under the hood.

I would recommend trying 2.x and 3.x for using with Polymer 1.x - if your project is using Polymer 1.8+ the hybrid version os the better choice. I will also take a look at #1081 to ensure it can be installed properly.

**Pull request closed without merging**
