### PR TITLE
Add v2 announce to README

### PR DESCRIPTION
**Pull request by limonte**
Connects to #673 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/705)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-KcvyAMJVbP-FwMLuHO9:-KcvyAMJVbP-FwMLuHOA:b-1ulrsq) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa10f8f29666dd35bebab352fa94bbe019963bac/README.md#L7)):*
> ```Markdown
> [&lt;vaadin-grid&gt;](https://vaadin.com/elements/-/element/vaadin-grid) is a free, high quality data grid / data table [Polymer](http://polymer-project.org) element, part of the [Vaadin Core Elements](https://vaadin.com/elements).
> 
> > :rocket: The upcoming [vaadin-grid v2](https://github.com/vaadin/vaadin-grid/tree/2.0-dev) release with a lot of exciting improvements is almost ready! Please see the [Migration Guide](https://github.com/vaadin/vaadin-grid/wiki/Migration-from-1.*-to-2.0) to find out what's changing.
> ```

Use brackets around the element name, please: `<vaadin-grid>`.

---

*[README.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-KcvyVf3geD5UkU5mmk4:-KcvyVf3geD5UkU5mmk5:b-5mf2g3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa10f8f29666dd35bebab352fa94bbe019963bac/README.md#L7)):*
> ```Markdown
> [&lt;vaadin-grid&gt;](https://vaadin.com/elements/-/element/vaadin-grid) is a free, high quality data grid / data table [Polymer](http://polymer-project.org) element, part of the [Vaadin Core Elements](https://vaadin.com/elements).
> 
> > :rocket: The upcoming [vaadin-grid v2](https://github.com/vaadin/vaadin-grid/tree/2.0-dev) release with a lot of exciting improvements is almost ready! Please see the [Migration Guide](https://github.com/vaadin/vaadin-grid/wiki/Migration-from-1.*-to-2.0) to find out what's changing.
> ```

FYI: Overall, this is pretty informal due to using the exclamation mark and contractions like `what's`.

This is fine by me, especially in README. Just want to note, that informal style does not sound quite aligned with the rest of the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-KcvyAMJVbP-FwMLuHO9:-Kcw-X0anHVhq0ScVEbW:bb7f2mf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa10f8f29666dd35bebab352fa94bbe019963bac/README.md#L7)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Use brackets around the element name, please: `<vaadin-grid>`.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705)*

**Comment by tomivirkki** [comment]
*[README.md, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-Kcw-n9FuMztRCqUOlrx:-Kcw-n9GXV6pzyxOG33s:b-ig6qa8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/37efb0495b1b297115388fa67ab7374f6c49ea78/README.md#L7)):*
> ```Markdown
> [&lt;vaadin-grid&gt;](https://vaadin.com/elements/-/element/vaadin-grid) is a free, high quality data grid / data table [Polymer](http://polymer-project.org) element, part of the [Vaadin Core Elements](https://vaadin.com/elements).
> 
> > :rocket: The upcoming [&lt;vaadin-grid&gt; v2](https://github.com/vaadin/vaadin-grid/tree/2.0-dev) release with a lot of exciting improvements is almost ready! Please see the [Migration Guide](https://github.com/vaadin/vaadin-grid/wiki/Migration-from-1.*-to-2.0) to find out what's changing.
> ```

Is there a reason this mentions the grid 2 as “upcoming” and “almost ready” (= temporary info we’ll have to remove once we release the stable)? IMO a link to the migration guide should be enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-Kcw-n9FuMztRCqUOlrx:-Kcw0MzTkcc2J-bfxmaZ:b70rpj6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/37efb0495b1b297115388fa67ab7374f6c49ea78/README.md#L7)):*
What's wrong with “upcoming” and “almost ready”? :)

> temporary info we’ll have to remove once we release the stable

I'll take 4.5 seconds to perform this task :)

> IMO a link to the migration guide should be enough

How do people know where to find it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705)*

**Comment by tomivirkki** [comment]
*[README.md, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-Kcw-n9FuMztRCqUOlrx:-Kcw1SXK8IvUOTJtDZF9:b-2jtizx) ([raw file](https://github.com/vaadin/vaadin-grid/blob/37efb0495b1b297115388fa67ab7374f6c49ea78/README.md#L7)):*
> What's wrong with “upcoming” and “almost ready”? :)

Nothing wrong, it just doesn't serve any purpose in a development branch's readme :)

> How do people know where to find it?

Umm, what? I meant that having the link with the explanation is ok here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705)*

**Comment by tomivirkki** [comment]
*[README.md, line 7 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-Kcw-n9FuMztRCqUOlrx:-Kcw3TgPdNVuqBIQjUZ4:b-g2ato) ([raw file](https://github.com/vaadin/vaadin-grid/blob/37efb0495b1b297115388fa67ab7374f6c49ea78/README.md#L7)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

> What's wrong with “upcoming” and “almost ready”? :)

Nothing wrong, it just doesn't serve any purpose in a development branch's readme :)

> How do people know where to find it?

Umm, what? I meant that having the link with the explanation is ok here.
</blockquote></details>

Wasn't aware this is targeting master, nevermind.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/705#-:-KcwnCAwD50uBrosyr9l:bnfp4nl)*

**Pull request merged**
