### PR TITLE
Fix/localizer

### LINKED ISSUE #727: AppLocalizeBehavior not working in header of vaadin-grid-2
Hello,

I created a simple vaadin-grid component, with localization in the header, but unfortunately it doesn't work.

Chrome console output:

> Uncaught TypeError: Cannot read property 'name' of null
    at TemplateInstance._annotatedComputationPathEffect (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:2272:32)
    at TemplateInstance._pathEffector (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:2242:6)
    at TemplateInstance._notifyPath (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:2143:6)
    at TemplateInstance.notifyPath (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:2137:6)
    at http://localhost:8080/pension/static/bower_components/vaadin-grid/vaadin-grid-table-cell.html:235:18
    at Array.forEach (native)
    at HTMLTableCellElement._forwardedParentPropsChanged (http://localhost:8080/pension/static/bower_components/vaadin-grid/vaadin-grid-table-cell.html:234:35)
    at HTMLTableCellElement._complexObserverEffect (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:1654:4)
    at HTMLTableCellElement._complexObserverPathEffect (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:2263:37)
    at HTMLTableCellElement._pathEffector (http://localhost:8080/pension/static/bower_components/polymer/polymer.html:2242:6)

The code:
```
<iron-ajax id="xhr" auto
      url="[[url]]"
      last-response="{{contributionDetails}}"
      handle-as="json">
</iron-ajax>

    <vaadin-grid id="grid" items="[[contributionDetails]]">
      <vaadin-grid-column>
        <template class="header">
          <vaadin-grid-filter path="contributionLine.organisationId"></vaadin-grid-filter>
          <vaadin-grid-sorter path="contributionLine.organisationId"> [[localize('orgId')]]</vaadin-grid-sorter>
        </template>
        <template><span class="label label-default">[[item.contributionLine.organisationId]]</span></template>
      </vaadin-grid-column>
    </vaadin-grid>
```
I'm using the version 2.0.0-pre.2 of the component.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #727

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/869)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/869#-:-KisouDpozME_E51IjRF:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 5 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-templatizer.html, line 106 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/869#-KjH7RmVF9b82GXArpsL:-KjH7RmVF9b82GXArpsM:boh006f) ([raw file](https://github.com/vaadin/vaadin-grid/blob/55ce97f516799d530fff0757bed8628a493f3a4a/vaadin-grid-templatizer.html#L106)):*
> ```HTML
> 
>         templateInstances.forEach(function(inst) {
>           inst[prop] = value;
> ```

`inst[prop] = value`, `inst.notifyPath(prop, value)` and `inst.set(prop, value)` do basically the same thing so only one of them should be enough.

However, I have a feeling that `inst[prop] = value` will crash in the case of `prop` being a subproperty like `foo.bar` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/869)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-templatizer.html, line 106 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/869#-KjH7RmVF9b82GXArpsL:-KjHDq3UUsiEf-iJ1CHg:bsyi5qe) ([raw file](https://github.com/vaadin/vaadin-grid/blob/55ce97f516799d530fff0757bed8628a493f3a4a/vaadin-grid-templatizer.html#L106)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

`inst[prop] = value`, `inst.notifyPath(prop, value)` and `inst.set(prop, value)` do basically the same thing so only one of them should be enough.

However, I have a feeling that `inst[prop] = value` will crash in the case of `prop` being a subproperty like `foo.bar` ?
</blockquote></details>

`inst[prop] = value` doesn't crash with sub-properties, but will assign an invalid property to the instance (with name "foo.bar"). `set(prop, value)` seems to be enough here :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/869)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 4 of 6 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/869#-:-KjI_VE7CTP_9bQk0li3:bnfp4nl)*

**Pull request merged**
