### PR TITLE
[Optimization] Delay requestAnimationFrame() to speed large detailsOpenedItems changes

### PR DESCRIPTION
**Pull request by moderndeveloperllc**
Don't resize on every details row if we are looping. We can wait for the next frame render. This will help when a large amount of rows is added to `detailsOpenedItems`. Can get a 200%+ speed increase for 100+ details rows. Further optimization may be possible by trying to minimize the times that `offsetHeight` is called on cells as that causes a synchronous style/layout recalc, but that's beyond my ability.

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
FYI, on my code with 101 rows, opening all went from 9 seconds to 2 seconds.

**Comment by Haprog** [comment]
I assume this is for fixing #1655?

**Comment by moderndeveloperllc** [comment]
@Haprog,  yes, forgot to link. As you can see, I did manage to get it to pass the test suite after a bit of redoing.

**Comment by moderndeveloperllc** [comment]
@Haprog Anything I can do to help move this along? It would really help as I have lots of pages with lots of details being opened for lots of items.

**Comment by tomivirkki** [comment]
The change seems to make UX of opening the row details a bit worse on IE11 and Edge. Could this glitch be prevented somehow?

Before:
Kapture 2019-10-17 at 11 32 29
After:
Kapture 2019-10-17 at 11 34 28

**Comment by moderndeveloperllc** [comment]
@tomivirkki I fixed the IE/Edge FOUC and sped up the `_updateDetailsCellHeights()` method. By reading the property, then writing the style, the method was sped up be about 40%. I tested this out on the `grid-row-details-demo.html` page by making the first grid `height-by-rows`, adding a `<vaadin-grid-selection-column>` and then the listener from above. I know that the renderer isn't really optimized for that `height-by-rows`, open-all-details kind of thrashing, but this is my attempt to help in these edge cases.

In my case I have clients with 100+ customers who have lots of orders. I hide the orders in the detailsRow, but have always given them the opportunity to open all customers at once and see all the orders at once. Hence the `height-by-rows` and `grid.detailsOpenedItems = grid.selectedItems` logic.

**Comment by tomivirkki** [comment]
Thanks for the update, I'll take another look this week

**Comment by tomivirkki** [comment]
@moderndeveloperllc It's probably not the changes in `_updateDetailsCellHeights()` that improved the performance. Effectively it does exactly the same as the master revision, but with two iterations. I tried reverting the `_updateDetailsCellHeights()` to the master revision but kept the rest of the changes and the same performance improvements were still there.

It's probably the removed lines in `_toggleDetailsCell` that synchronously measured the row's offsetHeight and added it as the padding-bottom to the row. With the changed revision, the measuring is done asynchronously, which improves performance but causes a glitch (recorded on Chrome with the demo changes you suggested):

Kapture 2019-11-15 at 10 48 19

**Comment by moderndeveloperllc** [comment]
@tomivirkki The `_updateDetailsCellHeights` help comes when you are opening all the rows at once, but you are correct in that its not where the majority of the improvement comes from. I didn't see that stutter when I was testing, though I guess that might be because I'm on a rather new, fast machine.

Do you see any way forward?

**Comment by tomivirkki** [comment]
Maybe the details cell could have a separate `opened` state attribute which only gets applied once the opening is finished (in the end of the requestAnimationFrame). Then in `vaadin-grid-styles.html`:
```
[part~="details-cell"]:not([opened]) {
  visibility: hidden;
}
```

**Comment by moderndeveloperllc** [comment]
Not sure how much I can work on that at the moment, but it might be work looking into.

**Comment by moderndeveloperllc** [comment]
@tomivirkki Any chance of this getting looked at? Rendering seems to be an issue even if the details aren't viewed at the outset. 480 rows with details hidden tool about 30 secs to render on a _fast_ machine. 

ScreenShot 2020-03-20 at 11 00 42 AM

**Comment by moderndeveloperllc** [comment]
I should note that even with this PR's changes, the first render of the 400+ rows is fast, but it seems to throw Chrome's renderer into a fit. It takes about 30 seconds to be able to scroll or do anything on the page. That means this PR's fixes are probably a wash.

**Comment by tomivirkki** [comment]
@moderndeveloperllc I'm spending some time next week on the grid's performance analysis. I'll make sure to include this issue/PR.

**Comment by moderndeveloperllc** [comment]
@tomivirkki Let me know if there is anything I can do to help. On a related not to the details rendering,  I've also noticed is that if the columns have a default sort order, the column renders will go through there cycle before _and_ after the sort happens. Perhaps there may be a way to delay the rendering until after the default sort happens?

**Comment by moderndeveloperllc** [comment]
@tomivirkki Have you had an opportunity to look into this? Should I close out this PR as it looks like the code, as is, won't help, or do you want to keep it active as it's a partial answer for the moment?

**Comment by tomivirkki** [comment]
@moderndeveloperllc I'm currently working on performance tests for the grid (Flow). Added a grid with the row details open as one of the cases; not sure if it covers this use-case properly, though. Would appreciate if you'd take a look and possibly suggest some changes to the test case: https://github.com/vaadin/vaadin-grid-flow/tree/benchmark Once the tests are in place, we'll evaluate different options for optimizing the grid's performance.

**Comment by moderndeveloperllc** [comment]
@tomivirkki I'm not a Java dev, but from what I can parse out, I don't think this case is covered. I see where in integration tests you are checking that when two checkboxes are opened, they both display, but I don't see anywhere in benchmarks where you are testing the selectAll box being checked and detailsOpenedItems == selectedItems. This with a renderer for the details row is the heart of the matter.

**Comment by moderndeveloperllc** [comment]
@tomivirkki Going to close as the move to Polymer 3 is going to invalidate any pulls. I'll see when it moves to beta if this is still an issue.

**Pull request closed without merging**
