### PR TITLE
Format autogenerated column headers.

### LINKED ISSUE #251: Format autogenerated default header content
Formatting rules:
- Drop everything up to last "."
- Strip all characters except a-z and 0-9
- Capitalize first letter
- Detect uppercase letters before lowercase letters and put a space in between

Add unit tests for all different formattings.

We should use the code from the Vaadin Framework if at all possible (SharedUtil.camelCaseToHumanFriendly).

### PR DESCRIPTION
**Pull request by manolo**
Fixes #251

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/261)

### CODE REVIEW

**Comment by tomivirkki** [comment]
There should be release notes in the pr

---

Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[demo/headers.html, line 481 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3TcV1KxmGq8IVHU19L:-K3TcV1KxmGq8IVHU19M:-1318963839) ([raw file](https://github.com/vaadin/vaadin-grid/blob/15b7226a00ec717ebbc3b4721346ce28c5c6f63b/demo/headers.html#L481)):_
Since we're using first and last names in the demo, it kind of screams for the random user api that's commonly used in the examples. This currently produces "FirstName-1" and "LastName-1" (suffixed with indexes) which is not too nice in a demo.

---

_[java/src/main/java/com/vaadin/elements/grid/table/GridLightDomTable.java, line 166 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3TbiR1_4TMRDeiM92P:-K3TbiR1_4TMRDeiM92Q:1504426642) ([raw file](https://github.com/vaadin/vaadin-grid/blob/15b7226a00ec717ebbc3b4721346ce28c5c6f63b/java/src/main/java/com/vaadin/elements/grid/table/GridLightDomTable.java#L166)):_
This is wrong class for doing the auto-formatting. The functionality should work in all cases, not just when using light dom table configuration. For example if one uses grid.addColumn JS api

---

_[test/grid-editing-columns.html, line 454 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3Tc4bMSq5vunC0S21U:-K3Tc4bMSq5vunC0S21V:-1622661366) ([raw file](https://github.com/vaadin/vaadin-grid/blob/15b7226a00ec717ebbc3b4721346ce28c5c6f63b/test/grid-editing-columns.html#L454)):_
This test is not enough. We also need to test that a nested property like item.name.first translates right = test all the new logic like cutting everything until last dot and so on

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-:-K3Td5rvW7B0awP0Jx2x:-1539925789)_

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

_[demo/headers.html, line 481 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3TcV1KxmGq8IVHU19L:-K3VD0gp0jD2sqUSRj3e:1934439889) ([raw file](https://github.com/vaadin/vaadin-grid/blob/15b7226a00ec717ebbc3b4721346ce28c5c6f63b/demo/headers.html#L481)):_
Changed it by static json with a couple of users, I don't want to introduce ajax in the example so as reader is able to see the json structure and levels.

---

_[java/src/main/java/com/vaadin/elements/grid/table/GridLightDomTable.java, line 166 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3TbiR1_4TMRDeiM92P:-K3VDM-3xBqiopajejuE:-890283906) ([raw file](https://github.com/vaadin/vaadin-grid/blob/15b7226a00ec717ebbc3b4721346ce28c5c6f63b/java/src/main/java/com/vaadin/elements/grid/table/GridLightDomTable.java#L166)):_
moved to GridStaticSection

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261)_

**Comment by tomivirkki** [comment]
_[demo/headers.html, line 527 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3YoSkE4lOyGMIZ3P-M:-K3YoSkE4lOyGMIZ3P-N:582575555) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e075c1adec91f346a9920b31df7c96b24dd3b5b5/demo/headers.html#L527)):_
This isn't quite right yet. How it works is that if the content of a header cell _on the default header row_ hasn't content defined, it falls back to the column name (if available) converted to human-readable form. The result has nothing to do with json data or grid data in general.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261)_

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

_[demo/headers.html, line 527 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3YoSkE4lOyGMIZ3P-M:-K3ZT_2nRpkFkF2qtmyF:1832113859) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e075c1adec91f346a9920b31df7c96b24dd3b5b5/demo/headers.html#L527)):_
The result depends on the name, and the name specifies the property in the json structure. So it depends on the data source. I want to demo that user.name.firstName is converted to 'First Name' . 
I thing the demo is quite illustrating  don't see the need to complicate it more.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261)_

**Comment by tomivirkki** [comment]
_[demo/headers.html, line 527 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3YoSkE4lOyGMIZ3P-M:-K3Z_1MZY0cZJZrX-TFe:-1358218592) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e075c1adec91f346a9920b31df7c96b24dd3b5b5/demo/headers.html#L527)):_
I'm not talking about changing the demo. Just the description because there it's not right. The headers would show the same with any datasource or no data source at all. What's shown in the header is totally independent from the data.

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261)_

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

_[demo/headers.html, line 527 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261#-K3YoSkE4lOyGMIZ3P-M:-K3_3l4emyXe7uvfuOaG:1871972306) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e075c1adec91f346a9920b31df7c96b24dd3b5b5/demo/headers.html#L527)):_
I see. modified

---


_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261)_

**Comment by tomivirkki** [comment]
Reviewed 1 of 6 files at r1, 5 of 7 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/261)_

**Pull request merged**
