### PR TITLE
Feature/flatten data

### LINKED ISSUE #160: Flatten data properties
The current nested properties syntax for some of the API is not very Polymer-like, and seems more complex than needed.

### Proposal:

```
data.source (array) -> items
data.source (function) -> datasource
data.sortOrder -> sortOrder (notify: true)
data.clearCache() -> clearCache()
data.getItem() -> getItem()
```

Keep the old API available, but output a deprecation warning to the browser console that the old API will be removed in the next minor version.

Collateral damage (needs to be done also):
- [x] Update code examples
 - Polymer integration example should be refactored to showcase the Polymer “databindability”
- [x] Update API docs
- [x] Update tests
- [x] Write clear release notes / migration guide about the changes
- [ ] Update JSFiddles
- [x] READMEs
- [ ] Notify marketing to update demos

### PR DESCRIPTION
**Pull request by Saulis**
Resolves #160

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/195)

### CODE REVIEW

**Comment by Saulis** [comment]
Reviewed 1 of 20 files at r2, 1 of 8 files at r3, 1 of 1 files at r5.
Review status: 3 of 26 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[vaadin-grid-doc.html, line 116 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K-xCOZPI-X1uAgkC_Wz)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/763f72d991014b4a1f16e10e865cb05d999d34f4/vaadin-grid-doc.html#L116)):</sup>
Needs to be removed, examples could be moved as they are to `vaadin-grid.html` ?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by tomivirkki** [comment]
<sup>**[demo/datasources.html, line 56 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K-xDqpeX7LGox9N0TLH)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/763f72d991014b4a1f16e10e865cb05d999d34f4/demo/datasources.html#L56)):</sup>
This is no longer true


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by Saulis** [comment]
Reviewed 3 of 13 files at r1, 12 of 20 files at r2, 6 of 8 files at r3, 2 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[demo/datasources.html, line 56 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K-xDqpeX7LGox9N0TLH)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/763f72d991014b4a1f16e10e865cb05d999d34f4/demo/datasources.html#L56)):</sup>
Done.


---

<sup>**[vaadin-grid-doc.html, line 116 \[r5\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K-xCOZPI-X1uAgkC_Wz)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/763f72d991014b4a1f16e10e865cb05d999d34f4/vaadin-grid-doc.html#L116)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by tomivirkki** [comment]
<sup>**[demo/react.html, line 57 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K01d5AnBnuaBTlQmkwT)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c05688629fdc413737240c934e9f3942842b4af7/demo/react.html#L57)):</sup>
This never evaluates truthy


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by Saulis** [comment]
Review status: 21 of 31 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[demo/react.html, line 57 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K01d5AnBnuaBTlQmkwT)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/c05688629fdc413737240c934e9f3942842b4af7/demo/react.html#L57)):</sup>
Nice catch.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by tomivirkki** [comment]
Review status: 20 of 31 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

<sup>**[demo/polymer.html, line 93 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K059UyiTc1rZI5ok9c1)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/demo/polymer.html#L93)):</sup>
The last two examples are almost identical. We should demonstrate datasource binding functionality in these demos but there's no point in showing the same thing twice for different types. Different ds types are already covered in datasources.html examples


---

<sup>**[java/src/main/java/com/vaadin/components/grid/GridComponent.java, line 515 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K0598PIAEbMPTxeX9mw)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/java/src/main/java/com/vaadin/components/grid/GridComponent.java#L515)):</sup>
Selection model should be reset even if the sort is not user originated, perhaps clearDataSourceCache too


---

<sup>**[vaadin-grid.html, line 929 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K058fFw3tPRvD6wcQaV)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/vaadin-grid.html#L929)):</sup>
Type validations could be done in GWT like for other properties


---

<sup>**[vaadin-grid.html, line 935 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K058_NhEkWrL5KHOD9e)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/vaadin-grid.html#L935)):</sup>
this._items is not used anywhere.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by Saulis** [comment]
Review status: 18 of 31 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[demo/polymer.html, line 93 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K059UyiTc1rZI5ok9c1)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/demo/polymer.html#L93)):</sup>
Done.


---

<sup>**[java/src/main/java/com/vaadin/components/grid/GridComponent.java, line 515 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K0598PIAEbMPTxeX9mw)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/java/src/main/java/com/vaadin/components/grid/GridComponent.java#L515)):</sup>
Done.


---

<sup>**[vaadin-grid.html, line 935 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K058_NhEkWrL5KHOD9e)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/b5311a4c15c9f4cb2a545a0addfcdc1983363499/vaadin-grid.html#L935)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by tomivirkki** [comment]
<sup>**[demo/react.html, line 57 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K05y9QrMlnSrrZ9bz37)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/9d67b25548458cf17be0e2ff641f71f067cbcb39/demo/react.html#L57)):</sup>
It still doesn't evaluate truthy :) Did you test it?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by Saulis** [comment]
Review status: 18 of 31 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[demo/react.html, line 57 \[r9\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195#-K05y9QrMlnSrrZ9bz37)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/9d67b25548458cf17be0e2ff641f71f067cbcb39/demo/react.html#L57)):</sup>
Got me!


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Comment by tomivirkki** [comment]
Reviewed 4 of 10 files at r6, 1 of 4 files at r8, 1 of 1 files at r9.
Review status: 23 of 31 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/195)

**Pull request merged**
