### PR TITLE
Unify type annotations

### LINKED ISSUE #483: @type annotations for function appear to be invalid
It looks like the `@type` annotations used for function are not valid Closure annotations, resulting in the following errors:

1x:
WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
       \* @type {(Array<Object>|function)}
3x:
WARNING - Bad type annotation. missing opening ( See https://github.com/google/closure-compiler/wiki/Bad-Type-Annotation for more information.
     \* @type {function}

Specifying the full function type should correct these issues.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #483

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/528)

### CODE REVIEW

**Comment by samiheikki** [comment]
Seems like there are a lot of functions in vaadin-grid.html with @param annotations with a type, but the types are in lowercase. For example getItem, refreshItems, setRowDetailsVisible and other functions. Should they be fixed?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-doc.html, line 397 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-KWbpLlP1FZqF1dIiQYv:-KWbpLlP1FZqF1dIiQYw:b2ccjs0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ba017d4931132dd0cb039f47815fa7c46d92c26c/vaadin-grid-doc.html#L397)):*
> ```HTML
>      * Returns an object reference to a particular header cell.
>      *
>      * @param {String} rowIndex - Index of the row.
> ```

Change back to Number

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWbr9K7ycJdMdnwT63A:b-w3i5ro)*

**Comment by manolo** [comment]
Be aware that all those annotations make sense for the gwt-api-generator, it has already certain rules for consolidate everything and camellize, etc.  I will check that all changes to see if the generated code is ok

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWgtN4CsnKp8nrWfLGO:baich5i)*

**Comment by manolo** [comment]
Tested with the generator, and the API produced is the same.

IIRC, we did change behavior names to downcase and hyphen in order to be displayed better in the documentation.
Ping @jouni . Is this ok for you?





---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWh1xLrkXtF0NjkSy_t:bj2euw2)*

**Comment by jouni** [comment]
Yes, the documentation was the main reason, that it looked more coherent with kebab-case. Those names are also used in the descriptions of some of the API documentation, so it might be good to revise them as well.

**Comment by Saulis** [comment]
Fixed the descriptions inside documentation to be coherent.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-doc.html, line 397 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-KWbpLlP1FZqF1dIiQYv:-KWieI8l3evoM0dzoR2f:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ba017d4931132dd0cb039f47815fa7c46d92c26c/vaadin-grid-doc.html#L397)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Change back to Number
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWieLoOGkTXFGd70GQ9:bpqsmkz)*

**Comment by manolo** [comment]
Documentation in Polymer is CamelCase so I think it's ok to use it here as well. 



A different question is if we should prefix these classes with a namespace like `Vaadin.Column` or something. 
The only thing is that we use these as plain javascript objects to configure the grid not as behaviours .

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWq7cbEKV5K8CCRRhgE:bg1rquy)*

**Comment by manolo** [comment]
Well, it's not necessary that we set namespaces here. These are actually plain JS objects that we don't declare as functions. We have to declare as behaviours in order to have then documented and to generate the java code.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWqAyHkbwNgjn5cIg9i:b-u8uah7)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWqBT3WqBk9fem1uSLc:bnfp4nl)*

**Comment by samiheikki** [comment]
:lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/528#-:-KWqEQ0x6l6wNr8Pf2gG:bg7igkv)*

**Pull request merged**
