### PR TITLE
Remove deprecated ng2 directives

### PR DESCRIPTION
**Pull request by manolo**
Connected to vaadin/components-team-tasks#179

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/446)

### CODE REVIEW

**Comment by tehapo** [comment]
Please also remove references to the `directives` directory from the `gulpfile.js` to make sure the `ng2` and `ng2:watch` tasks still work.

See if we need to restore the `tsconfig.json` file into to the `test/angular2` directory to be able to compile the `test/angular2/main.ts` with the Gulp tasks?

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/446#-:-KQ4M4i_0X_faVDMqsTF:b5dvgbt)*

**Comment by tehapo** [comment]
And also remove `directives` reference from `.gitignore` file. :smile: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/446#-:-KQ4NDzZ5-HLdntziHmg:b-hl4jyu)*

**Comment by manolo** [comment]
done

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/446#-:-KQ4kc8em0LYdqb4apIa:bb7f2mf)*

**Comment by tehapo** [comment]
But now the `gulp ng2` task does not work anymore. I fixed this on my local environment, so I'll just add another commit to this branch instead of commenting further.

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/446#-:-KQ5Crxw2EpvHVpHUIB3:b-3w8wh1)*

**Comment by tehapo** [comment]
Reviewed 6 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/446)*

**Comment by manolo** [comment]
I see now. I misunderstood the point. :lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/446#-:-KQ5HopTE9A1ylqPMrB3:bgn3bgr)*

**Pull request merged**
