### PR TITLE
Header text-align should respect writing direction

### PR DESCRIPTION
**Pull request by jouni**
If a parent element has `dir="rtl"`, the header texts should be aligned correctly as well.

IE11 and Edge don’t work with `initial`. All browsers except Safari work with `inherit`, but I don’t know a way to target Safari only – hence the IE11 and Edge specific workarounds.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1215)

### CODE REVIEW

**Comment by platosha** [comment]
Have you tried `text-align: unset;`? I suspect this should work for everything:

```css
tr {
  text-align: inherit;
  text-align: unset;
}
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L4eHar7_5LGs25cy6TC:b-sarw3j)*

**Comment by platosha** [comment]
Oh, let’s mention IE11 so that we remember what to throw away:

```css
tr {
  text-align: unset;
  text-align: inherit; /* MSIE 11 */
}
```

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L4eIzlPHjEUGWLQ68Bi:b-c6glun)*

**Comment by platosha** [comment]
https://caniuse.com/#search=css%20unset

(Using `tr` selector is just here, because we fix the UA stylesheet in this case, which is specifically targeting `tr` too.)

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L4eJJgnrUAIWGJQFi6d:b-2c14ye)*

**Comment by platosha** [comment]
P. S.: I mean `th`, of course. Not `tr`.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L4eJoTp0e1NrfE6RTl9:b-40u0k1)*

**Comment by jouni** [comment]
Just tried `unset`, and it’s the same as `inherit` in Safari – doesn’t work, the headers are always left-aligned.

But you’re right about the selector. Let’s use `th` instead.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L4tOE35jZG1GaTNTpyL:b-nbk62y)*

**Comment by platosha** [comment]
BTW you can probably target safari with `[safari]`: https://github.com/vaadin/vaadin-grid/blob/8b439b6846a881ab9684e55ae3c8bb46b488bad6/src/vaadin-grid.html#L36

Please make short comments in CSS for any quirks, see this file for examples.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L4tk3ZG1D3_VDyy7AcG:b7srslw)*

**Comment by tomivirkki** [comment]
Ping @jouni

**Comment by jouni** [comment]
Changed the workaround from Edge & IE11 to Safari.

Less code this way, but it’s now depending on the attribute on the scroller. If we ever remove that, the styles stop working. I’m wondering if we should add a test for this somehow?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1215#-:-L8aBaMHh0NJJTbGUaiE:bh5jxyv)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1215#-:-L8gEZ595zUJ_T8XqZ-U:bnfp4nl)*

**Pull request merged**
