### PR TITLE
Fix how a target row gets scrolled into viewport

### LINKED ISSUE #1199: Grid content scrolls without any reasons when focus moves from header to the content
Live demo: https://jsfiddle.net/6r5htd05/115/

### Steps
 - focus a header cell
 - press Tab

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1199

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1213)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-scroller.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-L4_McAUs7gvBnOUK2Ux:-L4_McAUs7gvBnOUK2Uy:b-pntkyh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/830d0d4248c4aff9c43272c69cfb310f50a756f9/vaadin-grid-scroller.html#L90)):*
> ```HTML
>         if (row) {
>           const headerOffset = row.getBoundingClientRect().top - this.$.header.getBoundingClientRect().bottom;
>           if (Math.abs(headerOffset) > 1) { 
> ```

nit: trailing whitespace

---

*[test/scroll-to-index.html, line 143 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-L4_MjFH7Iqh-UFb9zwG:-L4_MjFH7Iqh-UFb9zwH:b-e68fv8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/830d0d4248c4aff9c43272c69cfb310f50a756f9/test/scroll-to-index.html#L143)):*
> ```HTML
>         it('should scroll close to end', () => {
>           const viewPortItemCount = Math.round(grid._viewportHeight / grid._physicalAverage - 1); // - header;
>           const targetIndex = grid.size - viewPortItemCount - 2;          
> ```

nit: trailing whitespaces

---

*[test/scroll-to-index.html, line 148 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-L4_Mjv2MRcUDHAOLw_i:-L4_Mjv2MRcUDHAOLw_j:b-e68fv8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/830d0d4248c4aff9c43272c69cfb310f50a756f9/test/scroll-to-index.html#L148)):*
> ```HTML
>           const rect = grid.$.header.getBoundingClientRect();
>           grid.$.outerscroller.hidden = true;
>           const cell = (Polymer.Settings.useShadow ? grid.shadowRoot : document).elementFromPoint(rect.left + 1, rect.bottom + 2);          
> ```

nit: trailing whitespaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213)*

**Comment by platosha** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213)*

**Comment by tomivirkki** [comment]
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-scroller.html, line 90 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-L4_McAUs7gvBnOUK2Ux:-L4_SZ7_r4WXoRmrHfR8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/830d0d4248c4aff9c43272c69cfb310f50a756f9/vaadin-grid-scroller.html#L90)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing whitespace
</blockquote></details>

Done.

---

*[test/scroll-to-index.html, line 143 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-L4_MjFH7Iqh-UFb9zwG:-L4_SZhlw8XppUXX7mZ7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/830d0d4248c4aff9c43272c69cfb310f50a756f9/test/scroll-to-index.html#L143)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing whitespaces
</blockquote></details>

Done.

---

*[test/scroll-to-index.html, line 148 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-L4_Mjv2MRcUDHAOLw_i:-L4_S_12jb_HXyXW7lV6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/830d0d4248c4aff9c43272c69cfb310f50a756f9/test/scroll-to-index.html#L148)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing whitespaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-:-L4_TEaPWosJe_gcJKtO:bnfp4nl)*

**Comment by limonte** [comment]
This change introduces the new issue:

peek 2018-02-05 13-43
 
### Steps to reproduce (on the same jsfiddle as in the issue description):

- focus the first header cell
- <kbd>Tab</kbd>
- <kbd>Arrow Down</kbd> (5 times)
- <kbd>Arrow Up</kbd>

### Actual: 



### Expected:

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213)*

**Comment by tomivirkki** [comment]
@limonte the regression is fixed (and tested) in the PR

**Comment by limonte** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213#-:-L4fGLmQ_zXWLXRODhfC:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 2 of 2 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1213)*

**Pull request merged**
