### PR TITLE
Doc: Add default value

### PR DESCRIPTION
**Pull request by stramel**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/826)

### CODE REVIEW

**Comment by Saulis** [comment]
Hi!

Isn't the default value is currently `undefined` ? Should we make it `false` at the same time what do you think?

**Comment by stramel** [comment]
@Saulis Currently, the docs are displaying `UNKNOWN` since it is a function. Adding `@default` should allow you to set it. You are correct it implicitly returns `undefined` currently on a `Boolean` property. I have no problem either way, just assumed Polymer would treat `undefined` as false on a `Boolean` property. Thinking about it more, it probably leaves it as `undefined`.  JSFiddle confirms it. https://jsfiddle.net/stramel/xpv5u9cc/2/

Would you like me to change the documentation to `undefined` or default property to `false` instead of `undefined`?

**Comment by Saulis** [comment]
@stramel I think making it would be an improvement to have both the documentation and actual default value to be `false` – if you could add an else clause returning `false` I'd be happy to merge this PR. Thanks!

**Comment by Saulis** [comment]
@stramel actually, nevermind – I'll give you a hand and add the else clause :smile:. 
Thanks for the PR!

**Pull request merged**
