### PR TITLE
Creates items array if is undefined in crud demo

### PR DESCRIPTION
**Pull request by obedsoto**
Make sure items array exists before the manipulation

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/911)

### CODE REVIEW

**Comment by obedsoto** [comment]
CLA signed.

**Comment by Saulis** [comment]
Hi! Can you show an example in which case the `items` would be `undefined` ? It should be always set by the `x-array-data-source` before any `_add` or `_remove` functions are called.

**Comment by obedsoto** [comment]
Hi @Saulis, yes you are right, but in my case I used this example with no data, I am using the element to let the user to add records, so there's no initial data to append. Demo works great with a data source.

**Comment by tomivirkki** [comment]
Closing as wontfix

**Pull request closed without merging**
