### PR TITLE
Make index a row details template instance property

### LINKED ISSUE #837: Row details does not have proper index value
According to the documentation in vaadin-grid, all templates used inside vaadin-grid have access to a few built-in variables, including:

"index": Number representing the row index

In case of multiple row details open at the same time, the template instances all get the same value (which I think is the index of the last details opened), instead of each getting their row's index.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #837

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/840)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/row-details.html, line 204 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840#-KgYp5UZfXb5YclhevXi:-KgYp5U_v07Cqd2FTLKW:b-k4bbd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3b408c9f8598af1c5ce9cb6fece2474ac45c3c63/test/row-details.html#L204)):*
> ```HTML
> 
>           var cells = getRowCells(bodyRows[1]);
>           expect(getCellContent(cells[1]).textContent.trim()).to.equal('1-details');
> ```

should we also test another cell to contain `'0-details'`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840#-:-KgYtf2pceCbOrIvu0Xj:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/row-details.html, line 204 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840#-KgYp5UZfXb5YclhevXi:-KgZIDx-9cyiGCHvETJb:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3b408c9f8598af1c5ce9cb6fece2474ac45c3c63/test/row-details.html#L204)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

should we also test another cell to contain `'0-details'`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: 1 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840#-:-KgZShyVapKUd2wGq0Wy:bnfp4nl)*

**Comment by limonte** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/840)*

**Pull request merged**
