### PR TITLE
Allow Polymer 1.x

### PR DESCRIPTION
**Pull request by billy-hardy**
Since the Hybrid Element is being used, the bower.json should allow Polymer 1.x as a resolution.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1059)

### CODE REVIEW

**Comment by billy-hardy** [comment]
fixes #1081

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[bower.json, line 50 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1059#-KzYPXsqoH5lATA43cLj:-KzYPXsqoH5lATA43cLk:b-7zm7du) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4d31f33819451e0b55e79b05a458054286e01649/bower.json#L50)):*
> ```JSON
>   },
>   "dependencies": {
>     "polymer": "1.x - 2",
> ```

The hybrid mode was introduced in the [1.7.0](https://www.polymer-project.org/1.0/docs/release-notes#v-1-7-0) release, but all the official elements actually use`1.9 - 2` 
So, why have you reverted that change in your last commit? I would expect having it aligned with official elements which are used as dependencies.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1059)*

**Comment by billy-hardy** [comment]
@web-padawan this was me not understanding how ranges work. I assumed it was a one or the other approach (so 1.9 or 2, but not 1.10)

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---

*[bower.json, line 50 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1059#-KzYPXsqoH5lATA43cLj:-L-1T6pb70iS9Kjd7ff6:bt2vr1b) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4d31f33819451e0b55e79b05a458054286e01649/bower.json#L50)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

The hybrid mode was introduced in the [1.7.0](https://www.polymer-project.org/1.0/docs/release-notes#v-1-7-0) release, but all the official elements actually use`1.9 - 2` 
So, why have you reverted that change in your last commit? I would expect having it aligned with official elements which are used as dependencies.
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1059)*

**Comment by billy-hardy** [comment]
@web-padawan are we able to merge this? Or is more work required?

**Comment by billy-hardy** [comment]
@web-padawan or @jouni any status of whether this can get in?

**Comment by tomivirkki** [comment]
Tested the branch and it still installs the right versions by default. So I don't see why this couldn't be merged. @web-padawan does the PR look ok to you?

**Comment by web-padawan** [comment]
@tomivirkki in order to reproduce the conflict, do the following steps:

```
mkdir test && cd test && yes '' | bower init
bower i polymer@1.11.0 --save
bower i vaadin-grid@3.0.2 --save
```

This will end up in the conflicts like this: 
```
Unable to find a suitable version for polymer, please choose one by typing one of the numbers below:
    1) polymer#1.9 - 2 which resolved to 1.11.0 and is required by iron-a11y-announcer#2.0.0, iron-a11y-keys-behavior#2.0.1, iron-resizable-behavior#2.0.1, iron-scroll-target-behavior#2.0.0
    2) polymer#1.11.0 which resolved to 1.11.0 and is required by test
    3) polymer#^2.0.0 which resolved to 2.4.0 and is required by vaadin-grid#3.0.2
```

So yes, the PR is valid and looks good to me.

**Comment by tomivirkki** [comment]
LGTM

**Pull request merged**
