### PR TITLE
Fix: The grid disappears on Safari once you stop scrolling.

### PR DESCRIPTION
**Pull request by manolo**
Connects to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/957)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid-scroller.html, line 184 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-Kso1ISp6RlSXD_oUZut:-Kso1ISp6RlSXD_oUZuu:b-oz40kw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b6835e21da00127b4356d1c1025b431c71f90a91/vaadin-grid-scroller.html#L184)):*
> ```HTML
>       }
> 
>       // Need to override to use 2d translates to avoid Sarafi rendering issues
> ```

Committed by accident?

---

*[vaadin-grid-styles.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-Kso1POHJ8S3yvQc2iUh:-Kso1POHJ8S3yvQc2iUi:b-oz40kw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4fb9dc0819cce3c8243c9dc1dfd6516014802cc9/vaadin-grid-styles.html#L29)):*
> ```HTML
>         height: 100%;
>         width: 100%;
>         transform: translateZ(0);
> ```

Committed by accident?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid-scroller.html, line 184 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-Kso1ISp6RlSXD_oUZut:-KsoH_FsmcMx7uUAq2gc:b-xa0vlk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b6835e21da00127b4356d1c1025b431c71f90a91/vaadin-grid-scroller.html#L184)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Committed by accident?
</blockquote></details>

Ups, I thought this code was fixing the same issue. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid-styles.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-Kso1POHJ8S3yvQc2iUh:-KsoJGHx4Qf5f0ZMAwZZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4fb9dc0819cce3c8243c9dc1dfd6516014802cc9/vaadin-grid-styles.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Committed by accident?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-scroller.html, line 184 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-Kso1ISp6RlSXD_oUZut:-KsoKndeIF3BHJLGx-OM:b-xdiwfz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b6835e21da00127b4356d1c1025b431c71f90a91/vaadin-grid-scroller.html#L184)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Ups, I thought this code was fixing the same issue. Done
</blockquote></details>

It was for a different rendering issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-:-KsoKxeBDhsMRLkg3IzM:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-scroll-mixin.html, line 210 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957#-KsoL7acIEZckAcC7HBL:-KsoL7acIEZckAcC7HBM:b-lwo8rr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5275ec868b24e60c4ec07003b49e2659899a5499/vaadin-grid-scroll-mixin.html#L210)):*
> ```HTML
> 
>       // After scrolling, reordering causes that the grid disappears on Safari.
>       this.translate3d(0, 0, 0);
> ```

Oh, I was a bit too eager with the merge button. Let's not utilize the Polymer 1 API (translate3d) here. Also, this row only has effect the first time (it sets the translate inline style to the host element). 

Setting `transform: translateZ(0)` to the `:host`styles has the same effect. Pushed the fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/957)*

**Comment by manolo** [comment]
👍

**Pull request merged**
