### PR TITLE
Notify items array sub-property path

### LINKED ISSUE #1208: Two way binding on grid data
With this:
```html
Item 0 quantity: [[base_items.0.quantity]]
<vaadin-grid items="{{base_items}}">
    <vaadin-grid-column width="80px" flex-grow="0">
        <template class="header">Cantidad</template>
        <template>
           <vaadin-text-field pattern="[0-9].*" prevent-invalid-input value="[[item.quantity]]"></vaadin-text-field>
         </template>
     </vaadin-grid-column>
 </vaadin-grid>
```

When change the "quantity" field in `vaadin-text-field` the data in base_items changes, but the "Item 0 quantity" above still blank. Two way binding is not working.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1208

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1209)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[test/templates.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209#-L4HaTNBSUxDLfiwhrNE:-L4HaTNBSUxDLfiwhrNF:bnq0a35) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e058d89da2f02ec909ef8ea32873cf974d340a40/test/templates.html#L106)):*
> ```HTML
>         <template>
>           <div id="div">[[items.0.foo]]</div>
>           <vaadin-grid id="grid" items='{{items}}'>
> ```

nit: please use consistent attribute quotes (double vs single)

---

*[test/templates.html, line 306 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209#-L4HaGMQQ-m3en3RpcZp:-L4HaGMQQ-m3en3RpcZq:b-e68fv8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e058d89da2f02ec909ef8ea32873cf974d340a40/test/templates.html#L306)):*
> ```HTML
>     describe('using items array', () => {
>       let grid, div;
>       
> ```

nit: trailing whitespaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209)*

**Comment by tomivirkki** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/templates.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209#-L4HaTNBSUxDLfiwhrNE:-L4HbKZMMNye4kTnnua3:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e058d89da2f02ec909ef8ea32873cf974d340a40/test/templates.html#L106)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: please use consistent attribute quotes (double vs single)
</blockquote></details>

Done.

---

*[test/templates.html, line 306 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209#-L4HaGMQQ-m3en3RpcZp:-L4HbMvUGqXgZtuz_S0W:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e058d89da2f02ec909ef8ea32873cf974d340a40/test/templates.html#L306)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: trailing whitespaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209#-:-L4HbbTPLTvoERD3bKvO:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209#-:-L4LZP0xUzc_173S_o0N:bnfp4nl)*

**Comment by web-padawan** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1209)*

**Pull request merged**
