### PR TITLE
Update vaadin-grid-filter API

### LINKED ISSUE #553: Custom input field in <vaadin-grid-filter> doesn't work with native shadow enabled

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #553

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/593)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid-filter-behavior.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593#-KZWNfBpbJDjkoGfiE75:-KZWNfBpbJDjkoGfiE76:bw9sknl) ([raw file](https://github.com/vaadin/vaadin-grid/blob/350abece38acff8e35780ec611d806c88d475215/vaadin-grid-filter-behavior.html#L34)):*
> ```HTML
>       _filterChanged: function(path, value, isAttached) {
>         if (isAttached) {
>           this.debounce('filter-changed', function() {
> ```

Just as a comment, it hurts a bit inside to add a debounce here and forcing this property to act asynchronously. We can consider later adding a property to configure the debounce timeout so that it can be forced sync.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593#-:-KZWP2MsgIuJw3PsYAGk:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-filter-behavior.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593#-KZWNfBpbJDjkoGfiE75:-KZWPY3YBk_BKK0p-nVd:bqog80t) ([raw file](https://github.com/vaadin/vaadin-grid/blob/350abece38acff8e35780ec611d806c88d475215/vaadin-grid-filter-behavior.html#L34)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Just as a comment, it hurts a bit inside to add a debounce here and forcing this property to act asynchronously. We can consider later adding a property to configure the debounce timeout so that it can be forced sync.
</blockquote></details>

Agreed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593#-KZWRvNXEg2rvofn0Wmv:-KZWRvNXEg2rvofn0Wmw:br41cvb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/350abece38acff8e35780ec611d806c88d475215/docs/vaadin-grid-sorting-filtering.adoc#L170)):*
> ```AsciiDoc
> The code snippet above produces a three-column [vaadinelement]#vaadin-grid# with a filtering input that targets the data items' [propertyname]#user.email# property.
> 
> By default the [elementname]#vaadin-grid-filter# shows a plain text input field but you can replace it by including another element inside the [elementname]#vaadin-grid-filter#.
> ```

nit: this phrase is quite long to read, I would add a couple of coma. Not blocking though

"by default, ...  input field, but ..." 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593#-:-KZWSaFCD_jETKsiU12P:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-grid-sorting-filtering.adoc, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593#-KZWRvNXEg2rvofn0Wmv:-KZWTxsJLkhF_ouwcG3d:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/350abece38acff8e35780ec611d806c88d475215/docs/vaadin-grid-sorting-filtering.adoc#L170)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: this phrase is quite long to read, I would add a couple of coma. Not blocking though

"by default, ...  input field, but ..." 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/593)*

**Pull request merged**
