### PR TITLE
Add screenshot of vaadin-grid to README.md

### PR DESCRIPTION
**Pull request by tehapo**
Connects to vaadin/components-team-tasks#40

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/280)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[screenshot.png, line 0 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280#-K4wzTakwXcBWSjHY5DT:-K4wzTakwXcBWSjHY5DU:-842874454) ([raw file](https://github.com/vaadin/vaadin-grid/blob/095650191521c9a4da4ff9927ffa1aea9e8984cd/screenshot.png#L0)):*
Have you tried this grid in IE11? the result is different to this screen-shot (size of images), it's unrelated to this commit though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280)*

**Comment by tehapo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[screenshot.png, line 0 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280#-K4wzTakwXcBWSjHY5DT:-K4x8RSWGXVvIRa36xQs:-122143091) ([raw file](https://github.com/vaadin/vaadin-grid/blob/095650191521c9a4da4ff9927ffa1aea9e8984cd/screenshot.png#L0)):*
Didn't try on IE11, just simply took the screenshot on OSX/Chrome.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[screenshot.png, line 0 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280#-K4wzTakwXcBWSjHY5DT:-K5-cXyHoTch2IoJcAKy:1224022840) ([raw file](https://github.com/vaadin/vaadin-grid/blob/095650191521c9a4da4ff9927ffa1aea9e8984cd/screenshot.png#L0)):*
I don't see the issue now, but saw it in a virtual machine, anyway it's unrelated.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[screenshot.png, line 0 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280#-K5-b97LO9_h5Gy_zVrY:-K5-b97LO9_h5Gy_zVrZ:-755845986) ([raw file](https://github.com/vaadin/vaadin-grid/blob/095650191521c9a4da4ff9927ffa1aea9e8984cd/screenshot.png#L0)):*
Could we make the column headings not to end with “...”? Like this:

vaadin-grid screenshot

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/280)*

**Pull request merged**
