### PR TITLE
Active item should have a default value

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/843)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-grid-active-item-behavior.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843#-KgsCmpAUKaMnlvLUGUH:-KgsCmpAUKaMnlvLUGUI:b-b6qctq) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0e64f3f97f3620ef1ded35b490d6b914408a3826/vaadin-grid-active-item-behavior.html#L29)):*
> ```HTML
>         type: Object,
>         notify: true,
>         value: null
> ```

out of curiosity, why is it needed? what is broken otherwise ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-active-item-behavior.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843#-KgsCmpAUKaMnlvLUGUH:-KgsKqc-ddoJ2JdRI6OL:bdxhsqi) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0e64f3f97f3620ef1ded35b490d6b914408a3826/vaadin-grid-active-item-behavior.html#L29)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

out of curiosity, why is it needed? what is broken otherwise ?
</blockquote></details>

There's a discussion in the elements Gitter chat (from yesterday) about a case where this caused an issue. It was basically about using `activeItem` in a computed binding function. It didn't trigger because `activeItem` was undefined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843)*

**Comment by manolo** [comment]
The CI build is broken otherwise :lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-grid-active-item-behavior.html, line 29 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843#-KgsCmpAUKaMnlvLUGUH:-KgsQwJSfT_nuNQkMGjz:b-3ipcc8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0e64f3f97f3620ef1ded35b490d6b914408a3826/vaadin-grid-active-item-behavior.html#L29)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

There's a discussion in the elements Gitter chat (from yesterday) about a case where this caused an issue. It was basically about using `activeItem` in a computed binding function. It didn't trigger because `activeItem` was undefined.
</blockquote></details>

Clear, thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843#-:-KgsTr2rGMsKLQrGqI_Y:b-ekr95x)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/843#-:-KgtP_rS9h2Ibti_xNB9:bnfp4nl)*

**Pull request merged**
