### PR TITLE
2.0 column group frozen

### PR DESCRIPTION
**Pull request by manolo**
Connects to #441

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/505)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 17 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table.html, line 250 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KV5PNKMO6ozyad2Wcb4:-KV5PNKMO6ozyad2Wcb5:b-5p3gbr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4db84834a84c3763f85ad02306bb9ca02482cbed/vaadin-grid-table.html#L250)):*
> ```HTML
> 
>         var lastFrozen = 0;
>         var columns = this.columns[this.columns.length - 1];
> ```

I find `var columns` confusing  maybe `columnsRow`, or might be change the `this.columns` to  `this.columnMatrix`

---

*[vaadin-grid-table.html, line 252 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KV5Q4x0yS841oH1lwT2:-KV5Q4x0yS841oH1lwT3:bwovf2t) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4db84834a84c3763f85ad02306bb9ca02482cbed/vaadin-grid-table.html#L252)):*
> ```HTML
>         var columns = this.columns[this.columns.length - 1];
> 
>         columns.forEach(function(col, index) {
> ```

A reduce function could leave the code simpler ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by Saulis** [comment]
Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 158 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KV6K1grRFdrgp9ymuZM:-KV6K1grRFdrgp9ymuZN:b-de280b) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4db84834a84c3763f85ad02306bb9ca02482cbed/vaadin-grid-column.html#L158)):*
> ```HTML
>           // stop width/flex changes from child columns/groups from bubbling
>           // to the cell of this group.
>           // TODO: header and footer templates don't bubble by default,
> ```

Oh these comments are so out of date – I'll fix 'em

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by manolo** [comment]
Review status: 0 of 17 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-table.html, line 250 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KV5PNKMO6ozyad2Wcb4:-KV8y9lwSVPFrDdK5K-G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4db84834a84c3763f85ad02306bb9ca02482cbed/vaadin-grid-table.html#L250)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I find `var columns` confusing  maybe `columnsRow`, or might be change the `this.columns` to  `this.columnMatrix`
</details>
Done.

---

*[vaadin-grid-table.html, line 252 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KV5Q4x0yS841oH1lwT2:-KV8yA5aUsBcxU7d4s1v:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4db84834a84c3763f85ad02306bb9ca02482cbed/vaadin-grid-table.html#L252)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> A reduce function could leave the code simpler ?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by manolo** [comment]
Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 158 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KV6K1grRFdrgp9ymuZM:-KV9teM5n2UvBEXYhVO-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4db84834a84c3763f85ad02306bb9ca02482cbed/vaadin-grid-column.html#L158)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Oh these comments are so out of date – I'll fix 'em
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by tomivirkki** [comment]
The frozen columns separator is missing from the first header row and last footer row (grp.html) https://www.dropbox.com/s/ka1pl86yobleio7/Screenshot%202016-10-28%2014.51.35.png?dl=0

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVA7UvvlteIVfc79_rK:b-59xu7p)*

**Comment by manolo** [comment]
Fixed

---

Review status: 0 of 18 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVB8o2eHwOLIt5WygsQ:b-886gsx)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r1, 7 of 11 files at r2, 5 of 9 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVOcdI089hr2RioqADn:bnfp4nl)*

**Comment by Saulis** [comment]
Wait! Don't :shipit: just yet – I think there might be something wrong with initialising `frozen` value, just a sec.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVOl9fISmv1L5rCyGOg:bb4qmmg)*

**Comment by tomivirkki** [comment]
> Fixed

Could use a test case also

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 41 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVOpx2EWyihq13gkn75:-KVOpx2EWyihq13gkn76:b-8raq8q) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L41)):*
> ```HTML
>         },
> 
>         lastFrozen: {
> ```

Should be a private property

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVOpLGh6QpeGLWE0jjS:bbdfch9)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-grid-column.html, line 67 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVOrQ78T9uE7aFyJLhT:-KVOrQ7947bZ6vRpP-gH:bss8em) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L67)):*
> ```HTML
> 
>       _headerTemplateChanged: function(headerTemplate) {
>         this.fire('property-changed', {path: 'headerTemplate', value: headerTemplate}, {bubbles: false});
> ```

header and footer templates need to bubble, I'll make sure we have a test for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-scroll-behavior.html, line 66 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVOt1ne3xq1hW8aD8Cg:-KVOt1ne3xq1hW8aD8Ch:b-ese12l) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-table-scroll-behavior.html#L66)):*
> ```HTML
>       _frozenCells: {
>         type: Array,
>         value: []
> ```

Don't want to use the same array instance for all the vaadin-grids on the page

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 163 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVP53z_1mLIE964Q-wR:-KVP53z_1mLIE964Q-wS:b-lkuz0n) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L163)):*
> ```HTML
>         }
> 
>         if (/frozen/.test(e.detail.path)) {
> ```

Don't use regex for simple String equality test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 163 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVP53z_1mLIE964Q-wR:-KVPFS5xKLDUvMrnOGJ0:b-d1lrj0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L163)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Don't use regex for simple String equality test
</details>
This line was changed in the last commit but there's still same issues in -table and -cell at least

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by Saulis** [comment]
Review status: 12 of 18 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-column.html, line 41 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVOpx2EWyihq13gkn75:-KVPmlS2q5nSrAeShCnD:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L41)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Should be a private property
</details>
Done.

---

*[vaadin-grid-column.html, line 163 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVP53z_1mLIE964Q-wR:-KVPl0by_fcKr6Sw_BW1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L163)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This line was changed in the last commit but there's still same issues in -table and -cell at least
</details>
Done.

---

*[vaadin-grid-table-scroll-behavior.html, line 66 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVOt1ne3xq1hW8aD8Cg:-KVPjJ8p41KEbn-coKPt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-table-scroll-behavior.html#L66)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Don't want to use the same array instance for all the vaadin-grids on the page
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: 12 of 18 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 67 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-KVOrQ78T9uE7aFyJLhT:-KVPQScZz8ds6Ut0kOWT:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730c938bab003e9291882e3ac556a2c9d738620b/vaadin-grid-column.html#L67)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> header and footer templates need to bubble, I'll make sure we have a test for it.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVTa_fbSI0lvVhxGcHt:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/505#-:-KVTlhzDDBJWYQ-gLCbW:bnfp4nl)*

**Pull request merged**
