### PR TITLE
Make details cell navigatable

### LINKED ISSUE #684: Row Details cannot be accessed with keyboard
ydc99qe7qi

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #684

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/688)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688#-:-Kc36gYFnS-DzKD6D0qW:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-keyboard-navigation-behavior.html, line 551 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688#-Kc37N0PaQZTPg-i6oNh:-Kc37N0PaQZTPg-i6oNi:b-lgzoqa) ([raw file](https://github.com/vaadin/vaadin-grid/blob/01e8c40d2b115eec7f67e12cdfac80535db7cf6f/vaadin-grid-keyboard-navigation-behavior.html#L551)):*
> ```HTML
>       }
> 
>       // Horizontal
> ```

Details cell could be ignored here so we wouldn't get this jumpy effect when scrolled horizontally

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688#-:-KcHiC_b0er3y82FEjkL:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid-keyboard-navigation-behavior.html, line 551 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688#-Kc37N0PaQZTPg-i6oNh:-KcIfEoVP0pZwrmF3XM1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/01e8c40d2b115eec7f67e12cdfac80535db7cf6f/vaadin-grid-keyboard-navigation-behavior.html#L551)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Details cell could be ignored here so we wouldn't get this jumpy effect when scrolled horizontally
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/688#-:-KcMYyTbx9rh0N7NRn9H:bnfp4nl)*

**Pull request merged**
