### PR TITLE
Grid 2 hybrid

### LINKED ISSUE #710: vaadin-grid Polymer 2.0 support
<p>Developers can use vaadin-grid with Polymer2 projects</p>

[See more on IDEA 210 vaadin-grid Polymer 2.0 support](https://app.prodpad.com/ideas/210/canvas)

Premilinary Steps: (by @Saulis)
- [ ] ~~In preparation for using `<slot>`, place cells inside shadow root of `<vaadin-grid>`~~
- [x] Switch `<content>` for `<slot>` and `::content` to `::slotted()`
- [x] Replace custom elements extending native elements
- [ ] ~~Separate "fixed" elements sections to improve UX~~
- [x] Revise and fix multi-property observers with checks for `undefined` values
- [x] Replace `<style is="custom-style">` with `<custom-style>`
- [x] Modify the `Templatizer` functionality to work with both v1 and v2
- [ ] Deprecate CSS mixins
- [ ] ~~Modify scroller internals to use a flexbox~~

Other notable changes:
- `Polymer.dom(x).querySelectorAll(..)` returns `NodeList` instead of `Array`
- `<slot>` without a name cannot have fallback/default content
- `Polymer.Settings.useNativeShadow` -> `Polymer.Settings.useShadow`
- `Polymer.dom.flush()` no longer flushes mutation observers, they need to be explicitly flushed.
- adding listeners using `target.click`: `_onClick` in `listeners` block doesn't work

### PR DESCRIPTION
**Pull request by tomivirkki**
Closes #710

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/880)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 87 files reviewed at latest revision, 11 unresolved discussions, some commit checks broke.

---

*[.gemini.yml, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPTRW6nJLShAMCm6ss:-KkPTRW6nJLShAMCm6st:bvgcfht) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/.gemini.yml#L18)):*
> ```YAML
>       platform: "Windows 10"
> 
>   # Skipping FF gemini tests in the hybrid version
> ```

No worky?

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQ8LdykHKJf-YxU7I:-KkPQ8LdykHKJf-YxU7J:bh3x615) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/.travis.yml#L28)):*
> ```YAML
>   - gulp lint
>   - polymer lint --rules polymer-2-hybrid --input *.html
>   # - xvfb-run -s '-screen 0 1024x768x24' polymer test -l chrome
> ```

Commented out on purpose?

---

*[.travis.yml, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQCgX1-C5n03oaDp6:-KkPQCgY52GS2MeCYvDJ:bh3x615) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/.travis.yml#L69)):*
> ```YAML
>     test/doctype.html
>     test/lazy-import.html
>   # - if [[ "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_BRANCH" != quick/* ]]; then
> ```

Commented out on purpose?

---

*[bower.json, line 45 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQG6jb6_H2UES0Wwv:-KkPQG6jb6_H2UES0Www:b-ohdh75) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/bower.json#L45)):*
> ```JSON
>     "paper-styles": "PolymerElements/paper-styles#^v2.0.0",
>     "iron-component-page": "^v2.0.0",
>     "elements-demo-resources": "2.0-preview",
> ```

There's a `2.0.0` available now, upgrading to that removes some of the needed `resolutions`

---

*[iron-list-behavior.html, line 420 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQ_h4mIe1GgCcrcOb:-KkPQ_h4mIe1GgCcrcOc:b-4bmhp7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/iron-list-behavior.html#L420)):*
> ```HTML
> 
>         var estPhysicalSize = this._physicalSizes.reduce(function(prev, curr) {
>           return prev + (curr || 100);
> ```

Is `100` an estimated guess for a default height?

---

*[vaadin-grid-column-group.html, line 285 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPRp5R0vNZ0dnaPryJ:-KkPRp5R0vNZ0dnaPryK:blnrz28) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/vaadin-grid-column-group.html#L285)):*
> ```HTML
>             info.removedNodes.filter(isColumnElement).length > 0) {
>             this._rootColumns = this._getChildColumns(this);
>             this._childColumns = this._rootColumns;
> ```

Previously, `_childColumns` hasn't been assigned with column groups or selection columns. Has it been a bug that now has been fixed?

---

*[vaadin-grid-table-cell.html, line 365 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPXBuZMyq71YmtiN6R:-KkPXBuZMyq71YmtiN6S:b-xovv7i) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/vaadin-grid-table-cell.html#L365)):*
> ```HTML
>           e.preventDefault();
> 
>           // TODO: WTF doesn't bubble in tests?
> ```

Is this still accurate?

---

*[wct.conf.js, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPY3CXREfHuGrSnTyH:-KkPY3CXREfHuGrSnTyI:b4v9nel) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/wct.conf.js#L8)):*
> ```JavaScript
>     var saucelabsPlatforms = [
>       // TODO: Excluded iOS tests from the hybrid version. Re-enable for P2 version.
>       // 'OS X 10.12/iphone@10.2',
> ```

Would keeping `9.3` work any better?

---

*[test/index.html, line 54 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkP_FXPKVJ51ADkIK38:-KkP_FXPKVJ51ADkIK39:b785wvs) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/test/index.html#L54)):*
> ```HTML
>       if (document.head.createShadowRoot || document.head.attachShadow) {
>         // Full shadow polyfill isn't currently supported
>         return suites.concat([suite]); // runs native Shadow on P1 and Shady on P2
> ```

mmm.. I'm OK with skipping running Shady tests for Shadow enabled browsers, but I think we should then remove the whole `reduce` function.

---

*[test/light-dom-observing.html, line 460 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkP_bIa2PQt9b1vK4WI:-KkP_bIa2PQt9b1vK4WJ:b-5ujtzs) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/test/light-dom-observing.html#L460)):*
> ```HTML
>           });
> 
>           // TODO: Enable this test when the header cell cache is enabled back
> ```

When's that gonna happen? :-)

---

*[test/row-height.html, line 113 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkP_onENqQH-ANq4ZBA:-KkP_onENqQH-ANq4ZBB:b-wh09vp) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/test/row-height.html#L113)):*
> ```HTML
> 
>       beforeEach(function() {
>         this.currentTest.timeout(30000);
> ```

mmm.. why not just `this.timeout(30000)` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880)*

**Comment by tomivirkki** [comment]
Review status: 0 of 87 files reviewed at latest revision, 11 unresolved discussions.

---

*[.gemini.yml, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPTRW6nJLShAMCm6ss:-KkPaZrkqcFWj6DSn55B:b32w12) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/.gemini.yml#L18)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

No worky?
</blockquote></details>

No

---

*[.travis.yml, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQ8LdykHKJf-YxU7I:-KkPaeoYAbydwxcRacg7:b2ogqnj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/.travis.yml#L28)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Commented out on purpose?
</blockquote></details>

Yes. To reduce build time. Chrome and FF are run in the script phase anyway.

---

*[.travis.yml, line 69 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQCgX1-C5n03oaDp6:-KkParSh2_YmZMt8sz2Q:b1rtgq6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/.travis.yml#L69)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Commented out on purpose?
</blockquote></details>

Yes, replaced with the above

---

*[bower.json, line 45 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQG6jb6_H2UES0Wwv:-KkPj6bsqAASbJYO5WI2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/bower.json#L45)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

There's a `2.0.0` available now, upgrading to that removes some of the needed `resolutions`
</blockquote></details>

Done.

---

*[iron-list-behavior.html, line 420 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPQ_h4mIe1GgCcrcOb:-KkPb1-Obmjr7oHng6CZ:b-6id6pn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/iron-list-behavior.html#L420)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is `100` an estimated guess for a default height?
</blockquote></details>

It is. It's better to have a high default since the pool can always be increased after measure.

---

*[vaadin-grid-table-cell.html, line 365 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPXBuZMyq71YmtiN6R:-KkPjyV_7dbk0vQUaCMN:b-q663v4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/vaadin-grid-table-cell.html#L365)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is this still accurate?
</blockquote></details>

Seems to be ok now. Restored.

---

*[test/index.html, line 54 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkP_FXPKVJ51ADkIK38:-KkPkg5YziEwrgSnM8ue:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/test/index.html#L54)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

mmm.. I'm OK with skipping running Shady tests for Shadow enabled browsers, but I think we should then remove the whole `reduce` function.
</blockquote></details>

Done.

---

*[test/row-height.html, line 113 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkP_onENqQH-ANq4ZBA:-KkPkmiEtpCcBy_q7pKE:b-hs6xtl) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/test/row-height.html#L113)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

mmm.. why not just `this.timeout(30000)` ?
</blockquote></details>

`this.timeout` in beforeEach only affects the test setup (beforeEach). In this suite the setup seems to be done within the individual tests so this is required.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 81 of 87 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-:-KkPuDE4Ekm_wbNr9GKt:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[wct.conf.js, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-KkPY3CXREfHuGrSnTyH:-KkPyPoKa5DgIRE9IUmc:b-zcbc0a) ([raw file](https://github.com/vaadin/vaadin-grid/blob/44b013ea7052fe8da6b5a0116c80ee57b6e97bc1/wct.conf.js#L8)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Would keeping `9.3` work any better?
</blockquote></details>

Tested locally, getting the same timeouts :/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 81 of 87 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/880#-:-KkQrZdT8nFIVB2WixRD:bnfp4nl)*

**Pull request merged**
