### PR TITLE
Re-factor of JsColumns and remove custom setters

### LINKED ISSUE #230: Migrate from deprecated jsInterop to the JS_RC version

### PR DESCRIPTION
**Pull request by manolo**
Fixes #230

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/282)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 7 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 54 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B6Et21-XSl8XS_Dtb:-K5B6Et21-XSl8XS_Dtc:1253229462) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L54)):*
This combined with reassignProperties seems like a really hacky combo. Are you sure it's okay to promote native js objects to @JsTypes like this?

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B66klYDxXJwQIhTza:-K5B66klYDxXJwQIhTzb:611990212) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L68)):*
Method name has a typo

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 54 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B6Et21-XSl8XS_Dtb:-K5BLsYf6q9w6EERcm3_:1077060841) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L54)):*
This is the way GWT normally uses to promote any object to a java object.
You can see the same code for instance in Runtime.makeLambdaFunction.

It's hacky, but I'd rather this than rewriting getters and setters for each column.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B66klYDxXJwQIhTza:-K5BMbwWZp4yL0XQpjMg:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L68)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 54 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B6Et21-XSl8XS_Dtb:-K5BVKnCAMiDDY607jMY:-373015718) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L54)):*
Yeah, I agree. Both approaches are hacky but this is cleaner if it works ok. Apparently __proto__ is included in IE from version 11 so we're covered.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B66klYDxXJwQIhTza:-K5BVnDYv5ZXb6e6PUbK:103805117) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L68)):*
It still says 'reasign' while it should say  'reassign'. The methods contents also has 'reasignPending'.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 54 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B6Et21-XSl8XS_Dtb:-K5BXjVMu_33TaXJOK1b:1580538098) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L54)):*
Only case where this wouldn't work is if the given object has a prototype beforehand that has the necessary properties. But I guess that's a very unlikely case.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 54 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B6Et21-XSl8XS_Dtb:-K5B_CMznE6echoMtDaB:-660644348) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L54)):*
Exactly we are covered, I discarded copying the methods from prototype to the object which is the fallback approach used in GWT for lambdas.
The case of object with prototype shouldn't happen, the API documents JSO as configuration objects I don't think someone would pass a customised instance here.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B66klYDxXJwQIhTza:-K5Ba7Cdb5jOLsi9rc0c:-1941731163) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L68)):*
Not yet committed, I want to remove the gwt.xml optimisation to a separated PR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/common/js/JS.java, line 68 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5B66klYDxXJwQIhTza:-K5CXdpeeiSF5-1t1TyA:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5a37326b73944abf0925b3760d26e60a3f4c0c39/java/src/main/java/com/vaadin/elements/common/js/JS.java#L68)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
Needs a manual rebase

---

Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5FJonx0ja2HWm9FXJa:1360655753) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
Noticed that this test hasn't actually worked since https://github.com/vaadin/vaadin-grid/commit/83ebb455c3a2374fa363dc0b4514a1d393a5089e#diff-d4b7051fba2d73c6e9270196500898cdL87

Needs to be changed back (the done parameter). Proper way to do this would be to chain the then blocks like return grid.then(...).then(...); But because of async issues with columns (#288) it doesn't work currently.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-:-K5FKk1tZjm0Vt-LrEGM:-203097065)*

**Comment by tomivirkki** [comment]
*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5FMBjNwzQ01GDi4efx:1920178932) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
Ooh, actually it does, as long as you return grid from the first one "return grid.then(.... return grid;).then(...);"

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5USxDiVecHMNlqBoz-:1559453422) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
nested return grid.then is the same than running done in the deep then block

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5UTF24vMVgvc9EedR2:1415047163) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
So it seems. The "return" added in this patch fixes the previously broken test. Chaining would be cleaner but not a necessary change.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5UUNh4P8-gqo6OjnLg:4037692) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
Agree, let's change that stuff in a separate PR

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5UVj43NyBH9qmgS_GD:-1324216029) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
As a comment, it would be cleaner to chain multiple `then` calls rather than nesting them.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[demo/sizing.html, line 198 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYzEhaElbZ38N7bFi:-K5UYzEhaElbZ38N7bFj:1306025263) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/demo/sizing.html#L198)):*
Not related to this pr I think. Instead of adding such comment with a link to a ticket we could easily handle this in GridElement.setRowClassGenerator ourselves (return null internally when empty string received).

---

*[java/src/main/java/com/vaadin/elements/grid/config/JSColumn.java, line 137 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYWsXL_nTQMpRoyUR:-K5UYWsXL_nTQMpRoyUS:339679396) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/java/src/main/java/com/vaadin/elements/grid/config/JSColumn.java#L137)):*
All the functions that may affect column widths should invoke updateWidth. We need tests that would catch this kind of regression.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
Please reword the latest commit message. "Fix tests" doesn't really describe the changes. Something like "Column widths get recalculated when related properties change"

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-:-K5ZPp3bGWddMZ0z1p4K:-2087492143)*

**Comment by tomivirkki** [comment]
*[demo/sizing.html, line 198 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYzEhaElbZ38N7bFi:-K5ZZmaEMAxejqI91vqW:677534651) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/demo/sizing.html#L198)):*
bump

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[demo/sizing.html, line 198 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYzEhaElbZ38N7bFi:-K5_5_9KUmje-MS9k5lh:2100043790) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/demo/sizing.html#L198)):*
I was about handling this in our code, but the ideal fix is in the Grid, so I'd rather to leave this comment here and force us to send a fix.
The problem is only manifested in SDM, so this is the reason I did it here, because I realised during this story. I don't think we need a separate PR for this.

---

*[java/src/main/java/com/vaadin/elements/grid/config/JSColumn.java, line 137 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYWsXL_nTQMpRoyUR:-K5UuQEFQWBhPjeDZbfy:803535666) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/java/src/main/java/com/vaadin/elements/grid/config/JSColumn.java#L137)):*
good point

---

*[test/grid-editing-columns.html, line 92 \[r6\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5FJonx0ja2HWm9FXJ_:-K5Ui09EvxZ1ZMjle2Wp:-472598329) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0db7177ea14c824296c63c51df6ec91b0c993790/test/grid-editing-columns.html#L92)):*
agree

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
*[demo/sizing.html, line 198 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYzEhaElbZ38N7bFi:-K5_M0e-VLxxpkDyVbYi:-1575392002) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/demo/sizing.html#L198)):*
If it's only a problem in SDM then there's no reason to have this comment in our public example. It doesn't affect developers using grid so we shouldn't warn about it either.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demo/sizing.html, line 198 \[r7\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282#-K5UYzEhaElbZ38N7bFi:-K5_cjTh-i_bVGz4HccP:-1210510390) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a3b17ceabbc20f801d16fb0e26c33424c9dd6f48/demo/sizing.html#L198)):*
Sent patch https://dev.vaadin.com/review/#/c/12681/1, removed comment.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 18 files at r1, 2 of 5 files at r3, 1 of 3 files at r4, 1 of 1 files at r8, 3 of 3 files at r10.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r11.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/282)*

**Pull request merged**
