### PR TITLE
Set scroller size with empty items

### LINKED ISSUE #1221: vertical scrollbar is shown when data is empty
### Description
if we set `vaadin-grid` height to auto, then empty data causes `vaadin-grid` to show vertical scrollbar

### Expected outcome
No vertical scrollbar

### Actual outcome
Shows vertical scroll of `scrollTop` equal to `header`

### Live Demo
https://jsbin.com/fojujafawo/edit?html,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #1221

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1250)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/iron-list.html, line 676 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1250#-L7Ebbi6-x8Rtu_InfKI:-L7Ebbi6-x8Rtu_InfKJ:b-pr7jgj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/1581526f825110f014632917fb24c1b5b612330c/src/iron-list.html#L676)):*
> ```HTML
>       } else {
>         // List is empty, update the scroller size
>         this._updateScrollerSize();
> ```

We can't make changes to `iron-list.html`. That would make it non-upgradeable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1250)*

**Comment by samiheikki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/iron-list.html, line 676 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1250#-L7Ebbi6-x8Rtu_InfKI:-L7Iz_nbR2JPvCwGrs7G:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/1581526f825110f014632917fb24c1b5b612330c/src/iron-list.html#L676)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

We can't make changes to `iron-list.html`. That would make it non-upgradeable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1250)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250#-:-L9nG9H62cRuu64nlSwp:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/vaadin-grid-scroller.html, line 140 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250#-L9xwtQ25vZRMtzjTdV6:-L9xwtQ25vZRMtzjTdV7:b-uw7yot) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b84a41d9ad0b3929df80afd8136246863a4c2f9f/src/vaadin-grid-scroller.html#L140)):*
> ```HTML
>         this._assignModels();
> 
>         // Forces updating the scroller size when items length is 0
> ```

Why not always? So the unnecessary if block wouldn't be needed.

---

*[src/vaadin-grid-scroller.html, line 142 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250#-L9xwant5j8ZubtSf4q3:-L9xwant5j8ZubtSf4q4:be0unop) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b84a41d9ad0b3929df80afd8136246863a4c2f9f/src/vaadin-grid-scroller.html#L142)):*
> ```HTML
>         // Forces updating the scroller size when items length is 0
>         if (this.items.length === 0) {
>           Polymer.RenderStatus.afterNextRender(this, () => this._accessIronListAPI(super._updateScrollerSize));
> ```

This effectively forces iron-list to override the default 100% height of the body element. Let's rather just remove the default.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250)*

**Comment by tomivirkki** [comment]
*[src/vaadin-grid-scroller.html, line 140 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250#-L9xwtQ25vZRMtzjTdV6:-L9xyus3BjzfbKvM03xI:btdbqyi) ([raw file](https://github.com/vaadin/vaadin-grid/blob/34e2f1cab010d5bdc6ba2c136784d55dd5eb1a5e/src/vaadin-grid-scroller.html#L140)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why not always? So the unnecessary if block wouldn't be needed.
</blockquote></details>

No longer relevant

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250)*

**Comment by tomivirkki** [comment]
*[src/vaadin-grid-scroller.html, line 142 at r2](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250#-L9xwant5j8ZubtSf4q3:-L9xyxx-8fswNEp50ayV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/34e2f1cab010d5bdc6ba2c136784d55dd5eb1a5e/src/vaadin-grid-scroller.html#L142)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This effectively forces iron-list to override the default 100% height of the body element. Let's rather just remove the default.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250)*

**Comment by manolo** [comment]
Much better!  :lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1250#-:-L9yQIwb6haLCFva4R0i:bpra92p)*

**Pull request merged**
