### PR TITLE
Adapt demos to new vaadin site

### PR DESCRIPTION
**Pull request by manolo**
Connected to https://github.com/vaadin/components-team-tasks/issues/273

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/994)

### CODE REVIEW

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 19 of 25 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/index.html, line 19 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-KuTCsZIfgBxnaFeXg_q:-KuTCsZIfgBxnaFeXg_r:bt180x2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0411d09a6093209aac60cf7fe9a6f898dd4ec56/demo/index.html#L19)):*
> ```HTML
>   <link rel="import" href="../../polymer/polymer.html">
>   <link rel="import" href="../../vaadin-demo-helpers/vaadin-component-demo.html">
>   <link rel="import" href="../../vaadin-demo-helpers/vaadin-component-demo.html">
> ```

Nit: double importing.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-:-KuTDCXagAXObz9jDRYp:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 19 of 25 files at r1, 2 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-:-KuTHgroP_E6dy8KaRbM:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/grid-basic-demos.html, line 4 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-KuTIBQnQZAOmbATf5DF:-KuTIBQnQZAOmbATf5DG:b1df1wu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0411d09a6093209aac60cf7fe9a6f898dd4ec56/demo/grid-basic-demos.html#L4)):*
> ```HTML
>   <template>
>     <style>
>        :host {
> ```

nit: This indentation flaw occurs in _every_ new-demo pr

---

*[demo/index.html, line 19 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-KuTCsZIfgBxnaFeXg_q:-KuTIM9jXN0lCVV_YGuh:b-gfmbo4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0411d09a6093209aac60cf7fe9a6f898dd4ec56/demo/index.html#L19)):*
<details><summary><i>Previously, YuriyVaadin (Yuriy Yevstihnyeyev) wrote…</i></summary><blockquote>

Nit: double importing.
</blockquote></details>

This flaw occurs in _every_ new-demo pr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994)*

**Comment by manolo** [comment]
Review status: 14 of 16 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/grid-basic-demos.html, line 4 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-KuTIBQnQZAOmbATf5DF:-KuTNwrKqeCaHMd9PD0Q:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0411d09a6093209aac60cf7fe9a6f898dd4ec56/demo/grid-basic-demos.html#L4)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

nit: This indentation flaw occurs in _every_ new-demo pr
</blockquote></details>

Done.

---

*[demo/index.html, line 19 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994#-KuTCsZIfgBxnaFeXg_q:-KuTNruEgBqpktk3AxWE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0411d09a6093209aac60cf7fe9a6f898dd4ec56/demo/index.html#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This flaw occurs in _every_ new-demo pr
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/994)*

**Pull request merged**
