### PR TITLE
Put description that explains what happens when toggle is expanded.

### LINKED ISSUE #1104: Would be nice to see explanation that dataProvider gets called again when items get expanded.
Let us add that to the documentation (JSdoc).

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #1104

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1109)

### CODE REVIEW

**Comment by web-padawan** [comment]
You have included commits from the other PR.
Make sure to run `git checkout master` first before creating a new branch. 

---

Review status: 0 of 15 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-:-Kz43BYKW_hzx6kVz_IA:b-mq0xx)*

**Comment by tomivirkki** [comment]
Review status: 0 of 15 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-Kz4JkFoPDDXt1zJv2HY:-Kz4JkFoPDDXt1zJv2HZ:b-wll1c9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e3e4e1ecab1cf81094fc6304a28d9f640df1edc0/vaadin-grid.html#L121)):*
> ```HTML
>      * and the “Assigning Data” page in the demos.
>      *
>      * __Note that when the `expanded` attribute is bound to the `vaadin-grid`, expanding the tree grid's toggle will trigger a call to the `data-provider`.__
> ```

`expanded` isn't an attribute but an instance property. It doesn't need to be mentioned here though. Just state that the `dataProvider` gets invoked whenever items are expanded (for the first time).

---

*[demo/grid-tree-demos.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-Kz4KckD1XT2yiAe1E2_:-Kz4KckD1XT2yiAe1E2a:bonveem) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e3e4e1ecab1cf81094fc6304a28d9f640df1edc0/demo/grid-tree-demos.html#L12)):*
> ```HTML
>     <p>
>       When using the &lt;vaadin-grid-tree-toggle&gt;, you provide the data it'll use in rendering using the
>       <code>data-provider</code> attribute. This attribute accepts a function as parameter and,
> ```

This needs to be rephrased.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109)*

**Comment by vicsstar** [comment]
*[demo/grid-tree-demos.html, line 12 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-Kz4KckD1XT2yiAe1E2_:-KzNVfz-jl6wRFbFvoSy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e3e4e1ecab1cf81094fc6304a28d9f640df1edc0/demo/grid-tree-demos.html#L12)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This needs to be rephrased.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109)*

**Comment by vicsstar** [comment]
*[vaadin-grid.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-Kz4JkFoPDDXt1zJv2HY:-KzNXVgheNCIa5wzyF3v:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e3e4e1ecab1cf81094fc6304a28d9f640df1edc0/vaadin-grid.html#L121)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`expanded` isn't an attribute but an instance property. It doesn't need to be mentioned here though. Just state that the `dataProvider` gets invoked whenever items are expanded (for the first time).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-Kz4JkFoPDDXt1zJv2HY:-KzNc6hUXiCrh1a2Kg0p:b135ip9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e3e4e1ecab1cf81094fc6304a28d9f640df1edc0/vaadin-grid.html#L121)):*
> expanding the tree grid's toggle

The "toggle" isn't required to use grid's tree feature. You can bind any control element to expand an item in a template. Developer can even use the `expandItem` or `collapseItem` API's directly so a control element can be completely omitted.

As stated in the first comment, only mention that "..expanding a tree grid's _item_ will trigger a call to the `dataProvider`"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109)*

**Comment by vicsstar** [comment]
*[vaadin-grid.html, line 121 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-Kz4JkFoPDDXt1zJv2HY:-KzOh0wq0vFXa1PpAm1e:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e3e4e1ecab1cf81094fc6304a28d9f640df1edc0/vaadin-grid.html#L121)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

> expanding the tree grid's toggle

The "toggle" isn't required to use grid's tree feature. You can bind any control element to expand an item in a template. Developer can even use the `expandItem` or `collapseItem` API's directly so a control element can be completely omitted.

As stated in the first comment, only mention that "..expanding a tree grid's _item_ will trigger a call to the `dataProvider`"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1109#-:-KzOkoiFMZZoTfYbjWIx:bnfp4nl)*

**Pull request merged**
