### PR TITLE
Prepare for P3

### LINKED ISSUE #1255: Ensure Polymer 3 Modulizer compatibility
See “Generic steps” at vaadin/components-team-tasks#326

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1255

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1269)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.npmignore, line 10 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jawib01Re1a06PoI7:-L9Jawib01Re1a06PoI8:b-26foee) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/.npmignore#L10)):*
> ```
> bower.json
> gulpfile.js
> index.html
> ```

please also add ISSUE_TEMPLATE.md to npmignore

---

*[bower.json, line 19 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9JbLEg6G0pQREcYiXH:-L9JbLEg6G0pQREcYiXI:b-r4inn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/bower.json#L19)):*
> ```JSON
>     "data-table"
>   ],
>   "main": ["vaadin-grid.html", "vaadin-grid-column.html"],
> ```

nit: please format to be multi-line

---

*[wct.conf.js, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jbqf835OUDtIXVYH0:-L9Jbqf835OUDtIXVYH1:b5qgnl1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/wct.conf.js#L24)):*
> ```JavaScript
> 
>     const cronPlatforms = [
>       'Windows 10/chrome@55',
> ```

BTW maybe also update Chrome and Firefox for cron

---

*[wct.conf.js, line 77 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jc0KbBCtzSmMD2Y-v:-L9Jc0KbBCtzSmMD2Y-w:b-mjuj4g) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5505dd51a5d7a7d8e9fcabd4917f130b91e70b8/wct.conf.js#L77)):*
> ```JavaScript
> 
>   plugins: {
>     'random-output': true
> ```

please use `verbose: true` instead, as we do in combo-box and date-picker (this was previously passed to wct as a flag in travis config)

---

*[test/app-localize-behavior.html, line 48 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jd-ni4l9Rgl2t63-_:-L9Jd-ni4l9Rgl2t63-a:bj3trfy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/test/app-localize-behavior.html#L48)):*
> ```HTML
> 
>           before(done => {
>             Polymer.importHref('../../app-localize-behavior/app-localize-behavior.html', () => {
> ```

BTW need to also import `polymer/lib/utils/import-href.html`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by tomivirkki** [comment]
Review status: 20 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[.npmignore, line 10 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jawib01Re1a06PoI7:-L9Jkfqv8zqU-2yDbS7p:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/.npmignore#L10)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please also add ISSUE_TEMPLATE.md to npmignore
</blockquote></details>

Done.

---

*[bower.json, line 19 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9JbLEg6G0pQREcYiXH:-L9Jkko6C3KJsEdXCreh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/bower.json#L19)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: please format to be multi-line
</blockquote></details>

Done.

---

*[wct.conf.js, line 24 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jbqf835OUDtIXVYH0:-L9JktxlBvwBjmjbJ3BS:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/wct.conf.js#L24)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW maybe also update Chrome and Firefox for cron
</blockquote></details>

Done.

---

*[wct.conf.js, line 77 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jc0KbBCtzSmMD2Y-v:-L9JubTtAydAoikd1cW1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5505dd51a5d7a7d8e9fcabd4917f130b91e70b8/wct.conf.js#L77)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

please use `verbose: true` instead, as we do in combo-box and date-picker (this was previously passed to wct as a flag in travis config)
</blockquote></details>

Done.

---

*[test/app-localize-behavior.html, line 48 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Jd-ni4l9Rgl2t63-_:-L9JuudiAvxxbrfGM_OG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f4e5f0624f1961aa84719c3fcd91af6b30fded44/test/app-localize-behavior.html#L48)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW need to also import `polymer/lib/utils/import-href.html`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by web-padawan** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[.travis.yml, line 28 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9KESjRBZo7GsaNUZp1:-L9KELYsAISpJdKxCcZw:b-drk1ir) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730fe760a766504a95094ac23609be27a8ef5899/.travis.yml#L28)):*
> ```YAML
>       npm install -g polymer-cli &&
>       npm install &&
>       gulp lint &&
> ```

BTW also version:check

---

*[.travis.yml, line 29 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9KEXrd9ot08xE0QyII:-L9KEXrd9ot08xE0QyIJ:bl6rix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730fe760a766504a95094ac23609be27a8ef5899/.travis.yml#L29)):*
> ```YAML
>       npm install &&
>       gulp lint &&
>       polymer lint --rules polymer-2 --input *.html &&
> ```

BTW should be:  --input ./src/*.html ./theme/**/*.html

This would reveal some unwanted warnings though, so we might want to skip this at all.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by tomivirkki** [comment]
Review status: 25 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[.travis.yml, line 28 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9KESjRBZo7GsaNUZp1:-L9KG9RXDtwifU1i1DM4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730fe760a766504a95094ac23609be27a8ef5899/.travis.yml#L28)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW also version:check
</blockquote></details>

Done.

---

*[.travis.yml, line 29 at r3](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9KEXrd9ot08xE0QyII:-L9KG9m_0D3AarL41Mg-:b1q5tlv) ([raw file](https://github.com/vaadin/vaadin-grid/blob/730fe760a766504a95094ac23609be27a8ef5899/.travis.yml#L29)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

BTW should be:  --input ./src/*.html ./theme/**/*.html

This would reveal some unwanted warnings though, so we might want to skip this at all.
</blockquote></details>

Skipped.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Ka31x3kI1y23CC_Pj:-L9Ka31y8I_bYuq7qAa1:b7wfbzv) (no related file):*
This only seems to work on Chrome.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by tomivirkki** [comment]
*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Ka31x3kI1y23CC_Pj:-L9KaUbG6AQ9nTbS2NKc:b5zs5fu) (no related file):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This only seems to work on Chrome.
</blockquote></details>

Haha, wrong PR, nevermind

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-:-L9KdvhYCBuEQ4JSRufG:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 19 of 26 files at r1, 5 of 6 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[bower.json, line 21 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Khu6N96um6rpPmmuG:-L9Khu6O2hmW4v1YyzaQ:bo2oy9b) ([raw file](https://github.com/vaadin/vaadin-grid/blob/17ec41f4c7bf3c8f8fcdb18054b513cf46ae9330/bower.json#L21)):*
> ```JSON
>   "main": [
>     "vaadin-grid.html",
>     "vaadin-grid-column.html"
> ```

Should probably list all entrypoints here, incliding `all-imports.html`.

Just to be safe on that all of them are always treated as entrypoints on modulizer.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-:-L9KlUiTE4R4ZUyeIp19:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[bower.json, line 21 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Khu6N96um6rpPmmuG:-L9Kuszf-aC6WfmcO7ZG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/17ec41f4c7bf3c8f8fcdb18054b513cf46ae9330/bower.json#L21)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should probably list all entrypoints here, incliding `all-imports.html`.

Just to be safe on that all of them are always treated as entrypoints on modulizer.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[bower.json, line 21 at r4](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-L9Khu6N96um6rpPmmuG:-L9KwwL_9Lj3PnR7N__F:b-c782ux) ([raw file](https://github.com/vaadin/vaadin-grid/blob/17ec41f4c7bf3c8f8fcdb18054b513cf46ae9330/bower.json#L21)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Was `all-imports.html` forgotten or intentionally skipped?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1269#-:-L9Oa5cz5CPOgIHc0tTE:bnfp4nl)*

**Pull request merged**
