### PR TITLE
Remove unused iron-list code

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1210)

### CODE REVIEW

**Comment by limonte** [comment]
- Which issue this PR is fixing?
- Copy-pasting the dependency, adding it to the repo and changing it later is the perfect way to make it unmaintainable.
- https://github.com/vaadin/vaadin-grid/blob/master/src/iron-list.html#L18-LL24 won't be valid with this change

**Comment by tomivirkki** [comment]
1. It eliminates lots of dead code. There's no point in delivering code that's never visited.
2. What are you talking about? You actually linked the upgrading instructions yourself. Iron-list can be upgraded anytime to the newest version. Removing unused code is a completely optional phase (as stated in the upgrade guide), grid works just fine without a single (unused) line removed from the original source.
3. Of course it's still valid. This PR is all about the part 4 of the upgrade guide you linked. I actually just tested upgrading to newest iron-list and grid works fine.

And just to mention, even the current iron-list in grid repository has lots of unused code removed, this PR just takes it further.

**Comment by limonte** [comment]
> It eliminates lots of dead code. There's no point in delivering code that's never visited.

There are a lot of opened issues, I'm not sure how this type of optimization got bigger priority.

>   What are you talking about? You actually linked the upgrading instructions yourself. Iron-list can be upgraded anytime to the newest version. Removing unused code is a completely optional phase (as stated in the upgrade guide), grid works just fine without a single (unused) line removed from the original source.

I'm talking about the code maintainability. On each upgrade iteration, the developer will need to repeat all these changes manually, and that won't be fun.

**Comment by tomivirkki** [comment]
> There are a lot of opened issues, I'm not sure how this type of optimization got bigger priority.

This was done on my free time.

> I'm talking about the code maintainability. On each upgrade iteration, the developer will need to repeat all these changes manually, and that won't be fun.

Developer doesn't need to repeat anything. As I said earlier, no code _needs_ to be removed from the copied `iron-list` source. But it _can_ be (to minimize the payload).

So, to recap: If, for some reason (I don't see any), `iron-list` in this repo needs to be upgraded, you just remove all the source code from `iron-list.html` and copy-paste the newest source from the actual `iron-list` repo. There's no extra additional steps that this PR creates. _It only removes dead code_.

**Comment by limonte** [comment]
> So, to recap: If, for some reason (I don't see any), iron-list in this repo needs to be upgraded, you just remove all the source code from iron-list.html and copy-paste the newest source from the actual iron-list repo. There's no extra additional steps that this PR creates. It only removes dead code.

There could be some bug-fixes in future releases (e.g. https://github.com/PolymerElements/iron-list/issues/496), I doubt that `iron-list` is bug-free. Since this optimization is optional, I don't have anything against.

**Comment by tomivirkki** [comment]
Closing this for now. It's more important to get the newest iron-list in place now.

**Pull request closed without merging**
