### PR TITLE
Fix filter memory leak

### PR DESCRIPTION
**Pull request by dumbbillyhardy**
I would really like this for 3.x as well, should I make a PR with these changes cherry-picked over?

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1147)

### CODE REVIEW

**Comment by vicsstar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1147)*

**Comment by vicsstar** [comment]
> dd277d6
This needs a rebase.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1147#-:-L2ec0BbR5QGRq2FKyUc:bmp9dxv)*

**Comment by vicsstar** [comment]
Perhaps a cleaner rebase, one without merge commits.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1147#-:-L2ecS21ghtBaB-G-erI:b-atunvr)*

**Comment by tomivirkki** [comment]
Thanks for the PR @billy-hardy, it kind of solves the problem but it still requires the user to clear the filter value before removing it from the DOM. So the following test isn't satisfied:

```
it('should not keep disconnected filters', function() {
  const filter = grid._filters[0];
  // Filter gets removed from the dom
  filter.parentNode.removeChild(filter);
  flushFilters(grid);
  expect(grid._filters).to.not.include(filter);
});
```

Would it make sense to instead of removing the filter from the array when the value is cleared, to remove it when it gets disconnected.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1147#-:-L3bLgcco9VvZnPKhFGf:b9es3u6)*

**Comment by tomivirkki** [comment]
Closing as inactive, please re-open if this is still valid. I couldn't quite grasp how the current behaviour produces a memory leak or how the proposed change fixes one. The test case checks that a filter with an empty value is removed from the `_filters` array but doesn't explain why referencing one is a problem.

As stated in https://github.com/vaadin/vaadin-grid/pull/1147#issuecomment-360061565 to make sure there are no unwanted filter instances remaining in the array, they should be cleaned up on disconnect, regardless of whether they have a value or not.

**Pull request closed without merging**
