### PR TITLE
Add `first-column` attribute on the first visible column

### PR DESCRIPTION
**Pull request by jouni**
Enables theming to target the first column in the grid.

I think this is a small enhancement to the current “theming” feature, and could be released in a patch release. Not sure how strict our semver rules are, if this is considered a new feature and would require a minor version.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1444)

### CODE REVIEW

**Comment by jouni** [comment]
So, is this a patch or minor version? Does grid already use semantic-release or not – how should this PR be tagged?

**Comment by web-padawan** [comment]
@jouni we so not use semantic-release for components at the moment.
It should be ok to include this feature in the current alpha period, WDYT?

**Comment by tomivirkki** [comment]
We can include this in the ongoing minor/alpha period IMO

**Comment by limonte** [comment]
@jouni released as [v5.2.0-alpha5](https://github.com/vaadin/vaadin-grid/releases/tag/v5.2.0-alpha5) 🎉

**Pull request merged**
