### PR TITLE
Sorting helpers feature

### LINKED ISSUE #489: Sorting helpers

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #489 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/494)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Ping @magi42 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-:-KUVeBWR-mr8kq4ycZ2R:bi8tgph)*

**Comment by Saulis** [comment]
Reviewed 8 of 13 files at r1.
Review status: 8 of 13 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-sort-behavior.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpTubZmZ_hT4ZhySim:-KUpTubZmZ_hT4ZhySin:b-qryw98) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0d8f1f88793d2893f31b7b6c1be3b7ca6306a6d4/vaadin-grid-sort-behavior.html#L34)):*
> ```HTML
>     </style>
> 
>     <content></content>
> ```

Did we come to a conclusion about customizing the indicators? Should the user be able to provide their own content?

---

*[vaadin-grid-sort-behavior.html, line 72 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpSf1xnZWhEeyXWUej:-KUpSf1xnZWhEeyXWUek:b-jr5g6e) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0d8f1f88793d2893f31b7b6c1be3b7ca6306a6d4/vaadin-grid-sort-behavior.html#L72)):*
> ```HTML
>       },
> 
>       _parametersChanged: function(grid, path, direction) {
> ```

Arguments don't match the observer signature. Also, we could consider observing `isAttached` from `Polymer.Base` so we wouldn't need to have `attached` callback separately – not sure which is cleaner.

---

*[test/array-data-source.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpTZSWRiHT26yeBhlG:-KUpTZSWRiHT26yeBhlH:byrmhtd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d9af529fa0fa1efac3ea6502c01dfb45b68ccce5/test/array-data-source.html#L94)):*
> ```HTML
>       });
> 
>       it('should handle string values', function() {
> ```

Why was this removed? Just for the silliness of the use case? :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494)*

**Comment by tomivirkki** [comment]
Review status: 8 of 13 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-sort-behavior.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpTubZmZ_hT4ZhySim:-KUpUWK7ukLWbzKmyE7p:buiqi1l) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0d8f1f88793d2893f31b7b6c1be3b7ca6306a6d4/vaadin-grid-sort-behavior.html#L34)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Did we come to a conclusion about customizing the indicators? Should the user be able to provide their own content?
</details>
The content selectors proved problematic in this case. I suggest we add mixins for the indicators (once we get to the theming part) that can also be used to hide the default ones.

---

*[vaadin-grid-sort-behavior.html, line 72 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpSf1xnZWhEeyXWUej:-KUpVpwXbGIPs2mN92tQ:b-ee81qw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0d8f1f88793d2893f31b7b6c1be3b7ca6306a6d4/vaadin-grid-sort-behavior.html#L72)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Arguments don't match the observer signature. Also, we could consider observing `isAttached` from `Polymer.Base` so we wouldn't need to have `attached` callback separately – not sure which is cleaner.
</details>
Fixed the arguments list. isAttached seems to schedule different from attached callback (tests break).

---

*[test/array-data-source.html, line 94 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpTZSWRiHT26yeBhlG:-KUpWCBcJfsBD6CIWaLz:b-u73txg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d9af529fa0fa1efac3ea6502c01dfb45b68ccce5/test/array-data-source.html#L94)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Why was this removed? Just for the silliness of the use case? :-)
</details>
Indeed :) Just because a String 'seems' to work as an array data source in some cases, we shouldn't probably promote it. Additionally a String doesn't have sort() in it's API so this PR would break the use case. Finally, 'items' property is documented to be of type Array so we should jsut stick to that.

The use case in the test would work with `grid.items = 'FOO'.split('')`but that would just end up as a redundant test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-sort-behavior.html, line 72 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-KUpSf1xnZWhEeyXWUej:-KUpw30Xz95m0Z7taO7g:bbg8bzb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0d8f1f88793d2893f31b7b6c1be3b7ca6306a6d4/vaadin-grid-sort-behavior.html#L72)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Fixed the arguments list. isAttached seems to schedule different from attached callback (tests break).
</details>
Ah, it was about the event being fired on detached also. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494)*

**Comment by Saulis** [comment]
:lgtm: I'm gonna merge this now, possible comments about the documentation can be still added afterwards and we can get back to those.

---

Reviewed 4 of 13 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/494#-:-KUucsAG1fXiPPELmrKn:b58txw)*

**Pull request merged**
