### PR TITLE
Fix filter error

### LINKED ISSUE #1283: Filtering throws an error if scrolled to bottom
1. Open a filtering demo
2. Scroll to the bottom
3. Use the filter to empty the grid of items
-> Error is thrown

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1283

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1284)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[test/data-provider.html, line 245 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1284#-LAYICYlBLh7nR7sbwzN:-LAYICYlBLh7nR7sbwzO:b-lxalzr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4925dad027e249099ee24b6568186cb3b5165080/test/data-provider.html#L245)):*
> ```HTML
> 
>       it('should be in loading state when fetching new data', (done) => {
>         let raf;
> ```

What does this variable name mean? Is it abbreviation?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1284)*

**Comment by tomivirkki** [comment]
*[test/data-provider.html, line 245 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1284#-LAYICYlBLh7nR7sbwzN:-LAYIT5n2--ui5rsXZ7e:bhqw2ci) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4925dad027e249099ee24b6568186cb3b5165080/test/data-provider.html#L245)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

What does this variable name mean? Is it abbreviation?
</blockquote></details>

Yes, requestAnimationFrame

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1284)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1284#-:-LAYLmc20E3wbCbn1WF5:bnfp4nl)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1284#-:-LAYO6Q-7HMryLUlbt8Y:bnfp4nl)*

**Pull request merged**
