### PR TITLE
Column resize

### LINKED ISSUE #145: Column resizing
The end user should be able to resize the column widths by dragging the column dividers.

Note that work is being done in the Vaadin Framework Grid for this feature, so sync with that team before starting to implement this feature.

Tracking issue for the the Framework (until they move stuff over to GitHub): https://dev.vaadin.com/ticket/16838

Update (Aug 2016): the feature shipped in Vaadin Framework 7.6 some months ago.

### PR DESCRIPTION
**Pull request by davidpoling**
Fixes #145 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/420)

### CODE REVIEW

**Comment by jouni** [comment]
Official docs missing, but we can handle that once everything else is in order.

**Comment by davidpoling** [comment]
I currently have an issue with signing the CLA, as when I was committing before I was using an unregistered email address. I have rebased my commits and updated the authors for those commits, but it seems as if the CLA is still expecting the unregistered account to sign. Is there any way I can remove the history of the previous commits and possibly reopen the pull request? (Or is there a solution to this issue?)

**Comment by tehapo** [comment]
You can of course abandon this PR, create a completely new branch and make a new pull request with only the required commits.

Another option is that you could locally [modify your git history](https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase-i) and remove all the unwanted commits. After you have made the change you can push the changes to GitHub, but altering the history will required you to use the `--force` (or `-f`) option.

**Comment by manolo** [comment]
I think the easiest way is to add all email addresses to your github account. If the email does not exist anymore and you cannot validate it, then you have to rewrite your history and commit with -f as Teemu suggests.

Something like `git rebase -i HEAD~10`, marking the commits with incorrect emails for editing, and running `git commit --amend --author "Name <email>" --no-edit && git rebase --continue`, should work

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/420#-:-KPlqi1m6nzthEY1vkvV:b-srahjb)*

**Pull request closed without merging**
