### PR TITLE
2.0 columns private

### PR DESCRIPTION
**Pull request by manolo**
Connects to #441

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/508)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[test/x-scroller.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508#-KVA8DXnAJLhQfeh0Vgb:-KVA8DXnAJLhQfeh0Vgc:b-c97yfg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/61d943d80adf914c3139bcc9a191663692029fa4/test/x-scroller.html#L38)):*
> ```HTML
>     <template id="cell">[[index]]</template>
> 
>     <vaadin-grid-table  style$="[[_computedListHeight(listHeight)]]" size="[[size]]" id="scroller" grup-tree="[[columnTree]]">
> ```

Hmm....it says "grup-tree" but the tests are still passing. Does this mean that the x-scroller isn't used anymore (and could be removed)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508)*

**Comment by manolo** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/x-scroller.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508#-KVA8DXnAJLhQfeh0Vgb:-KVABou7kAWmqOtLvIcC:b-8y42pj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/61d943d80adf914c3139bcc9a191663692029fa4/test/x-scroller.html#L38)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Hmm....it says "grup-tree" but the tests are still passing. Does this mean that the x-scroller isn't used anymore (and could be removed)?
</details>
exactly there is no reference to x-scroller, do I remove it ? or fix the typo ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508)*

**Comment by tomivirkki** [comment]
*[test/x-scroller.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508#-KVA8DXnAJLhQfeh0Vgb:-KVACQcREv9dvrX9SE1v:bxb5a7m) ([raw file](https://github.com/vaadin/vaadin-grid/blob/61d943d80adf914c3139bcc9a191663692029fa4/test/x-scroller.html#L38)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> exactly there is no reference to x-scroller, do I remove it ? or fix the typo ?
</details>
I vote for removing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508)*

**Comment by manolo** [comment]
Review status: 0 of 19 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/x-scroller.html, line 38 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508#-KVA8DXnAJLhQfeh0Vgb:-KVAEAqCxPYJEntxzpSY:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/61d943d80adf914c3139bcc9a191663692029fa4/test/x-scroller.html#L38)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> I vote for removing
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508)*

**Comment by Saulis** [comment]
:lgtm: :shipit:  after #505 

---

Reviewed 18 of 19 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508#-:-KVOeJ5gPy4qIMeiZ5qk:b-5og9nn)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: 16 of 19 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508#-:-KVTsG0zfeJKVIpmYuSu:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 15 of 19 files at r1, 1 of 2 files at r2, 3 of 4 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/508)*

**Pull request merged**
