### PR TITLE
Observe columns changes instead of using events

### PR DESCRIPTION
**Pull request by Saulis**
Might've broken some tests 🎱  Let's fix them first thing on monday @tomivirkki 🌈 
Didn't touch `column.headers` property as it's probably gonna change with the column grouping thingie.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/448)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-grid-footer.html, line 23 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKGTHmVwWAj-ibe54J:-KQKGTHmVwWAj-ibe54K:b-c1h7wm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-footer.html#L23)):*
> ```HTML
>           }));
> 
>           this._rows = new Array(rowCount).fill(0).map(function(item, index) {
> ```

.fill is ES6, no worky in IE11

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448)*

**Comment by tomivirkki** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 117 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKITr9RV03nsMlyp5M:-KQKITr9RV03nsMlyp5N:b41iy1k) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-column.html#L117)):*
> ```HTML
> 
>       _flexChanged: function(grid, flex) {
>         var index = grid.columns.indexOf(this);
> ```

Why special handling for multiselect column and not:
`var index = grid._columns.indexOf(this);
grid.notifyPath('_columns.' + index + '.flex', flex);`

---

*[vaadin-grid-selection-behavior.html, line 113 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKNNYNXw08TITkxeEj:-KQKNNYNXw08TITkxeEk:bnrekip) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-selection-behavior.html#L113)):*
> ```HTML
>       } else if (e.path.indexOf('columns.#') === 0) {
>         var pathParts = e.path.split('.');
>         var index = parseInt(pathParts[1].substring(1)) + multiSelection ? 1 : 0;
> ```

This looks fragile. Could we observe _columns instead?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448)*

**Comment by Saulis** [comment]
Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 117 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKITr9RV03nsMlyp5M:-KQP-kiMreOyJGbsI6Ur:b-nrjom9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-column.html#L117)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Why special handling for multiselect column and not:
> `var index = grid._columns.indexOf(this);
> grid.notifyPath('_columns.' + index + '.flex', flex);`
</details>
Notifying `columns` is observed (allowing users to call grid.set('columns.0.foo', 'bar') etc) and will notify `_columns` for changes. Hasn't been bound the other way around, so notifying `_columns` won't notify `columns` of changes.

---

*[vaadin-grid-footer.html, line 23 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKGTHmVwWAj-ibe54J:-KQP0sYkMRkCfIFbXVDT:b-89okj9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-footer.html#L23)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> .fill is ES6, no worky in IE11
</details>
Crap.

---

*[vaadin-grid-selection-behavior.html, line 113 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKNNYNXw08TITkxeEj:-KQP69HzmrbnFHUt2XyN:b682msh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-selection-behavior.html#L113)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This looks fragile. Could we observe _columns instead?
</details>
We have to observe `columns` in order for the users to be able use `grid.set('columns.0.width', 'foo')` etc. bindings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 117 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448#-KQKITr9RV03nsMlyp5M:-KQPBtnmWwcL8WV7yGn1:bflc4z4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8242c1c613ce2914ed3b24a0dcae2cb87f3597aa/vaadin-grid-column.html#L117)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Notifying `columns` is observed (allowing users to call grid.set('columns.0.foo', 'bar') etc) and will notify `_columns` for changes. Hasn't been bound the other way around, so notifying `_columns` won't notify `columns` of changes.
</details>
I applied the proposed change and invoking
`grid.set('columns.1.width', '10px');`
works for me just fine.

Also all the tests pass. There should at least be a test case that fails after the change if it was erroneous.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 10 files at r1, 11 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/448)*

**Pull request merged**
