### PR TITLE
Use forked vaadin FW version for elements.

### PR DESCRIPTION
**Pull request by manolo**
This removes our local version of Escalator and any grid modification
in favour of elements fork which is reviewed by FW in gerrit

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/370)

### CODE REVIEW

**Comment by tomivirkki** [comment]
I don't think the fork is reviewed by the FW until we request a merge from it? My concern about this is that the branch isn't protected anyhow. There's no review process in prior to pushing changes to the branch but still our master vaadin-grid would depend on them (the unreviewed changes). Or am I missing something here?

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> #### Use forked vaadin FW version for elements\.
> 
> This removes our local version of Escalator and any grid modification
> 
> in favour of elements fork which is reviewed by FW in gerrit
> 
> 
> 
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/370#-:-KIXJ4WZHSf9k3UI5BhC:-200524981)*

**Comment by manolo** [comment]
Right now, all changes in this branch has been approved by Teemu. 
So the process is that we write some changes, they do a quick review and publish the artefact. This speeds up contributions, makes easier to rebase with master, and keep them informed.

Pasting the relevant part of a conversation I had with Teemu S.:


[27/04/16 14:29:17] Manuel Carrasco:
  What happens when we have new modifications, actually I have 3 new patches.
[27/04/16 14:29:37] Teemu Suo-Anttila:
  you push them to gerrit, we'll trigger the autovalidation to that branch asap
  autovalidation runs to see that the patches are OK
  after that, you push them through (I'd like to do a cursory review for them at the same time)
  then you ping us that "hey, I need a build"  and we trigger it
  you can also build it locally with just mvn clean install
  this will give you 7.7.0-SNAPSHOT to test against

<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> I don't think the fork is reviewed by the FW until we request a merge from it? My concern about this is that the branch isn't protected anyhow. There's no review process in prior to pushing changes to the branch but still our master vaadin-grid would depend on them (the unreviewed changes). Or am I missing something here?
</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/370#-:-KIaWzbwMp5ggMO8PK3M:-1951239202)*

**Comment by manolo** [comment]
So, in summary:
- our changes are monitored and known by FW team, vs having forked classes out of their control
- our changes are draft reviewed by them vs no review from them at all
- our changes are easier to merge in master
- they can pickup and review our changes whenever they need them or have a while

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Right now, all changes in this branch has been approved by Teemu. 
> So the process is that we write some changes, they do a quick review and publish the artefact. This speeds up contributions, makes easier to rebase with master, and keep them informed.
> 
> Pasting the relevant part of a conversation I had with Teemu S.:
> 
> 
> [27/04/16 14:29:17] Manuel Carrasco:
>   What happens when we have new modifications, actually I have 3 new patches.
> [27/04/16 14:29:37] Teemu Suo-Anttila:
>   you push them to gerrit, we'll trigger the autovalidation to that branch asap
>   autovalidation runs to see that the patches are OK
>   after that, you push them through (I'd like to do a cursory review for them at the same time)
>   then you ping us that "hey, I need a build"  and we trigger it
>   you can also build it locally with just mvn clean install
>   this will give you 7.7.0-SNAPSHOT to test against
</details>


---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/370#-:-KIalWryjROAGouPKnQ3:-1759509711)*

**Comment by tomivirkki** [comment]
Ok, sounds at least better than the current process then. :lgtm: 

<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> So, in summary:
> - our changes are monitored and known by FW team, vs having forked classes out of their control
> - our changes are draft reviewed by them vs no review from them at all
> - our changes are easier to merge in master
> - they can pickup and review our changes whenever they need them or have a while
> 
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/370#-:-KIarcXY22IYAzi8T72e:1249043954)*

**Comment by tomivirkki** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/370)*

**Pull request merged**
