### PR TITLE
Locate table element correctly when content is passed from a parent component

### LINKED ISSUE #237: Light DOM parsing doesn't work when passed as <content> from a parent component
Given a component which nests `<vaadin-grid>` the light DOM is not parsed:

```html
<!doctype html>
<html>

<head>
  <script src='https://cdn.vaadin.com/vaadin-components/latest/webcomponentsjs/webcomponents-lite.js'></script>
  <link href='../vaadin-grid.html' rel='import'>
</head>

<body>
  <dom-module id="grid-wrapper">
    <template>
      <vaadin-grid>
        <content></content>
      </vaadin-grid>
    </template>
  </dom-module>

  <grid-wrapper>
    <table>
      <col name="Foo"></col>
      <tbody>
        <tr>
          <td>Bar</td>
        </tr>
      </tbody>
    </table>
  </grid-wrapper>
  <script>
    HTMLImports.whenReady(function() {
      Polymer({
        is: 'grid-wrapper'
      });
    });
  </script>
</body>

</html>
```

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #237

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/241)

### CODE REVIEW

**Comment by tehapo** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[test/grid-rendering-light-dom.html, line 172 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241#-K2kQx1AdZZK6SJFEdxm)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/583db8bd29979f32a5070a11efba13a7c098d8da/test/grid-rendering-light-dom.html#L172)):</sup>
I would use double quotes inside the selector (colspan="2") to avoid the need to escape the single quotes.

I'm ok to merge without changing this minor thing, but it would look cleaner.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by Saulis** [comment]
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/grid-rendering-light-dom.html, line 172 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241#-K2kQx1AdZZK6SJFEdxm)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/583db8bd29979f32a5070a11efba13a7c098d8da/test/grid-rendering-light-dom.html#L172)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by tehapo** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by Saulis** [comment]
Reviewed 2 of 5 files at r1, 1 of 3 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[vaadin-grid.html, line 12 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241#-K2oxx-fll12dpzcTyyS)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a25fc22200dd997b423f18431281fc34b6de6571/vaadin-grid.html#L12)):</sup>
I guess this is still needed?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by Saulis** [comment]
iPhone seems the fail consistently on: test/grid-rendering-light-dom.html » rendering light DOM » with thead » should have colspan on th elements


---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by tomivirkki** [comment]
Strange...tests pass locally on iOS simulator


---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

<sup>**[vaadin-grid.html, line 12 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241#-K2oxx-fll12dpzcTyyS)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a25fc22200dd997b423f18431281fc34b6de6571/vaadin-grid.html#L12)):</sup>
I was also wondering about this. I think it's intended for polyfilled browsers for hiding the inner table element before the component gets upgraded.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Comment by Saulis** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/241)

**Pull request merged**
