### PR TITLE
Enable visual tests with Lumo

### PR DESCRIPTION
**Pull request by samiheikki**
Connects to https://github.com/vaadin/components-team-tasks/issues/314

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1308)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 53 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[test/visual/test.js, line 41 at r1](https://reviewable.io/reviews/vaadin/vaadin-grid/1308#-LDmbcjDBTcf7XjY6t2-:-LDmbcjDBTcf7XjY6t20:bh6nyqy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8a48e5145ce9f61521bfb936b15684071314b639/test/visual/test.js#L41)):*
> ```JavaScript
>       // "Permission denied to access property "__eventWrappers1527612800414""
>       // Skip sorting visual tests in Firefox
>       .only.notIn('firefox')
> ```

This does not work in my local,  also  tried in @yuriyvaadin  laptop.
Seems that `.only` is undefined in latest gemini. I did remove `node_modules` and  version `4.19.3` was installed after running `npm i --no-save gemini@^4.0.0 gemini-sauce gemini-polyserve` 
Can you try in your local?

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1308)*

**Comment by samiheikki** [comment]
Yeah I noticed I have gemini 5.x installed locally. Will fix today

**Comment by manolo** [comment]
Could you check at the same time whether the error described for FF is still happening, perhaps it might be fixed in new versions somehow

---

Review status: 0 of 53 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1308#-:-LDolwGoEL4Xmp3Gic6b:bpy3lr6)*

**Comment by manolo** [comment]
Sorry forgot about my last comment, I thought this exception was in previous tests, but was introduced now, so you have already checked that FF has the issues.

---

Review status: 0 of 53 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1308#-:-LDpgcB72styXPpB7lnj:b8w1n4f)*

**Comment by samiheikki** [comment]
Commented firefox on gemini.yml and visual tests are passing now. Let me know if you prefer a different approach.

**Comment by manolo** [comment]
This approach means that we lose all FF tests, not only sorting feature. I do prefer your previous approach, the only thing is that you need to update gemini version in travis batch file `npm i --no-save gemini@^5.0.0`.
We will update other components later to have the same version in all elements.

---

Review status: 0 of 53 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1308#-:-LDu151ZE0lzoW7l5Wws:b5cpwbh)*

**Comment by manolo** [comment]
I'll discuss in daily today if we can bump gemini version, if alright I'll update your previous commit.
Version update seems working in CI without problems : https://travis-ci.org/vaadin/vaadin-grid/builds/386519006 

---

Review status: 0 of 53 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1308#-:-LDu3nmz1D3vUOnWNCxE:bnbwdij)*

**Pull request merged**
