### PR TITLE
Use latest iron-component-page.

### PR DESCRIPTION
**Pull request by manolo**
Connected to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/950)

### CODE REVIEW

**Comment by tomivirkki** [comment]
- Wondering why `<vaadin-grid-column-group>` doesn't show up in the apidocs?
- There's also a couple of behaviors listed (all behaviors can be removed)
- `<vaadin-grid-column>` is showing `connectedCallback` and `disconnectedCallback` in the apidoc. Can those be marked private?
-  `<vaadin-grid-filter>` and -sorter are for some reason showing all these Polymer base api's like `get` and `notifySplices`. Any way to get them hidden?
- `<vaadin-grid-outer-scroller>`, `<vaadin-grid-scroller>` and `<vaadin-grid-templatizer>` are not meant for public use? Is it possible to hide them from the apidoc without major hacks?

---

Review status: 0 of 28 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[index.html, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPgxcPD56Qu99__5Rm:-KsPgxcPD56Qu99__5Rn:b81ead7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/index.html#L5)):*
> ```HTML
> <html>
>   <head>
>     <title>vaadin-combo-box</title>
> ```

vaadin-grid

---

*[vaadin-grid-column-group.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPh0zh_ldlA6vrrHcE:-KsPh0zi45mxjiw-j5Wt:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-column-group.html#L13)):*
> ```HTML
>   <script>
>     if (!Polymer.Element) {
>       throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---

*[vaadin-grid-column.html, line 345 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhDTvcBW2rEIylBZN:-KsPhDTvcBW2rEIylBZO:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-column.html#L345)):*
> ```HTML
>   <script>
>   if (!Polymer.Element) {
>     throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---

*[vaadin-grid-filter.html, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhFjGWNj5wCvTCOhO:-KsPhFjGWNj5wCvTCOhP:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-filter.html#L28)):*
> ```HTML
>   <script>
>     if (!Polymer.Element) {
>       throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---

*[vaadin-grid-outer-scroller.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhJsX_Rp-wjIkXugA:-KsPhJsX_Rp-wjIkXugB:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-outer-scroller.html#L34)):*
> ```HTML
> <script>
>   if (!Polymer.Element) {
>     throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---

*[vaadin-grid-scroller.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhMjgVedvvlXGRQNk:-KsPhMjgVedvvlXGRQNl:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-scroller.html#L13)):*
> ```HTML
> <script>
>   if (!Polymer.Element) {
>     throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---

*[vaadin-grid-selection-column.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhPiwAf1N5kLtQRg3:-KsPhPiwAf1N5kLtQRg4:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-selection-column.html#L23)):*
> ```HTML
>   <script>
>   if (!Polymer.Element) {
>     throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---

*[vaadin-grid-sorter.html, line 87 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhSi-FqcDDrOHx05e:-KsPhSi-FqcDDrOHx05f:b-5ij5vk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-sorter.html#L87)):*
> ```HTML
>   <script>
>     if (!Polymer.Element) {
>       throw new Error(`Unexpected Polymer version ${Polymer.version} is used, expected v2.0.0 or later.`);
> ```

One warning is enough (in vaadin-grid.html)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-:-KsPiLMPiNxK-se38fTN:b-xose9l)*

**Comment by manolo** [comment]
> Wondering why <vaadin-grid-column-group> doesn't show up in the apidocs?

It's because the `concat` in the observers block adding all super observers. I added a FIXME comment to fix it once we figure out a way to avoid that.

> There's also a couple of behaviors listed (all behaviors can be removed)

I didn't see a way for excluding those behaviours by adding any annotation. Apparently the only way is not to pass them as arguments to the polymer cli, hence we need to maintain somehow a file with the list of the classes to analyse.

Trying to figure out why internal API is shown in certain cases.

---

Review status: 0 of 28 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-:-KsQ5Iqfrx6BzaulJt4Y:b-p5r043)*

**Comment by tomivirkki** [comment]
> I didn't see a way for excluding those behaviours by adding any annotation

I meant that they aren’t used by grid at all and the files can be deleted. Not a blocker for this PR

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-:-KsbVpUTJ86vHhixnH02:bf09arx)*

**Comment by manolo** [comment]
- Removed unused behaviors
- Added private annotations to methods that we override but we don't want to have in final API docs
- Removing Polymer public api in elements extending directly the Polymer.Element cannot be fixed until analyzer fixes it  (reported at : https://github.com/PolymerElements/iron-component-page/issues/147) or we add an empty mixin workaround, prototyped at : https://github.com/vaadin/vaadin-grid/commit/c461c7a3f331d869ff223c25a9c1d3d2dba53ee8 

---

Review status: 0 of 30 files reviewed at latest revision, 8 unresolved discussions, some commit checks broke.

---

*[index.html, line 5 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPgxcPD56Qu99__5Rm:-KscKeO16DM1VpGYxIps:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/index.html#L5)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

vaadin-grid
</blockquote></details>

Done.

---

*[vaadin-grid-column-group.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPh0zh_ldlA6vrrHcE:-KscKfqfsa9gxKltUl_o:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-column-group.html#L13)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 345 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhDTvcBW2rEIylBZN:-KscKgOHQIbyP713W8w1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-column.html#L345)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---

*[vaadin-grid-filter.html, line 28 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhFjGWNj5wCvTCOhO:-KscKh731j3JEzu3Ae2e:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-filter.html#L28)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---

*[vaadin-grid-outer-scroller.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhJsX_Rp-wjIkXugA:-KscKhqQB4acPty0ODxJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-outer-scroller.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---

*[vaadin-grid-scroller.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhMjgVedvvlXGRQNk:-KscKiNTgSx78LfAL6gu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-scroller.html#L13)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhPiwAf1N5kLtQRg3:-KscKj2qHxMd1F-chvTB:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-selection-column.html#L23)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---

*[vaadin-grid-sorter.html, line 87 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-KsPhSi-FqcDDrOHx05e:-KscKjcZ0yBLZFW9UhrX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32cbab7643e09cb66436a87b09826551aa7c2fea/vaadin-grid-sorter.html#L87)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

One warning is enough (in vaadin-grid.html)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-:-KscJsuxolJZS2ukl54r:b-17etau)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 17 of 28 files at r1, 13 of 13 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/950#-:-KscPTJb4AG8CArTvvgS:b-uwkowd)*

**Pull request merged**
