### PR TITLE
Use font-smoothing on the host

### PR DESCRIPTION
**Pull request by tomivirkki**
Connects to https://github.com/vaadin/vaadin-checkbox/issues/58

Info: https://github.com/vaadin/vaadin-checkbox/issues/58#issuecomment-361255758

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1273)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[theme/lumo/vaadin-grid.html, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273#-L9jl4vnAamEiqWKfEcB:-L9jl4vnAamEiqWKfEcC:b-ctmsl8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/10577cf757ea7564973023eee79ab910d393aea3/theme/lumo/vaadin-grid.html#L22)):*
> ```HTML
>         -webkit-text-size-adjust: 100%;
>         -webkit-tap-highlight-color: transparent;
>         -webkit-font-smoothing: antialiased;
> ```

consider adding also `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273)*

**Comment by web-padawan** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-grid.html, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273#-L9jl4vnAamEiqWKfEcB:-L9jlEMGE--ui2JgQAHF:bd19lmc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/10577cf757ea7564973023eee79ab910d393aea3/theme/lumo/vaadin-grid.html#L22)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

consider adding also `
</blockquote></details>

... `-moz-osx-font-smoothing:grayscale` for visual consistency in Firefox.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273)*

**Comment by tomivirkki** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[theme/lumo/vaadin-grid.html, line 22 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273#-L9jl4vnAamEiqWKfEcB:-L9jp5_y0saAjkjXXkHN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/10577cf757ea7564973023eee79ab910d393aea3/theme/lumo/vaadin-grid.html#L22)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

... `-moz-osx-font-smoothing:grayscale` for visual consistency in Firefox.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273#-:-L9kOxaR1Tgqr7pQcwXe:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1273#-:-L9nGpb4EpdzKhRWCQ96:bnfp4nl)*

**Pull request merged**
