### PR TITLE
Feature/2.0 filtering

### LINKED ISSUE #500: Filtering helpers

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #500

---

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/507)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Ping @magi42

**Comment by manolo** [comment]
do you mind to add a demo ?

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-:-KVA1vC_sK1T-1ftiBRb:bf4lm5k)*

**Comment by tomivirkki** [comment]
The demo's aren't required/important at this point (there's no demo for groups/array data sources...).

If you're talking about the developer files 'demo.html, grp.html, dynamic.html', there should only be 1 file that has all grid features combined (maybe 'dev.html' would be least confusing), not scattered around like currently...but that's another PR.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-:-KVA4OFZ2ikgKnaKROaw:b80cdr2)*

**Comment by manolo** [comment]
I meant a demo file (like the grp.html in groups)  so as we can play with it. At least until we pick up best demos and align with other components.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-:-KVAEZh9ZurRadFZiNKL:b-xsv2fo)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid-array-data-source-behavior.html, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVAF2oSao8Yp4F1bowQ:-KVAF2oSao8Yp4F1bowR:b1c2y87) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-array-data-source-behavior.html#L30)):*
> ```HTML
>     _arrayDataSource: function(opts, cb) {
>       var items = (this.items || []).slice(0);
>       
> ```

nit: spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by tomivirkki** [comment]
Those are not demos (grp.html and demo.html (even though it's incorrectly named so) ). To repeat:

"If you're talking about the developer files 'demo.html, grp.html, dynamic.html', there should only be 1 file that has all grid features combined (maybe 'dev.html' would be least confusing), not scattered around like currently...but that's another PR."

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-:-KVAFnLv1QaGIvuoCB3p:b-bsf90m)*

**Comment by manolo** [comment]
I know those are no demos for the final user.
I just wanted a demo file so as I can play with it as a reviewer and facilitate the work.
Obviously I can spend a while and create my own one including all use cases based on the PR docs and code, but I guessed (probably my fault) that you already had one to play with while you was implementing the feature. 

---

Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-:-KVB0ZvPyxJR0QNc26X3:boec038)*

**Comment by manolo** [comment]
Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-filter-behavior.html, line 54 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3Xhw0mLVHFKOxsaS:-KVB3Xhw0mLVHFKOxsaT:bs4qxmh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L54)):*
> ```HTML
>   vaadin.elements.grid = vaadin.elements.grid || {};
> 
>   vaadin.elements.grid.FilterBehavior = {
> ```

mind to annotate the behavior

---

*[vaadin-grid-filter-behavior.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB21mA9yGYPHNKxvaF:-KVB21mA9yGYPHNKxvaG:bqog6yj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L76)):*
> ```HTML
>       e.stopPropagation();
> 
>       this.debounce('filters-changed', function () {
> ```

Is there a way to avoid this debouncing, to me it looks wrong to wait a min of  200 ms  to notify that filter has changed.
If it's a problem of multiple calls coming on filter-changed instead of one, I think it's could be a symptom of bad implementation.

---

*[vaadin-grid-filter-behavior.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3Ecdsdv7st8AS7eZ:-KVB3Ecdsdv7st8AS7e_:bo35cjn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L85)):*
> ```HTML
>     },
> 
>     _mapFilters: function() {
> ```

_map is confusing name, since it is returning an array of objects, not a map

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 144 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3rKlRChJjofEfG7a:-KVB3rKlRChJjofEfG7b:b-1pyhej) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L144)):*
> Filtering helpers behave a lot similarly to [vaadinelement]#vaadin-grid#'s sorting helpers.

remove `a lot` or replace with very

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 146 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB45o06HHHMA9amHdX:-KVB45o06HHHMA9amHdY:b-piqz5n) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L146)):*
> ```AsciiDoc
> Filtering helpers behave a lot similarly to [vaadinelement]#vaadin-grid#'s sorting helpers.
> 
> Place a [elementname]#vaadin-grid-filter# element with a [propertyname]#path# defined into a header/footer cell to show an input field that automatically affects the [vaadinelement]#vaadin-grid#'s data when using an array data source.
> ```

afffects -> filters

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 148 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB4Sy97jCmy5Ets_DX:-KVB4Sy97jCmy5Ets_DY:b9a8094) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L148)):*
> ```AsciiDoc
> Place a [elementname]#vaadin-grid-filter# element with a [propertyname]#path# defined into a header/footer cell to show an input field that automatically affects the [vaadinelement]#vaadin-grid#'s data when using an array data source.
> 
> The element helps in filtering with custom data sources also since they automatically include filtering information to the data source callback parameters.
> ```

Not sure if `helps in filtering` is right, I think `helps to filter custom data` would sound better.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 185 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB56XviBdAQOxBxg7k:-KVB56XviBdAQOxBxg7l:b5lvd3x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L185)):*
> ```AsciiDoc
> == Filtering Data with a Custom Data Source
> 
> While filtering works with array data sources without any extra code, custom data sources need to provide pre-filtered data to the [vaadinelement]#vaadin-grid#.
> ```

probably `without any extra code` can be replaced by `out-of-the-box`

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 187 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB5SPYaKKwgiQd1A26:-KVB5SPYaKKwgiQd1A27:b2qbu2e) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L187)):*
> ```AsciiDoc
> While filtering works with array data sources without any extra code, custom data sources need to provide pre-filtered data to the [vaadinelement]#vaadin-grid#.
> 
> Again, whenever the value of a [elementname]#vaadin-grid-filter# changes (for example when a user types something) the [propertyname]#dataSource# is asked for fresh data with filtering information included in the request.
> ```

Remove Again does not add any information.
`with filtering` -> `with the filtering`

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 210 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB61ZMl5EZbBDTSOD-:-KVB61ZMl5EZbBDTSOD0:b-baj9k4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L210)):*
> ```AsciiDoc
> ----
> 
> When the [vaadinelement]#vaadin-grid#'s filters change, it fires a [propertyname]#filters-changed# -event whose [propertyname]#detail.filters# is an array of the filters.
> ```

What is `filters` here ?  a property a collection ? Probably you can change the sentence by `When any of the vaadin-grid filters changes, ...` 

---

*[test/filtering.html, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB6cTss3kf3NeGEo9R:-KVB6cTss3kf3NeGEo9S:b4d35so) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/test/filtering.html#L71)):*
> ```HTML
> 
>       it('should update value after `input` event from a child', function(done) {
>         filter.addEventListener('filter-changed', function(e) {
> ```

I would expect that this test is synchronous

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by Saulis** [comment]
Review status: 0 of 7 files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-filter-behavior.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB21mA9yGYPHNKxvaF:-KVOgJG0Np-4jn_KIU9N:bcwizn1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L76)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Is there a way to avoid this debouncing, to me it looks wrong to wait a min of  200 ms  to notify that filter has changed.
> If it's a problem of multiple calls coming on filter-changed instead of one, I think it's could be a symptom of bad implementation.
</details>
Yeah I agree – I believe this `debounce` is meant to delay the user input coming through. We should instead set the `debounce` inside the `_filterChanged` of `<vaadin-grid-filter>` ?

---

*[vaadin-grid-filter-behavior.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3Ecdsdv7st8AS7eZ:-KVOgs9IqRf4OXz2GsJZ:bb6rrza) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L85)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> _map is confusing name, since it is returning an array of objects, not a map
</details>
`map` is used here more as a verb – a noun would be used in other order like e.g. `filterMap`

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 144 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3rKlRChJjofEfG7a:-KVOhCO7Cqe_gjL3UfLB:b-exc0ti) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L144)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> > Filtering helpers behave a lot similarly to [vaadinelement]#vaadin-grid#'s sorting helpers.
> 
> remove `a lot` or replace with very
</details>
I think just `behave similarly to...` is enough

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-filter-behavior.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3Ecdsdv7st8AS7eZ:-KVBmImhVudJXisCnGmg:b-vddktq) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L85)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> _map is confusing name, since it is returning an array of objects, not a map
</details>
"map" is a function that converts an array into another array while modifying its items. This is exactly what this function does. "map" in the function name doesn't refer to it's return type.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-filter-behavior.html, line 54 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3Xhw0mLVHFKOxsaS:-KVBlQG3mAya8YADO6R2:b-hwiv2d) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L54)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> mind to annotate the behavior
</details>
Doesn't make sense to annotate just one behavior in a PR while it is still based on a dev-2.0 where there's no other annotations yet. Merging the PR would end up in dev-2.0 with one random behavior annotated.

The annotations are currently added as part of the "columns-private" PR. If it gets merged before this, the annotation should be added here as part of the rebase process. If this get's merged before, the FilterBehavior annotation should be added in the other PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by tomivirkki** [comment]
Merged all the dev-time files into one (even though it's not in scope of this PR or DoD).

From now on do not create new temp files anymore but instead if you're creating a new feature, you may include related changes in the same grid in dev.html so we have all in one place. Eventually this file should be removed also.

---

Review status: 0 of 12 files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-grid-array-data-source-behavior.html, line 30 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVAF2oSao8Yp4F1bowQ:-KVEHOgfHYE5ex1anEgH:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-array-data-source-behavior.html#L30)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> nit: spaces
</details>
Done.

---

*[vaadin-grid-filter-behavior.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB21mA9yGYPHNKxvaF:-KVBmBaErjwd0b1SDMUk:b-owg6wo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L76)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Yeah I agree – I believe this `debounce` is meant to delay the user input coming through. We should instead set the `debounce` inside the `_filterChanged` of `<vaadin-grid-filter>` ?
</details>
We don't want grid asking the dataSource for new data on every keystroke to the filter input. It's ok to fire the event synchronously so moved that out of the debouncer.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 144 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB3rKlRChJjofEfG7a:-KVBqbsehPhaM5Zt6656:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L144)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> > Filtering helpers behave a lot similarly to [vaadinelement]#vaadin-grid#'s sorting helpers.
> 
> remove `a lot` or replace with very
</details>
Done.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 146 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB45o06HHHMA9amHdX:-KVBqf_5v1XUW_o7EY6g:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L146)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> afffects -> filters
</details>
Done.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 148 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB4Sy97jCmy5Ets_DX:-KVBqjkawwTGlO4XsSf8:bpumyt6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L148)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Not sure if `helps in filtering` is right, I think `helps to filter custom data` would sound better.
</details>
I think it's better as it is. "helps to filter custom data" sounds wrong imo.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 185 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB56XviBdAQOxBxg7k:-KVBrbLhPLWtednd3uBC:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L185)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> probably `without any extra code` can be replaced by `out-of-the-box`
</details>
Done.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 187 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB5SPYaKKwgiQd1A26:-KVBrm6ayq0ulnzIkLzO:b488s6n) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L187)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Remove Again does not add any information.
> `with filtering` -> `with the filtering`
</details>
Removed "Again".

"...with the filtering information included" would not be right in this case since the referred "filtering information" isn't mentioned before.

---

*[docs/vaadin-grid-sorting-filtering.adoc, line 210 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB61ZMl5EZbBDTSOD-:-KVOlzDkX3nj108Nq5dP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/docs/vaadin-grid-sorting-filtering.adoc#L210)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> What is `filters` here ?  a property a collection ? Probably you can change the sentence by `When any of the vaadin-grid filters changes, ...` 
</details>
Done.

---

*[test/filtering.html, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB6cTss3kf3NeGEo9R:-KVEIECpc2ws-IzUE1oV:b-wqa443) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/test/filtering.html#L71)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would expect that this test is synchronous
</details>
It follows the same pattern as the rest of the tests (that are also synchronous).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-:-KVEGxwmgq34wuLTeX1u:b-hvsijh)*

**Comment by Saulis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 11 unresolved discussions.

---

*[vaadin-grid-filter-behavior.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB21mA9yGYPHNKxvaF:-KVPPmbtMK5A5Uq2vxAi:b-q8bjd2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L76)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> We don't want grid asking the dataSource for new data on every keystroke to the filter input. It's ok to fire the event synchronously so moved that out of the debouncer.
</details>
I think the `debouncer` should be as closer to the keystrokes. Secondly, what's actually the purpose for firing `filters-changed` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-filter-behavior.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVB21mA9yGYPHNKxvaF:-KVQ3PRm0vwh3OT4DSGT:bgpn370) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce710a27b569ae13429b38120153981f8b630361/vaadin-grid-filter-behavior.html#L76)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> I think the `debouncer` should be as closer to the keystrokes. Secondly, what's actually the purpose for firing `filters-changed` ?
</details>
Done. Removed `filters-changed` and `sort-order-changed` events also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by Saulis** [comment]
Review status: 0 of 14 files reviewed at latest revision, 12 unresolved discussions.

---

*[test/filtering.html, line 115 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVQ5IomUxip_cNDheoN:-KVQ5IomUxip_cNDheoO:b-oyw4b3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce7c59d0900f9720eb8e4d638b65f9880a8e2262/test/filtering.html#L115)):*
> ```HTML
> 
>         grid._filters[0].value = '';
>         grid.flushDebouncer('filters-changed');
> ```

I guess this isn't necessary anymore? Otherwise, :lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by tomivirkki** [comment]
*[test/filtering.html, line 115 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507#-KVQ5IomUxip_cNDheoN:-KVTl0kC7TSPwucVBycO:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ce7c59d0900f9720eb8e4d638b65f9880a8e2262/test/filtering.html#L115)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> I guess this isn't necessary anymore? Otherwise, :lgtm: 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Comment by Saulis** [comment]
Reviewed 2 of 4 files at r1, 1 of 5 files at r2, 4 of 4 files at r3, 7 of 7 files at r4.
Review status: 7 of 14 files reviewed at latest revision, 11 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/507)*

**Pull request merged**
