### PR TITLE
Update to use latest iron-list

### PR DESCRIPTION
**Pull request by web-padawan**
Also remove unused code.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1248)

### CODE REVIEW

**Comment by web-padawan** [comment]
BTW might be worth to upgrade to the `

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1248#-:-L99cHd_95HzTjRxOFy0:bp8loen)*

**Comment by web-padawan** [comment]
BTW worth upgrading to 2.0.14, the only change compared to 2.0.13 is this one PolymerElements/iron-list@e21da8d

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1248#-:-L9A2bNG8Lh9psSw2FTO:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1248#-:-L9A7hk36Xp1U3GKPmCv:bg7igkv)*

**Pull request merged**
