### PR TITLE
Fix/header scroll

### PR DESCRIPTION
**Pull request by manolo**
Connected to #878 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/953)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid-column-resizing-mixin.html, line 56 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KsllNyuHtcNgpzwamoT:-KsllNyv6EvKqoYa4dRH:b-2b0ruf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/108a3eb9f5906da8a0db4a6796b75e4445e01a4c/vaadin-grid-column-resizing-mixin.html#L56)):*
> ```HTML
>     ready() {
>       super.ready();
>       const el = this.$.scroller;
> ```

Rename constant to `scroller` for clarity

---

*[vaadin-grid-column-resizing-mixin.html, line 64 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KslkznwaMZchNgryUMn:-KslkznwaMZchNgryUMo:b-rq4vxx) ([raw file](https://github.com/vaadin/vaadin-grid/blob/108a3eb9f5906da8a0db4a6796b75e4445e01a4c/vaadin-grid-column-resizing-mixin.html#L64)):*
> ```HTML
>       // Disable contextmenu if header has reordering enabled or when on resize separator
>       el.addEventListener('contextmenu',
>         e => (this.columnReorderingAllowed || e.currentTarget.getAttribute('part') != 'resize-handle') && e.preventDefault());
> ```

Doesn't this disable using context menu completely on the grid when column reordering is allowed. That we don't want. Also, column reordering related code should not be moved from column-reordering-mixin to here (column-resizing-mixin) even if that eliminates some code. (also fix comment)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953)*

**Comment by tomivirkki** [comment]
Ping @manolo 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-:-KsnuECRyniepIKiuOPH:bict1rl)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-column-resizing-mixin.html, line 56 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KsllNyuHtcNgpzwamoT:-KsnwMbpllfYhCwNUfp-:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/108a3eb9f5906da8a0db4a6796b75e4445e01a4c/vaadin-grid-column-resizing-mixin.html#L56)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rename constant to `scroller` for clarity
</blockquote></details>

Done.

---

*[vaadin-grid-column-resizing-mixin.html, line 64 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KslkznwaMZchNgryUMn:-KsnwP47of3k_WIPEnPE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/108a3eb9f5906da8a0db4a6796b75e4445e01a4c/vaadin-grid-column-resizing-mixin.html#L64)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Doesn't this disable using context menu completely on the grid when column reordering is allowed. That we don't want. Also, column reordering related code should not be moved from column-reordering-mixin to here (column-resizing-mixin) even if that eliminates some code. (also fix comment)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid-column-reordering-mixin.html, line 89 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KsnwwH7xT7TPsEMcCK0:-KsnwwH7xT7TPsEMcCK1:bxrlti8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c8abf789bc14fe9e4ab389cf5a3796332c36bec/vaadin-grid-column-reordering-mixin.html#L89)):*
> ```HTML
>       this.addEventListener('touchend', this._onTouchEnd.bind(this));
> 
>       // Cancel contextmenu when reordering columns
> ```

This file doesn't need to change. The behavior is the same in the old revision but better aligned with other listeners.

---

*[vaadin-grid-column-resizing-mixin.html, line 59 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KsnxGHiewWqZVOyU9Kk:-KsnxGHjd3rVl5TOW_l2:b3pnth6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c8abf789bc14fe9e4ab389cf5a3796332c36bec/vaadin-grid-column-resizing-mixin.html#L59)):*
> ```HTML
>       Polymer.Gestures.addListener(scroller, 'track', this._onHeaderTrack.bind(this));
> 
>       // Allow scrolling in headers if not resizing.
> ```

The comment is inverted. Should say "Disallow scrolling while resizing"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[vaadin-grid-column-reordering-mixin.html, line 89 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KsnwwH7xT7TPsEMcCK0:-Kso0jlhiGi2DtBDjzAT:b-bflzpf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c8abf789bc14fe9e4ab389cf5a3796332c36bec/vaadin-grid-column-reordering-mixin.html#L89)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This file doesn't need to change. The behavior is the same in the old revision but better aligned with other listeners.
</blockquote></details>

Well, I'd rather ES6 concise and modern syntax for trivial code. Anyways done.

---

*[vaadin-grid-column-resizing-mixin.html, line 59 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-KsnxGHiewWqZVOyU9Kk:-Kso0aSJmvgP8St5T49j:b-j4lzw2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c8abf789bc14fe9e4ab389cf5a3796332c36bec/vaadin-grid-column-resizing-mixin.html#L59)):*
> Disallow scrolling while resizing

Much better. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/953#-:-Kso1ihDAW4ysj0O5i8R:bnfp4nl)*

**Pull request merged**
