### PR TITLE
Fix/api doc

### LINKED ISSUE #621: Revise and FIX API doc
API doc have some issues, like wrong formatting component description in css section, missing property section in vaadin-grid-column, and event documentation.

screen shot 2016-12-27 at 14 17 58

screen shot 2016-12-27 at 14 15 35

### PR DESCRIPTION
**Pull request by manolo**
fixes #621

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/625)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_45DT2FEWNzJOXR2lp:-K_45DT2FEWNzJOXR2lq:b-p1xm0d) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L12)):*
> ```HTML
>

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_45DT2FEWNzJOXR2lp:-K_4D-Jz8FZbQMMqWY8a:b-3uah1y) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L12)):*
> Replace with vaadin-grid

What have I to replace here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 90 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_49-0DUbIhAeXSi40C:-K_4NgAEEzBl8Znc6w7r:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L90)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"When `true`, the column is frozen. When a column inside of a column group is frozen, all of the sibling columns inside the group will get frozen also."
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 162 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4AyOvXFLtBtXiG8_O:-K_4NmXmlxuneolEcLIm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L162)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Width of the cells for this column."
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 167 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4B3NCBMUXQGQwQXiT:-K_4NmyacCfzEZq2tTaf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L167)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Flex grow ratio for the cell widths. When set to `0`, cell width is fixed."
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 182 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4Bh89CXzRKY_IP6ZX:-K_4Nr_ZWoPNQgLyTCgR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L182)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"When set to `true`, the cells for this column are hidden.
</blockquote></details>

Done.

---

*[vaadin-grid-filter-behavior.html, line 46 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_463BcBBsDN0APiYlV:-K_4O69OodNq68in1_cN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-filter-behavior.html#L46)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Just realized `value` should have `notify: true` 
</blockquote></details>

Done.

---

*[vaadin-grid-filter-behavior.html, line 63 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_46AwKdD6I29_6BIdO:-K_4OB3XgrRANwlLtVLJ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-filter-behavior.html#L63)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This event has been meant more or less to be private, it's stopped from bubbling outside grid. If we add `notify: true`, users can listen to the notification event on the value.
</blockquote></details>

Done.

---

*[vaadin-grid-row-details-behavior.html, line 85 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_46fJvEsZZ2chxaK3S:-K_4OJtCpZcHiFWuGn2x:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-row-details-behavior.html#L85)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Expand the details row of ... "
</blockquote></details>

Done.

---

*[vaadin-grid-row-details-behavior.html, line 94 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_46jXKlq5OP5xJNyQC:-K_4OMBLwuExVBdpDSzk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-row-details-behavior.html#L94)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Collapse the details row of ... "
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 42 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4BzoyjrWnzPZaiV_U:-K_4OryTYTyMwKMYjhxA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-selection-column.html#L42)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

should be `flexGrow`
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 47 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4C38GUCuj3pJ7NtMy:-K_4Ou8paoxcEkPuRw22:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-selection-column.html#L47)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"`true` when all displayed items are selected."
</blockquote></details>

Done.

---

*[vaadin-grid-sort-behavior.html, line 130 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_470N8vucNmjxjUKfl:-K_4P-Nt_wAy7Q9Gde34:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-sort-behavior.html#L130)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This is also a private event same way as `filter-changed`
</blockquote></details>

Done.

---

*[vaadin-grid.html, line 172 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_47JvWPa2Wzr_te9Aj:-K_4PCDr1iB3sskgmc6w:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid.html#L172)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Fired when a non-focusable element inside a cell is clicked."
</blockquote></details>

Done.

---

*[vaadin-grid.html, line 174 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_47PY-VKvl4icQ3UV6:-K_4P9dVznkcYAf3gcLs:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid.html#L174)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I think this note can be removed, this event is targeted for public users for use cases that `activeItem` doesn't cover.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625)*

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_45DT2FEWNzJOXR2lp:-K_4UC1QGwbCXjNdpjvV:b-k1i7wl) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L12)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

> Replace with vaadin-grid

What have I to replace here?
</blockquote></details>

The [vaadinelement]#vaadin-grid# (this isn't asciidocs)

---

*[vaadin-grid-column.html, line 257 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UjpjDjeUsswsmTqE:-K_4UjpjDjeUsswsmTqF:b-eu7tsh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L257)):*
> ```HTML
>       },
> 
>       flexGrow: {
> ```

"Flex grow ratio for the column group as the sum of the ratios of its child columns." 

---

*[vaadin-grid-column.html, line 262 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4Wn6Vl8xN5who9aKQ:-K_4Wn6W5zP_EuB5n3kh:b5fn58v) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L262)):*
> ```HTML
>       },
> 
>       width: {
> ```

"Width of the column group as the sum of the widths of its child columns."

---

*[vaadin-grid-column.html, line 269 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4WuODARFx6SywfVP1:-K_4WuODARFx6SywfVP2:b-b1gcrm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L269)):*
> ```HTML
>       _visibleChildColumns: Array,
> 
>       hidden: {
> ```

"`true` when all of its child columns are hidden."

---

*[vaadin-grid-column.html, line 275 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UgKWZwFva7tf4XhJ:-K_4UgKWZwFva7tf4XhK:b-ph66yc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L275)):*
> ```HTML
>       },
> 
>       colSpan: {
> ```

`colSpan` can be removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-column.html, line 12 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_45DT2FEWNzJOXR2lp:-K_4mmElJz2gb_ak6ywk:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a5461a7503893c8cca34df42346c98b29d180446/vaadin-grid-column.html#L12)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

The [vaadinelement]#vaadin-grid# (this isn't asciidocs)
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 257 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UjpjDjeUsswsmTqE:-K_4n4mrk7WQi5oZRXHV:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L257)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Flex grow ratio for the column group as the sum of the ratios of its child columns." 
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 262 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4Wn6Vl8xN5who9aKQ:-K_4n5gXDu-8R6W15OUd:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L262)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"Width of the column group as the sum of the widths of its child columns."
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 269 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4WuODARFx6SywfVP1:-K_4nUUbYjGZTF2iRaP2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L269)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

"`true` when all of its child columns are hidden."
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 275 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UgKWZwFva7tf4XhJ:-K_4o3hyJAJDWDy6DEeG:bxn1c5i) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L275)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

`colSpan` can be removed.
</blockquote></details>

Do you mean from properties block, or all the implementation and usage in cells and tests?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625)*

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 257 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UjpjDjeUsswsmTqE:-K_4vfzec9OsfCAT0e9P:bgv99cl) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L257)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks like you just copied the descriptions from `vaadin-column` ? :-) they are supposed to be different for groups.

---

*[vaadin-grid-column.html, line 275 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UgKWZwFva7tf4XhJ:-K_4vRaJMGs4NErWBnle:b-nscf48) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L275)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Do you mean from properties block, or all the implementation and usage in cells and tests?
</blockquote></details>

oh right, my bad, we actually still use it :-)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 257 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UjpjDjeUsswsmTqE:-K_4zSQkFJTjr0TAnB4Q:b-kv4nnv) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L257)):*
> Flex grow ratio for the column group as the sum of the ratios of its child columns

Right I copied that. Done

---

*[vaadin-grid-column.html, line 275 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-K_4UgKWZwFva7tf4XhJ:-K_50C35-tPdUBO0agI9:b-422sdd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3f83d40518347489cc8b10171d64cd4544bdc25d/vaadin-grid-column.html#L275)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

oh right, my bad, we actually still use it :-)
</blockquote></details>

Documented

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 9 files at r3, 2 of 6 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/625#-:-K_9l89FDvSclg9zuY_w:bnfp4nl)*

**Pull request merged**
