### PR TITLE
4.0 iron list api warning

### PR DESCRIPTION
**Pull request by tomivirkki**
Connects to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/986)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-scroller.html, line 63 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusgFG-D8k4QOqxtAvx:-KusgFG0w0Od20ewW2VG:b-qnovyo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L63)):*
> ```HTML
>       * @private
>       */
>       scrollToIndex(index) {
> ```

Maybe off topic, but feels like this has to be in public API.

We have an issue about that: https://github.com/vaadin/vaadin-grid/issues/927

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-scroller.html, line 63 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusgFG-D8k4QOqxtAvx:-Kush2EYhXhC-EJHl6Tq:b-533d0j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L63)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe off topic, but feels like this has to be in public API.

We have an issue about that: https://github.com/vaadin/vaadin-grid/issues/927
</blockquote></details>

Totally agree on that. But was planning to postpone new features to future minor releases. 3 -> 4 was planned to be unchanged API-wise.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by platosha** [comment]
Review status: 0 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-scroller.html, line 63 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusgFG-D8k4QOqxtAvx:-KushkNLG8bfyyf0__JV:b-gxztsp) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L63)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Totally agree on that. But was planning to postpone new features to future minor releases. 3 -> 4 was planned to be unchanged API-wise.
</blockquote></details>

Fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by platosha** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-scroller.html, line 254 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusiVxTvQLUd8z5Vs8z:-KusiVxTvQLUd8z5Vs9-:b8it3y) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L254)):*
> ```HTML
>           this._debouncerWarnPrivateAPIAccess,
>             Polymer.Async.animationFrame,
>             () => Polymer.RenderStatus.afterNextRender(this, () => {
> ```

Looks odd. Debounce should already add one frame async delay, shouldn’t it? Why add another `afterNextRender` on top then?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by platosha** [comment]
Review status: 9 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-scroller.html, line 250 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusknVmvQvumq6yZvWH:-KusknVmvQvumq6yZvWI:b-l7vakb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L250)):*
> ```HTML
>       _accessIronListAPI(cb, asynchronous) {
>         this._warnPrivateAPIAccessAsyncEnabled = false;
>         const returnValue = cb.apply(this);
> ```

OK Since debouncers are async, sync return after enqueuing flag removal should work. In other words, memoizing `returnValue` is perhaps unnecessary:

```javascript
this._flag = true;
this._debouncer = Polymer.Debouncer.debounce(...);
return cb.apply(this);
```

sorry for nitpicking, not blocking on this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-scroller.html, line 254 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusiVxTvQLUd8z5Vs8z:-KusmUMfciDOxc6I_Axy:b-vi29um) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L254)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Looks odd. Debounce should already add one frame async delay, shouldn’t it? Why add another `afterNextRender` on top then?
</blockquote></details>

It's because iron-list uses similar timing for example in `https://github.com/vaadin/vaadin-grid/blob/4.0-iron-list-api-warning/iron-list.html#L1079`. The issue manifests in FF especially.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-scroller.html, line 250 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusknVmvQvumq6yZvWH:-KusqPq2TerTlVzT5Ex4:bu2ayyv) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L250)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK Since debouncers are async, sync return after enqueuing flag removal should work. In other words, memoizing `returnValue` is perhaps unnecessary:

```javascript
this._flag = true;
this._debouncer = Polymer.Debouncer.debounce(...);
return cb.apply(this);
```

sorry for nitpicking, not blocking on this.
</blockquote></details>

Ah, yes. Don't know how that slipped in. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986)*

**Comment by platosha** [comment]
:lgtm: despite of nitpicks

---

Reviewed 1 of 4 files at r2.
Review status: 7 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-scroller.html, line 254 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-KusiVxTvQLUd8z5Vs8z:-Kusu5bZiViwpYSEV_yj:b-dq9d91) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9eba94246e5b059a480f8f516afba839bd5b0fb1/vaadin-grid-scroller.html#L254)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's because iron-list uses similar timing for example in `https://github.com/vaadin/vaadin-grid/blob/4.0-iron-list-api-warning/iron-list.html#L1079`. The issue manifests in FF especially.
</blockquote></details>

This looks more explicit and less magical.

Explicitly allow API usage in `_debounceRender` callbacks:

```javascript
      _accessIronListAPI(cb) {
        this._warnPrivateAPIAccessAsyncEnabled = false;
        this._debouncerWarnPrivateAPIAccess = Polymer.Debouncer.debounce(
          this._debouncerWarnPrivateAPIAccess,
          Polymer.Async.animationFrame,
          () => this._warnPrivateAPIAccessAsyncEnabled = true
        );
        return cb.apply(this);
      }

      _debounceRender(cb, asyncModule) {
        super._debounceRender(() => this._accessIronListAPI(cb), asyncModule);
      }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-:-Kusz9FDeuPinpd-oBIM:b-mb6hsh)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 7 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/986#-:-Kut-Vjyid7OOjrUgdel:bg7igkv)*

**Pull request merged**
