### PR TITLE
Don’t access undefined _lastFocusedCell

### PR DESCRIPTION
**Pull request by tomivirkki**
Click body, click header, click body again -> sometimes you get an error. This PR fixes that.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/789)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-focusable-cell-container-behavior.html, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789#-KelwN6LfFOW-FBzVSAV:-KelwN6LfFOW-FBzVSAW:b7xn4n3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/98840f39fdba908e88f77a3604437798cb9030b3/vaadin-grid-focusable-cell-container-behavior.html#L53)):*
> ```HTML
>       // <vaadin-grid-sorter>.
>       if (this._lastFocusedCell) {
>         this._lastFocusedCell._cellContent.dispatchEvent(new CustomEvent('cell-focusout'));
> ```

Shouldn't this event be fired only in the cell is different to last cell ?

---

*[test/keyboard-navigation.html, line 1178 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789#-KelunpZ1NnGH_eIdBrw:-Kelunp_jmit2M4At9jr:b-hhp4lk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/98840f39fdba908e88f77a3604437798cb9030b3/test/keyboard-navigation.html#L1178)):*
> ```HTML
>           });
> 
>           it('should not throw on focus change', function() {
> ```

description is not meaningful to me. Maybe `should not throw any error when switching focus between body and header` ?
did this happened on footers as well ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-focusable-cell-container-behavior.html, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789#-KelwN6LfFOW-FBzVSAV:-Kem1TvkGpvhpdU8x81M:b-me68w1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/98840f39fdba908e88f77a3604437798cb9030b3/vaadin-grid-focusable-cell-container-behavior.html#L53)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Shouldn't this event be fired only in the cell is different to last cell ?
</blockquote></details>

I think the idea here is to fire `cell-focusout` when focused cell changes (when `cell` is different from `this._lastFocusedCell`) or when the cell container loses focus `focused` is `false`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789)*

**Comment by tomivirkki** [comment]
*[test/keyboard-navigation.html, line 1178 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789#-KelunpZ1NnGH_eIdBrw:-Kem6YLrN3OAl0XJQerE:b8le8v4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/98840f39fdba908e88f77a3604437798cb9030b3/test/keyboard-navigation.html#L1178)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

description is not meaningful to me. Maybe `should not throw any error when switching focus between body and header` ?
did this happened on footers as well ?
</blockquote></details>

Done. Probably happens with footer also since (besides the positioning) it's identical to header. No need to test footer because of the same reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-focusable-cell-container-behavior.html, line 53 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789#-KelwN6LfFOW-FBzVSAV:-Kem8cR10FO9B3TvdktA:bcetczj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/98840f39fdba908e88f77a3604437798cb9030b3/vaadin-grid-focusable-cell-container-behavior.html#L53)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I think the idea here is to fire `cell-focusout` when focused cell changes (when `cell` is different from `this._lastFocusedCell`) or when the cell container loses focus `focused` is `false`
</blockquote></details>

The thing is, what happens if the user focus a cell, then focus the header/footer, and finally focuses the same cell. Does this function be called? and it fires focusout? or it does not happen since cell has not changed ? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789)*

**Comment by Saulis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/789#-:-Keme9nQfUVDJ_Pwf4Li:bnfp4nl)*

**Pull request merged**
