### PR TITLE
Make grid aware of vaadin-grid-flow-selection-column

### PR DESCRIPTION
**Pull request by ahie**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1038)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Might be weird to have queries for `<vaadin-grid-flow-selection-column>` in the codebase while the component doesn't exist there. Would it be an option to instead query all elements and then filter them by super type `el instanceof Vaadin.GridColumnGroupElement || el instanceof Vaadin.GridColumnElement`?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwJWjv7LzCdJJ5a1PH3:bsvxvod)*

**Comment by manolo** [comment]
ups responded at the same time, @tomivirkki and me came with the same solution. Can you modify your PR to check the instance of all children,  for instance `queryDistributedElements('*').filter( e => e instanceof Vaadin.GridColumnElement || e instanceof Vaadin.GridColumnGroupElement)` 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwJhbVNuFz2X89nSjop:b-u3f07b)*

**Comment by ahie** [comment]
Done.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwJmMLAv4dqO_UNEv-D:b-896fix)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column-group.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwJoid5AtUy39OL-KKR:-KwJoid6JX2C_rfP-NiK:b-4mdrvh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3e1bb4b2db9e54f1dd92e7fbf09d25dae9bcfa44/vaadin-grid-column-group.html#L253)):*
> ```HTML
>           this._observer = Polymer.dom(this).observeNodes(info => {
>             const isColumnElement =
>               node => (node.nodeType === Node.ELEMENT_NODE && /^vaadin-grid-(column|selection|flow)/i.test(node.localName));
> ```

You need here the `instanceof` check instead of the tag name of the component

---

*[vaadin-grid-dynamic-columns-mixin.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwJoshAjA-q2DZr1Ufw:-KwJoshAjA-q2DZr1Ufx:b-8xcl5e) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3e1bb4b2db9e54f1dd92e7fbf09d25dae9bcfa44/vaadin-grid-dynamic-columns-mixin.html#L76)):*
> ```HTML
>       this._observer = new Polymer.FlattenedNodesObserver(this, info => {
>         var isColumnElement = node => {
>           return (node.nodeType === Node.ELEMENT_NODE && /^vaadin-grid-(column|selection|flow)/i.test(node.localName));
> ```

Use `instanceof` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038)*

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-column-group.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwJoid5AtUy39OL-KKR:-KwJr0N7UFQePkSpKUM4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3e1bb4b2db9e54f1dd92e7fbf09d25dae9bcfa44/vaadin-grid-column-group.html#L253)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

You need here the `instanceof` check instead of the tag name of the component
</blockquote></details>

Done.

---

*[vaadin-grid-dynamic-columns-mixin.html, line 76 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwJoshAjA-q2DZr1Ufw:-KwJr-nRZAZ-I4C1beBU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3e1bb4b2db9e54f1dd92e7fbf09d25dae9bcfa44/vaadin-grid-dynamic-columns-mixin.html#L76)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Use `instanceof` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038)*

**Comment by tomivirkki** [comment]
Newest revision has some test failures. Run the tests locally at `http://localhost:8080/components/vaadin-grid/test/`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwJv33OyLZOapa7EEBv:budrmr8)*

**Comment by manolo** [comment]
Note that in order to use `Vaadin.GridColumnGroupElement;` `vaadin-grid-column-group` need to be imported, so add it to the vaadin-grid block of imports

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column-group.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwJoid5AtUy39OL-KKR:-KwJyvN3pDiHx1FpNsE2:b-kdwwoz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3e1bb4b2db9e54f1dd92e7fbf09d25dae9bcfa44/vaadin-grid-column-group.html#L253)):*
<details><summary><i>Previously, ahie (Aleksi Hietanen) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are many places in the code repeating the pattern 
`node instanceof Vaadin.GridColumnElement || node instanceof Vaadin.GridColumnGroupElement`

I would create a private method in `vaadin-grid-dynamic-columns`  

```
_isColumnElement(node) {
    return node instanceof Vaadin.GridColumnElement || node instanceof Vaadin.GridColumnGroupElement;
}
```

and call it everywhere else.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwK-3667hNfK3g39yFN:bsgvdvf)*

**Comment by ahie** [comment]
Ran tests locally and got 3 failures. Tried reverting to the first revision there were no test failures. I really don't know the root cause, but I would guess the `instanceof` check doesn't quite match the correct elements. Any ideas?

Test failures were:
- expected false to be true flush at column-groups.html:428
- expected false to be true flush at column-groups.html:440
- expected false to deeply equal undefined Context.it at column.html:118

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column-group.html, line 253 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwJoid5AtUy39OL-KKR:-KwKn492Xs5tfCnz4L9U:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3e1bb4b2db9e54f1dd92e7fbf09d25dae9bcfa44/vaadin-grid-column-group.html#L253)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

There are many places in the code repeating the pattern 
`node instanceof Vaadin.GridColumnElement || node instanceof Vaadin.GridColumnGroupElement`

I would create a private method in `vaadin-grid-dynamic-columns`  

```
_isColumnElement(node) {
    return node instanceof Vaadin.GridColumnElement || node instanceof Vaadin.GridColumnGroupElement;
}
```

and call it everywhere else.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwZ5o_-tHSWV1JmoCgv:b-yrkjs0)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 25 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwZhyMS4zZ9kswDeNUf:-KwZhyMS4zZ9kswDeNUg:b-w584o2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/7e05ed9c6b05f4bd69c76ad883bf3dd135359868/vaadin-grid.html#L25)):*
> ```HTML
> <link rel="import" href="vaadin-grid-column-resizing-mixin.html">
> <link rel="import" href="vaadin-grid-column.html">
> <link rel="import" href="vaadin-grid-column-group.html">
> ```

Remove this addition. Column group is an optional helper element so the import is optional as well. See the first demo notes at https://vaadin.com/elements/vaadin-grid/html-examples/grid-columns-demos

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038)*

**Comment by tomivirkki** [comment]
It's failing because the elements haven't been upgraded yet. Change `_isColumnNode` to check that `node.localName` matches `vaadin-grid.*column.*` instead

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwZlP2mu39cJDWZzMos:b-itgrgf)*

**Comment by ahie** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid.html, line 25 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-KwZhyMS4zZ9kswDeNUf:-KwZuwndnaAVuP9Xz7ol:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/7e05ed9c6b05f4bd69c76ad883bf3dd135359868/vaadin-grid.html#L25)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Remove this addition. Column group is an optional helper element so the import is optional as well. See the first demo notes at https://vaadin.com/elements/vaadin-grid/html-examples/grid-columns-demos
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038)*

**Comment by tomivirkki** [comment]
:lgtm: 

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1038#-:-KwZvpjV1osfg-YLAeiC:bg7igkv)*

**Pull request merged**
