### PR TITLE
Rename vaadin-grid-hierarchy-toggle to vaadin-grid-tree-toggle.

### LINKED ISSUE #1102: Rename hierarchy toggle to <vaadin-grid-tree-toggle>
Also rename `icon-hidden` to `leaf`

See that the docs are up-to-date (change mentions of hierarchy to tree data structure)

### PR DESCRIPTION
**Pull request by vicsstar**
Fixes #1102

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1108)

### CODE REVIEW

**Comment by platosha** [comment]
As discussed, should also rename `icon-hidden` → `leaf`

---

Reviewed 18 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-tree-toggle.html, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz-7cBHte5ri2nAXm1t:-Kz-7cBHte5ri2nAXm1u:biicjnj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/1ba0ebc3973971bb3d55ddc7d36c59b545dbd0dd/vaadin-grid-tree-toggle.html#L14)):*
> ```HTML
>   @font-face {
>     font-family: "vaadin-grid-tree-icons";
>     src: url(data:application/font-woff;charset=utf-8;base64,d09GRgABAAAAAAQkAA0AAAAABrwAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABGRlRNAAAECAAAABoAAAAcgHwa6EdERUYAAAPsAAAAHAAAAB4AJwAOT1MvMgAAAZQAAAA/AAAAYA8TBIJjbWFwAAAB8AAAAFUAAAFeGJvXWmdhc3AAAAPkAAAACAAAAAgAAAAQZ2x5ZgAAAlwAAABLAAAAhIrPOhFoZWFkAAABMAAAACsAAAA2DsJI02hoZWEAAAFcAAAAHQAAACQHAgPHaG10eAAAAdQAAAAZAAAAHAxVAgBsb2NhAAACSAAAABIAAAASAIAAVG1heHAAAAF8AAAAGAAAACAACgAFbmFtZQAAAqgAAAECAAACTwflzbdwb3N0AAADrAAAADYAAABZQ7Ajh3icY2BkYGAA4twv3Vfi+W2+MnCzMIDANSOmbGSa2YEZRHEwMIEoAAoiB6sAeJxjYGRgYD7w/wADAwsDCDA7MDAyoAI2AFEEAtIAAAB4nGNgZGBg4GBgZgDRDAxMDGgAAAGbABB4nGNgZp7JOIGBlYGBaSbTGQYGhn4IzfiawZiRkwEVMAqgCTA4MDA+38d84P8BBgdmIAapQZJVYGAEAGc/C54AeJxjYYAAxlAIzQTELAwMBxgZGB0ACy0BYwAAAHicY2BgYGaAYBkGRgYQiADyGMF8FgYbIM3FwMHABISMDArP9/3/+/8/WJXC8z0Q9v8nEp5gHVwMMMAIMo+RDYiZoQJMQIKJARUA7WBhGN4AACFKDtoAAAAAAAAAAAgACAAQABgAJgA0AEIAAHichYvBEYBADAKBVHBjBT4swl9KS2k05o0XHd/yW1hAfBFwCv9sIlJu3nZaNS3PXAaXXHI8Lge7DlzF7C1RgXc7xkK6+gvcD2URmQB4nK2RQWoCMRiFX3RUqtCli65yADModOMBLLgQSqHddRFnQghIAnEUvEA3vUUP0LP0Fj1G+yb8R5iEhO9/ef/7FwFwj28o9EthiVp4hBlehcfUP4Ur8o/wBAv8CU+xVFvhOR7UB7tUdUdlVRJ6HnHWTnhM/V24In8JT5j/KzzFSi2E53hUz7jCcrcIiDDwyKSW1JEct2HdIPH1DFytbUM0PofWdNk5E5oUqb/Q6HHBiVGZpfOXkyUMEj5IyBuNmYZQjBobfsuassvnkKLe1OuBBj0VQ8cRni2xjLWsHaM0jrjx3peYA0/vrdmUYqe9iy7bzrX6eNP7Jh1SijX+AaUVbB8AAHicY2BiwA84GBgYmRiYGJkZmBlZGFkZ2djScyoLMgzZS/MyDQwMwLSruZMzlHaB0q4A76kLlwAAAAEAAf//AA94nGNgZGBg4AFiMSBmYmAEQnYgZgHzGAAD6wA2eJxjYGBgZACCKxJigiD6mhFTNowGACmcA/8AAA==) format('woff');
> ```

FYI: this changes the resource name metadata contained in the font file.

(Noticable when you inspect for “Renderend Fonts”)



Not a blocker, I made the change already.

---

*[demo/demos.json, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz-8FAW6JsUtQkzJjpk:-Kz-8FAW6JsUtQkzJjpl:b9gyurn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d070bdbd017214701b6cf85ccbae5481582ad540/demo/demos.json#L93)):*
> ```JSON
>   ,
>   {
>     "name": "Tree",
> ```

BTW maybe have “Tree Grid” in the title? Not a blocker though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz-4YF3d4UWV-65YMqz:b-1y5pvq)*

**Comment by vicsstar** [comment]
*[vaadin-grid-tree-toggle.html, line 14 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz-7cBHte5ri2nAXm1t:-Kz-D-jpbmW8x6E5a9cP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/1ba0ebc3973971bb3d55ddc7d36c59b545dbd0dd/vaadin-grid-tree-toggle.html#L14)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

FYI: this changes the resource name metadata contained in the font file.

(Noticable when you inspect for “Renderend Fonts”)



Not a blocker, I made the change already.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108)*

**Comment by vicsstar** [comment]
*[demo/demos.json, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz-8FAW6JsUtQkzJjpk:-Kz-D3wGTz9LImmLE7Ir:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d070bdbd017214701b6cf85ccbae5481582ad540/demo/demos.json#L93)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW maybe have “Tree Grid” in the title? Not a blocker though.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108)*

**Comment by platosha** [comment]
Wow, I thought we decided to use just `leaf`. Normally we don’t have `is` prefixes to boolean properties.

---

Review status: 9 of 15 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/demos.json, line 97 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz32WFPOKGKSLxDrzRB:-Kz32WFPOKGKSLxDrzRC:bvq5pxb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/238d601a9d84862ea6c669f366f2b96732da8f2f/demo/demos.json#L97)):*
> ```JSON
>     "src": "grid-tree-demos.html",
>     "meta": {
>       "title": "vaadin-grid – Tree",
> ```

This should maybe say `Tree Grid` too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz320LVd_F3J11mandd:bi4obbk)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-tree-toggle.html, line 149 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz3FfuKF3dI3ac9Na6M:-Kz3FfuKF3dI3ac9Na6N:b-x198qy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/238d601a9d84862ea6c669f366f2b96732da8f2f/vaadin-grid-tree-toggle.html#L149)):*
> ```HTML
>            * Hides the toggle icon and disables toggling a tree sublevel.
>            */
>           isLeaf: {
> ```

As @platosha mentioned, just `leaf`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108)*

**Comment by vicsstar** [comment]
Acknowledged. Must have thought I saw the latter in the suggestion.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz3_RAc9arTYzLL1nyU:b-jy3yli)*

**Comment by vicsstar** [comment]
*[demo/demos.json, line 97 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz32WFPOKGKSLxDrzRB:-Kz3bspmk8S_Vc9zW5J1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/238d601a9d84862ea6c669f366f2b96732da8f2f/demo/demos.json#L97)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

This should maybe say `Tree Grid` too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108)*

**Comment by vicsstar** [comment]
*[vaadin-grid-tree-toggle.html, line 149 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-Kz3FfuKF3dI3ac9Na6M:-Kz3bxQD5whCKvH0e18U:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/238d601a9d84862ea6c669f366f2b96732da8f2f/vaadin-grid-tree-toggle.html#L149)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

As @platosha mentioned, just `leaf`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108)*

**Comment by platosha** [comment]
Please update `analysis.json` again. The current one still have traces of `isLeaf`...

---

Reviewed 3 of 18 files at r1, 1 of 6 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz3gj9xxJjeH18IqDHM:b3je9b5)*

**Comment by vicsstar** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz3hbcCLm1HRygb-UkC:b-896fix)*

**Comment by tomivirkki** [comment]
It still has `isLeaf` mentions in analysis.json

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz3vx9IubdeRssi96Ei:b-yaj2pw)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz49f6hfcSG37Fvrb30:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 12 of 18 files at r1, 5 of 5 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1108#-:-Kz4ABs5WeIdT2_n8na2:bnfp4nl)*

**Pull request merged**
