### PR TITLE
Make column groups hidable

### LINKED ISSUE #743: Make vaadin-grid-column-group hidable
- Make `hidden` writable in `<vaadin-grid-column-group>`

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #743

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/764)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764#-KeJMapxDP1HPKNsV_Sc:-KeJMapxDP1HPKNsV_Sd:bd0gvza) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0f6afddd9728e01202869540500acea07862f5c4/vaadin-grid-column.html#L84)):*
> ```HTML
>        * When set to true, the cells for this column are hidden.
>        */
>       hidden: Boolean,
> ```

this needs `notify: true` since it can be modified internally

---

*[test/column-group.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764#-KeJNdLXCGbpncmNgZp4:-KeJNdLXCGbpncmNgZp5:b-yuwr9z) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0f6afddd9728e01202869540500acea07862f5c4/test/column-group.html#L145)):*
> ```HTML
>       });
> 
>       it('should unhide group column', function() {
> ```

Should also test that the second column stays hidden when group is made visible by the first column.

`expect(columns[1].hidden).to.be.true`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764)*

**Comment by tomivirkki** [comment]
Review status: 0 of 6 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-column.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764#-KeJMapxDP1HPKNsV_Sc:-KeJSErIS4vwOVpt5EU5:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0f6afddd9728e01202869540500acea07862f5c4/vaadin-grid-column.html#L84)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

this needs `notify: true` since it can be modified internally
</blockquote></details>

Done.

---

*[test/column-group.html, line 145 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764#-KeJNdLXCGbpncmNgZp4:-KeJSGsKSKgScD-huZiF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0f6afddd9728e01202869540500acea07862f5c4/test/column-group.html#L145)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Should also test that the second column stays hidden when group is made visible by the first column.

`expect(columns[1].hidden).to.be.true`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764)*

**Comment by Saulis** [comment]
:lgtm: merge after build passes

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764#-:-KeXhkcCmdiB1WHS0dBL:b-i5fmus)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764#-:-KeXzvxwmsjW8x5C034t:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/764)*

**Pull request merged**
