### PR TITLE
Replace cellContent focus workaround with mouseup focus workaround

### LINKED ISSUE #1029: Regression: text selection with mouse does not work

### PR DESCRIPTION
**Pull request by platosha**
Fixes #1029

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1030)

### CODE REVIEW

**Comment by tomivirkki** [comment]
This approach doesn't seem to work with selecting text within a single cell.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1030#-:-KvgV8QpqkGH9W7g0XQQ:b28o782)*

**Comment by platosha** [comment]
@tomivirkki fixed.

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1030#-:-KvgqXElhMI8mzI65rXG:b-ez8ixu)*

**Comment by tomivirkki** [comment]
Works on Chrome and Firefox but Safari still has the same issue

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1030#-:-KvkTdViJVl4VwGnpzDR:bwiq3yt)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1030#-:-KvlYLzg0YWi8-cOxj9q:bnfp4nl)*

**Pull request merged**
