### PR TITLE
Fixed issues with native shadow

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/486)

### CODE REVIEW

**Comment by Saulis** [comment]
What kind of issues exactly we're talking about here? :octocat: 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KTnpK-zWAtkSor6Bmu7:bsom1h7)*

**Comment by tomivirkki** [comment]
At least on my environment grid 2 on native shadow has been broken for a while now. After these changes it works.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KTnqduTrlbU_yTqxxgG:b-4tvh4k)*

**Comment by Saulis** [comment]
Broken how? I can't find anything wrong (expect some paper-input styles) when running `demo/index.html` on `2.0-dev` using native shadow..? Tried on Polymer 1.6.1 and 1.7.0, Chrome 52 and 53.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KToqT-9zEIl0TLkH7WC:b-jtvmbd)*

**Comment by Saulis** [comment]
Don't tell me you're running Safari 10 :-)

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KTos9CEIdbcSm6D877X:biqshy5)*

**Comment by tomivirkki** [comment]
Ok, the issue doesn't reproduce in demo/index.html but in demo/demo.html (Chrome)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KTrw_fY2Mn48fQwZmJ1:b5i0udp)*

**Comment by manolo** [comment]
Verified, and happens in my environment.
Why this was not detected in Travis, don't we run shadow tests ?
Could you add a test? 

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KTuTvdEXRZzY48wcnUb:bwbc5c3)*

**Comment by tomivirkki** [comment]
Unfortunately this doesn't reproduce in test environment so can't write a unit test for this

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KTwiNb1vDdeYZuSBaGG:bxspsim)*

**Comment by Saulis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-data-source-behavior.html, line 237 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-KTy54dBLOiCuatjB8uq:-KTy54dBLOiCuatjB8ur:b-sqekry) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c341f82b8893c79231d9b14e1865308fbf429517/vaadin-grid-data-source-behavior.html#L237)):*
> ```HTML
>       this._cache = {};
>       this._pendingRequests = {};
>       this.$.scroller._update();
> ```

We could consider having a separate observer/listener for `pageSize` which calls `clearCache()` only when the size actually changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-data-source-behavior.html, line 237 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-KTy54dBLOiCuatjB8uq:-KTyIp_ieabBXWXFH8mX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c341f82b8893c79231d9b14e1865308fbf429517/vaadin-grid-data-source-behavior.html#L237)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> We could consider having a separate observer/listener for `pageSize` which calls `clearCache()` only when the size actually changes.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KU0jUAScNQe2A-FAGAr:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/486#-:-KU1h_SonzjiEjNskL9Q:bnfp4nl)*

**Pull request merged**
