### PR TITLE
common.html: load everything dynamically, and avoid xhr patching twice

### PR DESCRIPTION
**Pull request by manolo**
connects to vaadin/components-team-tasks#6

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/196)

### CODE REVIEW

**Comment by tomivirkki** [comment]
This change has as strange side effect: Polyserve the vaadin-grid folder -> open http://localhost:8080/components/vaadin-grid/demo/ -> select one of the demos -> the page goes blank


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196)

**Comment by tomivirkki** [comment]
<sup>**[demo/xhrpatch.js, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196#-K01CfaC3hzDdiOA50Xz)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/d89b13a7114ab0738a4904063d246fddf7e550f8/demo/xhrpatch.js#L16)):</sup>
Why have the patch and not use the local users.json file?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196)

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[demo/xhrpatch.js, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196#-K01CfaC3hzDdiOA50Xz)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/d89b13a7114ab0738a4904063d246fddf7e550f8/demo/xhrpatch.js#L16)):</sup>
Don't follow, could you elaborate the question?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196)

**Comment by tomivirkki** [comment]
<sup>**[demo/xhrpatch.js, line 16 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196#-K01CfaC3hzDdiOA50Xz)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/d89b13a7114ab0738a4904063d246fddf7e550f8/demo/xhrpatch.js#L16)):</sup>
Sorry my bad, didn't notice you moved users.json linking to common.html


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196)

**Comment by tomivirkki** [comment]
This problem is much more obvious on Firefox for example. Reproduces every time. On Chrome it works randomly.


---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196)

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/196)

**Pull request merged**
