### PR TITLE
Rename rows to visibleRows, remove visibleColumns

### LINKED ISSUE #222: Rename "rows" to "visible-rows"
In order to avoid confusion between “items” and “rows” in the grid, the `rows` attribute should be renamed to `visible-rows` and the property to `visibleRows`.

To avoid confusion between `visibleRows` and `visibleColumns` (other returning a number and other returning an array), the `visibleColumns` property should be removed.

### PR DESCRIPTION
**Pull request by tehapo**
Connects to #222
Fixes #222

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/231)

### CODE REVIEW

**Comment by jounik** [comment]
The old "rows" property could be kept along until 1.1 as deprecated and log
a warning message to the console.

Also, there needs to be clear release notes about this change. You can
draft a new release in GitHub for it and see the 0.9.0-beta3 as an example
how to do it.
ma 2. marraskuuta 2015 klo 16.51 Teemu Pöntelin <notifications@github.com>
kirjoitti:

**Comment by Saulis** [comment]
What he said ^^ Otherwise looks :+1 to me


---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/231)

**Comment by tehapo** [comment]
A drafted release: https://github.com/vaadin/vaadin-grid/releases/tag/untagged-07686125baa1d8e555df

**Comment by jounik** [comment]
Made some minor additions to the draft release notes, looks good!

**Comment by tehapo** [comment]
Updated the pull request with actual removal instead of deprecation (as was discussed yesterday). Also updated the [drafted release](https://github.com/vaadin/vaadin-grid/releases) notes.

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/231)

**Pull request merged**
