### PR TITLE
Revert examples to es5

### PR DESCRIPTION
**Pull request by tomivirkki**
Also replaced Paper elements with Vaadin elements in the demos

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1062)

### CODE REVIEW

**Comment by manolo** [comment]
Still not working in IE11 with server or polyserver, I guess it could be because demo helper ? 

---

Review status: 0 of 10 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1062#-:-Kxfyy9487vUgwHqWAS9:b-9l9evg)*

**Comment by tomivirkki** [comment]
Works for me. Have you installed the latest dependencies (demo helper was updated)?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1062#-:-Kxg0puynxANvYHIHh9n:b-ps9jff)*

**Comment by manolo** [comment]
Yes, after clearing my bower folder it works with polyserver. Still not working with server or cdn since we are not transpiling.  :lgtm: 

---

Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1062#-:-KxgKKb_G_QrV8aeCMb-:b-m1j1fh)*

**Comment by YuriyVaadin** [comment]
Checked on real device, it works with polyserver. :lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1062#-:-KxgOrACgTORtKFzvi-B:b-f4p5p)*

**Pull request merged**
