### PR TITLE
Add hidden property to columns and column groups

### LINKED ISSUE #502: Add hidden property to column
- Proposal: Set `display: none` to `<vaadin-grid-table-cell>` when `column.hidden` is set to `true`

### PR DESCRIPTION
**Pull request by samiheikki**
Fixes #502

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/511)

### CODE REVIEW

**Comment by Saulis** [comment]
Nicely done! :lgtm_strong: 

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-:-KVYuZr6eaRFV7LpgNrB:b9wpkzk)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[vaadin-grid-column.html, line 176 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwIPmidekB7eqvmsz:-KVYwIPmidekB7eqvmt-:b-h6eqos) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L176)):*
> ```HTML
>           this.fire('property-changed', {path: 'hidden', value: this._childColumns.filter(function(col) { return !col.hidden; }).length === 0});
>         }
> ```

I think we could maintain a _visibleColumns property which is computed once (when this.hidden changes or the hidden event comes from a child) instead of executing and maintaining maintaining two filters.

---

*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVYwqGr7nXCOA_nW-Ac:bl0j81k) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
> ```HTML
>       _hiddenChanged: function(childColumns, hidden) {
>         childColumns.forEach(function(col) {
>           col.hidden = hidden;
> ```

That is not necessary true. What happens if a column of three is hidden. then the user hides the group. When the user unhides the group we should still see two columns instead of three

---

*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVYumvANaAhVWQHkwft:bmj0ed0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
> ```HTML
> 
>       _hiddenChanged: function(hidden) {
>         this.style.display = hidden ? 'none' : '';
> ```

I would use a property reflected to an attribute, and do this by css.  So as the we or the user could customise this with animations, opacities or whatever. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZ2bSg8NCo_z4LBgJE:b1ziqci) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would use a property reflected to an attribute, and do this by css.  So as the we or the user could customise this with animations, opacities or whatever. 
</details>
No need to add css, I think. If you reflect the hidden property to an attribute, it should hide the cell without additional css.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
Hiding a column inside a column group should affect the "group cell's" colspan

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-:-KVZ2xXFw8USgZg1-DJF:blt2ikf)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZ26ASyjXPP19tWUzQ:b-pk829y) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> That is not necessary true. What happens if a column of three is hidden. then the user hides the group. When the user unhides the group we should still see two columns instead of three
</details>
I disagree, if user unhides the group, I'd say they want then also to see the whole group. Otherwise they would unhide only the two columns.

---

*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZ2dNtHMMxJGiQMHsr:b-93ndeg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I would use a property reflected to an attribute, and do this by css.  So as the we or the user could customise this with animations, opacities or whatever. 
</details>
Sounds like a good idea to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 176 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwIPmidekB7eqvmsz:-KVZ4QVJRCw9A8Wgd2QH:bjnxwk6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L176)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> I think we could maintain a _visibleColumns property which is computed once (when this.hidden changes or the hidden event comes from a child) instead of executing and maintaining maintaining two filters.
</details>
@samiheikki we could refine this idea maybe to expose a property for visible childs from a group, listen for that in the header cell and calculate both the `hidden` and `colSpan` values there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by samiheikki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 176 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwIPmidekB7eqvmsz:-KVZ4luAiOnKlfOPMgDr:b-orumjy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L176)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> @samiheikki we could refine this idea maybe to expose a property for visible childs from a group, listen for that in the header cell and calculate both the `hidden` and `colSpan` values there.
</details>
Good point

---

*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZ4KOhN56ovhYQNisT:bo9ghce) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Sounds like a good idea to me.
</details>
I'm now going to add `reflectToAttribute` to `hidden` property, remove this `_hiddenChanged` and add `[hidden]: display :none` to vaadin-grid-table.html css. I got that right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZ5LspMRbWJDUmWFh_:bypbbae) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> I'm now going to add `reflectToAttribute` to `hidden` property, remove this `_hiddenChanged` and add `[hidden]: display :none` to vaadin-grid-table.html css. I got that right?
</details>
"[hidden]: display :none" Shouldn't be needed. A built-in browser feature

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZ7PB_Lqn28pMrBlEN:b-nwea9d) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> I disagree, if user unhides the group, I'd say they want then also to see the whole group. Otherwise they would unhide only the two columns.
</details>
I'd also not make this assumption but leave it as the developer's decision. You might still want to keep some children hidden while unhiding a parent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZ9PyU3y6CCGOjjKrS:bqxb7sz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> I'd also not make this assumption but leave it as the developer's decision. You might still want to keep some children hidden while unhiding a parent.
</details>
Yep that is the point

---

*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZ9xCkGegdCQRQfZVF:b-m4nw47) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> "[hidden]: display :none" Shouldn't be needed. A built-in browser feature
</details>
good point, hidden attribute is well supported browsers and also very common to use in polymer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-table.html, line 258 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZCIBNH3Fj6lbvWJA0:-KVZCIBNH3Fj6lbvWJA1:b-ra3f9l) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table.html#L258)):*
> ```HTML
> 
>       if ('hidden' === e.detail.path) {
>         this.notifyResize();
> ```

Pls add a test for this

---

*[docs/vaadin-grid-configuring-columns.adoc, line 135 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZ9vEatKEqX1sVQBQ0:-KVZ9vEatKEqX1sVQBQ1:b-1d4lqo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/docs/vaadin-grid-configuring-columns.adoc#L135)):*
> ```AsciiDoc
> 
> When a column is hidden, it is not visible in the table.
> Hiding is done by applying [propertyname]#hidden# to the column.
> ```

'column' could be changed to [vaadinelement]#vaadin-grid-column# here

---

*[docs/vaadin-grid-configuring-columns.adoc, line 144 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZ9Mxhv_4VlCGYC2Cs:-KVZ9MxiZkAlUu9SLNFD:bo5kcbu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/docs/vaadin-grid-configuring-columns.adoc#L144)):*
> ```AsciiDoc
> ----
> 
> [propertyname]#hidden# can also be applied to a [vaadinelement]#vaadin-grid-column-group# which
> ```

This sentence starts with a lower case letter (property name).

Doesn't the word 'which' refer to the group here (not the hidden property)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZDhVt4i9OLmdycKsl:bmbaznm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> good point, hidden attribute is well supported browsers and also very common to use in polymer
</details>
https://developer.mozilla.org/en/docs/Web/HTML/Global_attributes/hidden the default behaviour is overridden because we use `display: flex` in cells. Need to add the style explicitly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZEvzmnzxuMLEfDNgX:bhejhpa) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary>
> Yep that is the point
</details>
Well it's gonna be an assumption of the desired behaviour in any way we choose. I would like to use the current behaviour since the implementation is simpler: we use `column.hidden` determine if a cell should be hidden or not. And when a parent group is set to `hidden: true`, it will also set the child columns `hidden: true`.

Now if we wanted to restore the original states of the `hidden` properties for the child columns when the group is set to `hidden: false`, we would need to store the original states -> adds complexity.

For me, I feel it should work similar to a "select all" checkbox, when you "deselect all", it doesn't restore your original selection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZJW3gvOhQBhNJadTO:b-5ajlpk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Well it's gonna be an assumption of the desired behaviour in any way we choose. I would like to use the current behaviour since the implementation is simpler: we use `column.hidden` determine if a cell should be hidden or not. And when a parent group is set to `hidden: true`, it will also set the child columns `hidden: true`.
> 
> Now if we wanted to restore the original states of the `hidden` properties for the child columns when the group is set to `hidden: false`, we would need to store the original states -> adds complexity.
> 
> For me, I feel it should work similar to a "select all" checkbox, when you "deselect all", it doesn't restore your original selection.
</details>
If you think it from a point of view of HTML elements (which they actually are), changing a parent element's `hidden` attribute doesn't affect its child elements' `hidden` attributes. That's why I see the current behaviour as unexpected.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZNMIsPOiX3dcdyWHK:baeh9gk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> If you think it from a point of view of HTML elements (which they actually are), changing a parent element's `hidden` attribute doesn't affect its child elements' `hidden` attributes. That's why I see the current behaviour as unexpected.
</details>
I'd also be ok leaving out the hidden property from column groups altogether for now (it's not in the proposed spec either) if the implementation gets too messy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by Saulis** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZNYIh_xkcVdXMoN-E:b8uzfj5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> I'd also be ok leaving out the hidden property from column groups altogether for now (it's not in the proposed spec either) if the implementation gets too messy.
</details>
Yeah I get your point – and dropping out the group hiding is a good idea. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by samiheikki** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-column.html, line 176 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwIPmidekB7eqvmsz:-KVZt9p_grG9fJgAIOuz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L176)):*
<details><summary><i>Previously, samiheikki (Sami Suo-Heikki) wrote…</i></summary>
> Good point
</details>
Done.

---

*[vaadin-grid-column.html, line 211 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYwqGq3Ez_tIYhEZlI:-KVZt8ZrPUZ_5nmm3Udg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-column.html#L211)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Yeah I get your point – and dropping out the group hiding is a good idea. 
</details>
Done.

---

*[vaadin-grid-table-cell.html, line 120 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVYumvANaAhVWQHkwfs:-KVZt0KP_4DCBzmgvRoy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table-cell.html#L120)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> https://developer.mozilla.org/en/docs/Web/HTML/Global_attributes/hidden the default behaviour is overridden because we use `display: flex` in cells. Need to add the style explicitly.
</details>
Done.

---

*[vaadin-grid-table.html, line 258 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZCIBNH3Fj6lbvWJA0:-KVZsxm64pcQHz8lUOoX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/vaadin-grid-table.html#L258)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Pls add a test for this
</details>
Done.

---

*[docs/vaadin-grid-configuring-columns.adoc, line 135 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZ9vEatKEqX1sVQBQ0:-KVZHFnVN5eiYQ0D6HCo:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/docs/vaadin-grid-configuring-columns.adoc#L135)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> 'column' could be changed to [vaadinelement]#vaadin-grid-column# here
</details>
Done.

---

*[docs/vaadin-grid-configuring-columns.adoc, line 144 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZ9Mxhv_4VlCGYC2Cs:-KVZHcR5Hr8MI002Ezxz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/bc1fe869f4281b6856306c7cc4c45f664ba7ede8/docs/vaadin-grid-configuring-columns.adoc#L144)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> This sentence starts with a lower case letter (property name).
> 
> Doesn't the word 'which' refer to the group here (not the hidden property)?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 192 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZv_rsCvFsTIpBkrqf:-KVZv_rsCvFsTIpBkrqg:bpjngsx) ([raw file](https://github.com/vaadin/vaadin-grid/blob/50e5259fe316603ce05303a204fa54c34190e27b/vaadin-grid-column.html#L192)):*
> ```HTML
> 
>         if (e.detail.path === 'lastFrozen') {
>           console.log('lastFrozen');
> ```

Oh noes, those darn `console.log` just keep popping up for some reason :popcorn: 

---

*[vaadin-grid-table.html, line 257 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZvoYfPMcL2G9uGWeq:-KVZvoYfPMcL2G9uGWer:bl9bvog) ([raw file](https://github.com/vaadin/vaadin-grid/blob/50e5259fe316603ce05303a204fa54c34190e27b/vaadin-grid-table.html#L257)):*
> ```HTML
>           col._lastFrozen = false;
>           return col.frozen && !col.hidden ? index : prev;
>         }, undefined);
> ```

As a comment, we found a bug here which set `lastFrozen` to `0` even if there wasn't any frozen columns at all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by samiheikki** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-grid-column.html, line 192 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-KVZv_rsCvFsTIpBkrqf:-KV_BHSpb8XSB097VqA7:bi55a7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/50e5259fe316603ce05303a204fa54c34190e27b/vaadin-grid-column.html#L192)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Oh noes, those darn `console.log` just keep popping up for some reason :popcorn: 
</details>
:1234: done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by Saulis** [comment]
:lgtm: again!

---

Reviewed 6 of 9 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-:-KV_MLJTlR7rIS4O5jls:butqos0)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511#-:-KV_Q2QV9_6jY5qfSJHk:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 6 of 9 files at r2, 1 of 1 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/511)*

**Pull request merged**
