### PR TITLE
PD-618 fix "grid not defined" error

### PR DESCRIPTION
**Pull request by n1ywb**
https://github.com/vaadin/vaadin-grid/issues/1139

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1140)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Good catch. Please sign the CLA so we can accept this PR.

**Comment by jouni** [comment]
Ping @n1ywb, please sign the CLA.

**Comment by vicsstar** [comment]
@n1ywb could you please sign the CLA?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1140#-:-L2eI9Q8OgGhqk6txppC:b-wb3gcj)*

**Comment by vicsstar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1140)*

**Comment by vicsstar** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1140#-:-L2eQ7E7fhTQWTL3Y_yN:bnfp4nl)*

**Comment by tomivirkki** [comment]
LGTM

**Pull request merged**
