### PR TITLE
Fixed order of events on column sort (fixes #206)

### LINKED ISSUE #206: Fire sort event before clearing the selection
Change the order of events on sort so that the event is fired _before_ clearing the selection. The issue is discussed [here](https://vaadin.com/forum#!/thread/11192400)

### PR DESCRIPTION
**Pull request by tomivirkki**
[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/214)

### CODE REVIEW

**Comment by Saulis** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[java/src/main/java/com/vaadin/components/grid/GridComponent.java, line 520 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214#-K131bY7eSLQ_ASHUiA-)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/bb2f0b490654303ebec65274b20809e93accccd7/java/src/main/java/com/vaadin/components/grid/GridComponent.java#L520)):</sup>
I deferred a must? :-)


---

<sup>**[test/grid-sorting-rows.html, line 93 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214#-K1317PsVkrfs0DJiqOb)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/bb2f0b490654303ebec65274b20809e93accccd7/test/grid-sorting-rows.html#L93)):</sup>
This test should either return a promise or use `done()` - as it is it exits before running the expectation?

I would also use a spy instead of the listener - I can provide an example of that.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214)

**Comment by Saulis** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214)

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

<sup>**[test/grid-sorting-rows.html, line 93 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214#-K1317PsVkrfs0DJiqOb)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/bb2f0b490654303ebec65274b20809e93accccd7/test/grid-sorting-rows.html#L93)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214)

**Comment by Saulis** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/214)

**Pull request merged**
