### PR TITLE
2.0 moar examples

### PR DESCRIPTION
**Pull request by Saulis**
Connects to #587 

https://polygit.org/vaadin-grid+vaadin+:2.0-moar-examples/elements-demo-resources+vaadin+:master/polymer+polymer+v1.7.0/components/vaadin-grid/demo/index.html

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/721)

### CODE REVIEW

**Comment by manolo** [comment]
Shouldnt this be connected to #587 ?

**Comment by manolo** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[demo/crud.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIGcspZUbWVQVS-yOH:-KdIGcspZUbWVQVS-yOI:b3ad4mw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L35)):*
> ```HTML
>     </style>
> 
>     <h3>CRUD</h3>
> ```

Maybe a small description ? Like grid does not feature editing rows out-of-the-box, but it's easy to implement ...

---

*[demo/crud.html, line 119 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIGBzCbGv1a3HR_kIj:-KdIGBzDx4a-1VKJZKS3:bz9m69c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L119)):*
> ```HTML
>                 },
> 
>                 _edit: function(e) {
> ```

It would be nice if focus is moved to the first input to draw the user's attention on the input.

---

*[demo/crud.html, line 144 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIEGJ3c6cdgf4irrU6:-KdIEGJ3c6cdgf4irrU7:b29htaj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L144)):*
> ```HTML
> 
>                 _add: function(e) {
>                   this.items.unshift({user: {name: {first: this.$.firstname.value, last: this.$.lastname.value}}});
> ```

probably should check whether first and lastname are empty in order not to add empty rows.

---

*[demo/pagination.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIHbd9ZOO3OobSSpVe:-KdIHbd9ZOO3OobSSpVf:b-i8ogy5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/pagination.html#L35)):*
> ```HTML
>     </style>
> 
>     <h3>Pagination</h3>
> ```

A description here as well. Something like ' grid behavior provides an infinite scrolling, but if you need pagination, you can implement easily such as in this demo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721)*

**Comment by tomivirkki** [comment]
Review status: 0 of 14 files reviewed at latest revision, 4 unresolved discussions.

---

*[demo/crud.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIGcspZUbWVQVS-yOH:-KdPrgM056CaFFKl3l0t:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L35)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Maybe a small description ? Like grid does not feature editing rows out-of-the-box, but it's easy to implement ...
</blockquote></details>

Done.

---

*[demo/crud.html, line 119 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIGBzCbGv1a3HR_kIj:-KdPflgbF4u2iLdr_h64:b4kj3tf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L119)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It would be nice if focus is moved to the first input to draw the user's attention on the input.
</blockquote></details>

Not easily doable with native input since focus can't be bound and readonly change doesn't fire an event.

---

*[demo/crud.html, line 144 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIEGJ3c6cdgf4irrU6:-KdPfv9PgjLHS-6GJGQt:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L144)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

probably should check whether first and lastname are empty in order not to add empty rows.
</blockquote></details>

Done.

---

*[demo/pagination.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIHbd9ZOO3OobSSpVe:-KdPyOiHI1IHorKoBWqP:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/pagination.html#L35)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

A description here as well. Something like ' grid behavior provides an infinite scrolling, but if you need pagination, you can implement easily such as in this demo
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721)*

**Comment by tomivirkki** [comment]
Reviewed 11 of 13 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721)*

**Comment by manolo** [comment]
Reviewed 11 of 13 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[demo/crud.html, line 119 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIGBzCbGv1a3HR_kIj:-KdQ-V7VvOgjbA0NjEUT:bmu54c6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L119)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Not easily doable with native input since focus can't be bound and readonly change doesn't fire an event.
</blockquote></details>

Don't you can figure out in the JS the input element and just call focus on it. I mean without complicating so much the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721)*

**Comment by tomivirkki** [comment]
*[demo/crud.html, line 119 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-KdIGBzCbGv1a3HR_kIj:-KdQ3adMVXRo4WyvPEh6:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/99bbe6099959414cd37c1fe3598a42a9c3c11384/demo/crud.html#L119)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Don't you can figure out in the JS the input element and just call focus on it. I mean without complicating so much the code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 1 of 2 files at r3.
Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-:-KdQ4UfRbYUqAj-HE0Yq:b-uwkowd)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 13 of 14 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721#-:-KdQ8nBbUoUEWQ-x3-El:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/721)*

**Pull request merged**
