### PR TITLE
Fix Android Chrome jumpy headers issue

### LINKED ISSUE #1020: Jumpy headers on Android Chrome
The newest Chrome for Android introduced an issue that causes jumpiness in all the still sections (headers/footers/frozen columns) while scrolling the grid. This manifests in all the grid versions.

kapture 2017-09-29 at 21 14 49

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1020

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1021)

### CODE REVIEW

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid-styles.html, line 129 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1021#-KvRjl-zbieDr3j6EWZQ:-KvRjl-zbieDr3j6EWZR:b-pprt0z) ([raw file](https://github.com/vaadin/vaadin-grid/blob/3972b5954d78e7a1e0e83473e040541a6cff2f25/vaadin-grid-styles.html#L129)):*
> ```HTML
>       #scroller:not([safari]) #outerscroller {
>         /* Needed for Android Chrome. Can't be applied to Safari
>         since it would re-introduce the sub-pixel overflow bug */
> ```

would be nice to have the ID of the sub-pixel overflow bug for the reference

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1021)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1021#-:-KvSISAF0NCYcWmaeGtt:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1021)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1021#-:-KvSjyzofhuEC7fdZrqA:bnfp4nl)*

**Pull request merged**
