### PR TITLE
Fix missing style scope when using array items and ShadyDOM

### PR DESCRIPTION
**Pull request by platosha**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1071)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-grid-data-provider-mixin.html, line 328 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071#-Kxr7xrZJAY_NsLcfBis:-Kxr7xr_UB4pWD6W4Ixp:b-f8jp3c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5f217f1dbaea8622c3b28a90baf82fb56bc62bff/vaadin-grid-data-provider-mixin.html#L328)):*
> ```HTML
>       this._cache = new Vaadin.Grid.ItemCache(this);
>       if (this.size !== undefined) {
>         this._cache.size = this.size;
> ```

Oh, it's quite inconsistent if the cache size is restored from `this.size` while cache size updates coming from the dataProvider aren't stored as `this.size`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-data-provider-mixin.html, line 328 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071#-Kxr7xrZJAY_NsLcfBis:-KxvtlvJwHZoAs7wXRiU:b5yju6c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5f217f1dbaea8622c3b28a90baf82fb56bc62bff/vaadin-grid-data-provider-mixin.html#L328)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Oh, it's quite inconsistent if the cache size is restored from `this.size` while cache size updates coming from the dataProvider aren't stored as `this.size`
</blockquote></details>

So what would you suggest?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-data-provider-mixin.html, line 328 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071#-Kxr7xrZJAY_NsLcfBis:-KxvtvU4fLBlYjVdCzjd:b-2fp7s0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5f217f1dbaea8622c3b28a90baf82fb56bc62bff/vaadin-grid-data-provider-mixin.html#L328)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

So what would you suggest?
</blockquote></details>

To set `this.size` in loadPage if the request was for root cache and a size was delivered

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-data-provider-mixin.html, line 328 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071#-Kxr7xrZJAY_NsLcfBis:-Kxvw9UJu1wAeoAjZnpI:b-k1oxv0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/5f217f1dbaea8622c3b28a90baf82fb56bc62bff/vaadin-grid-data-provider-mixin.html#L328)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

To set `this.size` in loadPage if the request was for root cache and a size was delivered
</blockquote></details>

If a user doesn’t set `size` property, and delivers size through `dataProvider`’s callback arg, is it expected that the public `size` property takes value other than `undefined`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1071#-:-Kxw1useuawiRV1-GvOn:b-uwkowd)*

**Pull request merged**
