### PR TITLE
Add indeterminate state to select-all. Fixes #573

### LINKED ISSUE #573: Add indeterminate mode to "Select All" checkbox
Key features for the checkbox needed:
- should be "checked" only when all currently *filtered* items are selected
- should be "unchecked" only when selected items is empty
- should be "indeterminate" basically when the two conditions above aren't true

- when in "indeterminate", clicking on "select all" should always go to "checked" mode first.
- when in "checked", clicking on "select all" should go to "unchecked"
- since `<paper-checkbox>` doesn't support "indeterminate", I don't think it would be 100% necessary at this point to expose a property for "indeterminate". But this is up for discussions if there's a solid use case for it.

### PR DESCRIPTION
**Pull request by manolo**
Fix #573

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/590)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 48 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQlp13s8o1hy5dFj3:-KZVQlp13s8o1hy5dFj4:b-hk9gnd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L48)):*
> ```HTML
>     ],
> 
>     dettached: function() {
> ```

detached

---

*[vaadin-grid-selection-column.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQzE97X0MA8SCRaEl:-KZVQzE97X0MA8SCRaEm:b-jkl7qb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L74)):*
> ```HTML
> 
>     _onSelectAllChanged: function(selectAll, grid) {
>       // We always select-all when comming from an undeterminated state (classic grid behavior)
> ```

Doesn't require the comment IMO

---

*[vaadin-grid-selection-column.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVR6L8rd7sGzLZHBnF:-KZVR6L8rd7sGzLZHBnG:b-pc9zk7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L83)):*
> ```HTML
>     },
> 
>     _onSelectItemsChanged: function(e) {
> ```

The argument list doesn't match that defined in the observer (selectedItems)

Also rename to _onSelectedItemsChanged

---

*[test/selecting.html, line 128 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQRANXtqCqWZi08Al:-KZVQRANXtqCqWZi08Am:b-v099v2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/test/selecting.html#L128)):*
> ```HTML
>         grid = fixture('multiselect');
>         grid.items = ['foo', 'bar', 'baz'];
>         delete grid.dataSource;
> ```

Why is the data source deleted? When you define `grid.items` it internally sets a datasource that can access the items array

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-selection-column.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVSBLrcC6JMkHqmO8e:-KZVSBLrcC6JMkHqmO8f:b-qizt28) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L7)):*
> ```HTML
>   <template>
>     <template class="header">
>       <input id="all" hidden$="[[!_grid.items]]" type="checkbox" checked="{{selectAll::change}}" indeterminate="[[_indeterminate]]"/>
> ```

Unused id

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 7 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVSBLrcC6JMkHqmO8e:-KZVU5Ywyy2R_GGDJwI4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L7)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Unused id
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 48 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQlp13s8o1hy5dFj3:-KZVU67IMfhgzEU6Uol4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L48)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

detached
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQzE97X0MA8SCRaEl:-KZVU7_Ek_ZxwjIR19_E:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L74)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Doesn't require the comment IMO
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVR6L8rd7sGzLZHBnF:-KZVU8Q5AWsCcct5vcPG:byh7psc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L83)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The argument list doesn't match that defined in the observer (selectedItems)

Also rename to _onSelectedItemsChanged
</blockquote></details>

The observer is not needed, Removed.

Renamed.

---

*[test/selecting.html, line 128 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQRANXtqCqWZi08Al:-KZVTqN_qAehYsrtvDYZ:b389cso) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/test/selecting.html#L128)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is the data source deleted? When you define `grid.items` it internally sets a datasource that can access the items array
</blockquote></details>

The select-all checkbox was not being shown in the UI, and I played with this. I forgot to remove it. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQzE97X0MA8SCRaEl:-KZVni99R5r0F73iwziA:b-ggj1c3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L74)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I would consider actually adding a `tap` listener to the select all checkbox which calls `e.preventDefault()` and then manually switch the `selectAll` and `indeterminate` properties so that we don't need to have a lock. Prototyped this quickly and seemed to work.

---

*[vaadin-grid-selection-column.html, line 90 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVog5R7Akoptlx0-Ww:-KZVog5R7Akoptlx0-Wx:b-kfikbm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c209d6c8c5cf8a86f17b21cb280d2ec9c56f81cd/vaadin-grid-selection-column.html#L90)):*
> ```HTML
>         this._indeterminate = false;
>         this.selectAll = false;
>       } else if (this._grid.selectedItems.length == this._grid.items.length) {
> ```

Need to compare selected items against the filtered items here: `grid._filter(grid.items)` I would also add `grid` in the observer arguments.

Also, one thing to take notice here is that once we start preserving selection after filtering and sorting, comparing array lengths isn't enough anymore – instead we need to check the contents. But no need to consider that yet, just wanted to add a note.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQzE97X0MA8SCRaEl:-KZWAAI9WeZVqC5NjTLW:b6xba6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L74)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I would consider actually adding a `tap` listener to the select all checkbox which calls `e.preventDefault()` and then manually switch the `selectAll` and `indeterminate` properties so that we don't need to have a lock. Prototyped this quickly and seemed to work.
</blockquote></details>

Already considered that, but then it does not work if the user has it's custom checkbox element.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 90 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVog5R7Akoptlx0-Ww:-KZWLDilaz55SU4dyuja:bd8siss) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c209d6c8c5cf8a86f17b21cb280d2ec9c56f81cd/vaadin-grid-selection-column.html#L90)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Need to compare selected items against the filtered items here: `grid._filter(grid.items)` I would also add `grid` in the observer arguments.

Also, one thing to take notice here is that once we start preserving selection after filtering and sorting, comparing array lengths isn't enough anymore – instead we need to check the contents. But no need to consider that yet, just wanted to add a note.

</blockquote></details>


Comparison: Done (it covers all those cases).

About observer, I'm not using observer here but listening for grid changes. Listener is re-set when the grid changes on attach/detach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQzE97X0MA8SCRaEl:-KZWRTokAVd3IDb4B5Ht:b32wtd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L74)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Already considered that, but then it does not work if the user has it's custom checkbox element.
</blockquote></details>

ok

---

*[vaadin-grid-selection-column.html, line 90 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVog5R7Akoptlx0-Ww:-KZWUb_3r6YJKFEZIlfR:bdpjug2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c209d6c8c5cf8a86f17b21cb280d2ec9c56f81cd/vaadin-grid-selection-column.html#L90)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>


Comparison: Done (it covers all those cases).

About observer, I'm not using observer here but listening for grid changes. Listener is re-set when the grid changes on attach/detach.

</blockquote></details>

still missing comparing selected items against filtered items `grid._filter(grid.items)`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590)*

**Comment by tomivirkki** [comment]
On IE11 switching from indeterminate to "all selected" doesn't seem to work

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/selection.html, line 181 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZX0FkMBsU5LXhS2RfA:-KZX0FkMBsU5LXhS2RfB:b-tabzvh) ([raw file](https://github.com/vaadin/vaadin-grid/blob/cdfb1a53604ae57b0c7c76bcb33d3742aef6f206/demo/selection.html#L181)):*
> ```HTML
>                   this.$.grid.selectItem(e.model.item);
>                 }
>                 this.indeterminate = this.$.grid.selectedItems.length > 0;
> ```

The indeterminate mode only works the first time in the second demo.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-:-KZX0NJGahyUvu5rvG1F:bb729z8)*

**Comment by manolo** [comment]
IE click changes from indeterminate to previous checked value and does not notify any change like it's documented here:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/944049/ and https://github.com/jquery/jquery/issues/1698 .

There is no way but finding the checkbox in light dom and adding click or tap handlers.

Switching from binding properties to tap observers  is an option, but there are some issues:
- When checkbox implementation is replaced by customisation listeners do not work.
- The option of adding 'on-tap' syntax does not work because it is not bound to the selection column context.
- We have to transverse the light dom to find checkboxes in header otherwise

Not sure if we should add any of those hacks to fix IE issue, or just disable indeterminate feature in IE like the classic grid does.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vaadin-grid-selection-column.html, line 74 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVQzE97X0MA8SCRaEl:-KZ_J1_WBr_q5Hy31Mey:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87aced82ad3372cecf7baeef5c438604d7f5990c/vaadin-grid-selection-column.html#L74)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---

*[vaadin-grid-selection-column.html, line 90 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZVog5R7Akoptlx0-Ww:-KZX1exooMC9MtnpYbs1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c209d6c8c5cf8a86f17b21cb280d2ec9c56f81cd/vaadin-grid-selection-column.html#L90)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

still missing comparing selected items against filtered items `grid._filter(grid.items)`
</blockquote></details>

Done.

---

*[demo/selection.html, line 181 at r4](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-KZX0FkMBsU5LXhS2RfA:-KZ_GuGYrgBclN7znkSQ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/cdfb1a53604ae57b0c7c76bcb33d3742aef6f206/demo/selection.html#L181)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The indeterminate mode only works the first time in the second demo.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-:-KZ_H-ldbC1w6ue7sFTb:bn8qodd)*

**Comment by manolo** [comment]
As said in the daily, I have disabled the indeterminate feature in IE like we do in FW grid.

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-:-KZ_RE7gdMv3OjKnjVuO:bwt5whv)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-:-KZaPzD8ZzArqLf6ctas:bnfp4nl)*

**Comment by manolo** [comment]
sorry @tomivirkki I found a last issue. In IE we have to set selectAll to false when indeterminate like it's done in FW

---

Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-:-KZaXkzvIo5BpGzLKu7T:b-vs3s1i)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/590#-:-KZfirAh3WmSR0070ekF:bnfp4nl)*

**Pull request merged**
