### PR TITLE
Array data source

### LINKED ISSUE #482: Array data source

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #482

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/485)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-grid-array-data-source-behavior.html, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmygvtYNeNyfpFGMkv:-KTmygvtYNeNyfpFGMkw:b-dvoiuv) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-array-data-source-behavior.html#L24)):*
> ```HTML
>     _itemsChanged: function(items, splices) {
>       this.size = (items || []).length;
>       this.clearCache();
> ```

Just a comment for the future, we probably want to have another method for just reloading the currently visible page so that we're not forcing scrolling to be reset when just a single item is updated.

---

*[vaadin-grid-data-source-behavior.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmxVESoD7BZiT7q3Km:-KTmxVESoD7BZiT7q3Kn:b9h5dws) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-data-source-behavior.html#L83)):*
> ```HTML
>        */
>       dataSource: {
>         type: Function,
> ```

I think it would be better to keep `dataSource` without default value and instead assign it in the `_itemsChanged`. 

---

*[vaadin-grid-row-details-behavior.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmxeoe2eT543fWIXzS:-KTmxeofeKxZD5PFncmV:b-kuxl48) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-row-details-behavior.html#L39)):*
> ```HTML
> 
>     observers: [
>       '_expandedItemsChanged(expandedItems.*, dataSource, size)'
> ```

observing `size` isn't probably necessary if we always assign a new function to `dataSource` in `_itemsChanged`. Keep in mind that `size` will not change in cases where a new items array with the same size is assigned.

---

*[vaadin-grid-table.html, line 247 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmyB8MSVJ9NX0yXP3g:-KTmyB8MSVJ9NX0yXP3h:b-hjxd6h) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-table.html#L247)):*
> ```HTML
>       // observing _physicalCount instead of _physicalItems.length because grid
>       // seems to startup somewhat faster without using this.push('_physicalItems')...
>       this._physicalItems.forEach(function(row) {
> ```

Remove `this` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485)*

**Comment by tomivirkki** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-grid-array-data-source-behavior.html, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmygvtYNeNyfpFGMkv:-KTn0uJJPg8kW93FzXFS:b7fm7ed) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-array-data-source-behavior.html#L24)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Just a comment for the future, we probably want to have another method for just reloading the currently visible page so that we're not forcing scrolling to be reset when just a single item is updated.
</details>
Hmm...why does clearCache reset scroll position? Doesn't sound logical

---

*[vaadin-grid-table.html, line 247 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmyB8MSVJ9NX0yXP3g:-KTn7rC_WzF3viK3zdSm:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-table.html#L247)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> Remove `this` 
</details>
Done.

---

*[vaadin-grid-data-source-behavior.html, line 83 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmxVESoD7BZiT7q3Km:-KTn2S62McpOZAuWoIRR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-data-source-behavior.html#L83)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> I think it would be better to keep `dataSource` without default value and instead assign it in the `_itemsChanged`. 
</details>
Done.

---

*[vaadin-grid-row-details-behavior.html, line 39 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmxeoe2eT543fWIXzS:-KTn7EVTQwAzdCtja6bc:bbr1oj4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-row-details-behavior.html#L39)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> observing `size` isn't probably necessary if we always assign a new function to `dataSource` in `_itemsChanged`. Keep in mind that `size` will not change in cases where a new items array with the same size is assigned.
</details>
The dependency could be removed now that setting the `dataSource` is moved to `_itemsChanged`. Doesn't need to be a new function.

Added a test case for changing the items to a new array with same size.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485)*

**Comment by magi42** [comment]
Documentation part looked excellent, only found a few things to mention.

---

Reviewed 10 of 16 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/vaadin-grid-assigning-data.adoc, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnOhNQTnKsB-JaEfkq:-KTnOhNRhxva2wgR8N28:b-yutfuw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L19)):*
> ```AsciiDoc
> 
> [[vaadin-grid.items.property]]
> == Assigning the grid items
> ```

* Capitalize titles: "Assigning the Grid Items"

---

*[docs/vaadin-grid-assigning-data.adoc, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnTdyqddc6DUReYIHn:-KTnTdyqddc6DUReYIHo:b-cadl0a) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L24)):*
> ```AsciiDoc
> 
> First, you need to define the columns and a mapping between object properties and the columns.
> You can do this declaratively with the body [elementname]#template# of a [elementname]#vaadin-grid-column# element, as in the example below.
> ```

* Don't use "below", which can look odd because of pagination or columns, and also doesn't imply how much below. Always use "following": "_...as in the following example._"

---

*[docs/vaadin-grid-assigning-data.adoc, line 96 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnP_OQptQGYbAHodHV:-KTnP_OQptQGYbAHodHW:b7z3jlt) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L96)):*
> ```AsciiDoc
> ----
> 
> If the [propertyname]#items# array changes dynamically without the use of Polymer's array mutation methods, the [vaadinelement]#vaadin-grid# must be explicitly notified of the changes.
> ```

* Maybe rather "without the use of" -> "otherwise than by using"

---

*[docs/vaadin-grid-assigning-data.adoc, line 97 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnQ0n7KFJ20mLp7qrY:-KTnQ0n7KFJ20mLp7qrZ:b5vyed4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L97)):*
> ```AsciiDoc
> 
> If the [propertyname]#items# array changes dynamically without the use of Polymer's array mutation methods, the [vaadinelement]#vaadin-grid# must be explicitly notified of the changes.
> Invoke [propertyname]#notifyPath# function with the exact path of the changes as the parameter to make [vaadinelement]#vaadin-grid# synchronize.
> ```

* Functions should be emphasized with the `[methodname]` style. Also use parentheses () to signify method names or functions. Hence in this case, no need to mention that it's a function.
* A bit complex sentence. Probably more clear as: "`To synchronize [vaadinelement]#vaadin-grid# with the array, invoke [methodname]#notifyPath()# with the exact path of the changes as the parameter.`"

---

*[docs/vaadin-grid-assigning-data.adoc, line 101 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnRY5icgu6jIKAR2Wf:-KTnRY5icgu6jIKAR2Wg:b-1qisu4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L101)):*
> ```AsciiDoc
> [source,javascript]
> ----
> // In this case 'user' is a reference to one of the items in 'items' array but the email is changed without the help of Polymer's array mutation methods
> ```

* Comma after introductory phrase: "In this case, "
* Too long code line. For BoV the limit would be 63 characters, although it's more relaxed here, as we're not printing Elements docs, at least yet. But that's way too much, possibly causing the line to cut or scrollbars.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-:-KTnSUy35k2-hRvYQGyc:btkx3lp)*

**Comment by tomivirkki** [comment]
Review status: 10 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[docs/vaadin-grid-assigning-data.adoc, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnOhNQTnKsB-JaEfkq:-KTncgSFZoWXokXtiFeg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L19)):*
<details><summary><i>Previously, magi42 (Marko Grönroos) wrote…</i></summary>
> * Capitalize titles: "Assigning the Grid Items"
</details>
Done.

---

*[docs/vaadin-grid-assigning-data.adoc, line 24 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnTdyqddc6DUReYIHn:-KTnch9XMxOpogFCHDTh:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L24)):*
<details><summary><i>Previously, magi42 (Marko Grönroos) wrote…</i></summary>
> * Don't use "below", which can look odd because of pagination or columns, and also doesn't imply how much below. Always use "following": "_...as in the following example._"
</details>
Done.

---

*[docs/vaadin-grid-assigning-data.adoc, line 96 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnP_OQptQGYbAHodHV:-KTnclEAFlYIvxgI7flN:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L96)):*
<details><summary><i>Previously, magi42 (Marko Grönroos) wrote…</i></summary>
> * Maybe rather "without the use of" -> "otherwise than by using"
</details>
Done.

---

*[docs/vaadin-grid-assigning-data.adoc, line 97 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnQ0n7KFJ20mLp7qrY:-KTnco8A-VgaqhNEVn-7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L97)):*
<details><summary><i>Previously, magi42 (Marko Grönroos) wrote…</i></summary>
> * Functions should be emphasized with the `[methodname]` style. Also use parentheses () to signify method names or functions. Hence in this case, no need to mention that it's a function.
> * A bit complex sentence. Probably more clear as: "`To synchronize [vaadinelement]#vaadin-grid# with the array, invoke [methodname]#notifyPath()# with the exact path of the changes as the parameter.`"
</details>
Done.

---

*[docs/vaadin-grid-assigning-data.adoc, line 101 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnRY5icgu6jIKAR2Wf:-KTnctCAkW5VViVdQZ85:basz606) ([raw file](https://github.com/vaadin/vaadin-grid/blob/87fb78c8f664747c879206f8eee84d0b2dd6f809/docs/vaadin-grid-assigning-data.adoc#L101)):*
<details><summary><i>Previously, magi42 (Marko Grönroos) wrote…</i></summary>
> * Comma after introductory phrase: "In this case, "
> * Too long code line. For BoV the limit would be 63 characters, although it's more relaxed here, as we're not printing Elements docs, at least yet. But that's way too much, possibly causing the line to cut or scrollbars.
</details>
Done. Cut the sentence into 2 lines.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485)*

**Comment by Saulis** [comment]
Review status: 10 of 11 files reviewed at latest revision, 9 unresolved discussions.

---

*[vaadin-grid-array-data-source-behavior.html, line 24 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTmygvtYNeNyfpFGMkv:-KTngjd1gcj1UJvrRj2P:b-tpqgpy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/315ebafa1fc1f9a7087ee0e0096570ace2e239d6/vaadin-grid-array-data-source-behavior.html#L24)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary>
> Hmm...why does clearCache reset scroll position? Doesn't sound logical
</details>
I think it only happens when the number of items changes.

---

*[vaadin-grid-array-data-source-behavior.html, line 19 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnn5aCgAnMhM1T0pqw:-KTnn5aCgAnMhM1T0pqx:b-hi5fux) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e013f7f922b6582c52cf92613d19b4f4b9fbdc0a/vaadin-grid-array-data-source-behavior.html#L19)):*
> ```HTML
> 
>     observers: [
>       '_itemsChanged(items, items.*)'
> ```

Comment: we can optimize later `_itemsChanged` not to for example run twice when items is spliced (for `items.splice` and `items.length`)

---

*[vaadin-grid-selection-behavior.html, line 149 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnnPXrqyeVVHH8KK6O:-KTnnPXrqyeVVHH8KK6P:b-la6tbs) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e013f7f922b6582c52cf92613d19b4f4b9fbdc0a/vaadin-grid-selection-behavior.html#L149)):*
> ```HTML
>     },
> 
>     _selectedItemsChanged: function(e, dataSource) {
> ```

It's not really obvious why `dataSource` is being observed – I would be leaned towards just adding a `this.$.scroller._physicalItems` check inside the existing if clause. Should be safe since we `selected` is checked again once the rows are actually rendered.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485)*

**Comment by tomivirkki** [comment]
Review status: 8 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[vaadin-grid-selection-behavior.html, line 149 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-KTnnPXrqyeVVHH8KK6O:-KTnqT-Qx9-5sGsxY2U2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e013f7f922b6582c52cf92613d19b4f4b9fbdc0a/vaadin-grid-selection-behavior.html#L149)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary>
> It's not really obvious why `dataSource` is being observed – I would be leaned towards just adding a `this.$.scroller._physicalItems` check inside the existing if clause. Should be safe since we `selected` is checked again once the rows are actually rendered.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 9 of 16 files at r1, 6 of 6 files at r2, 1 of 1 files at r3.
Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/485#-:-KTns1Wd6F1MC7FXMWu0:bnfp4nl)*

**Pull request merged**
