### PR TITLE
Add activeItem property

### LINKED ISSUE #567: Add a property for item that user last interacted with
### As a developer, I want to be able to present item details in a separate view

Currently, you can somewhat use `selectedItem` property, but in #519 it's planned to be dropped.

Alternatively, you can listen to `cell-click` and pick up the clicked item from there.

Current API:

```html
<my-item-overlay id="details">
  <template is="dom-bind" id="detailsTemplate">
    <div>[[item.value]]</div>
  </template>
</my-item-overlay>
<vaadin-grid on-cell-click="_details">
  <vaadin-grid-column>
     ...
  </vaadin-grid-column>
</vaadin-grid>
<script>
  _details: function(e) {
    this.$.detailsTemplate.item = e.detail.model.item;
    this.$.details.opened = true;
  };
</script>
```

Proposal: add `activeItem` property which will hold the item object user has last interacted with, either by clicking or by hitting space/enter on keyboard.

- We can have a CSS mixin for the "active" item, which wouldn't have any styles by default.
- `activeItem` goes to `null` when the currently active item is interacted with.

This would allow doing more of the "single-selection" use cases purely declaratively.

New API:

```html
<!-- Disclaimer: haven't tried if toggling the opened using an object works, but in theory it should :-) -->
<!-- Another declarative approach for opening would be to have on-active-item-changed="_details.open()" -->
<my-item-overlay opened="{{activeItem}}">
  <template is="dom-bind" item="[[activeItem]]">
    <div>[[item.value]]</div>
  </template>
</my-item-overlay>
<vaadin-grid active-item="{{activeItem}}">
  <vaadin-grid-column>
   ...
  </vaadin-grid-column>
</vaadin-grid>
```

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #567

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/571)

### CODE REVIEW

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KYwNKlPBW0CHd9Mxtcb:bnfp4nl)*

**Comment by manolo** [comment]
What is the scope of this PR? just MVP or do we add more features in it.

I miss, proper info about any input flags, like keyboard shift/control and which event type fired the activation.

Another concern, this project has a lot of .html small files, I know there are mechanisms to vulcanise or use HTTP2, but by default there are a lot of hits to the server. Probably we could try to reduce the number of them.

Otherwise it looks ok to me

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KYw_kesGiOgFqHxZNQq:b7552t1)*

**Comment by manolo** [comment]
BTW, the feature needs to be documented.
It could be merged in the selection api temporary branch, probably some code could be simplified with this.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KYwcUmskieFVtT4C_fs:b-z1iepk)*

**Comment by Saulis** [comment]
Keyboard navigation will be implemented separately in #487. I wasn't sure if I should've done a separate behavior for this property, but didn't find any other suitable place for it.

Regarding server hits, personally I think it's up to the app developer to decide if they need to optimize the server hits or not. Of course less files is always less files, but I would rather optimize for modularity at this point until someone actually approaches us stating this is an issue.

About documentation, I did update one of the selection examples to be simpler. And then we have the API docs for the property. I don't know what other info we could add?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KYwc5c2mju_Wzhs5m9X:b-butjx3)*

**Comment by manolo** [comment]
To me activation and cell-click are very related, I think it's worth for the DX to add a section in documentation explaining them and use cases. We can do later or now. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KYwvA_X_2aEwcabQXLg:b-t0vx4m)*

**Comment by Saulis** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[docs/vaadin-grid-interaction.adoc, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0THQz3y2jeoRTwl_x:-KZ0THQz3y2jeoRTwl_y:bn4q6ss) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L12)):*
> ```AsciiDoc
> Grid allows the user to interact with rows.
> 
> The `vaadin-grid-active-item-behavior` keeps track of the last user action, updating conveniently the `activeItem` property of the grid.
> ```

This behavior is an implementation detail that might change, doesn't give any value to the user.

---

*[docs/vaadin-grid-interaction.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0TksH1ExyTc3Zscts:-KZ0TksH1ExyTc3Zsctt:bb1dd71) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L20)):*
> ```AsciiDoc
> 
> [propertyname]#activeItem#::
>   It is the grid property that reflects the last item activated by the user, or null if there was no item activated.
> ```

 I'm not sure what new info this gives the user apart from the API docs for `activeItem`?

---

*[docs/vaadin-grid-interaction.adoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0TmE837DVgSnTgbBe:-KZ0TmE837DVgSnTgbBf:b-6pjdv0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L23)):*
> ```AsciiDoc
> 
> [propertyname]#active-item-changed#::
>   It is the event fired when an activation action happens.
> ```

As this is a normal Polymer notification event, I don't think we should explicitly document that. It's mentioned already in the API docs.

---

*[docs/vaadin-grid-row-details.adoc, line 87 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0Sxxw3G0cEHMmgaHA:-KZ0Sxxw3G0cEHMmgaHB:b-2x17gt) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-row-details.adoc#L87)):*
> ```AsciiDoc
> ----
> // Expand o collapse the last active item
> grid.addEventListener('active-item-changed', function(e) {
> ```

Please don't replace the whole example with this snippet, just change the `on-cell-click` to `on-active-item-changed` etc. Also, use `e.detail.value` rather than `grid.activeItem` directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by tomivirkki** [comment]
Review status: 4 of 7 files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/vaadin-grid-interaction.adoc, line 2 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0VOc_1jdj6gGJEZe9:-KZ0VOc_1jdj6gGJEZeA:b-zgh2xl) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L2)):*
> ```AsciiDoc
> ---
> title: Cell Interaction
> ```

Naming the article for `activeItem` as "Cell Intercation" and subsection as "User Interaction" feels vague. Let's just limit this to `activeItem` for now.

---

*[docs/vaadin-grid-interaction.adoc, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0W8qnu5tHZJcjOmlW:-KZ0W8qnu5tHZJcjOmlX:b-bvu6sr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L10)):*
> ```AsciiDoc
> = User Interaction
> 
> Grid allows the user to interact with rows.
> ```

This needs to be more descriptive.

---

*[docs/vaadin-grid-interaction.adoc, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0Vbtl6T8MfSwviMsl:-KZ0Vbtl6T8MfSwviMsm:b-p3xo6e) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L15)):*
> ```AsciiDoc
> 
> [[vaadin-grid.interaction.events]]
> == Interaction API
> ```

vaadin-grid.interaction.events = Intercation API? This doesn't really describe what the activeItem property is about.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by manolo** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[docs/vaadin-grid-interaction.adoc, line 2 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0VOc_1jdj6gGJEZe9:-KZ0_kdpjDCZ0sGbP6Ot:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L2)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Naming the article for `activeItem` as "Cell Intercation" and subsection as "User Interaction" feels vague. Let's just limit this to `activeItem` for now.
</blockquote></details>

Done.

---

*[docs/vaadin-grid-interaction.adoc, line 10 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0W8qnu5tHZJcjOmlW:-KZ0_oll0t8GxHbmkiyR:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This needs to be more descriptive.
</blockquote></details>

Done.

---

*[docs/vaadin-grid-interaction.adoc, line 12 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0THQz3y2jeoRTwl_x:-KZ0_qTOcP7ouI0BtEdH:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L12)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This behavior is an implementation detail that might change, doesn't give any value to the user.
</blockquote></details>

Done.

---

*[docs/vaadin-grid-interaction.adoc, line 15 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0Vbtl6T8MfSwviMsl:-KZ0_s7oyONA3pJ_xrXA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L15)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

vaadin-grid.interaction.events = Intercation API? This doesn't really describe what the activeItem property is about.
</blockquote></details>

Done.

---

*[docs/vaadin-grid-interaction.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0TksH1ExyTc3Zscts:-KZ0_wMOj7T0rt1aM2o8:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L20)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

 I'm not sure what new info this gives the user apart from the API docs for `activeItem`?
</blockquote></details>

Done.

---

*[docs/vaadin-grid-interaction.adoc, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0TmE837DVgSnTgbBe:-KZ0_tr_NDbR4UIeVhSX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-interaction.adoc#L23)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

As this is a normal Polymer notification event, I don't think we should explicitly document that. It's mentioned already in the API docs.
</blockquote></details>

Done.

---

*[docs/vaadin-grid-row-details.adoc, line 87 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ0Sxxw3G0cEHMmgaHA:-KZ0_RQDCPR4joiBXRtZ:b-8iyl2a) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e02dd41001e1ac20ab4a5a401ea9e8aa233c4c71/docs/vaadin-grid-row-details.adoc#L87)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Please don't replace the whole example with this snippet, just change the `on-cell-click` to `on-active-item-changed` etc. Also, use `e.detail.value` rather than `grid.activeItem` directly.
</blockquote></details>

I just wanted #ffs, anyway Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by manolo** [comment]
Reviewed 3 of 5 files at r3.
Review status: 8 of 9 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by manolo** [comment]
Reviewed 1 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by Saulis** [comment]
:lgtm: 

---

Reviewed 4 of 5 files at r1, 1 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KZ19kBp2UJ5eJuNA1Xp:bg7igkv)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-grid-row-details.adoc, line 79 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1ML-xzsUKCmRkyWS0:-KZ1ML-xzsUKCmRkyWS1:bftwuw3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L79)):*
> ```AsciiDoc
> When modifying [propertyname]#expandedItems#, remember to use the array mutation methods from Polymer.Base
> 
> [[vaadin-grid.row-details.activation]]
> ```

activation -> activeitem

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-grid-row-details.adoc, line 79 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1ML-xzsUKCmRkyWS0:-KZ1MdxGbPSPO0zTB-_x:b-rrv4sj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L79)):*
> row-details
?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-grid-row-details.adoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1MmXyS0IEJLomQ9QI:-KZ1MmXyS0IEJLomQ9QJ:b-sn8fjo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L82)):*
> ```AsciiDoc
> == Expanding and Collapsing Items on activation
> 
> You can listen to [propertyname]#active-item-changed# event which is fired whenever a user activates a row in the grid. Then you can access the last activated item by using the `activeItem` of the grid.
> ```

It's quite unclear what it means when "a user activates a row in the grid"

---

*[docs/vaadin-grid-row-details.adoc, line 97 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1N-8ZgksJqQJkqt7z:-KZ1N-8ZgksJqQJkqt8-:bqav0ae) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L97)):*
> ```AsciiDoc
>   ...
>     _onActiveItemChanged: function(e) {
>       var grid = this.$.grid;
> ```

This variable is only used once. Feels unnecessary to declare it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-grid-row-details.adoc, line 79 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1ML-xzsUKCmRkyWS0:-KZ1PKpy6ftponTbMEG-:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L79)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

> row-details
?
</blockquote></details>

Done

---

*[docs/vaadin-grid-row-details.adoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1MmXyS0IEJLomQ9QI:-KZ1NyFyD9726S8QIP-a:bo3b331) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L82)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's quite unclear what it means when "a user activates a row in the grid"
</blockquote></details>

I think activate is the most generic way to say this. I didn't want to use select, or click, because selection is done separately and the action that the user does for activating could be tap, click, space, or whatever implementations we do.  Do you have an idea how to clarify it, to me is understandable enough. 

---

*[docs/vaadin-grid-row-details.adoc, line 97 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1N-8ZgksJqQJkqt7z:-KZ1OmRhU-WNCvA4l8Yc:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L97)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This variable is only used once. Feels unnecessary to declare it.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by tomivirkki** [comment]
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---

*[docs/vaadin-grid-row-details.adoc, line 79 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1ML-xzsUKCmRkyWS0:-KZ1Q4aLYaH_LFebHiMe:b-z8dwup) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L79)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done
</blockquote></details>

It still says row-details.

---

*[docs/vaadin-grid-row-details.adoc, line 82 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-KZ1MmXyS0IEJLomQ9QI:-KZ1QIB-oUPlQjeexibk:b-oar36k) ([raw file](https://github.com/vaadin/vaadin-grid/blob/400880d56ccb4b03805e84c8f1afba02609216cf/docs/vaadin-grid-row-details.adoc#L82)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think activate is the most generic way to say this. I didn't want to use select, or click, because selection is done separately and the action that the user does for activating could be tap, click, space, or whatever implementations we do.  Do you have an idea how to clarify it, to me is understandable enough. 
</blockquote></details>

"activeItem" is a term we came up with so it needs to be explained somehow other than saying "it's the row that is activated by the user"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571#-:-KZ1T67iqkPFpzjjDITe:bnfp4nl)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/571)*

**Pull request merged**
