### PR TITLE
Fix screen reader support broken in Hybrid migration

### LINKED ISSUE #889: Screen reader support
Screen reader support doesn't function in 3.0.0-alpha1

### PR DESCRIPTION
**Pull request by platosha**
Fixes #889

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/897)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm: once tests pass

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/897#-:-KmBRk_bJwwO6Q0Gn4BD:bplk40w)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-cell.html, line 85 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/897#-KmBgrryTSBK7-S4_No6:-KmBgrryTSBK7-S4_No7:b-rdq8qy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c8f641571e863dfc76abc4c437c332c1d6f7455/vaadin-grid-table-cell.html#L85)):*
> ```HTML
>       },
> 
>       hostAttributes: {
> ```

Is this needed for something?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/897)*

**Comment by platosha** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table-cell.html, line 85 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/897#-KmBgrryTSBK7-S4_No6:-KmBlBFZmLWk0FujcVGC:bu2j3sr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9c8f641571e863dfc76abc4c437c332c1d6f7455/vaadin-grid-table-cell.html#L85)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Is this needed for something?
</blockquote></details>

Nope. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/897)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/897#-:-KmBgfM2AT_btyQ136KK:bnfp4nl)*

**Pull request merged**
