### PR TITLE
Use font icons in hierarchy toggle, prettify default theme

### PR DESCRIPTION
**Pull request by platosha**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1074)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-grid-hierarchy-toggle.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1074#-Kxw8DpSrkl1s9P_u42V:-Kxw8DpTQ6HaoHnAp5D1:b-oij399) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0260cb20679510fd3a652cf482ad60a19fd73f1d/vaadin-grid-hierarchy-toggle.html#L11)):*
> ```HTML
> 
> <style>
>   @font-face {
> ```

Hierarchy toggle icons are so simple, we could just use CCS triangles instead https://css-tricks.com/snippets/css/css-triangle/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1074)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid-hierarchy-toggle.html, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1074#-Kxw8DpSrkl1s9P_u42V:-KxwPZn13nmxYJ9_ysK2:b-ycrqjc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/0260cb20679510fd3a652cf482ad60a19fd73f1d/vaadin-grid-hierarchy-toggle.html#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hierarchy toggle icons are so simple, we could just use CCS triangles instead https://css-tricks.com/snippets/css/css-triangle/
</blockquote></details>

Font icons don’t require alignment with text, and also provide out-of-the-box support for changing color, font size and line height.

Apart from that, if we do CSS triangles manually here, we would have to decide the sizes, position, angle values, and so on. I could put decisions to my taste here, but nobody trusts my design taste. :-(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1074)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1074#-:-KxwePMmpkEJyLZ_vd_m:bnfp4nl)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1074#-:-KxwefO5tv9zaouJUWov:bnfp4nl)*

**Pull request merged**
