### PR TITLE
Use ES6 syntax in demos

### PR DESCRIPTION
**Pull request by manolo**
Connected to #878 

This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/981)

### CODE REVIEW

**Comment by tomivirkki** [comment]
The title says “Use ES6 syntax in demos” but only the tests are changed. The purpose of the task is to switch demos from `Polymer(` to es6 classes so we don’t advocate the old syntax in our demos

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981#-:-KtokrUavk--dkr2zjgp:b-blhpju)*

**Comment by tomivirkki** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/crud.html, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981#-KtpBEtPeGu4NnRk8Fxe:-KtpBEtPeGu4NnRk8Fxf:betnwbw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/11f2eefc66f323f7a6b22bdb376995c50eb4add3/demo/crud.html#L93)):*
> ```HTML
> 
>           <script>
>             class XCrud extends Polymer.Element {
> ```

The demo functionality no longer works

---

*[demo/pagination.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981#-KtpBNrqlnlC5zufgnAz:-KtpBNrqlnlC5zufgnB-:betnwbw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/11f2eefc66f323f7a6b22bdb376995c50eb4add3/demo/pagination.html#L106)):*
> ```HTML
>           <script>
>             window.addEventListener('WebComponentsReady', function() {
>               class XPagination extends Polymer.Element {
> ```

The demo functionality no longer works

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/crud.html, line 93 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981#-KtpBEtPeGu4NnRk8Fxe:-KtpHafo50HJkHBTPN-j:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/11f2eefc66f323f7a6b22bdb376995c50eb4add3/demo/crud.html#L93)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The demo functionality no longer works
</blockquote></details>

Done.

---

*[demo/pagination.html, line 106 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981#-KtpBNrqlnlC5zufgnAz:-KtpHbFJBPm_lYLpYIuX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/11f2eefc66f323f7a6b22bdb376995c50eb4add3/demo/pagination.html#L106)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The demo functionality no longer works
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/981#-:-KtpIhihV5jItz3yoqma:b-uwkowd)*

**Pull request merged**
