### PR TITLE
Fix/select all

### LINKED ISSUE #247: grid.selection.selectAll() doesn’t update the selection-mode attribute
If you call `grid.selection.selectAll()`, the `selection-mode` attribute on the element is not updated to “all”. The `grid.selection.mode` property returns “all” correctly.

At the same time,  check that setting the select.mode property reflects correctly, and that selection.clear() correctly sets the attribute and property from "all" to "multi" (when in single-select mode, the mode doesn’t change when clear() is called).

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #247

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/273)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 76 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z3QCWQ1mPUxKXIt2S:-K3z3QCWQ1mPUxKXIt2T:-1017721243) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L76)):*
I would have a more generic event so as we eventually could use it in other circumstances : SelectionModelHasChanged ?

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 369 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yyZDnBHDXXcNMeBH-:-K3yyZDnBHDXXcNMeBH0:1077606224) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L369)):*
Do we use this method somewhere?, make it private or utilise the public one, I don't see any reason for overloading it

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 372 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z46Ptpr_KS3G5ct_E:-K3z46Ptpr_KS3G5ct_F:-1878493327) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L372)):*
Could we somehow remove all code related with multi/all from here? what about 

    if ( ! model.canBeReused(newMode))  {  // or recycle or whatever name
         ...
    }

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 384 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z4hTXfeK_mCIaNjC2:-K3z4hTXfeK_mCIaNjC3:-1701348628) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L384)):*
this logic should be encapsulated in model

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 613 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z5QPRGA5oFSoIlnGQ:-K3z5QPRGA5oFSoIlnGR:1279758946) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L613)):*
remove the 'on' prefix, just selectionModeChanged looks better

---

*[java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedEvent.java, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3ywurk7QGrm8V6V4CT:-K3ywurk7QGrm8V6V4CU:-1031914063) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedEvent.java#L6)):*
I would hide this class into another class related with this. Probably in IndexBasedSelectionMode or IndexBasedSelectionModel.
In GWT the tendency is not expose these classes in folders for simplicity and avoiding having to document so much the API

---

*[java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedHandler.java, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yy-ITpmnFxlduJ1eH:-K3yy-ITpmnFxlduJ1eI:1765840886) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedHandler.java#L5)):*
Move this class as well like above.

---

*[vaadin-grid.html, line 957 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yyNE2MY8NqmAqfswm:-K3yyNE2MY8NqmAqfswn:1253137482) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/vaadin-grid.html#L957)):*
Update example to use this event as well

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273)*

**Comment by tomivirkki** [comment]
Review status: 0 of 10 files reviewed at latest revision, 8 unresolved discussions.

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 76 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z3QCWQ1mPUxKXIt2S:-K41tPM1NQSsPydsaO33:-945233239) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L76)):*
No need to prematurely prepare for that. We can change the event later if necessary. With custom selection models I think the logic will change quite a lot anyway.

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 369 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yyZDnBHDXXcNMeBH-:-K41ttMgKFt6nQbrhvk4:-260594845) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L369)):*
Good catch, fixed

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 372 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z46Ptpr_KS3G5ct_E:-K41wPEw-a3Rz70FUWvz:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L372)):*
done

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 384 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z4hTXfeK_mCIaNjC2:-K41wcVDNpohpb3J0PUE:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L384)):*
done

---

*[java/src/main/java/com/vaadin/elements/grid/GridElement.java, line 613 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3z5QPRGA5oFSoIlnGQ:-K41wm2nYLpaoBIkaoMf:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/GridElement.java#L613)):*
done

---

*[java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedEvent.java, line 6 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3ywurk7QGrm8V6V4CT:-K41xYGOkHWK5Q2gElZ1:850236712) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedEvent.java#L6)):*
At least all the events/handlers under com.google.gwt.event.dom.client and com.vaadin.client.widget.grid.events are listed as individual classes

---

*[java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedHandler.java, line 5 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yy-ITpmnFxlduJ1eH:-K41xz7I4LzKnj7_WO7m:850236712) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/java/src/main/java/com/vaadin/elements/grid/selection/MultiSelectModeChangedHandler.java#L5)):*
At least all the events/handlers under com.google.gwt.event.dom.client and com.vaadin.client.widget.grid.events are listed as individual classes

---

*[vaadin-grid.html, line 957 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yyNE2MY8NqmAqfswm:-K41y-AVL9UWpP1yjdt5:1264950259) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/vaadin-grid.html#L957)):*
Changes in the PR don't affect the public events. All demos should be up-to-date already

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273)*

**Comment by tehapo** [comment]
Review status: 0 of 10 files reviewed at latest revision, 9 unresolved discussions.

---

*[test/grid-selecting-rows.html, line 154 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K42NqBl4K7gOeW1POjl:-K42NqBms0QKCfkAMPLr:-255206201) ([raw file](https://github.com/vaadin/vaadin-grid/blob/cbf6c51eaa2408fa63cd51bdd2cd44c883e457bb/test/grid-selecting-rows.html#L154)):*
Missing the last word here ("all")?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273)*

**Comment by tomivirkki** [comment]
*[test/grid-selecting-rows.html, line 154 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K42NqBl4K7gOeW1POjl:-K42PMRy5DdYGN0Lax-5:677588487) ([raw file](https://github.com/vaadin/vaadin-grid/blob/cbf6c51eaa2408fa63cd51bdd2cd44c883e457bb/test/grid-selecting-rows.html#L154)):*
done

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273)*

**Comment by tehapo** [comment]
LGTM. Although I don't have much insight on the GWT side of the Grid.

---

Reviewed 3 of 8 files at r1, 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-:-K42PwNREfF7Hn7m82iP:-1372285178)*

**Comment by manolo** [comment]
*[vaadin-grid.html, line 957 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yyNE2MY8NqmAqfswm:-K42kpSUTAvx3wSltdWa:-1289214306) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/vaadin-grid.html#L957)):*
The example is updating the selection box each time selection change, it should change only when mode changes

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 957 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273#-K3yyNE2MY8NqmAqfswm:-K42m8BOV3e5twzyE_-0:-207198981) ([raw file](https://github.com/vaadin/vaadin-grid/blob/f0a3f5b9ee0e1fc9df7fd601c5084f30c21e64c0/vaadin-grid.html#L957)):*
Ah, so it seems. Not related to this ticket however.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/273)*

**Pull request merged**
