### PR TITLE
added row stripe cell mixin

### PR DESCRIPTION
**Pull request by billy-hardy**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/425)

### CODE REVIEW

**Comment by billy-hardy** [comment]
@jouni Just wanted to let someone know this small change is up.

**Comment by jouni** [comment]
Thanks! That’s a very obvious addition to the styling API, we’ve just forgotten about it completely.

Could you add it to the official documentation as well (in the last section): https://github.com/vaadin/vaadin-grid/blob/master/docs/vaadin-grid-styling.adoc

**Comment by billy-hardy** [comment]
@jouni Updated and also rephrased it to match the other docs. Thanks for taking a look at this.

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/425#-:-KPloBBDLm_h7jVDG9IF:bnfp4nl)*

**Pull request merged**
