### PR TITLE
Fix pagination example for mobile devices

### PR DESCRIPTION
**Pull request by limonte**
https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha3/demo/pagination.html

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/772)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/columns.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-KeXw86lwCzOfH_JDSub:-KeXw86lwCzOfH_JDSuc:bxxate5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0fd511b57348960600895ab4ebce5a8c7e276b5/demo/columns.html#L23)):*
> ```HTML
>   <link rel="import" href="../../iron-icons/iron-icons.html">
>   <link rel="import" href="../../iron-media-query/iron-media-query.html">
>   <link rel="import" href="../../vaadin-grid/vaadin-grid-column-group.html">
> ```

I've changed the import URLs deliberately to be relative to enable previewing demos through dev branches with `polygit.org`. Did you encounter and issue with the URLs?

---

*[demo/pagination.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-KeXvpC0d_ZB5AdjLHbT:-KeXvpC0d_ZB5AdjLHbU:by2oydz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8fffbd3668d9ab331028c709f43bc8dfed9f0c4c/demo/pagination.html#L58)):*
> ```HTML
>                 user-select: none;
>                 padding: 5px;
>                 margin: 0 5px;
> ```

To me `justify-content: space-between` works better than fixed margin, especially if the number of buttons change at some point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772)*

**Comment by limonte** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[demo/columns.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-KeXw86lwCzOfH_JDSub:-KeXwy5pJrQdWvLYgX-2:b-h7duzz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0fd511b57348960600895ab4ebce5a8c7e276b5/demo/columns.html#L23)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I've changed the import URLs deliberately to be relative to enable previewing demos through dev branches with `polygit.org`. Did you encounter and issue with the URLs?
</blockquote></details>

Yup, in my setup those paths produce 404 errors. Also, this is inconsistent with all demos of other components and skeleton. 

---

*[demo/pagination.html, line 58 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-KeXvpC0d_ZB5AdjLHbT:-KeXxmwxt3xYZf1TRaHa:bsfyam5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8fffbd3668d9ab331028c709f43bc8dfed9f0c4c/demo/pagination.html#L58)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

To me `justify-content: space-between` works better than fixed margin, especially if the number of buttons change at some point.
</blockquote></details>

Agree, but at the same time `justify-content: space-between` looks ugly for wrapped content: https://i.imgur.com/ldBInpo.png

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772)*

**Comment by limonte** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[demo/columns.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-KeXw86lwCzOfH_JDSub:-KeYNTeKxcC4apGSsqX4:b-uzk9zw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0fd511b57348960600895ab4ebce5a8c7e276b5/demo/columns.html#L23)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Yup, in my setup those paths produce 404 errors. Also, this is inconsistent with all demos of other components and skeleton. 
</blockquote></details>

I can't get your change working with NGinx as it does not provide the polyserve-polygit-like magic for linking the component to the bower_components folder. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[demo/columns.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-KeXw86lwCzOfH_JDSub:-KeYSt3OOFfxpDDiqNeV:bx6r6ie) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0fd511b57348960600895ab4ebce5a8c7e276b5/demo/columns.html#L23)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

I can't get your change working with NGinx as it does not provide the polyserve-polygit-like magic for linking the component to the bower_components folder. 
</blockquote></details>

ok, let's go with these changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-:-KeYSvi0DL87j4QV1SPc:bnfp4nl)*

**Comment by Saulis** [comment]
rebase and merge

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/772#-:-KeYSz4BN6bIA6zM5-EG:b-lawqug)*

**Pull request merged**
