### PR TITLE
Fixes for Closure Compiler

### PR DESCRIPTION
**Pull request by davitykale**
Changes to behaviors per guidance from: google/closure-compiler#2042 + misc fixes.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/886)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Hi @davitykale,
Can you provide steps (or even better, a test case) for reproducing the original issue with Closure Complier & vaadin-grid. This might be something we need to fix in all of our elements (not just the Grid) so we need means to test it.

**Comment by davitykale** [comment]
Hi @tomivirkki,

The two main issues are:

1. All Polymer properties need to have the type explicitly defined (even if it's obvious), aka:
```
Polymer({
...
  properties: {
    foo: {
      type: Number, // This always needs to be added
      value: 1
    }
  }
});

2. Behaviors must be global names or qualified names.
Issue and solution are discussed here: https://github.com/google/closure-compiler/issues/2042

**Comment by tomivirkki** [comment]
Ok created a build step for Closure compilation at branch [`fix/closure-compile`](https://github.com/vaadin/vaadin-grid/tree/fix/closure-compile). Please rebase your work on top of that to make sure the compilation works after the fixes.

**Comment by davitykale** [comment]
Closing because my employer will unfortunately not let me sign the CLA at this time.

**Pull request closed without merging**
