### PR TITLE
Fix(keyboard): skip hidden header and footer rows

### PR DESCRIPTION
**Pull request by platosha**
Connected to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/972)

### CODE REVIEW

**Comment by manolo** [comment]
Broken tests. pls fix them.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/972#-:-Ktjt9NFds_QZ44n4-Co:bvzv8pl)*

**Comment by tomivirkki** [comment]
There's something odd in the column mapping here. The screenshot shows how I can use up/down arrows to move focus between some cells but the focus doesn't move between correct column groups.

screenshot 2017-09-25 13 28 41

**Comment by platosha** [comment]
@tomivirkki fixed

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/972#-:-KuskJYPlQBZJPrN5JZO:b-9ncesw)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/972#-:-Kusqq7S7XxKOeg7T2fa:b-uwkowd)*

**Pull request merged**
