### PR TITLE
Fix/2.0 tests

### LINKED ISSUE #678: Add missing platforms to test scripts
- Add tests for Edge, Safari 10, iOS 10 (fix problems :-)

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #678

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/682)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

---

Review status: 0 of 23 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-:-KbzCyMD-v62ql9xVcMr:bnfp4nl)*

**Comment by Saulis** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[wct.conf.js, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-Kc1tj0yHit9p0DWfVvA:-Kc1tj0yHit9p0DWfVvB:bqsrtqa) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97d9c50cd6d1af3441c08979a387260876815e1a/wct.conf.js#L9)):*
> ```JavaScript
> 
>     var otherPlatforms = [
>       'OS X 10.11/iphone@9.3',
> ```

Did you try if  iOS 10 works?

---

*[test/keyboard-navigation.html, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-Kc1xJ_7hRu7udGwUD97:-Kc1xJ_7hRu7udGwUD98:bfimo0e) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97d9c50cd6d1af3441c08979a387260876815e1a/test/keyboard-navigation.html#L57)):*
> ```HTML
> 
>   <script>
>     describe('keyboard navigation', function() {
> ```

We could save time by skipping all the keyboard tests for iOS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682)*

**Comment by tomivirkki** [comment]
Review status: 0 of 23 files reviewed at latest revision, 2 unresolved discussions.

---

*[wct.conf.js, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-Kc1tj0yHit9p0DWfVvA:-Kc1yHhgJY8dKJQ-kUWk:b-ufa3ln) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97d9c50cd6d1af3441c08979a387260876815e1a/wct.conf.js#L9)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Did you try if  iOS 10 works?
</blockquote></details>

Yes, run them locally on a simulator

---

*[test/keyboard-navigation.html, line 57 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-Kc1xJ_7hRu7udGwUD97:-Kc1zjBMrKk73zMiioXU:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97d9c50cd6d1af3441c08979a387260876815e1a/test/keyboard-navigation.html#L57)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

We could save time by skipping all the keyboard tests for iOS
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 21 of 23 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[wct.conf.js, line 9 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-Kc1tj0yHit9p0DWfVvA:-Kc2X4ido6pDgrL_qhLm:b-392afm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97d9c50cd6d1af3441c08979a387260876815e1a/wct.conf.js#L9)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yes, run them locally on a simulator
</blockquote></details>

OK then, let's update the automated tests later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/682#-:-Kc2K8RszWHwPsKOdZk2:bnfp4nl)*

**Pull request merged**
