### PR TITLE
Replace native input with vaadin-checkbox

### PR DESCRIPTION
**Pull request by manolo**
Connected to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/960)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid-selection-column.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-KtAgpouvPgGcLabcDcN:-KtAgpovC6H76n4f6zvX:b-b72056) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32acb556836247b34163d67628b27c738c9bdc8d/vaadin-grid-selection-column.html#L14)):*
> ```HTML
>   <template>
>     <template class="header" id="defaultHeaderTemplate">
>       <vaadin-checkbox aria-label="Select All" hidden$="[[_selectAllHidden]]" on-click="_onSelectAll"
> ```

This only changes the "Select all" checkbox (in header)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960)*

**Comment by manolo** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-selection-column.html, line 14 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-KtAgpouvPgGcLabcDcN:-KtBB0AxjlP_8wAczG7N:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/32acb556836247b34163d67628b27c738c9bdc8d/vaadin-grid-selection-column.html#L14)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This only changes the "Select all" checkbox (in header)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960)*

**Comment by platosha** [comment]
Please consider keyboard navigation workflow. Activating the selection column checkbox by pressing <kbd>Space</kbd> when cell is focused does not work well now. Couple of issues:

1. This removes focus from the cell and focuses the checkbox. Because of this, keyboard navigation stops working as expected, <kbd>Esc</kbd> is then required to continue navigating with keyboard on the grid.
2. Toggling the header “select all” checkbox with <kbd>Space</kbd> works only once. After the first press, next presses change only the checkbox state but do not select/deselect the rows.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-KtBVkJFS4t2zKMsrWDg:b-u55ho5)*

**Comment by platosha** [comment]
To solve these, I think, we should make `<vaadin-checkbox>` not to steal focus on programmatic `.click()`. This depends on https://github.com/vaadin/vaadin-control-state-mixin/pull/17

Doing tricks with focus without a straightforward way of preventing mouse click stealing focus is not good.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-KtMAr4RqhGqLVTjtyZv:b-2szh9r)*

**Comment by platosha** [comment]
Also indeed making `.click()` to toggle in `<vaadin-checkbox>` https://github.com/vaadin/vaadin-checkbox/issues/24 would help much to bring the original UX back here.

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-KtRlTAHvI1y99wrSAF1:b-xer3dn)*

**Comment by tomivirkki** [comment]
The commit message says "vaadin-combobox"

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/selecting.html, line 279 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-Kt_DwCa8C6Nfv5kmi3i:-Kt_DwCa8C6Nfv5kmi3j:b-qpbawu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c88be4801249923aa0c9723a3b8a704316e704b6/test/selecting.html#L279)):*
> ```HTML
> 
>       it('should be unchecked when nothing is selected', function() {
>         expect(selectAllCheckbox.indeterminate).to.be.undefined;
> ```

Rather check that the value is falsy: `...).not.to.be.ok;`

---

*[test/selecting.html, line 292 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-Kt_E6LGQwb0wXDL-Hiw:-Kt_E6LGQwb0wXDL-Hix:b-qpbawu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c88be4801249923aa0c9723a3b8a704316e704b6/test/selecting.html#L292)):*
> ```HTML
>       it('should have indeterminate and select-all when an item is selected', function() {
>         expect(selectAllCheckbox.checked).to.be.false;
>         expect(selectAllCheckbox.indeterminate).to.be.undefined;
> ```

Rather check that the value is falsy: `...).not.to.be.ok;`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-Kt_DnT8D695rdviXI3q:b6hycwz)*

**Comment by manolo** [comment]
Changed commit message

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[test/selecting.html, line 279 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-Kt_DwCa8C6Nfv5kmi3i:-Ktjq0l0eo5Kad089XjK:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c88be4801249923aa0c9723a3b8a704316e704b6/test/selecting.html#L279)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rather check that the value is falsy: `...).not.to.be.ok;`
</blockquote></details>

Done.

---

*[test/selecting.html, line 292 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-Kt_E6LGQwb0wXDL-Hiw:-Ktjq1TvkrG_yK3NCZB1:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/c88be4801249923aa0c9723a3b8a704316e704b6/test/selecting.html#L292)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Rather check that the value is falsy: `...).not.to.be.ok;`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-KtCHmA9S4gZdgfHOAw7:bimgprj)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-Ktjvm_hCFR29lqvv1FS:b-uwkowd)*

**Comment by manolo** [comment]
:lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/960#-:-KtjyV8HorgthbZG88GR:bg7igkv)*

**Pull request merged**
