### PR TITLE
Run Polymer.flush() before measuring details cell height

### LINKED ISSUE #1141: Weird display when using dom-repeat for row details (v4.0.0)
### Description
Using row details with dom-repeat on v4.0.0 (v4.0.0-alpha 2 not affected)

### Expected outcome
Normal display

### Actual outcome
Details are expanded over the rows, hiding them. When multiples details are expanded, it displays properly.  Expand a previously expanded row will behave as expected.

### Live Demo
https://jsfiddle.net/jx80nm35/6/

### Steps to reproduce
1. click on `Show Details`

### Browsers Affected
- [X] Chrome
- [X] Firefox

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1141

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1143)

### CODE REVIEW

**Comment by web-padawan** [comment]
BTW I'm wondering if this can also help with #1089 ?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1143#-:-L-GGASvr35vVBCR0Sg4:bv4iedj)*

**Comment by tomivirkki** [comment]
Ah, It most likely does. I'll add the reference to the description.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1143#-:-L-GHR65veMCaDqO1LIx:b-wl02e8)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1143#-:-L-GLLRCaEka8QGNRRpM:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm: but it doesn't fix https://github.com/vaadin/vaadin-grid/issues/1089

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1143#-:-L-GNf7t6RfRo3nIDwDd:bdbqy78)*

**Comment by tomivirkki** [comment]
Ok, removed the reference.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1143#-:-L-GNxnG0pn7SffPRNHh:b-bdra9l)*

**Comment by limonte** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1143)*

**Pull request merged**
