### PR TITLE
add focus row mixin

### PR DESCRIPTION
**Pull request by billy-hardy**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/790)

### CODE REVIEW

**Comment by billy-hardy** [comment]
@jouni any chance I can get someone to look at this PR? Also, the build seems to be failing because of some configuration not being set, I don't see anywhere in the contributing file on how to set this, so any help would be great. Thanks

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/790#-:-Kfk8qVmZ63QhYIuUjH7:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/790#-:-KfkAb-FDhX-NbkZ9yCi:bnfp4nl)*

**Comment by tomivirkki** [comment]
Released in https://github.com/vaadin/vaadin-grid/releases/tag/v1.2.2

**Pull request merged**
