### PR TITLE
Navigate using Page, Home, End keys

### PR DESCRIPTION
**Pull request by Saulis**
Connects to #487

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/662)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/keyboard-navigation.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-KapgXMxgjcepyI-9fjW:-KapgXMxgjcepyI-9fjX:bghxr81) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ff7e6a2b91f900d77b82f4a579c2945dade2876d/test/keyboard-navigation.html#L23)):*
> ```HTML
>         height: 50px;
>       }
>     }
> ```

Why do we need this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662)*

**Comment by Saulis** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/keyboard-navigation.html, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-KapgXMxgjcepyI-9fjW:-KaqTp6ttAVWpgtlkLv7:b-hxc97t) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ff7e6a2b91f900d77b82f4a579c2945dade2876d/test/keyboard-navigation.html#L23)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Why do we need this?
</blockquote></details>

To know in the vertical scroll tests how high each item is compared to the grid height.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662)*

**Comment by limonte** [comment]
could you please rebase this branch

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-:-KaqiH9b_5Tga3zs0A3s:bg3wxbt)*

**Comment by limonte** [comment]
:lgtm:  Superb!

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-:-KavhPIOcdtax9IBegy-:b-mi1atz)*

**Comment by tomivirkki** [comment]
Looks like #653 introduced this strange issue we didn't notice: If you scroll a grid downwards (without focusing it) and then click any cell, it jumps back to the first item. Needs to be fixed here (or in a separete PR)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-:-Kb9Kvhd__otMsgtMjRp:b-qdjcho)*

**Comment by Saulis** [comment]
good catch, I'll fix it in this PR.

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-:-KbAhPz7vLWQJU55RBIj:bdbrbcc)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 5 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/662#-:-KbFBOsZNwFBgpqlNo-i:bnfp4nl)*

**Pull request merged**
