### PR TITLE
Combine mixins to work in Chrome 65

### LINKED ISSUE #1234: "Aw, Snap!" in Chrome Canary 66.0.3352.0
### Description
Chrome Canary 66.0.3352.0 dies with an "Aw, Snap!" page error attempting to load the [vaadin-grid 4.1.5 demos](https://vaadin.com/elements/vaadin-grid/html-examples/grid-basic-demos). I have seen this error with my own use of vaadin-grid beginning with Chrome Canary 66.0.3349.0. The demos (and my app) run fine in Chrome 64.

### Expected outcome
The demos page should load and the demos run.

### Actual outcome
Chrome Canary dies with 
"**Aw, Snap!**
Something went wrong while displaying this webpage."

### Live Demo
Example: https://vaadin.com/elements/vaadin-grid/html-examples/grid-basic-demos

### Steps to reproduce
Just open the demo. The app dies immediatel.

### Browsers Affected

- [ ] Chrome release
- [x] Chrome Canary
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #1234

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1245)

### CODE REVIEW

**Comment by tomivirkki** [comment]
LGTM

**Comment by moderndeveloperllc** [comment]
@web-padawan Just curious - how did you figure this out? The Chromium bug report has a mention of 25+ mixins causing an issue, but `vaadin-grid` only had 16. Was the number you combined arbitrary or anything?

**Comment by web-padawan** [comment]
@moderndeveloperllc actually the `Polymer.Element` brings following mixins:

- PropertiesChanged
- PropertyAccessors
- TemplateStamp
- PropertyEffects
- PropertiesMixin
- ElementMixin

... and since we are also using behaviors, that means the `LegacyElementMixin` usage which turns out to include another bunch of mixins:

- GestureEventListeners
- Dir
- LegacyElement
- MutableData
- OptionalMutableData

My initial idea was to get rid of the `LegacyElementMixin` but that would mean copying the external code (`IronResizableBehavior` etc), and anyways would not be sufficient.

So, actually, I combined the exact number of mixins needed to mitigate the issue + 1 (just in case if someone is brave enough to extend the `vaadin-grid` itself).

**Comment by moderndeveloperllc** [comment]
@web-padawan Thanks for the explanation. I hadn't considered the `Polymer.Element` mixins. FWIW, the `vaadin-grid` 5.0 branch has been working for be very well. It seems to render faster and be more responsive to scrolls for very long lists where I'm not setting the height  - just doing `heightByRows`.

**Comment by karsten-eger** [comment]
> So, actually, I combined the exact number of mixins needed to mitigate the issue + 1 (just in case if someone is brave enough to extend the vaadin-grid itself).

So the consumer of vaadin-grid "only" have one mixin available now? Should be fine for now I guess - at least Chrome is fixing this


already upgraded on our end, it works again, thanks for the quick solution.

**Comment by web-padawan** [comment]
@karsten-eger we tried not to collapse everything into one mixin, and to keep at least some of the biggest untouched. Hope that we will be able to get rid of this workaround before going to stable `5.0.0`, but there still might be some changes until that time, e. g. there is a PR for `column-reordering-mixin` in review as of now, etc.

**Pull request merged**
