### PR TITLE
Use 2d transforms only to avoid Safari rendering issues

### LINKED ISSUE #444: Row elements overflow the grid outer border
Depending on the viewport width, sometimes the row elements cover the right edge border of the grid:

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #444

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/709)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709#-Kd5jN3MzhxXOHJ02o1F:-Kd5jN3MzhxXOHJ02o1G:b-3dq3v5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8b1fff3e3087c919e78c3a05dcaccc7c69ea0347/vaadin-grid-table.html#L61)):*
> ```HTML
>         /* iron-list expects top to be 0. Might cause issues */
>         /* top: 0; */
>         will-change: transform;
> ```

Is it required to remove `will-change: transform;`?

I would leave it in otherwise. We’re still changing transform, makes sense to indicate that.

---

*[demo/styling.html, line 101 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709#-Kd5jvDot0YrXOmMpZbd:-Kd5jvDot0YrXOmMpZbe:b-82kbur) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8b1fff3e3087c919e78c3a05dcaccc7c69ea0347/demo/styling.html#L101)):*
> ```HTML
>             vaadin-grid#material vaadin-grid-sorter iron-icon {
>               transform: scale(0.8) translateZ(0);
>               transition: all 0.3s;
> ```

Was it intentional to remove transition here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709)*

**Comment by jouni** [comment]
> Is it required to remove will-change: transform;?

It is required, otherwise Safari will revert back to the same bug.

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid-table.html, line 61 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709#-Kd5jN3MzhxXOHJ02o1F:-Kd5lGzguXzcOCRx1Cm5:b-53axf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8b1fff3e3087c919e78c3a05dcaccc7c69ea0347/vaadin-grid-table.html#L61)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Is it required to remove `will-change: transform;`?

I would leave it in otherwise. We’re still changing transform, makes sense to indicate that.
</blockquote></details>

Would like to have it also, but it's required for this fix. Fortunately there's no noticeable performance hit from removing this (at least on the devices I tested with).

---

*[demo/styling.html, line 101 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709#-Kd5jvDot0YrXOmMpZbd:-Kd5lc7raHOmuRhyevcu:b-wmvvtm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/8b1fff3e3087c919e78c3a05dcaccc7c69ea0347/demo/styling.html#L101)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Was it intentional to remove transition here?
</blockquote></details>

Unfortunately yes, if you scroll the grid down a bit and then rotate the arrow, grid loses top border while transitioning... It's an internal element and should have 0 effect on Grid but still... Safari...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709)*

**Comment by platosha** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/709#-:-Kd5sZlQQSqIDnmq2ynr:bnfp4nl)*

**Pull request merged**
