### PR TITLE
Fix width for preceding columns on resize

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/695)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[test/column-resizing.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/695#-Kcx9e9kFV5f3Hrj2GA1:-Kcx9e9kFV5f3Hrj2GA2:bmdlw5d) ([raw file](https://github.com/vaadin/vaadin-grid/blob/43e787c256b5ea3b8a44393ebab569ac726359fd/test/column-resizing.html#L147)):*
> ```HTML
>         grid._columnTree[0][0].flexGrow = 1;
>         Polymer.Base.fire('track', {state: 'start'}, {node: headerCells[1]._resizeHandle});
>         expect(grid._columnTree[0][0].width).not.to.equal('50%');
> ```

Maybe expect the value string to end with 'px' units?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/695)*

**Comment by tomivirkki** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/column-resizing.html, line 147 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/695#-Kcx9e9kFV5f3Hrj2GA1:-Kd-ffD267MvsUwtWiXq:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/43e787c256b5ea3b8a44393ebab569ac726359fd/test/column-resizing.html#L147)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Maybe expect the value string to end with 'px' units?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/695)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/695#-:-Kd0jegdaPRzL1R412-4:bnfp4nl)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/695#-:-Kd0tg6R6eqdzrpCekMS:bnfp4nl)*

**Pull request merged**
