### PR TITLE
Observe for column template changes

### LINKED ISSUE #890: Add Dom Observers for Templates
Discussed with @Saulis. The grid won't work with Angular 2 and other libraries where elements are created and attached programatically.

Specifically, the column templates in Angular 2 are first created, then attached to `<vaadin-grid-column>` before child elements are attached to the `<template>`.

Adding some observers for when templates or their content changes will resolve any issues with programmatically creating and attaching a grid and its children. Alternatively, we could expose an API to inform the grid that its templates or columns have changed so that it knows to re-stamp them.

Relates to https://github.com/hotforfeature/origami/issues/18 for Angular 4/Polymer 2 support.

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #890 

Ran tests manually for Edge, Safari, Chrome, Firefox, iOS 🆗

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/918)

### CODE REVIEW

**Comment by manolo** [comment]
Pls fix CI.

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/918#-:-KnrUdM45xGFo3Jsu2ud:b-l3n8fl)*

**Comment by tomivirkki** [comment]
*[test/filtering.html, line 187 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/918#-KnsGXbJKrxSO6LU1G0I:-KnsGXbJKrxSO6LU1G0J:b-op4elj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ee286b8ced5b2ea1fd16899163ee37a43287c8bf/test/filtering.html#L187)):*
> ```HTML
>         Polymer.dom.flush();
> 
>         if (Polymer.Element) {
> ```

This is repeated a lot. How about moving the snippet to common `helpers.html`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/918)*

**Comment by samiheikki** [comment]
Review status: 0 of 14 files reviewed at latest revision, 1 unresolved discussion.

---

*[test/filtering.html, line 187 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/918#-KnsGXbJKrxSO6LU1G0I:-Kr4jfp27EMIj6wPputE:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ee286b8ced5b2ea1fd16899163ee37a43287c8bf/test/filtering.html#L187)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This is repeated a lot. How about moving the snippet to common `helpers.html`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/918)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 11 files at r2, 6 of 11 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/918#-:-Kr5K21aO6oICEdS6-DP:bnfp4nl)*

**Pull request merged**
