### PR TITLE
All cells should have a content wrapper

### PR DESCRIPTION
**Pull request by tomivirkki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/555)

### CODE REVIEW

**Comment by Saulis** [comment]
So what's the background for this? Why do all cells need to have a content wrapper?

**Comment by tomivirkki** [comment]
It's needed for themability. Since we're (most likely) going to target the "cell-content" wrappers with our mixins, placing let's say a backgroud color for --vaadin-grid-header-cell mixin would result in empty squares in your header if every cell didn't contain a wrapper

**Comment by Saulis** [comment]
Oh right.. should reconsider applying the mixins to cells instead? I remember you and Jouni thinking if it's a bit hacky to apply styles to generated items? Also, exposing (internal) class names to light DOM will prevent us from choosing freely any class names we want due to the risk of styles leaking from outside. (this is probably not a huge issue, but still..)

I think I would prefer keeping it all internal – in case the user applies some styles to the cells that conflict with the cell content wrappers, some general styles can still be applied from outside.

**Comment by tomivirkki** [comment]
What we referred to as "hacky" with Jouni was enabling the user to directly apply CSS rules for the light DOM cell-content wrapper elements by classnames applied on the fly. This is not the case here. What we're planning is targeting the wrappers with the style mixins instead. It's actually more risky exposing mixins for the internal cells. Please read the "open questions" section at https://github.com/vaadin/vaadin-grid/issues/534#issuecomment-264159208

"in case the user applies some styles to the cells that conflict with the cell content wrappers, some general styles can still be applied from outside"
Again, we're really not considering adding classnames to the wrappers on the fly and you really shouldn't target them directly with any CSS rules. Their sole purpose is to provide an insertion point for arbitrary cell content so we can distribute light DOM nodes to grid cells in a clean manner.

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/555#-KYNz-RkE0UR8zzAlwXK:-KYNz-RkEP_IBcSJJmy-:b-q558ii) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9edf3772d0fbfa066daf8bcdae55e4ff9f199cc5/vaadin-grid-column.html#L20)):*
> ```HTML
>           type: Object,
>           value: function() {
>             return this._findTemplate('template.header') || null;
> ```

Would it make more sense to add `document.createElement('template')` here as a default value instead of `null` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/555)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/555#-KYNz-RkE0UR8zzAlwXK:-KYO7qCG0oNxCNNFO3si:b5i750y) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9edf3772d0fbfa066daf8bcdae55e4ff9f199cc5/vaadin-grid-column.html#L20)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Would it make more sense to add `document.createElement('template')` here as a default value instead of `null` ?
</blockquote></details>

This is a column-specific property (`headerTemplate`) but we need a template for each cell on that column (even the empty ones). This 'null' value is set here only to make `_headerTemplateChanged` invoke for cells on a column that don't have a `headerTemplate`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/555)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/555#-:-KYOnKps8dCYC3ChHjvO:bnfp4nl)*

**Pull request merged**
