### PR TITLE
Skip checking undefined or empty paths

### LINKED ISSUE #817: Internet Explorer: Unable to get property 'indexOf' of undefined or null reference
Hi Folks,

When setting the grid's `items` array, either through binding or setting, (working from 2.0.0-alpha4 and 2.0-dev) Internet explorer gives an error:  Unable to get property 'indexOf' of undefined or null reference. Referenced in line 67 of vaadin-grid-array-data-provider-behavior.html

A simple fix is to handle an undefined `path` variable as an empty string.
ex:
```
        // skip simple paths
        if ((path || '').indexOf('.') === -1) {
          continue;
        }
```

I would like to fork and submit a pull request, but am unsure which branch you would like to work off of, or if you would like to investigate a better solution.  Our current case required an immediate workaround, and this is it.

Happy to receive input!

-Colin

### PR DESCRIPTION
**Pull request by limonte**
Fix #817

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/818)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Can you provide a test case to validate this fix?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/818#-:-Kfusq8KHv0-Kuzl51SY:b39pgup)*

**Comment by limonte** [comment]
I can't reproduce this case, but it is reproducible by our user. Simple fix, not worth testing IMO.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/818#-:-KfvCB04A-fZYmofbkIB:b-e2wqsb)*

**Comment by krumware** [comment]
thanks folks! this thing has been a thorn in our side for some time

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/818#-:-KfzNCdy3XSErCz_CUBw:bnfp4nl)*

**Pull request merged**
