### PR TITLE
function -> ES6 arrows, var -> const/let

### PR DESCRIPTION
**Pull request by manolo**
Connected to #878 

This is the latest PR related with ES6 syntax sugar

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/984)

### CODE REVIEW

**Comment by limonte** [comment]
This syntax is horrible to debug and maintain.

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/984#-:-Ktq6PzUb-aDFPQQZsXb:b9c5veh)*

**Comment by manolo** [comment]
What concretely ?

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/984#-:-Ktq6jcrGpXf7rrnGMz1:b-c6kxfc)*

**Comment by tomivirkki** [comment]
:lgtm_strong: 

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/984#-:-KtqAg9tB_9Nm8bi7apW:b-uwkowd)*

**Comment by web-padawan** [comment]
@limonte BTW what about using some tool to avoid further syntax-related discussions like this one about one-line arrow functions?

It could be [prettier](https://github.com/survivejs/maintenance-book/blob/master/manuscript/code-quality/02-code-formatting.md#formatting-javascript-with-prettier), or maybe `clang-format` (used by Polymer tools team in their TypeScript projects) or something like this.

**Pull request merged**
