### PR TITLE
Support slotted row details template

### LINKED ISSUE #923: Putting row-details template inside a <slot> ?
Hello everyone,

is it possible to put the row-details template for a vaadin-grid inside a <slot>?

Here's my "poly-grid" element where I want to be able to plug-in various rowDetail templates, depending on the context where the grid is used:

```
<dom-module id="poly-grid">
   <template>
      <vaadin-grid items=[[data]]>
         <!-- SLOT FOR A OPTIONAL ROW TEMPLATE -->
         <slot name="rowDetailTemplate"></slot>

         <!-- columns etc ..... -->
      </vaadin-grid>
   </template>
</dom-module>
```

Now, when using my poly-grid, I'd like to plug-in the rowDetail template:

```
<poly-grid id="grid1">
   <template slot="rowDetailTemplate" class="row-details">
      <div >         
         <div class="details">
             <p>Hello! I'm the row detail for [[item.firstName]]!</p>
           </div>
        </div>
   </template>
</poly-grid>
```

Doing so, nothing happens when expanding a row.

Changing my poly-grid and call-site like below, the row detail appears when expanding a row, but contains the non-evaluated content of the row details -> "Hello! I'm the row detail for [[item.firstName]]!":

```
<dom-module id="poly-grid">
   <template>
      <vaadin-grid items=[[data]]>
         <!-- SLOT FOR A OPTIONAL ROW TEMPLATE -->
         <template class="row-details">
            <slot name="rowDetailTemplate"></slot>
         </template>

         <!-- columns etc ..... -->
      </vaadin-grid>
   </template>
</dom-module>
```
```
<poly-grid id="grid1">
   <div slot="rowDetailTemplate" class="details">
      <p>Hello! I'm the row detail for [[item.firstName]]!</p>
   </div>
</poly-grid>
```

So that isn't working too because the [[item.firstName]] doesn't get evaluated.

I tried some more variants, but non of them got working like expected.

What am I doing wrong? Is it possible at all? Any ideas?

Regards,
Michael

### LINKED ISSUE #1196: row-details template can't be changed dynamically
### Description
This feature is required by vaadin-grid-flow. Programmatically  changed row details template must be supported.

### Live Demo
http://elmot.xyz/grid-element-bug/

### Steps to reproduce
1. Open the page
1. Click any row
1. Observe "No details" label
1. Click "add details" button
1. Click any other row

### Expected outcome
*Hi! My name is ???*

### Actual outcome
No Details

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #923
Fixes #1196

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1225)

### CODE REVIEW

**Comment by moderndeveloperllc** [comment]
@tomivirkki Changing it over to a `<slot>` looks nice. The only thing I think y'all might want to check is how this interacts with `<iron-form>` 2.1+ as that now flattens out slots. I know that some of the other Vaadin elements had issues for a while with this. Then again, y'all might not want to support the edge case of `<iron-form>` wrapping a `vaadin-grid`.

**Comment by tomivirkki** [comment]
@moderndeveloperllc The change in the test suite is slightly misleading. We're not completely switching to slotted details templates but just enabling them on top of the current API. I'll change the test suite to reflect this better.

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1225#-:-L5JKyLpcpNJ6RgV2sQ2:bnfp4nl)*

**Comment by YuriyVaadin** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1225#-:-L5TByHaZgCfHQUNPXO4:bnfp4nl)*

**Pull request merged**
