### PR TITLE
Fix Firefox tests

### LINKED ISSUE #634: Tests are failing in Firefox

### PR DESCRIPTION
**Pull request by limonte**
Fixes #634

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/637)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-table-header-footer.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cRaFCIHxE69tEbl81:-K_cRaFCIHxE69tEbl82:b-kniown) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/vaadin-grid-table-header-footer.html#L13)):*
> ```HTML
>       },
> 
>       observers: ['_columnTreeChanged(columnTree, isAttached)', '_rowsChanged(_rows)'],
> ```

Why is this necessary? It makes the grid re-render everything on each re-attach (slow operation). Like for example when the grid is moved in the DOM.

---

*[test/.eslintrc.json, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cSBuhEbfMcnqo8qgY:-K_cSBuhEbfMcnqo8qgZ:bhaej4u) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/.eslintrc.json#L37)):*
> ```JSON
>     "isVisible": false,
>     "defaultCellWidth": false,
>     "firefox": false
> ```

Can't we just use:
```
"no-undef": 0,
"no-unused-vars": 0
```
for tests? Enumerating each global variable in a separate file is nasty.

---

*[test/light-dom-observing.html, line 494 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cS_uP65Pgdx9mU5Vo:-K_cS_uP65Pgdx9mU5Vp:b-6ayva) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/light-dom-observing.html#L494)):*
> ```HTML
>             expectFirstColumn('', columnsLevel);
>             expectNumberOfColumns(3);
>             expect(1).to.be.equal(1);
> ```

Pretty sure we don't need to test this :)

---

*[test/outer-scroller.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cShApMQZ-8Snsv2TS:-K_cShApMQZ-8Snsv2TT:b-prbj3x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/outer-scroller.html#L181)):*
> ```HTML
>           scroller.addEventListener('mousemove', function() {
>             // TODO: @limonte revisit in future
>             if (!firefox) { // firefox has the blinking issue here (current version is 50)
> ```

For me this is passing even with FF

---

*[test/row-height.html, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cT6n0C1QAESzAa5y_:-K_cT6n0C1QAESzAa5ya:b-hexvz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/row-height.html#L259)):*
> ```HTML
>         init('default-content');
>         scrollToEnd(grid, function() {
>           scroller.$.outerscroller.addEventListener('scroll', function() {
> ```

Removing this changes the test logic quite a bit. Are you sure it's still testing the right thing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by limonte** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-table-header-footer.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cRaFCIHxE69tEbl81:-K_cVZL8_uAmhDktj6Kf:bx90x19) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/vaadin-grid-table-header-footer.html#L13)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this necessary? It makes the grid re-render everything on each re-attach (slow operation). Like for example when the grid is moved in the DOM.
</blockquote></details>

Good point. The reason of adding `isAttached` is that Firefox firing this observer **before** the grid is attached. In that case`row.target = this.domHost.domHost;` will cause the exception as `this.domHost` is `null`.

---

*[test/.eslintrc.json, line 37 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cSBuhEbfMcnqo8qgY:-K_cWnpBdB95YvpB_5RT:bj3fgqu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/.eslintrc.json#L37)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Can't we just use:
```
"no-undef": 0,
"no-unused-vars": 0
```
for tests? Enumerating each global variable in a separate file is nasty.
</blockquote></details>

Enumerating each global variable is the lesser evil. Disabling `no-unused-vars` could be very tricky and will not save a developer from hard-to-find typos which cause build errors. Simple example: you defined `comboBox` and then trying to use `combobox`. Without `no-unused-vars` you should worry about  such cases manually and debug the code (sometimes a lot) to find them.

---

*[test/light-dom-observing.html, line 494 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cS_uP65Pgdx9mU5Vo:-K_cXdVwm0jjvGo_vpk2:bgfa4tn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/light-dom-observing.html#L494)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Pretty sure we don't need to test this :)
</blockquote></details>

Oops, removed :)

---

*[test/outer-scroller.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cShApMQZ-8Snsv2TS:-K_cXjYUBa2TcmcvOiCG:b-nato5z) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/outer-scroller.html#L181)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

For me this is passing even with FF
</blockquote></details>

This issue is blinking and it's passing in 50% cases, I believe it's up to Firefox so I disabled it temporary.

---

*[test/row-height.html, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cT6n0C1QAESzAa5y_:-K_cYEP99-82ZnL3IKHd:b14nrlm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/row-height.html#L259)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Removing this changes the test logic quite a bit. Are you sure it's still testing the right thing?
</blockquote></details>

The reason of deleting this handler was that Firefox for some reason catches `scroll` event more than once, and so `done()` is called more than once and throws the exception. I think the test logic remains the same after deleting this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-grid-table-header-footer.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cRaFCIHxE69tEbl81:-K_c_9TS4hhP70DhSpU9:b7gcuwg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/vaadin-grid-table-header-footer.html#L13)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Good point. The reason of adding `isAttached` is that Firefox firing this observer **before** the grid is attached. In that case`row.target = this.domHost.domHost;` will cause the exception as `this.domHost` is `null`.
</blockquote></details>

`this.domHost.domHost` refers to grid I guess. Would be cleaner to pass the reference here instead of using domHost.domHost...then we wouldn't need to worry about the reattach issue

---

*[test/outer-scroller.html, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_c_qRAIzCg5BRYvwu1:-K_c_qRAIzCg5BRYvwu2:b8s1op8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L170)):*
> ```HTML
>         });
> 
>         it('should not passtrough iff scrollbars exist (vertical scrollbar hover)', function(done) {
> ```

"iff" was here on purpose

---

*[test/outer-scroller.html, line 178 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cZBe0OkaRzuUDGO-G:-K_cZBe0OkaRzuUDGO-H:b8s1op8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L178)):*
> ```HTML
>         });
> 
>         it('should not passtrough iff scrollbars exist (horizontal scrollbar hover)', function(done) {
> ```

"iff" was here on purpose

---

*[test/outer-scroller.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cShApMQZ-8Snsv2TS:-K_cZeGZQhTaFVlq2t6h:b-nnvdyi) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/outer-scroller.html#L181)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

This issue is blinking and it's passing in 50% cases, I believe it's up to Firefox so I disabled it temporary.
</blockquote></details>

Maybe we should examine this more. Perhaps async would help?

---

*[test/row-height.html, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cT6n0C1QAESzAa5y_:-K_cZQq1OIbWttQWKeYW:b-a9e1h9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/row-height.html#L259)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

The reason of deleting this handler was that Firefox for some reason catches `scroll` event more than once, and so `done()` is called more than once and throws the exception. I think the test logic remains the same after deleting this.
</blockquote></details>

You can define the listener as a variable and remove it when it's hit the first time

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by limonte** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions.

---

*[test/outer-scroller.html, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_c_qRAIzCg5BRYvwu1:-K_caE0WOboLILmb4pP3:bkmzsx4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L170)):*
> iff

What does "iff" mean?

---

*[test/outer-scroller.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cShApMQZ-8Snsv2TS:-K_caLAtQ18ssnlpIiwA:b7iunrs) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/outer-scroller.html#L181)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Maybe we should examine this more. Perhaps async would help?
</blockquote></details>

Nope. That weird bug with horizontal scrollbar when `scrollWindth` > `clientWidth` is the reason. Sometimes it's visible, sometimes not. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
*[test/outer-scroller.html, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_c_qRAIzCg5BRYvwu1:-K_cbJgTK_zJnq5Q719b:b-frip4e) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L170)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

> iff

What does "iff" mean?
</blockquote></details>

https://en.wikipedia.org/wiki/If_and_only_if

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-header-footer.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cRaFCIHxE69tEbl81:-K_cfr1xgCgUfYpx2GkC:b5oqkdi) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/vaadin-grid-table-header-footer.html#L13)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`this.domHost.domHost` refers to grid I guess. Would be cleaner to pass the reference here instead of using domHost.domHost...then we wouldn't need to worry about the reattach issue
</blockquote></details>

If that gets too tricky we could set `row.target = this.domHost.domHost;` to each row (in `this._rows`) in a separate function that depends on `isAttached`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by Saulis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-table-header-footer.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cRaFCIHxE69tEbl81:-K_clf9qtotFG53tNBBu:bexdby) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/vaadin-grid-table-header-footer.html#L13)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

If that gets too tricky we could set `row.target = this.domHost.domHost;` to each row (in `this._rows`) in a separate function that depends on `isAttached`
</blockquote></details>

Good point Tomi – I actually suggested to add `isAttached` but didn't consider the case when the whole grid would be moved or re-attached. I think the most straight-forward solution would be to add `target` property this element which gets bound to the grid element.

---

*[test/outer-scroller.html, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_c_qRAIzCg5BRYvwu1:-K_cmGRJuvAbSlUJpYJc:b-v8ctgu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L170)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

https://en.wikipedia.org/wiki/If_and_only_if
</blockquote></details>

Maybe it would be a good idea to spell the term out in the description :-) I would've also thought its a typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
*[test/outer-scroller.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cShApMQZ-8Snsv2TS:-K_d3XterrJohk2fz_vU:b-5rhgs4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/outer-scroller.html#L181)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

Nope. That weird bug with horizontal scrollbar when `scrollWindth` > `clientWidth` is the reason. Sometimes it's visible, sometimes not. 
</blockquote></details>

Hmm..just installed FF 50 and this test passes 100% of times I tried (without the FF check of course).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
*[test/row-height.html, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cT6n0C1QAESzAa5y_:-K_d4xTh40IBNGw8waeu:bt4royw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/row-height.html#L259)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

You can define the listener as a variable and remove it when it's hit the first time
</blockquote></details>

Actually, this test passes every time for me even without the changes. The proposed changes do affect test logic since the resizing should occur only after the scrollTop is set to 100.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
*[test/row-height.html, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cT6n0C1QAESzAa5y_:-K_dCdF6ej5ykrK01YcL:b-xgp3vu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/row-height.html#L259)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Actually, this test passes every time for me even without the changes. The proposed changes do affect test logic since the resizing should occur only after the scrollTop is set to 100.
</blockquote></details>

Ah, ignore my previous comment (brainfart). The test is passing but as you said done() is called multiple times. This can be fixed as I instructed in the comment before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by limonte** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-table-header-footer.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cRaFCIHxE69tEbl81:-K_dCruGwTm8_UWnR-2y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/vaadin-grid-table-header-footer.html#L13)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Good point Tomi – I actually suggested to add `isAttached` but didn't consider the case when the whole grid would be moved or re-attached. I think the most straight-forward solution would be to add `target` property this element which gets bound to the grid element.
</blockquote></details>

Done.

---

*[test/outer-scroller.html, line 170 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_c_qRAIzCg5BRYvwu1:-K_dUHWznOFnkeUL_d9r:bffb0os) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L170)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Maybe it would be a good idea to spell the term out in the description :-) I would've also thought its a typo
</blockquote></details>

`iff` is replaced by `if and only if`

---

*[test/outer-scroller.html, line 181 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cShApMQZ-8Snsv2TS:-K_dQIoQDsi9_48neQ8F:b56vck8) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ea15b5c4392c86e14262464e03166b5c72b4a527/test/outer-scroller.html#L181)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Hmm..just installed FF 50 and this test passes 100% of times I tried (without the FF check of course).
</blockquote></details>

I can reproduce this in Firefox/Linux and it's reproducible in Travis also, so let's wait for the Firefox update :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by limonte** [comment]
Review status: 0 of 11 files reviewed at latest revision, 5 unresolved discussions.

---

*[test/outer-scroller.html, line 178 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cZBe0OkaRzuUDGO-G:-K_dYC6rE04BiMLYIBSO:bffb0os) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/outer-scroller.html#L178)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"iff" was here on purpose
</blockquote></details>

`iff` is replaced by `if and only if`

---

*[test/row-height.html, line 259 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-K_cT6n0C1QAESzAa5y_:-K_dY8lYNiigVMEczSIj:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/53f48b4591a6266d531bb27f2c4606165621dc83/test/row-height.html#L259)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Ah, ignore my previous comment (brainfart). The test is passing but as you said done() is called multiple times. This can be fixed as I instructed in the comment before.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/637#-:-K_dZA818YRcInzPMjFA:bnfp4nl)*

**Pull request merged**
