### PR TITLE
Fix row details demos

### LINKED ISSUE #1089: Buggy inconsistent behavior for row details in Firefox
Sometimes when I click 'Show Details' row jumps and covers a preceding row:

recorded

Firefox/Linux

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1089

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1144)

### CODE REVIEW

**Comment by web-padawan** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[demo/grid-row-details-demos.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1144#-L-GR30u1KG0vyTr-qXf:-L-GR30u1KG0vyTr-qXg:b-494p14) ([raw file](https://github.com/vaadin/vaadin-grid/blob/7f53871c7b4d18c7581e5856fd98d2d772e1ccde/demo/grid-row-details-demos.html#L22)):*
> ```HTML
>         <dom-bind>
>           <template>
> ```

nit: please also align indentation of `<style>` tag below

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1144)*

**Comment by tomivirkki** [comment]
*[demo/grid-row-details-demos.html, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1144#-L-GR30u1KG0vyTr-qXf:-L-GSABmBbfJOt8itD34:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/7f53871c7b4d18c7581e5856fd98d2d772e1ccde/demo/grid-row-details-demos.html#L22)):*
<details><summary><i>Previously, web-padawan (Sergey Kulikov) wrote…</i></summary><blockquote>

nit: please also align indentation of `<style>` tag below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1144)*

**Comment by limonte** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1144#-:-L-GSI-WjM208xnWjYX_:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1144#-:-L-GU4gX7yMoi4lXxWKI:bnfp4nl)*

**Pull request merged**
