### PR TITLE
Warn about missing imports

### LINKED ISSUE #752: Add console warnings for missing imports
If the following exist in the light DOM, check whether they are upgraded:
- `<vaadin-grid-column-group>`
- `<vaadin-grid-sorter>`
- `<vaadin-grid-filter>`
- `<vaadin-grid-selection-column>`

You might want to wait a couple of seconds after grid is attached to do the check to give time for the async imports to finish.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #752

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/765)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeImtMPwaV77UNfjkJK:-KeImtMPwaV77UNfjkJL:b-9ys0y3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L241)):*
> ```HTML
>         'vaadin-grid-filter',
>         'vaadin-grid-selection-column'
>       ].forEach(function(elementName) {
> ```

Probably you could use `querySelectorAll('vaadin-grid-column-group, vaadin-grid-sorter, ...') instead

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeImtMPwaV77UNfjkJK:-KeInI1LCpwVeJyaLpEE:b-t0kvg4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L241)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Probably you could use `querySelectorAll('vaadin-grid-column-group, vaadin-grid-sorter, ...') instead
</blockquote></details>

Sure, but it wouldn't be any cleaner IMO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid.html, line 235 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeInILf65JXjKA7B1Tc:-KeInILf65JXjKA7B1Td:b5ihnbu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L235)):*
> ```HTML
>     },
> 
>     _checkImports: function() {
> ```

This has to be checked when the group tree structure changes dynamically also

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeImtMPwaV77UNfjkJK:-KeInaNopa5FavB_FzZi:b77vcab) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L241)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Sure, but it wouldn't be any cleaner IMO.
</blockquote></details>

But you #useThePlatform for selecting all components at once, instead of transversing the dom multiple times.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeImtMPwaV77UNfjkJK:-KeIntirPIq4oaCjj8rn:brd7617) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L241)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

But you #useThePlatform for selecting all components at once, instead of transversing the dom multiple times.
</blockquote></details>

How is querySelector not #usingThePlatform? This is a very rare operation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vaadin-grid.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeImtMPwaV77UNfjkJK:-KeIoEK7-dt86dpc3qXW:b-d2dkgn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L241)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

How is querySelector not #usingThePlatform? This is a very rare operation.
</blockquote></details>

I meant, you are using your own JS for visiting all possible element names and then query the dom once per element, otherwise you could use the selector-all API just once taking advantage of the CSS selector syntax

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid.html, line 235 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeInILf65JXjKA7B1Tc:-KeJAsA-41WOBCEGk5co:bfbq99i) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L235)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This has to be checked when the group tree structure changes dynamically also
</blockquote></details>

Good point, done.

---

*[vaadin-grid.html, line 241 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-KeImtMPwaV77UNfjkJK:-KeJAujUO_PH_RNCnuzb:bx250rn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/52374124ada484133634531007a08ea1f727460c/vaadin-grid.html#L241)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I meant, you are using your own JS for visiting all possible element names and then query the dom once per element, otherwise you could use the selector-all API just once taking advantage of the CSS selector syntax
</blockquote></details>

We agreed to leave this as it was. Fixes an issue with the selector though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765)*

**Comment by manolo** [comment]
Fix the build and :lgtm: 

---

Reviewed 1 of 2 files at r1, 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-:-KeJHz5dixn95JS-r7Tp:b-i6oeg6)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/765#-:-KeJY-4s94u7Apj8Oui2:bnfp4nl)*

**Pull request merged**
