### PR TITLE
Improve wheel behavior

### LINKED ISSUE #574: Improve scroll behavior
After #442 (“scroll trap”) was fixed, the behavior of native `overflow: auto;` elements is not really that great for the use case of our data grid.

We might want to only allow the wheel/scroll events to pass the grid after a certain timeout after we’ve reached the end of the scrolling region. So basically, if the user is close to the end of the grid, and does one long and fast swipe, the grid should scroll to the bottom, but the page should not scroll from that gesture yet. Only after about 200ms after the bottom of the grid is reached, should the next swipe scroll the whole page.

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #574

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/579)

### CODE REVIEW

**Comment by manolo** [comment]
The same issue is still appreciable in touch devices. Do we want to target them ?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/579#-:-KZLorp0ijlcgQngfEEh:b4f6mrc)*

**Comment by tomivirkki** [comment]
There's https://github.com/vaadin/vaadin-grid/issues/575 already. This PR is only about the wheel behavior.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/579#-:-KZLpFyKB2VZ-EG8CFfj:bqwcj6l)*

**Comment by manolo** [comment]
Yep, that is the touch issue. It's better to do in a separated PR.

:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/579#-:-KZLpnvOLiw5dbHr9l1m:bfc44qn)*

**Comment by manolo** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/579)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/579#-:-KZQNxDWu1K9Merbs-BZ:bnfp4nl)*

**Pull request merged**
