### PR TITLE
Fix/sorter themable

### LINKED ISSUE #999: vaadin-grid-sorter should extend ThemableMixin
Currently it‘s not possible to theme the sort indicator.

Version 4.0.0-alpha1

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #999

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1009)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-sorter.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyAWHMrp6SKjH8LVvB:-KuyAWHMrp6SKjH8LVvC:b9y8g77) ([raw file](https://github.com/vaadin/vaadin-grid/blob/46ba02c2a9bdb3c1208898514cdad7efdbcac6f4/vaadin-grid-sorter.html#L49)):*
> ```HTML
>       :host(:not([direction])) [part="indicators"]::before {
>         content: "\e901";
>         opacity: 0.2;
> ```

Should we introduce a default theme as well?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by platosha** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-sorter.html, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyBBuwFXdYF357LQKq:-KuyBBuwFXdYF357LQKr:b-z1hcj3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/47283786335dd174d614a1b447cc3036c9237ad9/vaadin-grid-sorter.html#L23)):*
> ```HTML
>     <style>
>       :host {
>         cursor: pointer;
> ```

OK maybe cursor is a builtin style? The entire element is clickable.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-sorter.html, line 49 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyAWHMrp6SKjH8LVvB:-KuyB_1-eP0x1sgGWQP0:bjlygxt) ([raw file](https://github.com/vaadin/vaadin-grid/blob/46ba02c2a9bdb3c1208898514cdad7efdbcac6f4/vaadin-grid-sorter.html#L49)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should we introduce a default theme as well?
</blockquote></details>

Yep, that was failing the tests. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-sorter.html, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyBBuwFXdYF357LQKq:-KuyBsqUMHnOeLR4vqdJ:b-dakwzi) ([raw file](https://github.com/vaadin/vaadin-grid/blob/47283786335dd174d614a1b447cc3036c9237ad9/vaadin-grid-sorter.html#L23)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK maybe cursor is a builtin style? The entire element is clickable.
</blockquote></details>

For example in pw-field it's in default-theme https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-password-field.html#L24

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by platosha** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-sorter.html, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyBBuwFXdYF357LQKq:-KuyC5noc0lJ-_h4Ik4F:b-h087ww) ([raw file](https://github.com/vaadin/vaadin-grid/blob/47283786335dd174d614a1b447cc3036c9237ad9/vaadin-grid-sorter.html#L23)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

For example in pw-field it's in default-theme https://github.com/vaadin/vaadin-text-field/blob/master/vaadin-password-field.html#L24
</blockquote></details>

That thing in pw-field is invisible without a theme. The host is visible here though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-sorter.html, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyBBuwFXdYF357LQKq:-KuyDWNTJkrPEDd7w-Gh:bbtjfhb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/47283786335dd174d614a1b447cc3036c9237ad9/vaadin-grid-sorter.html#L23)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

That thing in pw-field is invisible without a theme. The host is visible here though.
</blockquote></details>

Some more examples from combo-box: https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box-styles.html#L23 and https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box-styles.html#L33

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-sorter.html, line 23 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-KuyBBuwFXdYF357LQKq:-KuyECGovQfoMevFtc5Y:b2w7dfo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/47283786335dd174d614a1b447cc3036c9237ad9/vaadin-grid-sorter.html#L23)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Some more examples from combo-box: https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box-styles.html#L23 and https://github.com/vaadin/vaadin-combo-box/blob/master/vaadin-combo-box-styles.html#L33
</blockquote></details>

Maybe it makes more sense in this case, moved to default styles

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009#-:-KuyERNJiuYKT_1gwapY:bnfp4nl)*

**Comment by platosha** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1009)*

**Pull request merged**
