### PR TITLE
Add warnings about invalid path for filters/sorters

### LINKED ISSUE #566: Inconsistent item paths between templates and filter + sorter helpers
Users might easily end up accidentally prefixing the `path` with `item`, since it's used like that in the templates. The following snippet is from an actual user.

```html
<vaadin-grid-column>
  <template class="header">
    <vaadin-grid-sorter path="item.id">
      Id
    </vaadin-grid-sorter>
  </template>
  <template>[[item.id]]</template>
</vaadin-grid-column>
```

I'm proposing we prefix the `path` with item, so it becomes more apparent that the property is related with the item.

```html
<vaadin-grid-column>
  <template class="header">
    <vaadin-grid-sorter item-path="id">
      Id
    </vaadin-grid-sorter>
  </template>
  <template>[[item.id]]</template>
</vaadin-grid-column>
```

### PR DESCRIPTION
**Pull request by limonte**
Fixes #566

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/781)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vaadin-grid-array-data-provider-behavior.html, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KecP-RFiXaUQaEFtnC8:-KecP-RFiXaUQaEFtnC9:bmu6pjk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/vaadin-grid-array-data-provider-behavior.html#L66)):*
> ```HTML
> 
>         if (typeof Polymer.Base.get(path, items[0]) === 'undefined') {
>           console.warn('Path "' + path + '" seems to be invalid, skipping it');
> ```

I think the warning could be more explicit: "Path 'xx.xx' used for filtering/sorting does not exist in all of the items. Filtering/sorting is disabled." 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-array-data-provider-behavior.html, line 65 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KecVHeOQXuarq6rTtzf:-KecVHeOQXuarq6rTtzg:bz96ies) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/vaadin-grid-array-data-provider-behavior.html#L65)):*
> ```HTML
>         }
> 
>         if (typeof Polymer.Base.get(path, items[0]) === 'undefined') {
> ```

Undefined is an acceptable value so we don't want to warn about/skip that.

Only warn if a parent property value of the last property is undefined. For example when path is`foo.bar.baz`, we want a warning only if an item's `foo.bar` is undefined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by tomivirkki** [comment]
Review status: 0 of 12 files reviewed at latest revision, 4 unresolved discussions, some commit checks broke.

---

*[test/array-data-provider.html, line 175 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-Kec_Ukg7EhgAAvwV2ST:-Kec_Ukg7EhgAAvwV2SU:b-fnhgqb) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/test/array-data-provider.html#L175)):*
> ```HTML
>           var spy = console.warn = sinon.spy();
> 
>           invalidPaths.withDots.addEventListener('sorter-changed', function() {
> ```

No need for the test to be asynchronous. You can run the assertion right after `click` is called.

The filter tests can also be made synchronous by flushing the filter's 'filter-changed' debouncer right after setting its value.

---

*[test/array-data-provider.html, line 178 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KecYF0I6IkhTaRbk1gW:-KecYF0J-QsosuktjFHK:b-kje16k) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/test/array-data-provider.html#L178)):*
> ```HTML
>             Polymer.Base.async(function() {
>               expect(spy.called).to.be.true;
>               console.warn = _warn;
> ```

This line should be above the `expect` line. If the assertion fails, this line is never reached and console.warn will be left with the spy.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by tomivirkki** [comment]
*[test/array-data-provider.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KechUMWMNS4xcmI9i4T:-KechUMWMNS4xcmI9i4U:b-ma1750) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/test/array-data-provider.html#L35)):*
> ```HTML
>         </vaadin-grid-column>
> 
>         <vaadin-grid-column>
> ```

Instead of adding all these columns to an existing fixture, prefer creating new ones since the existing tests don't really have anything to do with sorters and filters.

I'd personally add a fixture with just one column, inside of which would be just one sorter. You can then in the beginning of your test case modify the `path` value of that sorter:
```
sorter.path = 'foo.bar';
click(sorter);
expect(spy.called).to.be.true;
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by limonte** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[vaadin-grid-array-data-provider-behavior.html, line 65 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KecVHeOQXuarq6rTtzf:-KehledMRa9IYn0EysWC:b-dtkds3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/vaadin-grid-array-data-provider-behavior.html#L65)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Undefined is an acceptable value so we don't want to warn about/skip that.

Only warn if a parent property value of the last property is undefined. For example when path is`foo.bar.baz`, we want a warning only if an item's `foo.bar` is undefined.
</blockquote></details>

Done, thanks!

---

*[vaadin-grid-array-data-provider-behavior.html, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KecP-RFiXaUQaEFtnC8:-KehlhhJMOlMDL_lb7Sg:b-dtkds3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/vaadin-grid-array-data-provider-behavior.html#L66)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I think the warning could be more explicit: "Path 'xx.xx' used for filtering/sorting does not exist in all of the items. Filtering/sorting is disabled." 
</blockquote></details>

Done, thanks!

---

*[test/array-data-provider.html, line 35 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KechUMWMNS4xcmI9i4T:-Kehll_60PF-Ig7tIrOz:b-dtkds3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/test/array-data-provider.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Instead of adding all these columns to an existing fixture, prefer creating new ones since the existing tests don't really have anything to do with sorters and filters.

I'd personally add a fixture with just one column, inside of which would be just one sorter. You can then in the beginning of your test case modify the `path` value of that sorter:
```
sorter.path = 'foo.bar';
click(sorter);
expect(spy.called).to.be.true;
```
</blockquote></details>

Done, thanks!

---

*[test/array-data-provider.html, line 175 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-Kec_Ukg7EhgAAvwV2ST:-KehluoU4w-JwUnWvSZ7:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/test/array-data-provider.html#L175)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No need for the test to be asynchronous. You can run the assertion right after `click` is called.

The filter tests can also be made synchronous by flushing the filter's 'filter-changed' debouncer right after setting its value.
</blockquote></details>

Done.

---

*[test/array-data-provider.html, line 178 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KecYF0I6IkhTaRbk1gW:-KehlwbgV5ZEqzJO4QXp:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9a8e9dd7425618f49c560a5e41be6ab14f5aa3fe/test/array-data-provider.html#L178)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This line should be above the `expect` line. If the assertion fails, this line is never reached and console.warn will be left with the spy.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by tomivirkki** [comment]
Review status: 0 of 15 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-array-data-provider-behavior.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-Kehv-wE-TXY7EBJAa4e:-Kehv-wE-TXY7EBJAa4f:b-3kflm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/vaadin-grid-array-data-provider-behavior.html#L34)):*
> ```HTML
>       var items = (this.items || []).slice(0);
> 
>       this.size = items.length;
> ```

Changing the size has lots of side-effects in the grid, rather not change it twice on every data request.

---

*[vaadin-grid-array-data-provider-behavior.html, line 35 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KehvcPIVAKTEEh9RrRH:-KehvcPIVAKTEEh9RrRI:b3sky2c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/vaadin-grid-array-data-provider-behavior.html#L35)):*
> ```HTML
> 
>       this.size = items.length;
>       if (this.size) {
> ```

Why must the size be checked here? All the tests pass without it

---

*[vaadin-grid-array-data-provider-behavior.html, line 36 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KehvQS8RZHonpKRhJ3h:-KehvQS964kCgJTLMGO3:b-6i09ge) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/vaadin-grid-array-data-provider-behavior.html#L36)):*
> ```HTML
>       this.size = items.length;
>       if (this.size) {
>         // filtering
> ```

No need for these comments. The code is quite self-explanatory.

---

*[test/array-data-provider.html, line 163 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KehwQoAv4K3tuk2B-47:-KehwQoAv4K3tuk2B-48:bbn9uxj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/test/array-data-provider.html#L163)):*
> ```HTML
>         });
> 
>         it('should warn about invalid path with one or more dots', function() {
> ```

Also test that warning is not shown for path "name.middle"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by limonte** [comment]
Review status: 0 of 15 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-array-data-provider-behavior.html, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-Kehv-wE-TXY7EBJAa4e:-Kei-xy0cO6gJOB-YwPc:b-dtkds3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/vaadin-grid-array-data-provider-behavior.html#L34)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Changing the size has lots of side-effects in the grid, rather not change it twice on every data request.
</blockquote></details>

Done, thanks!

---

*[vaadin-grid-array-data-provider-behavior.html, line 35 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KehvcPIVAKTEEh9RrRH:-Kei0-7yaaO6aqgGoegA:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/vaadin-grid-array-data-provider-behavior.html#L35)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why must the size be checked here? All the tests pass without it
</blockquote></details>

Done.

---

*[vaadin-grid-array-data-provider-behavior.html, line 36 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KehvQS8RZHonpKRhJ3h:-Kei0-pW7G-M51lG3J0X:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/vaadin-grid-array-data-provider-behavior.html#L36)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

No need for these comments. The code is quite self-explanatory.
</blockquote></details>

Done.

---

*[test/array-data-provider.html, line 163 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-KehwQoAv4K3tuk2B-47:-Kei04lOt6eDjPkzA2iZ:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/95da6b756853d9ce663f10a3297fed528963875e/test/array-data-provider.html#L163)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Also test that warning is not shown for path "name.middle"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 7 of 12 files at r1, 5 of 8 files at r2, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/781#-:-Kei6tlbq26EusXDvJyi:bnfp4nl)*

**Pull request merged**
