### PR TITLE
Fix polymer error when building with gulp

### LINKED ISSUE #576: Polymer build fails on 2.0 pre2
Polymer build fails to build a project that contains vaadin-grid 2.0 (using latest 0.6 version). 

Problems:

1. Missing HTML imports. Each of the following needs to import polymer or the behavior requested. The UNKNOWN refers to the Edge browser check, that doesn't work.
```
error:   In bower_components/vaadin-grid/vaadin-grid-table-cell.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.Templatizer`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/vaadin-grid-table-cell.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.Templatizer`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/vaadin-grid-table-cell.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.Templatizer`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/vaadin-grid-table-edge-behavior.html: [unknown-polymer-behavior] - Unable to resolve behavior `vaadin.elements.grid.GridTableScrollBehavior`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/iron-list-behavior.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.Templatizer`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/iron-list-behavior.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.IronResizableBehavior`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/iron-list-behavior.html: [unknown-polymer-behavior] - Unable to resolve behavior `Polymer.IronScrollTargetBehavior`. Did you import it? Is it annotated with @polymerBehavior?
error:   In bower_components/vaadin-grid/vaadin-grid-table.html: [unknown-polymer-behavior] - Unable to resolve behavior `UNKNOWN`. Did you import it? Is it annotated with @polymerBehavior?
```

2. iron-list-behavior extends a behavior incorrectly. Should be:
```

 ```/**
 * @polymerBehavior vaadin.elements.grid.IronListBehavior
 */
vaadin.elements.grid.IronListBehaviorImpl = (function() {
  // exactly the same as how you have it, except remove the behaviors property
})();

/**
 * @polymerBehavior vaadin.elements.grid.IronListBehavior
 */
vaadin.elements.grid.IronListBehavior = [
  Polymer.Templatizer,
  Polymer.IronResizableBehavior,
  Polymer.IronScrollTargetBehavior,
  vaadin.elements.grid.IronListBehaviorImpl
];
```
See: https://www.polymer-project.org/1.0/docs/devguide/behaviors#extending

3. vaadin.elements.grid.GridTableScrollBehavior in vaadin-grid-table-edge-behavior.html is not defined, should it be vaadin.elements.grid.TableScrollBehavior?

### PR DESCRIPTION
**Pull request by manolo**
fixes #576

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/578)

### CODE REVIEW

**Comment by Saulis** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578#-KZ5qjSB8iI_4AbRLkyF:-KZ5qjSB8iI_4AbRLkyG:b-pp6kuo) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4837a4969642f1d92421a99ff66bcc8ab74f1fb4/vaadin-grid-column.html#L18)):*
> ```HTML
>    * @polymerBehavior vaadin.elements.grid.vaadinGridColumnBaseBehavior
>    */
>   vaadin.elements.grid.vaadinGridColumnBaseBehavior = {
> ```

I guess we could rename these follow the same naming convention as others: `vaadin.elements.grid.ColumnBaseBehavior` etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column.html, line 18 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578#-KZ5qjSB8iI_4AbRLkyF:-KZ5vTkhWD-i12CWkzuX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/4837a4969642f1d92421a99ff66bcc8ab74f1fb4/vaadin-grid-column.html#L18)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I guess we could rename these follow the same naming convention as others: `vaadin.elements.grid.ColumnBaseBehavior` etc.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578)*

**Comment by tomivirkki** [comment]
*[iron-list-behavior.html, line 11 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578#-KZ6zfFoQrm21TKA9I2J:-KZ6zfFoQrm21TKA9I2K:b-sjogws) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ecb1629c0d7010bab4e8a95e4a43c92c3cd51ab3/iron-list-behavior.html#L11)):*
> ```HTML
> 
>   /**
>    * @polymerBehavior vaadin.elements.grid.IronListBehavior
> ```

IronListBehavior -> IronListBehaviorImpl

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578)*

**Comment by manolo** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[iron-list-behavior.html, line 11 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578#-KZ6zfFoQrm21TKA9I2J:-KZ7H6g4Y1p2DahVPEOP:b-vz3yex) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ecb1629c0d7010bab4e8a95e4a43c92c3cd51ab3/iron-list-behavior.html#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

IronListBehavior -> IronListBehaviorImpl
</blockquote></details>

Ups. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/578#-:-KZL0Vw-FAM-JdHwiNi8:bnfp4nl)*

**Pull request merged**
