### PR TITLE
Feature/2.0 column reordering

### PR DESCRIPTION
**Pull request by tomivirkki**
Connects to #660 

Note to reviewers: This PR is mostly about the implementation for now. @Jouni will consider if the feature still needs a visual facelift or not.

Will create a second PR connected to the same ticket to fix the styles and expose style mixins/variables based on the decision.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/667)

### CODE REVIEW

**Comment by Saulis** [comment]
Reviewed 1 of 13 files at r1.
Review status: 1 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column-reordering-behavior.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbFBTICir88PgQKGe6-:-KbFBTIDAaKUoqmOG7wE:bu682g4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-column-reordering-behavior.html#L84)):*
> ```HTML
> 
>     _onDragStart: function(e) {
>       var cell = this._getCellByCellContent(e.target);
> ```

Is there a reason why we don't set the cell itself draggable instead of the cell-content? 

---

*[vaadin-grid-column.html, line 363 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbFCpZBYGmTGi9zoWmI:-KbFCpZBYGmTGi9zoWmJ:b-agsika) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-column.html#L363)):*
> ```HTML
>     _orderChanged: function(order, rootColumns) {
>       if (order) {
>         var trailingZeros = /(0+)$/.exec(order).pop().length;
> ```

This is pretty high-order math right here :-) could maybe benefit from a small comment block with a simple example what kind of numbers are being returned.

---

*[vaadin-grid-table-cell.html, line 232 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbElnfVqopsxzNfAYVb:-KbElnfVqopsxzNfAYVc:bli02il) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-table-cell.html#L232)):*
> ```HTML
>         'mouseout': '_disableDrag'
>       },
> ```

Maybe a comment here stating we are enabling and disabling the dragging on the fly to enable selecting text on the headers.

---

*[vaadin-grid-table-row.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbEmEfTaULjnc3MKME7:-KbEmEfTaULjnc3MKME8:b7k1k4q) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-table-row.html#L79)):*
> ```HTML
>           rowDetailsCell.target = target;
>           rowDetailsCell.template = rowDetailsTemplate;
>           rowDetailsCell.toggleAttribute('lastcolumn', true);
> ```

I guess we should apply `order` to `rowDetailsCell` somewhere also to make sure it stays last always?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by manolo** [comment]
A couple of observations:

- when dragging the column header it would be ideal to restrict the draggable area and not move out of the grid area.  Not sure that it could be done though.
- if the scroll is not at the top, moving the dragged element up moves the grid position, probably it's possible to prevent that

---

Review status: 1 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-:-KbFTC2H63STAq5nAjwh:b-r29j9g)*

**Comment by tomivirkki** [comment]
> when dragging the column header it would be ideal to restrict the draggable area and not move out of the grid area.  Not sure that it could be done though.

I don't think the spec allows that. However, this is doable once we switch to using our own implementation instead of HTML5 d&d (this is being discussed)

> if the scroll is not at the top, moving the dragged element up moves the grid position, probably it's possible to prevent that

This is a built-in feature in Chrome, Opera and IE. I haven't found a way to disable that. Some sources suggest canceling `mousedown` event but that will also disable d&d

---

Review status: 0 of 13 files reviewed at latest revision, 4 unresolved discussions.

---

*[vaadin-grid-column-reordering-behavior.html, line 84 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbFBTICir88PgQKGe6-:-KbFDHdv_CF6FB-zm7lH:b-3ldc4s) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-column-reordering-behavior.html#L84)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Is there a reason why we don't set the cell itself draggable instead of the cell-content? 
</blockquote></details>

Setting the cell draggable doesn't work with native shadow enabled

---

*[vaadin-grid-column.html, line 363 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbFCpZBYGmTGi9zoWmI:-KbF_GByPXUWe_JDh06E:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-column.html#L363)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This is pretty high-order math right here :-) could maybe benefit from a small comment block with a simple example what kind of numbers are being returned.
</blockquote></details>

Done.

---

*[vaadin-grid-table-cell.html, line 232 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbElnfVqopsxzNfAYVb:-KbFDWukRp3d6BWKFP1S:byx6j4a) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-table-cell.html#L232)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Maybe a comment here stating we are enabling and disabling the dragging on the fly to enable selecting text on the headers.
</blockquote></details>

Well...that's not the only reason for doing this on the fly. This is also less verbose and error prone than adding the attribute on grid-level property change. The `window.getSelection().toString()` could use a comment though. Done.

---

*[vaadin-grid-table-row.html, line 79 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbEmEfTaULjnc3MKME7:-KbFDo6Jtlhi2TPhPf5e:b-o48sim) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a87e28994c439fff99df57f206b65915426ddd8f/vaadin-grid-table-row.html#L79)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I guess we should apply `order` to `rowDetailsCell` somewhere also to make sure it stays last always?
</blockquote></details>

The `rowDetailsCell` has `position: absolute` so it's out of the flexbox' flow

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-:-KbFaml6qqCmzZ3ty6Nd:b-sqml8y)*

**Comment by manolo** [comment]
> This is a built-in feature in Chrome, Opera and IE. I haven't found a way to disable that. 

Gotcha. I'm wondering why that feature only works with scroll up, because it does not scroll the grid down. Anyway it's not a blocker for this PR. Let's see if it is a problem in UX, probably not.

---

Review status: 0 of 13 files reviewed at latest revision, 14 unresolved discussions.

---

*[vaadin-grid-column-reordering-behavior.html, line 73 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJYIdRNN2DGjZkMW5d:-KbJYIdSUs90udFNdZhK:b-t9an89) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column-reordering-behavior.html#L73)):*
> ```HTML
> 
>     observers: [
>       '_updateOrders(columnTree, columnTree.*)',
> ```

Shouldn't be enough to observe `columnTree.*` it should call the method when the columnTree is assigned. Unless you want to use the `columnTree` parameter in the method instead of `this.columnTree`

---

*[vaadin-grid-column-reordering-behavior.html, line 101 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJbCBLq3oaysUclx47:-KbJZIXRISgN1nQnbgpt:b-ls1aa0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column-reordering-behavior.html#L101)):*
> ```HTML
>     _setSiblingsReorderStatus: function(column, status) {
>       Polymer.dom(Polymer.dom(column).parentNode).children.filter(function(child) {
>         return /COLUMN/.test(child.tagName) && this._isSwapAllowed(child, column);
> ```

Nit: We are using more frequently `localName` instead of `tagName`.  I would use always the same property

---

*[vaadin-grid-column-reordering-behavior.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJcowr0ambBMqQWthO:-KbJcowr0ambBMqQWthP:bvp9o5j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column-reordering-behavior.html#L114)):*
> ```HTML
>       if (targetColumn &&
>         this._isSwapAllowed(this._draggedColumn, targetColumn) &&
>         this._isSwappableByPosition(targetColumn, e.clientX)) {
> ```

It would be nice if the columns does not swap until the drag position is at least the half of the target column. That is the behaviour of mac finder and seems a good UX.
In this implementation if the mouse drags the source very closed to the left edge of the column and move left column it swaps very quick, otherwise moving right it takes a long to happen.

---

*[vaadin-grid-column.html, line 367 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJf7vwMQ3Zd0HyrmQZ:-KbJf7vwMQ3Zd0HyrmQ_:b-kooplc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column.html#L367)):*
> ```HTML
>         // [             1000              ]
>         // [     1100    ] | [     1200    ]
>         // [1110] | [1120] | [1210] | [1220]
> ```

What happens if a group have more than 10 children ? 

---

*[vaadin-grid-column.html, line 437 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJfIwkRksqQ4_GX_rz:-KbJfIwkRksqQ4_GX_s-:b28p0vm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column.html#L437)):*
> ```HTML
>       this._observer = Polymer.dom(this).observeNodes(function(info) {
>         this._rootColumns = Polymer.dom(this).children.filter(function(child) {
>           return /COLUMN/.test(child.tagName);
> ```

if possible, use localName here as well

---

*[vaadin-grid-table-row.html, line 172 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJha7Fz2ItUcrkd-pM:-KbJha7Fz2ItUcrkd-pN:bkdn6gw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-row.html#L172)):*
> ```HTML
> 
>       updateLastColumn: function() {
>         this.cells.slice(0).sort(function(a, b) {
> ```

you are ordering ascending, so `this.cells.slice(0).sort().forEach()` should work out-of-the-box without any function.

---

*[vaadin-grid-table-row.html, line 173 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJhu0IB8qHEbZblL9C:-KbJhu0IB8qHEbZblL9D:b-dqqcpf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-row.html#L173)):*
> ```HTML
>       updateLastColumn: function() {
>         this.cells.slice(0).sort(function(a, b) {
>           return a.column._order < b.column._order ? -1 : 1;
> ```

Otherwise this could be simplified to `return a.column._order - b.column._order;`

---

*[vaadin-grid-table-scroll-behavior.html, line 373 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJiKtKKN-FetIzmZGo:-KbJiKtKKN-FetIzmZGp:b5xpf7m) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-scroll-behavior.html#L373)):*
> ```HTML
>     _updateLastFrozen: function() {
>       var columnsRow = this.columnTree[this.columnTree.length - 1].slice(0);
>       columnsRow.sort(function(a, b) {
> ```

as before, just use `.sort()`

---

*[demo/columns.html, line 120 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJitmMtGZuzgltnGwG:-KbJitmNydc3dkJg1Uzg:b-rirbjn) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/demo/columns.html#L120)):*
> ```HTML
>     </demo-snippet>
> 
>     <h3>Reordering Columns</h3>
> ```

I feel like interesting to have a group sorting demo, so as users can visually figure out  how it behaves.
I had to add the `column-reordering-allowed` to the groups template demo to experiment with the feature.

---

*[docs/vaadin-grid-configuring-columns.adoc, line 149 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJjJwxBens1pH89sYK:-KbJjJwxBens1pH89sYL:bla33kq) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/docs/vaadin-grid-configuring-columns.adoc#L149)):*
> ```AsciiDoc
> Switch on the [vaadinelement]#vaadin-grid#'s [propertyname]#column-reordering-allowed# flag to make the visible columns reorderable.
> 
> When column reordering is allowed, the user can drag and drop columns by their header cells to change their visual order.
> ```

Please, can you add a note with grouping constrains ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-:-KbJWUoeWLFOovgaIzJM:b-h3oyx6)*

**Comment by manolo** [comment]
Reviewed 8 of 13 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by tomivirkki** [comment]
Review status: 7 of 13 files reviewed at latest revision, 14 unresolved discussions.

---

*[vaadin-grid-column-reordering-behavior.html, line 73 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJYIdRNN2DGjZkMW5d:-KbJjq13dmuLcqmnV6ek:bfof6wg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column-reordering-behavior.html#L73)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Shouldn't be enough to observe `columnTree.*` it should call the method when the columnTree is assigned. Unless you want to use the `columnTree` parameter in the method instead of `this.columnTree`
</blockquote></details>

That's exactly the reason, we want to list all the dependencies and use the parameters directly

---

*[vaadin-grid-column-reordering-behavior.html, line 101 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJbCBLq3oaysUclx47:-KbK6JERjWFr_RKJsHCy:bddeb6a) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column-reordering-behavior.html#L101)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Nit: We are using more frequently `localName` instead of `tagName`.  I would use always the same property
</blockquote></details>

localName has a history of being inconsistent between browsers. I guess it's ok to use it nowadays. Done.

---

*[vaadin-grid-column-reordering-behavior.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJcowr0ambBMqQWthO:-KbJki7NCHSBlGxYSv6R:b-6eznu2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column-reordering-behavior.html#L114)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It would be nice if the columns does not swap until the drag position is at least the half of the target column. That is the behaviour of mac finder and seems a good UX.
In this implementation if the mouse drags the source very closed to the left edge of the column and move left column it swaps very quick, otherwise moving right it takes a long to happen.

</blockquote></details>

We discussed this with @jouni yesterday. Going with this UX for the first version.

---

*[vaadin-grid-column.html, line 367 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJf7vwMQ3Zd0HyrmQZ:-KbJkxVtpjDjaoh-7P2V:b-t07w7r) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column.html#L367)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

What happens if a group have more than 10 children ? 
</blockquote></details>

See couple of lines below. It's covered by the `childCountDigits` variable

---

*[vaadin-grid-column.html, line 437 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJfIwkRksqQ4_GX_rz:-KbK6ZustvhWiqtO0BXg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column.html#L437)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

if possible, use localName here as well
</blockquote></details>

Done.

---

*[vaadin-grid-table-row.html, line 172 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJha7Fz2ItUcrkd-pM:-KbK78-SHtcU4OiCpbd9:bw47rc0) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-row.html#L172)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

you are ordering ascending, so `this.cells.slice(0).sort().forEach()` should work out-of-the-box without any function.
</blockquote></details>

Hmm...I'm not following. We need to do the comparison of `cell.column._order` properties so a function should be required, right?

---

*[vaadin-grid-table-row.html, line 173 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJhu0IB8qHEbZblL9C:-KbK77ZejJB04VzRzQyf:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-row.html#L173)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Otherwise this could be simplified to `return a.column._order - b.column._order;`
</blockquote></details>

Done.

---

*[vaadin-grid-table-scroll-behavior.html, line 373 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJiKtKKN-FetIzmZGo:-KbK7ggo8cf2bmACpk1k:b-mdbca7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-scroll-behavior.html#L373)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

as before, just use `.sort()`
</blockquote></details>

Need to compare `column._order`'s here. I don't think just `.sort()` does that automatically.

---

*[demo/columns.html, line 120 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJitmMtGZuzgltnGwG:-KbK9GUKPvPyINqAKx_S:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/demo/columns.html#L120)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I feel like interesting to have a group sorting demo, so as users can visually figure out  how it behaves.
I had to add the `column-reordering-allowed` to the groups template demo to experiment with the feature.
</blockquote></details>

Done.

---

*[docs/vaadin-grid-configuring-columns.adoc, line 149 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJjJwxBens1pH89sYK:-KbKAIyT5dstYaT0Xmmu:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/docs/vaadin-grid-configuring-columns.adoc#L149)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Please, can you add a note with grouping constrains ?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by manolo** [comment]
Review status: 7 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 367 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJf7vwMQ3Zd0HyrmQZ:-KbKPC-hIgqI-bsMSFbK:b-5jrh9o) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column.html#L367)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

See couple of lines below. It's covered by the `childCountDigits` variable
</blockquote></details>

Right, I forgot to trash this comment after reading the log10 code.

BTW, I think we don't have a 10+ columns test for testing this ?

---

*[vaadin-grid-table-scroll-behavior.html, line 373 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJiKtKKN-FetIzmZGo:-KbKPfMGanE1aAlTIp7j:bxb7bfy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-table-scroll-behavior.html#L373)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Need to compare `column._order`'s here. I don't think just `.sort()` does that automatically.
</blockquote></details>

no it doesn't, you need the block for that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by manolo** [comment]
Review status: 7 of 14 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[.travis.yml, line 18 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbKSPHMabdoCvcLxe6d:-KbKSPHMabdoCvcLxe6e:b-vm727g) ([raw file](https://github.com/vaadin/vaadin-grid/blob/63330096ed36a06d9d0390ff05b58fddf8ac8dcd/.travis.yml#L18)):*
> ```YAML
> 
> script:
>   - travis_wait xvfb-run -s '-screen 0 1024x768x24' wct -l chrome -l firefox
> ```

does this mean that our tests last more than 10 minutes?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by tomivirkki** [comment]
*[.travis.yml, line 18 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbKSPHMabdoCvcLxe6d:-KbKSheRlt1yGg80AMw_:b-rh6lvz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/63330096ed36a06d9d0390ff05b58fddf8ac8dcd/.travis.yml#L18)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

does this mean that our tests last more than 10 minutes?
</blockquote></details>

Got a couple of timeouts not that shadow/non-shadow tests are run in the same go. Just trying this out (apparently it doesn't work = will revert).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-column.html, line 367 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-KbJf7vwMQ3Zd0HyrmQZ:-KbKXEB-h3fnjtU7_G_8:b5mg09u) ([raw file](https://github.com/vaadin/vaadin-grid/blob/015e802313e73d9e9aff4dd32d993e7a73478b53/vaadin-grid-column.html#L367)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Right, I forgot to trash this comment after reading the log10 code.

BTW, I think we don't have a 10+ columns test for testing this ?


</blockquote></details>

Good point, there is now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667)*

**Comment by manolo** [comment]
fix travis build, and  :lgtm:

---

Review status: 6 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-:-KbL8JoZK02FYkuQ9eFF:b-khpouk)*

**Comment by Saulis** [comment]
:lgtm:

---

Reviewed 2 of 13 files at r1, 3 of 5 files at r2, 6 of 7 files at r3, 1 of 2 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/667#-:-KbPRhnCAfRNtlz8-jd1:bnfp4nl)*

**Pull request merged**
