### PR TITLE
Detailed event should be cancelable

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes vaadin/vaadin-context-menu#43

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/570)

### CODE REVIEW

**Comment by platosha** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid.html, line 1484 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-KYsb5Fo5aHzurwpbjYb:-KYsb5Fo5aHzurwpbjYc:bh5o5at) ([raw file](https://github.com/vaadin/vaadin-grid/blob/739b9ac650db599a2184fcfd2189d7c53df6166a/vaadin-grid.html#L1484)):*
> ```HTML
>       details.sourceEvent = event;
>       var detailedEvent = this.fire('detailed-' + event.type, details, {
>         cancelable: true
> ```

Should we set the cancelable flag here depending on if the source event was cancelable?

---

*[test/grid-properties.html, line 354 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-KYsbS856nsYR6D5h7HS:-KYsbS856nsYR6D5h7HT:b-nc5rzf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/739b9ac650db599a2184fcfd2189d7c53df6166a/test/grid-properties.html#L354)):*
> ```HTML
>       };
>       grid.addEventListener('detailed-foo', listener);
>       var sourceEvent = Polymer.Base.fire('foo', {}, {
> ```

BTW I’d like to see empty lines around this fire call, just to emphasise the importance of the trigger step here among the rest of the test setup and cleanup code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570)*

**Comment by tomivirkki** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[vaadin-grid.html, line 1484 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-KYsb5Fo5aHzurwpbjYb:-KYsdrNFuIjJT0WuovrE:b-on8lm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/739b9ac650db599a2184fcfd2189d7c53df6166a/vaadin-grid.html#L1484)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Should we set the cancelable flag here depending on if the source event was cancelable?
</blockquote></details>

Done. Added a test for non-cancelable case also.

---

*[test/grid-properties.html, line 354 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-KYsbS856nsYR6D5h7HS:-KYsdvThGN6tMLfkgwul:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/739b9ac650db599a2184fcfd2189d7c53df6166a/test/grid-properties.html#L354)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

BTW I’d like to see empty lines around this fire call, just to emphasise the importance of the trigger step here among the rest of the test setup and cleanup code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570)*

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid.html, line 1484 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-KYsb5Fo5aHzurwpbjYb:-KYslLKFN5SeYigE_nL5:b-q6hh0n) ([raw file](https://github.com/vaadin/vaadin-grid/blob/739b9ac650db599a2184fcfd2189d7c53df6166a/vaadin-grid.html#L1484)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Done. Added a test for non-cancelable case also.
</blockquote></details>

OK :thumbsup: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-:-KYslV2bdHMsYNmz8TQQ:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 1484 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-KYsb5Fo5aHzurwpbjYb:-KYswBZ5Ya1G4uNW4Q-c:b6ubq62) ([raw file](https://github.com/vaadin/vaadin-grid/blob/739b9ac650db599a2184fcfd2189d7c53df6166a/vaadin-grid.html#L1484)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

OK :thumbsup: 
</blockquote></details>

...just realized the new test was testing the wrong thing though. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/570#-:-KYwvpmwo6tCxYx2R8M0:bnfp4nl)*

**Pull request merged**
