### PR TITLE
Fixes #341 added css var to selected row background color

### LINKED ISSUE #341: Vaadin-grid selected row background color needs a css variable
Add a css variable to background color for selected row, enabling developers to set background color without `::shadow` and `/deep/`

### PR DESCRIPTION
**Pull request by billy-hardy**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/342)

### CODE REVIEW

**Comment by billy-hardy** [comment]
@jouni Is there a certain process that I have to go through to get this PR looked at by someone?

**Comment by jouni** [comment]
Hi! Sorry about forgetting you for a little longer here, was not intentional. We’ve been so focused on Angular 2 support and stabilizing the 1.0’s of all the other elements, that everything else goes a little unnoticed. My apologies!

I think we might want to lean on CSS mixins more initially, to keep the theme API less specific. How would you feel about using the following:

```css
vaadin-grid {
  vaadin-grid-selected-row: {
    background-color: blue;
  }
}
```

**Comment by billy-hardy** [comment]
Works for me! Updated the pull request.

Thanks.

**Comment by billy-hardy** [comment]
@jouni This is just a gentle reminder that this pull request is still open and needs to be reviewed.

**Comment by jouni** [comment]
Ouch, this is starting to be embarrasing ☺️ Sorry!

@tomivirkki or @tehapo, could you add your comments to this? Looks quite alright to me. Perhaps I would mention in the mixin documentation that it targets the selected row cell elements specifically, not the whole row element.

**Comment by tomivirkki** [comment]
The documentation could be rephrased as stated by @jouni but other than that, LGTM

**Comment by jouni** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/342)*

**Comment by jouni** [comment]
I’ll update the documentation myself afterwards. :lgtm: 

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/342#-:-KGHezZ3fPhQPN81NRip:-2048221056)*

**Pull request merged**
