### PR TITLE
Refactor data request API

### LINKED ISSUE #229: Refactor "items" function API parameters
Separate the `success` callback outside of the data request parameters object, and remove the `failure` callback.

```javascript
grid.items = function(params, callback) {
  fetch("data/from/url?index=" + params.index + "&count=" + params.count)
    .then(function(response) {
      callback(response.json(), count);
    }).catch(function() {
      callback([], 0);
    });
}
```

- [ ] Implementation
- [ ] Examples
- [ ] API docs

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #229

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/236)

### CODE REVIEW

**Comment by tehapo** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/grid-selecting-rows.html, line 566 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236#-K2MXGKTiQJKey_OVdlI)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/eefbe41a21d148e9c863cc4bb2feb31626a752dc/test/grid-selecting-rows.html#L566)):</sup>
Some kind of merge conflict here?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236)

**Comment by Saulis** [comment]
Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/grid-selecting-rows.html, line 566 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236#-K2MXGKTiQJKey_OVdlI)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/eefbe41a21d148e9c863cc4bb2feb31626a752dc/test/grid-selecting-rows.html#L566)):</sup>
Oh yes sir


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236)

**Comment by tehapo** [comment]
Reviewed 17 of 17 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236)

**Comment by Saulis** [comment]
Review status: 16 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[test/grid-selecting-rows.html, line 566 \[r1\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236#-K2MXGKTiQJKey_OVdlI)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/eefbe41a21d148e9c863cc4bb2feb31626a752dc/test/grid-selecting-rows.html#L566)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236)

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/236)

**Pull request merged**
