### PR TITLE
Do not activate column resize while reordering

### LINKED ISSUE #1076: Column resizing should be disabled whed d&d column
recorded

Expected: when in d&d mode, resizing indicators should now work, the cursor should not be changed, dragging should not be interrupted.

Chrome/Linux

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #1076

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1084)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-grid-styles.html, line 186 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1084#-KyGp9llbRFGWXZrV1-p:-KyGp9llbRFGWXZrV1-q:b-gr0uz9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/50a8df608cf2dfd5a67ed549dc6e5d2e60ac0fec/vaadin-grid-styles.html#L186)):*
> ```HTML
> 
>       :host([reordering]) [part~="resize-handle"] {
>         cursor: default;
> ```

`cursor` has no effect when `pointer-events: none` is set, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1084)*

**Comment by web-padawan** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-styles.html, line 186 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1084#-KyGp9llbRFGWXZrV1-p:-KyGsATIOKxGwoXGg7jz:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/50a8df608cf2dfd5a67ed549dc6e5d2e60ac0fec/vaadin-grid-styles.html#L186)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`cursor` has no effect when `pointer-events: none` is set, right?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1084)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1084#-:-KyGsdFhfOFlWHIqWM4e:bnfp4nl)*

**Comment by limonte** [comment]
That was quite an efficient first working day! :lgtm: :muscle: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1084#-:-KyH6b7R80Xc98eDktb-:b4jrxks)*

**Pull request merged**
