### PR TITLE
Fix(keyboard): resizing focuses header cell

### PR DESCRIPTION
**Pull request by platosha**
Connected to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/961)

### CODE REVIEW

**Comment by manolo** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column-resizing-mixin.html, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961#-KtBV7CQFN4mDDkTIeox:-KtBV7CQFN4mDDkTIeoy:bnvfwsu) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0a3465b405306769195b8b00cba8064c0fd228b/vaadin-grid-column-resizing-mixin.html#L66)):*
> ```HTML
> 
>       // Disable native cell focus when resizing
>       scroller.addEventListener('mousedown', e => e.target.getAttribute('part') === 'resize-handle' && e.preventDefault());
> ```

nit: can you align equal operator with the line above. I'm not fan on the triple operator in this case, but anyone works to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961)*

**Comment by platosha** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column-resizing-mixin.html, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961#-KtBV7CQFN4mDDkTIeox:-KtBYbKSXbYyIPcywCNw:byvbbfm) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0a3465b405306769195b8b00cba8064c0fd228b/vaadin-grid-column-resizing-mixin.html#L66)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

nit: can you align equal operator with the line above. I'm not fan on the triple operator in this case, but anyone works to me.
</blockquote></details>

Not sure about this. The line above is the only double-equal operator in this file, all the others are triple-equal.

IMO, triple equal operator should be preferred and enforced with a linter rule, as it’s more strict. We had this at some point.

Seems to me like it’s rather the line above should be with everything else, rather then this new line by me. But that is a separate issue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column-resizing-mixin.html, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961#-KtBV7CQFN4mDDkTIeox:-KtD-GG6IOQhw1L4YYlN:b-v27xs5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0a3465b405306769195b8b00cba8064c0fd228b/vaadin-grid-column-resizing-mixin.html#L66)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Not sure about this. The line above is the only double-equal operator in this file, all the others are triple-equal.

IMO, triple equal operator should be preferred and enforced with a linter rule, as it’s more strict. We had this at some point.

Seems to me like it’s rather the line above should be with everything else, rather then this new line by me. But that is a separate issue.
</blockquote></details>

"My advice is to never use the evil twins. Instead, always use === and !==" (Douglas Crockford)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961#-:-KtD-NJxtSrjw5Z4dw67:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-column-resizing-mixin.html, line 66 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961#-KtBV7CQFN4mDDkTIeox:-KtG1Mc-rZrd3gVvDF8O:bq648ng) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e0a3465b405306769195b8b00cba8064c0fd228b/vaadin-grid-column-resizing-mixin.html#L66)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"My advice is to never use the evil twins. Instead, always use === and !==" (Douglas Crockford)
</blockquote></details>

Yep, it's one of the recurrent problems of dealing with JS. So his solution is just 'I follow my own convention' I forgot about the double operator to avoid problems. But double operators are easy to read for developers handling multiple languages, and actually the triple operator only makes full sense when checking zero nulls empties undefined, in this case where right side is a string constant it does not aport any advantage, but the convention. 

Anyways, I just wanted to have both lines aligned instead of starting a discussion thread. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/961#-:-KtG37iMNGEDUHnRSAPY:bnfp4nl)*

**Pull request merged**
