### PR TITLE
Expose public  element for multi-selection.

### PR DESCRIPTION
**Pull request by manolo**
Connects to #519 

- `vaadin-grid-column-selection` can be used now instead of multi-selection property.
- The selection column can be placed in any position

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/557)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Docs should be synced to match the new API

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGevJkE_TCqKoxVBS:-KYDGevJkE_TCqKoxVBT:blkuir6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
> ```HTML
> </dom-module>
> 
> <dom-module id="vaadin-grid-column-selection">
> ```

Why is this named "vaadin-grid-column-selection"? The ticket says "vaadin-grid-multi-select-column".

---

*[vaadin-grid-selection-behavior.html, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHDjEA7OppYwHsZWy:-KYDHDjFMNq1NQwQQRii:b8vynkc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-selection-behavior.html#L44)):*
> ```HTML
> 
>     ready: function() {
>       this._addColumnTreeProcessor(this._addSelectAllListener);
> ```

I think this shouldn't exist anymore. The ticket says: "The "column tree processor" will become obsolete, so it should be refactored out"

---

*[vaadin-grid-selection-behavior.html, line 183 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGHqbVDPO8R-yXE1j:-KYDGHqbVDPO8R-yXE1k:b-g6hs8g) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-selection-behavior.html#L183)):*
> ```HTML
>   };
> </script>
> ```

These modules should remain in `vaadin-grid-selection-behavior`since they're closely related to selection API.

---

*[vaadin-grid-table.html, line 169 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHsI2xNE-FGslxe1x:-KYDHsI2xNE-FGslxe1y:bf9j8xa) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-table.html#L169)):*
> ```HTML
>       }
>     </style>
>     <content select="vaadin-grid-column, vaadin-grid-column-group"></content>
> ```

Multi-select column should also be included

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-:-KYDIT_FSeGlS9mA9vKx:bt3sxr5)*

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHEouS0KF_TS5FTPa:-KYDHEouS0KF_TS5FTPb:bgdwbrz) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
> ```HTML
> </dom-module>
> 
> <dom-module id="vaadin-grid-column-selection">
> ```

Rename to `<vaadin-grid-multi-selection-column>` also, this should be in a separate file which is not automatically imported since it's not needed in all cases.

---

*[vaadin-grid-column.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHZjoV8HVpDK6u417:-KYDHZjpZ_13076YS3ko:b-akbq1f) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L34)):*
> ```HTML
>   (function(){
>     /**
>      * @polymerBehavior vaadinGridColumnBaseBehavior
> ```

I would leave the current `vaadinGridColumnBehavior` as it is and not extract any functionality to a separate behaviour – there isn't any clear distinction between the responsibilities of `vaadinGridColumnBehavior` and `vaadinGridColumnBaseBehavior` currently.

---

*[vaadin-grid-selection-behavior.html, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHDjEA7OppYwHsZWy:-KYDIqAi0HnA8IsEj0Bz:b-ebephj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-selection-behavior.html#L44)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I think this shouldn't exist anymore. The ticket says: "The "column tree processor" will become obsolete, so it should be refactored out"
</blockquote></details>

That's correct, this should be removed together with `_addSelectAllListener`

---

*[vaadin-grid-selection-behavior.html, line 183 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGHqbVDPO8R-yXE1j:-KYDJ36_yLPF3TlMgW-X:bf03wug) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-selection-behavior.html#L183)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

These modules should remain in `vaadin-grid-selection-behavior`since they're closely related to selection API.
</blockquote></details>

The styles module yes, but not the column of course.

---

*[vaadin-grid-table.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDK1DKyoczQqZ3L6KH:-KYDK1DKyoczQqZ3L6KI:b-45sujr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-table.html#L13)):*
> ```HTML
> <link rel="import" href="vaadin-grid-row-details-behavior.html">
> <link rel="import" href="vaadin-grid-data-source-behavior.html">
> <link rel="import" href="vaadin-grid-selection-behavior.html">
> ```

This import shouldn't be removed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Done

---

Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGevJkE_TCqKoxVBS:-KYDJuEpxgODo4rKi71L:b-mxw3gd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Why is this named "vaadin-grid-column-selection"? The ticket says "vaadin-grid-multi-select-column".
</blockquote></details>

I know, but I think it should be aligned with `vaadin-grid-column` like the group column does. The removed element was aligned with the behaviour name since it was used implemented in this file and only used by the behavior.  To me makes more `vaadin-grid-column-selection` or `vaadin-grid-column-multiselection`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-:-KYDJqqQB9XBaE7l8t_5:bb6un1j)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHEouS0KF_TS5FTPa:-KYDK__Jw5EdjJsrVN_P:b-mwjni4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Rename to `<vaadin-grid-multi-selection-column>` also, this should be in a separate file which is not automatically imported since it's not needed in all cases.
</blockquote></details>

Since the implementation is based in the column behavior API to me makes more sense the other name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHZjoV8HVpDK6u417:-KYDKoYoeSfe591nFI8g:b-ocdt7r) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L34)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

I would leave the current `vaadinGridColumnBehavior` as it is and not extract any functionality to a separate behaviour – there isn't any clear distinction between the responsibilities of `vaadinGridColumnBehavior` and `vaadinGridColumnBaseBehavior` currently.
</blockquote></details>

now we have 3 elements v-g-column b-g-column-group and v-g-column-selection, they share some code, so my idea is diferentiate and reuse common code. Behaviors is the way in polymer  to share common code, this the reason I end with 3 different blocks. Naming is not important since they are private

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-grid-selection.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDLI1nmgWxuZYQanFx:-KYDLI1nmgWxuZYQanFy:by7gsaj) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L20)):*
> ```AsciiDoc
> 
> You can switch on multi select mode by adding a [vaadinelement]#vaadin-grid-column-selection# column to the grid.
> The default implementation of [vaadinelement]#vaadin-grid-column-selection# reveals a checkbox column that can be used to select multiple rows.
> ```

I'd drop "The default implementation of". It suggests that you could somehow modify the implementation...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/vaadin-grid-selection.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDLI1nmgWxuZYQanFx:-KYDMQSGLI8JkzQPOBsL:boje9by) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I'd drop "The default implementation of". It suggests that you could somehow modify the implementation...
</blockquote></details>

Actually you can customize the implementation with your own content if it changes select and selectAll, for instance:

```

<vaadin-grid-column-selection>
    <template class="header">
       NO select checkbox
    </template>
</vaadin-grid-column-selection>
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-selection-behavior.html, line 183 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGHqbVDPO8R-yXE1j:-KYDNDA1usHY4B7hAcvo:bk18a4c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-selection-behavior.html#L183)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

The styles module yes, but not the column of course.
</blockquote></details>

I think the styles should be in the file where the html for the selection column is

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-table.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDK1DKyoczQqZ3L6KH:-KYDNQqaWKNB6P7_fIuf:b6y82t9) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-table.html#L13)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

This import shouldn't be removed
</blockquote></details>

It's not used, why do we include it so?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by tomivirkki** [comment]
*[vaadin-grid-selection-behavior.html, line 183 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGHqbVDPO8R-yXE1j:-KYDNMdhhCvRHoVlB1bL:bows9iv) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-selection-behavior.html#L183)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I think the styles should be in the file where the html for the selection column is
</blockquote></details>

The styles don't relate to the selection column but the selection feature (doesn't require the column), this is the correct place for them

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-selection-behavior.html, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHDjEA7OppYwHsZWy:-KYDNohN4CkUQH2gzCtn:byadpam) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-selection-behavior.html#L44)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

That's correct, this should be removed together with `_addSelectAllListener`
</blockquote></details>

I know it must be removed, but my idea was in a separated PR so as each commit in this one was less intrusive and easier to follow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by tomivirkki** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGevJkE_TCqKoxVBS:-KYDRb4jpgax8t2igQij:b-mzzijg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I know, but I think it should be aligned with `vaadin-grid-column` like the group column does. The removed element was aligned with the behaviour name since it was used implemented in this file and only used by the behavior.  To me makes more `vaadin-grid-column-selection` or `vaadin-grid-column-multiselection`
</blockquote></details>

Agreed to `vaadin-grid-selection-column` with the team

---

*[vaadin-grid-selection-behavior.html, line 44 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHDjEA7OppYwHsZWy:-KYDPC2ZqgzDbuDwGwWh:b-q4dzt2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-selection-behavior.html#L44)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I know it must be removed, but my idea was in a separated PR so as each commit in this one was less intrusive and easier to follow.
</blockquote></details>

Removing the processor is an integral part of this change (dropping the internal multi select column) so it most definitely should be done as part of this PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-grid-selection.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDLI1nmgWxuZYQanFx:-KYDSApl526zN6451CB3:b-bg2ddy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Actually you can customize the implementation with your own content if it changes select and selectAll, for instance:

```

<vaadin-grid-column-selection>
    <template class="header">
       NO select checkbox
    </template>
</vaadin-grid-column-selection>
```
</blockquote></details>

Then is should be mentioned in the documentation.

But I'd still rather not advice developers to customize the selection column. If custom behaviour is required, `<vaadin-grid-column>` is there just for that purpose.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-table.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDK1DKyoczQqZ3L6KH:-KYDkyWs4HBUmHDL-qOh:bjfdblw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-table.html#L13)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

It's not used, why do we include it so?
</blockquote></details>

Like discussed, the `vaadin-grid-selection-behavior.html` contains the style module which is used by the `vaadin-grid-table.html`

---

*[docs/vaadin-grid-selection.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDLI1nmgWxuZYQanFx:-KYDioF1ZGmOimD4nILZ:b1qhrng) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Then is should be mentioned in the documentation.

But I'd still rather not advice developers to customize the selection column. If custom behaviour is required, `<vaadin-grid-column>` is there just for that purpose.
</blockquote></details>

Yeah, kinda the whole point of `<vaadin-grid-selection-column>` is the fact that it provides ready-made templates for you. So in case you want to customise those, you should go ahead and just use the regular column for that.

You can also give the internal templates ids and override the template properties like this:

```js
headerTemplate: {
          type: Object,
          value: function() {
            return this.$.header;
          }
        }
```

(all that `dataHost` stuff inside `_findTemplate()` is only needed for externally defined templates.)

---

*[test/selecting.html, line 33 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDksdpI_y8cKLcIYce:-KYDksdpI_y8cKLcIYcf:bgqqkh7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/test/selecting.html#L33)):*
> ```HTML
>   <test-fixture id="multiselect">
>     <template>
>       <vaadin-grid style="width: 200px; height: 200px;" size="10000" selection-enabled>
> ```

`selection-enabled` doesn't exist?

---

*[test/selecting.html, line 54 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDjKQjNE7KxOFwEfEj:-KYDjKQjNE7KxOFwEfEk:b-eshwqc) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/test/selecting.html#L54)):*
> ```HTML
>       afterEach(function() {
>         if (grid) {
>           grid.parentElement.removeChild(grid);
> ```

Cleanup is automatic, this shouldn't be needed.

---

*[test/selecting.html, line 114 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDkdkXyJgK2TNxE9zp:-KYDkdkXyJgK2TNxE9zq:b-vccyj3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/test/selecting.html#L114)):*
> ```HTML
>         });
> 
>         it('should reset selection', function() {
> ```

This should work as before?

---

*[test/selecting.html, line 127 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDkJ2mAHMR75rlQoeW:-KYDkJ2mAHMR75rlQoeX:bpuzog1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/test/selecting.html#L127)):*
> ```HTML
> 
>         it('should change inverted selection', function () {
>           expect(grid.selectedItems.inverted).to.be.false;
> ```

This test should remain as it is, there should be an observer for the `selectAll` inside `<vaadin-grid-selection-column>` which takes care of the functionality related with "select all". Like setting the `selectedItems.inverted`to `false` when "select all" is unchecked.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 9 files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[docs/vaadin-grid-selection.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDLI1nmgWxuZYQanFx:-KYDn0MC_hXi_Mlf2KQO:bha776v) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L20)):*
> vaadin-grid-selection-column

is also a marker name, so when the column is this type, there is more to do like configure listeners for selectAll unless we allow any column to fire that event

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by Saulis** [comment]
Review status: 0 of 9 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[vaadin-grid-column.html, line 34 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHZjoV8HVpDK6u417:-KYDt_ljXY982ThClUw5:buqk28w) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L34)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

now we have 3 elements v-g-column b-g-column-group and v-g-column-selection, they share some code, so my idea is diferentiate and reuse common code. Behaviors is the way in polymer  to share common code, this the reason I end with 3 different blocks. Naming is not important since they are private
</blockquote></details>

OK, I tried things out and I see the purpose now, since properties can't really be overridden when using properties, things like `flex` and `hidden` which behave differently in `<vaadin-grid-column-group>` need to be declared separately.

---

*[vaadin-grid-column.html, line 158 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDtvwSyAs1fryrquWg:-KYDtvwSyAs1fryrquWh:b-in75y5) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/vaadin-grid-column.html#L158)):*
> ```HTML
>       is: 'vaadin-grid-column',
> 
>       behaviors: [vaadinGridColumnBaseBehavior, vaadinGridColumnBehavior],
> ```

You can add `vaadinGridColumnBaseBehavior` in the `behaviors` property of `vaadinGridColumnBehavior` directly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by tomivirkki** [comment]
*[docs/vaadin-grid-selection.adoc, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDwTC-1Ukp6R3AWxF7:-KYDwTC-1Ukp6R3AWxF8:b-nbnv3o) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L19)):*
> ```AsciiDoc
> This means that it allows only one row to be selected at once.
> 
> You can switch on multi select mode by adding a [vaadinelement]#vaadin-grid-column-selection# column to the grid.
> ```

To be precise, this whole "[[vaadin-grid-selection.mode]]"-section should be removed/rewritten now that the selection functionality is changed. 

There's no longer "multi select mode" or "single select mode" (the sentence above still talks about single-select mode being the default and so forth...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Comment by manolo** [comment]
Review status: 0 of 11 files reviewed at latest revision, 13 unresolved discussions.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGevJkE_TCqKoxVBS:-KYET6m85BO53C60cWCe:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Agreed to `vaadin-grid-selection-column` with the team
</blockquote></details>

Done.

---

*[vaadin-grid-column.html, line 20 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDHEouS0KF_TS5FTPa:-KYET7UMOjCv5i-heNAy:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/97ee3f8ca0d3d74eb76ea58314e0c11ca7f51ae5/vaadin-grid-column.html#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Since the implementation is based in the column behavior API to me makes more sense the other name
</blockquote></details>

Done.

---

*[vaadin-grid-selection-behavior.html, line 183 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDGHqbVDPO8R-yXE1j:-KYETfYHkBFcq2SqH6BX:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-selection-behavior.html#L183)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The styles don't relate to the selection column but the selection feature (doesn't require the column), this is the correct place for them
</blockquote></details>

Done.

---

*[vaadin-grid-table.html, line 13 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDK1DKyoczQqZ3L6KH:-KYEThxR79R9EsUakHl4:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b51468c73ca811f40d16dc849a8250b91b2ab319/vaadin-grid-table.html#L13)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Like discussed, the `vaadin-grid-selection-behavior.html` contains the style module which is used by the `vaadin-grid-table.html`
</blockquote></details>

Done.

---

*[docs/vaadin-grid-selection.adoc, line 19 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDwTC-1Ukp6R3AWxF7:-KYERZu5_d3vaRuqukE1:bubfo63) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L19)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

To be precise, this whole "[[vaadin-grid-selection.mode]]"-section should be removed/rewritten now that the selection functionality is changed. 

There's no longer "multi select mode" or "single select mode" (the sentence above still talks about single-select mode being the default and so forth...)
</blockquote></details>

Agree 100%, let's delay this until the implementation in this PR is done.

---

*[docs/vaadin-grid-selection.adoc, line 20 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDLI1nmgWxuZYQanFx:-KYERjPwN_WlbNXJFXgi:bgs27ho) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/docs/vaadin-grid-selection.adoc#L20)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

> vaadin-grid-selection-column

is also a marker name, so when the column is this type, there is more to do like configure listeners for selectAll unless we allow any column to fire that event
</blockquote></details>

Ok, will refine docs after code looks ok

---

*[test/selecting.html, line 54 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557#-KYDjKQjNE7KxOFwEfEj:-KYES_vL94LS1t_EQQUE:bhzlvcy) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e6174b987e5ea024622811f8bda0ceebcc80ed5a/test/selecting.html#L54)):*
<details><summary><i>Previously, Saulis (Sauli Tähkäpää) wrote…</i></summary><blockquote>

Cleanup is automatic, this shouldn't be needed.
</blockquote></details>

default fixture remains in the dom without this,  try to stop the tests in second block. I have not dived into this to figure out a reason.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/557)*

**Pull request merged**
