### PR TITLE
Doc introduction for grid

### PR DESCRIPTION
**Pull request by manolo**
Connects to vaadin/components-team-tasks/issues/62

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/303)

### CODE REVIEW

**Comment by manolo** [comment]
Live demo with the introduction : http://wc.demo.vaadin.com/mcm/out/

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[demo/introduction.html, line 125 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GDmf9IEsT_HPK5wFs:-K7GDmf9IEsT_HPK5wFt:2013174426) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L125)):*
Unnecessary extra space between &quot; and &gt;.

---

*[demo/introduction.html, line 128 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GDiLfg9ubg3jyMn9M:-K7GDiLfg9ubg3jyMn9N:1545859238) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L128)):*
Typo. Should be "infrastructure".

---

*[demo/introduction.html, line 130 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GDrF9wpQmaqKupI8D:-K7GDrF9wpQmaqKupI8E:2013174426) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L130)):*
Unnecessary extra space between &quot; and &gt;.

---

*[demo/introduction.html, line 133 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GF6Rht-FkTmqsIaxc:-K7GF6Rht-FkTmqsIaxd:816040987) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L133)):*
Headings typically do not end with a period. I would remove it.

---

*[demo/introduction.html, line 137 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GFADSBxFqcbRTsiFB:-K7GFADSBxFqcbRTsiFC:-718049976) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L137)):*
In my opinion this paragraph could use a bit more explaining of the example that follows. Currently it is a bit short. Maybe mention explicitly about defining the columns with <col> and their headings with <th>. Also a mention about the option to use a function datasource could be nice.

---

*[demo/introduction.html, line 166 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GF373iwd6aYGn6dKb:-K7GF373iwd6aYGn6dKc:816040987) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L166)):*
Headings typically do not end with a period. I would remove it.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[demo/introduction.html, line 125 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GDmf9IEsT_HPK5wFs:-K7kcVC35BFkhKThAc4q:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L125)):*
Done.

---

*[demo/introduction.html, line 128 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GDiLfg9ubg3jyMn9M:-K7kcb3Q0Tu1k_PS7U6t:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L128)):*
Done.

---

*[demo/introduction.html, line 130 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GDrF9wpQmaqKupI8D:-K7kcf55lwBNog9p8iBP:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L130)):*
Done.

---

*[demo/introduction.html, line 133 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GF6Rht-FkTmqsIaxc:-K7kci-neyF2Lhae9MJD:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L133)):*
Done.

---

*[demo/introduction.html, line 166 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GF373iwd6aYGn6dKb:-K7kcxMDV7Gd_WpS0OLm:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L166)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303)*

**Comment by manolo** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[demo/introduction.html, line 137 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303#-K7GFADSBxFqcbRTsiFB:-K7khK2tgenExptr_eHZ:-499146009) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa2d8ae4dd6707f907465a62a46393e6ead5aebd/demo/introduction.html#L137)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/303)*

**Comment by tehapo** [comment]
Squashed the commits of this PR into a single one and did a pretty major rewrite of the Overview page according to instructions added by @jounik.

**Comment by tomivirkki** [comment]
Merged

**Pull request merged**
