### PR TITLE
Feature/event rename

### LINKED ISSUE #210: Rename selection related event names
The event name for selection mode change event should follow Polymer conventions, and be `selection-mode-changed` and not `selectionmodechange`.

The `select` event name should be reconsidered at the same time, as `selected-items-changed` could be more inline with the other event names, and would not get mixed with the standard HTML `select` event.

- [ ] Implementation
- [ ] Examples
- [ ] API docs

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #210

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/242)

### CODE REVIEW

**Comment by Saulis** [comment]
Small `CHANGES.md` update and we're all GROOD! :+1: 


---

Reviewed 11 of 16 files at r1, 11 of 12 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[demo/angular2.html, line 135 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/242#-K2klUlgbyRCR1c021_J)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/4864a5774e8b450229eb255e42d00e8dcba3d19b/demo/angular2.html#L135)):</sup>
`params` and `callback` maybe?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/242)

**Comment by tomivirkki** [comment]
done


---

Review status: 20 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[demo/angular2.html, line 135 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/242#-K2klUlgbyRCR1c021_J)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/4864a5774e8b450229eb255e42d00e8dcba3d19b/demo/angular2.html#L135)):</sup>
Indeed, they were changed back by accident


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/242)

**Comment by Saulis** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/242)

**Comment by jounik** [comment]
You should add release notes here as well: https://github.com/vaadin/vaadin-grid/releases/tag/untagged-46ddfde7ac6d075a0760

**Pull request merged**
