### PR TITLE
Enable tests for Safari 9

### PR DESCRIPTION
**Pull request by samiheikki**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1236)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Should we add a new build job (Mobile) for this instead?

**Comment by tomivirkki** [comment]
Just changes to repo files required. Currently, there are jobs (badly) named as "desktop" and "polyfilled" https://travis-ci.org/vaadin/vaadin-grid/builds/348003261. Just add a new one for "mobile" and include mobile Safari in that.

**Comment by samiheikki** [comment]
@tomivirkki I see you have disabled it 3 months ago https://github.com/vaadin/vaadin-grid/commit/004ec41eef2bb1751e49e717253fb3234ec741b8 I guess phone safari 9 would have the same timeout issues?

**Comment by tomivirkki** [comment]
Could be that it still has the same timeout issues. Only one way to find out :)

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1236#-:-L7A2kmKe_ypCZj9kW6x:bnfp4nl)*

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2, 3 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1236#-:-L7A2xHatBLnD5JiurkG:bnfp4nl)*

**Pull request merged**
