### PR TITLE
Fix multiple observer calls

### LINKED ISSUE #1264: [5.0.0-beta7] Vaadin cells are rendered multiple time
### Description
Vaadin cells renders a lot of time which makes vaadin grid really slow when having a lot of rows and columns. 

### Expected outcome
Vaadin should render the cell once

### Actual outcome
I have a function that is in the template of the cell and registers how many time the template is called. As you can see, the template is called 135 times (which mean that the cell is rendered 135 times ??). This throttle the CPU to around 80% and the grid is not fluid for a period of 20-30sec. 

capture

### Live Demo
```html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../polymer/polymer-element.html">
<link rel="import" href="../vaadin-grid/vaadin-grid.html">
<link rel="import" href="../vaadin-grid/vaadin-grid-column.html">
<link rel="import" href="../vaadin-grid/vaadin-grid-column-group.html">
<link rel="import" href="../vaadin-grid/vaadin-grid-sorter.html">
<link rel="import" href="../vaadin-grid/vaadin-grid-filter.html">

<dom-module id="my-grid">
  <template preserve-content>
  <style>....</style>
 <vaadin-grid id="grid" items="[[_items]]" multi-sort="true" size="[[_size]]">
      <template is="dom-repeat" items="[[_columns]]" as="column" initial-count="30" target-framerate=1>
        <vaadin-grid-column-group resizable>
          <vaadin-grid-column flex-grow="1" resizable>
            <template class="header">
              <vaadin-grid-sorter path="[[column.key]]">
                <vaadin-grid-filter path="[[column.key]]" value="[[column._filterBinding]]">
                  <input class="filter" type="text" slot="filter" placeholder="[[column.name]]" value="{{column._filterBinding::change}}" focus-target>
                </vaadin-grid-filter>
              </vaadin-grid-sorter>
            </template>
            <template>

                [[get(column.key, item)]] [[_stats(index, column.key, item)]]

            </template>
          </vaadin-grid-column>
        </vaadin-grid-column-group>
      </template>
    </vaadin-grid>
  </template>
<script>
    /* jshint esversion:6, asi:true */
    class MyGrid extends Polymer.Element {

      static get is() { return 'my-grid'; }

      static get properties() {
        return {
          items: {
            type: Array
          },
          _items: {
            type: Array
          },
          _size: {
            type: Number
          },
          _columns: {
            type: Array,
            computed: "_computeColumns( items)",
            observer: "_columnsObserver"
          },
          done: {
            type: Boolean,
          }
        }
      }

      ready(){
        super.ready();
      }

      _computeColumns( items) {
        return Object.keys(items[0]).map( (column) => {
          return {key: column, name: column.toUpperCase()}
        });
      }

      _columnsObserver( _columns) {
        console.log( "MYGRID> _columns changed", _columns);
        // Loading items after the columns are generated seems way more efficient
        this._loadItems();
      }

      _loadItems() {
        this._size = this.items.length;
        this._items = this.items;
      }

      _stats(index, key, item) {
        if(!window.stats) {
          window.stats = {};
        }
        if(!window.stats[index]){
          window.stats[index] = {}
        }
        if(!window.stats[index][key]) {
          window.stats[index][key] = 1;
        } else {
          window.stats[index][key]++;
        }
      }
    }
    window.customElements.define(MyGrid.is, MyGrid);
  </script>
</dom-module>
```

### Steps to reproduce
Vaadin grid with 50 columns and 200 rows, just let the grid load itself and see the result in window.stats (don't scroll) else you'll have more render which make sense (if you scroll).

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge
- [ ] IE 11
- [ ] iOS Safari
- [ ] Android Chrome

### LINKED ISSUE #1267: [4.1.7]  assigned provider function called multiple times on load when column filters are present
### Description
When a vaadin-grid instance has column filters, the assigned data provider function is called with page 0 as many times as there are filters.

### Expected outcome
The provider should be called only once for page 0 on page load.

### Actual outcome
If all the data is loaded at once, this does not seem to present visible issues.  If, however, lazy-loading via asynchronous AJAX calls using paging (offset + limit) is used, the multiple calls to fetch and load page 0 result in a corrupted data cache for the table which is not rectified until a refresh or reset which does not reload the entire component.

### Live Demo
https://github.com/alrossi/vaadin-issues/tree/filter-with-provider

### Steps to reproduce
Checkout/clone the GitHub repository and follow the README.

### Browsers Affected
I have tested only:
- [x] Chrome
- [x] Firefox
- [x] Safari

### PR DESCRIPTION
**Pull request by tomivirkki**
Fixes #1264
Fixes #1267 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1277)

### CODE REVIEW

**Comment by web-padawan** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277#-:-L9yl5W2Cg69xinMQKwS:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[src/vaadin-grid.html, line 513 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277#-L9ymLC0E-ybsFsQxGXV:-L9ymLC0E-ybsFsQxGXW:b-pbtm51) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9112cc28b00f15fd82ddbf43b3c7eb3d4753d7e6/src/vaadin-grid.html#L513)):*
> ```HTML
>           if (cell._instance) {
>             cell._instance.setProperties({
>               item,
> ```

what does this? shouldn't be `item: item`? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277#-:-L9ylfdfDDlSNduLztwW:bnfp4nl)*

**Comment by tomivirkki** [comment]
*[src/vaadin-grid.html, line 513 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277#-L9ymLC0E-ybsFsQxGXV:-L9yn1R71VHPLkbL6ARW:b-jacg76) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9112cc28b00f15fd82ddbf43b3c7eb3d4753d7e6/src/vaadin-grid.html#L513)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

what does this? shouldn't be `item: item`? 
</blockquote></details>

It's using https://ariya.io/2013/02/es6-and-object-literal-property-value-shorthand

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-grid.html, line 513 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277#-L9ymLC0E-ybsFsQxGXV:-L9yslr97Itw5Q7O1hEu:b-kdqco4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/9112cc28b00f15fd82ddbf43b3c7eb3d4753d7e6/src/vaadin-grid.html#L513)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's using https://ariya.io/2013/02/es6-and-object-literal-property-value-shorthand
</blockquote></details>

gotcha, thanks.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1277#-:-L9yswz1DHykNNqtjrWe:bnfp4nl)*

**Pull request merged**
