### PR TITLE
Use separate test suites

### PR DESCRIPTION
**Pull request by tomivirkki**
Connected to #878

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/973)

### CODE REVIEW

**Comment by manolo** [comment]
How does this help to our build? are the three suites run sequentially or in parallel ?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/973#-:-KtWNIEsVkDhaQxgY6MO:b-ryxjhc)*

**Comment by tomivirkki** [comment]
In parallel. If one of them fails, you'll only need to re-run the failed suite, rest will remain green. Once all suites are green, the whole build is green.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/973#-:-KtWNgMcFaX2ZVFHOqjn:b-ohnsd6)*

**Comment by manolo** [comment]
A ok, so the main feature is that we can re-run only a suite. Nice!

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[.travis.yml, line 22 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/973#-KtWTwoSDQNvAF0aY2P-:-KtWTwoSDQNvAF0aY2P0:b7hmthr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/e73da470ac69b4e2f2102245508a993942e7bc3d/.travis.yml#L22)):*
> ```YAML
> 
> env:
>   - TEST_SUITE=mobile
> ```

Probably I would have as many platforms as devices, that facilitates just to retry one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/973#-:-KtWU2aMjrzbEwFN0E_6:bpwu3t7)*

**Comment by manolo** [comment]
:lgtm_strong: 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/973#-:-KtWUGU9YU6fBylyj06Y:b-uwkowd)*

**Pull request merged**
