### PR TITLE
Replace multiSelection property with vaadin-grid-selection-column

### LINKED ISSUE #514: Missing dependency: paper-checkbox
`<paper-checkbox>`, although imported in vaading-grid-selection-behavior.html, is missing from bower.json dependencies (listed in `devDependencies`, but not in plain `dependencies`).

### LINKED ISSUE #519: Refine Selection API
I have found these issues when implementing the component demo:

- When grid.multiSelection changes from true to false, all selected items should be reset.
- selected-items-changed event is fired twice
- In multi-selection mode if there are some items selected and you click on select-all it should toggle selections
- Clicking on a row in multi-selection it should select/deselect the row. Since cell-click event is fired, prevent default could work for not selecting the row.
- There should be a way to enable selection single, it might be by default or might be disabled and enabled with `single-selection` flag.
- Clicking on a row in single-selection should toggle selection

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #519
Fixes #514

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/577)

### CODE REVIEW

**Comment by Saulis** [comment]
:lgtm: 

---

Reviewed 9 of 12 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-:-KZ0alBSxpaGQQg-6D9y:bg7igkv)*

**Comment by manolo** [comment]
:lgtm:

---

Reviewed 9 of 12 files at r1, 2 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-:-KZ0avu0EouP5AkRDLcP:bnfp4nl)*

**Comment by tomivirkki** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[demo/selection.html, line 178 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1HwUP8b9v_Tw1HRNx:-KZ1HwUP8b9v_Tw1HRNy:b-xt7z2b) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/demo/selection.html#L178)):*
> ```HTML
>               },
> 
>               _isSelected: function(selectAll, selected) {
> ```

`selectAll` -> `inverted`
and below:
`this.inverted`-> `inverted`

---

*[docs/vaadin-grid-selection.adoc, line 10 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1p3k9AfUU7Xw3AvxP:-KZ1p3k9AfUU7Xw3AvxQ:b3p4y8g) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L10)):*
> ```AsciiDoc
> == Binding to the Selection State
> 
> [vaadinelement]#vaadin-grid# implements multi selection behavior by default.
> ```

This doesn't sound right

---

*[docs/vaadin-grid-selection.adoc, line 52 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q-4I6Qdp6F6ZOwDS:-KZ1q-4I6Qdp6F6ZOwDT:b-1rvsse) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L52)):*
> ```AsciiDoc
> image::img/vaadin-grid-selection-column.png[]
> 
> In addition, you can customize the selection column by changing its width, flex, frozen properties, or by providing your own templates.
> ```

property names

---

*[docs/vaadin-grid-selection.adoc, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q8uJRt05LfgMd8uX:-KZ1q8uJRt05LfgMd8uY:b-g1h47x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L88)):*
> ```AsciiDoc
> 
> [propertyname]#selectedItems#::
>   It's the property that represents the Array of currently selected items. You can either use `selectItem` or `deselectItem` to modify the list, or modify the array directly by using Polymer API.
> ```

- Drop "It's the".
- "...modify the list, or modify the array..." doesn't sound right. You're referring to the same array in both cases anyway.
- selectItem and deselectItems are methods.

---

*[docs/vaadin-grid-selection.adoc, line 100 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1tkI-J-GlpPM8hj8k:-KZ1tkI-J-GlpPM8hj8l:b-i1gqhw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L100)):*
> ```AsciiDoc
> ----
> 
> [[vaadin-grid.selection.model]]
> ```

"model"? I'm not following

---

*[docs/vaadin-grid-selection.adoc, line 105 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1IKltHAAWKCdrFQQ6:-KZ1IKltHAAWKCdrFQQ7:b-d2tiir) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L105)):*
> ```AsciiDoc
> In case you want to modify the default selection behavior, you can interact directly with the `selectedItems` array.
> 
> For instance in the next example, we enable a single selection mode by setting the `selectedItems` array with only the last modified item.
> ```

- Wouldn't call it "enabling single selection mode".
- selectedItems is a property name.

---

*[docs/vaadin-grid-selection.adoc, line 109 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1sV5azylFNPVsXrRk:-KZ1sV5azylFNPVsXrRl:b-cw6dqf) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L109)):*
> ```AsciiDoc
> [source,javascript]
> ----
> // Log the selections to console on select event.
> ```

This doesn't log anything

---

*[docs/vaadin-grid-selection.adoc, line 111 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1t2id42q_d6NcpSp8:-KZ1t2id42q_d6NcpSp9:b-ssthmd) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L111)):*
> ```AsciiDoc
> // Log the selections to console on select event.
> // Example output: "Selected: 3,5,6"
> <dom-module id="grid-single-selection">
> ```

The example doesn't actually work as it is.

---

*[docs/vaadin-grid-selection.adoc, line 121 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1rwfriH7rvrEVZGXD:-KZ1rwfriH7rvrEVZGXE:brosemw) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L121)):*
> ```AsciiDoc
>       <vaadin-grid-column width="40px" flex="0">
>         <template>
>           <input type="checkbox" on-change="_onSelectionChange" checked="{{selected}}"></input>
> ```

You don't need 2-way binding here since you're already listening to `change` event and modifying `selectedItems` on the listener.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[demo/selection.html, line 178 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1HwUP8b9v_Tw1HRNx:-KZ22QKv1Vq-5yq29tPk:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/demo/selection.html#L178)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

`selectAll` -> `inverted`
and below:
`this.inverted`-> `inverted`
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 10 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1p3k9AfUU7Xw3AvxP:-KZ28SrmOGJFrGuk2Bpu:b-sy1w63) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L10)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This doesn't sound right
</blockquote></details>

I don't have a better idea how to improve the phrase, maybe remove it?

---

*[docs/vaadin-grid-selection.adoc, line 52 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q-4I6Qdp6F6ZOwDS:-KZ2379XbC8t6TQJVq1X:bw6yh9p) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L52)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

property names
</blockquote></details>

you cannot change the name of properties. Though you can change property values, so I think the sentence is correct. Or don't I follow ? 

---

*[docs/vaadin-grid-selection.adoc, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q8uJRt05LfgMd8uX:-KZ25hV7QLSXAj4mMS1J:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L88)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

- Drop "It's the".
- "...modify the list, or modify the array..." doesn't sound right. You're referring to the same array in both cases anyway.
- selectItem and deselectItems are methods.
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 100 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1tkI-J-GlpPM8hj8k:-KZ28PGUMU4iYSBqNdb8:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L100)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

"model"? I'm not following
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 105 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1IKltHAAWKCdrFQQ6:-KZ26YazXLx5BpHQQaDP:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L105)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

- Wouldn't call it "enabling single selection mode".
- selectedItems is a property name.
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 109 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1sV5azylFNPVsXrRk:-KZ285qDKqBQLQrwW8US:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L109)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

This doesn't log anything
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 111 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1t2id42q_d6NcpSp8:-KZ287n8DUuJPFdcXcp-:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L111)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

The example doesn't actually work as it is.
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 121 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1rwfriH7rvrEVZGXD:-KZ28A8Rur5eQDyvNWoB:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L121)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

You don't need 2-way binding here since you're already listening to `change` event and modifying `selectedItems` on the listener.
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Comment by manolo** [comment]
Review status: 11 of 14 files reviewed at latest revision, 9 unresolved discussions.

---

*[docs/vaadin-grid-selection.adoc, line 10 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1p3k9AfUU7Xw3AvxP:-KZ5U0JlDW4vgs0Qc1vu:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L10)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

I don't have a better idea how to improve the phrase, maybe remove it?
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 52 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q-4I6Qdp6F6ZOwDS:-KZ5VL_yDZO2pR8dsnAv:blu7a3d) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L52)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

you cannot change the name of properties. Though you can change property values, so I think the sentence is correct. Or don't I follow ? 
</blockquote></details>

Ok, I think you meant to mark appropriately them with `[propertyname]#`. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Comment by tomivirkki** [comment]
Review status: 11 of 14 files reviewed at latest revision, 2 unresolved discussions.

---

*[docs/vaadin-grid-selection.adoc, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q8uJRt05LfgMd8uX:-KZ5XnSMGERVrolyHY5_:b-dmpvi1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L88)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Done
</blockquote></details>

[propertyname]

---

*[docs/vaadin-grid-selection.adoc, line 11 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ5X_64njxPwWW837HG:-KZ5X_64njxPwWW837HH:b-dmpvi1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa9d58730f21ff8ec269a56f8fe74a90614ed859/docs/vaadin-grid-selection.adoc#L11)):*
> ```AsciiDoc
> 
> By default, any number of items in the grid can be marked as selected, either programmatically or through the user interaction.
> The rows representing the selections are highlighted visually, and the selected items are bi-directionally bound to the `selectedItems` property of the grid.
> ```

[propertyname]

---

*[docs/vaadin-grid-selection.adoc, line 18 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ5XeYj9NGP0nzNB-DV:-KZ5XeYj9NGP0nzNB-DW:b-dmpvi1) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa9d58730f21ff8ec269a56f8fe74a90614ed859/docs/vaadin-grid-selection.adoc#L18)):*
> ```AsciiDoc
> == Binding to the Selection State
> 
> The Two-way binding `selected` property inside templates can be used to allow users to select rows.
> ```

[propertyname]

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Comment by manolo** [comment]
Review status: 11 of 15 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/vaadin-grid-selection.adoc, line 88 at r3](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ1q8uJRt05LfgMd8uX:-KZ5_Cw14p-hpsj9XWlm:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/a56bb4e72abe996c2f4b92cda552e4ffc37394a5/docs/vaadin-grid-selection.adoc#L88)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

[propertyname]
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 11 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ5X_64njxPwWW837HG:-KZ5_Gen0SSp1sJvK6XH:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa9d58730f21ff8ec269a56f8fe74a90614ed859/docs/vaadin-grid-selection.adoc#L11)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

[propertyname]
</blockquote></details>

Done

---

*[docs/vaadin-grid-selection.adoc, line 18 at r5](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-KZ5XeYj9NGP0nzNB-DV:-KZ5_ALuyz-5YFKfPinp:bb6un1j) ([raw file](https://github.com/vaadin/vaadin-grid/blob/aa9d58730f21ff8ec269a56f8fe74a90614ed859/docs/vaadin-grid-selection.adoc#L18)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

[propertyname]
</blockquote></details>

Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Comment by tomivirkki** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577#-:-KZ5a9YBLU4iFFWWimGs:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 1 of 2 files at r6.
Review status: 12 of 15 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Comment by manolo** [comment]
Reviewed 2 of 3 files at r5, 1 of 2 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/577)*

**Pull request merged**
