### PR TITLE
Remove asciidoc documentation

### LINKED ISSUE #754: Drop Asciidocs
- Make sure all the relevant information is included in `index.html` and Examples + API Docs.

- Add link to vaadin.com/docs for "2.0.0" to point to cdn.vaadin.com (or vaadin.com/elements)

- Add also a link to vaadin.com/docs to the migration guide

### PR DESCRIPTION
**Pull request by platosha**
Fixes #754

Related: vaadin/vaadin-docs#94

Related: vaadin/demo-data#1

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/787)

### CODE REVIEW

**Comment by limonte** [comment]
:lgtm:

Nice sorting/filtering examples for dataProvider :+1: 

---

Review status: 0 of 31 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-:-KeiISvhcGYnkcDZxR31:b6boq7w)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 8 of 8 files at r6, 1 of 1 files at r7, 18 of 18 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KeiO6JFlbnJ15BeeiDY:bigv0tg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
> ```HTML
>     </vaadin-grid>
> 
> See also the <a href="demo/styling.html" target="_blank">styling live examples</a>.
> ```

I wonder if these links work at webcomponents.org

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-:-KeiRFCCecCU2pcOUafO:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm: Needs rebasing

---

Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3, 8 of 8 files at r11, 1 of 1 files at r12, 18 of 18 files at r13.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-:-KelyQwfeJwfoD4nhvWj:b-9lao25)*

**Comment by manolo** [comment]
Rebased, waiting for CI

---

Reviewed 2 of 2 files at r15, 1 of 1 files at r16, 8 of 8 files at r19, 1 of 1 files at r20, 18 of 18 files at r21.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-:-Kelyqu7xL-xwqB6LbQJ:b-4iiwf5)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemECtyj18Lly8PmjkT:b-l0lkfx) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

I wonder if these links work at webcomponents.org
</blockquote></details>

Actually webcomponents.org seems broken with grid-2.0, but fixing should be accomplished in a separated PR

No demo working
https://www.webcomponents.org/preview/vaadin/vaadin-grid/cbc4f2f70a4a0f50dcd08c9cdd0cac2fb0948377/

No API working
https://www.webcomponents.org/preview/vaadin/vaadin-grid/cbc4f2f70a4a0f50dcd08c9cdd0cac2fb0948377/vaadin-grid

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by manolo** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemGIQ0BSiYBVO8eytb:b-jfbyes) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Actually webcomponents.org seems broken with grid-2.0, but fixing should be accomplished in a separated PR

No demo working
https://www.webcomponents.org/preview/vaadin/vaadin-grid/cbc4f2f70a4a0f50dcd08c9cdd0cac2fb0948377/

No API working
https://www.webcomponents.org/preview/vaadin/vaadin-grid/cbc4f2f70a4a0f50dcd08c9cdd0cac2fb0948377/vaadin-grid
</blockquote></details>

Added separated issue : https://github.com/vaadin/vaadin-grid/issues/791

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemHU1yFTdzBpQ6DQS9:b-s9a1y7) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Added separated issue : https://github.com/vaadin/vaadin-grid/issues/791
</blockquote></details>

But my question was about the links. And they don't seem to work https://www.webcomponents.org/preview/vaadin/vaadin-grid/9adfaa5d4bfe82444cbd850995f9a269469c5a33/vaadin-grid (There's a test link "styling live examples" at the top)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r22.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemIXvSVKDaAd-qU7l-:bg3o893) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

But my question was about the links. And they don't seem to work https://www.webcomponents.org/preview/vaadin/vaadin-grid/9adfaa5d4bfe82444cbd850995f9a269469c5a33/vaadin-grid (There's a test link "styling live examples" at the top)
</blockquote></details>

No, links in local with `polyserve` works different  in `webcomponents.org`

Local API:
http://127.0.0.1:8081/components/vaadin-grid/
Local DEMO:
http://127.0.0.1:8081/components/vaadin-grid/demo/selection.html

Webcomponents.org API:
https://www.webcomponents.org/element/vaadin/vaadin-grid/vaadin-grid/
Webcomponents.org DEMO:
https://www.webcomponents.org/element/vaadin/vaadin-grid/demo/demo/selection.html

I would fix this in a different PR, make those links absolute (maybe using cdn links) or just remove those links, and just say that there is a demo about that

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemL51Iapl_Xk7_v-MP:b-fuj1rp) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

No, links in local with `polyserve` works different  in `webcomponents.org`

Local API:
http://127.0.0.1:8081/components/vaadin-grid/
Local DEMO:
http://127.0.0.1:8081/components/vaadin-grid/demo/selection.html

Webcomponents.org API:
https://www.webcomponents.org/element/vaadin/vaadin-grid/vaadin-grid/
Webcomponents.org DEMO:
https://www.webcomponents.org/element/vaadin/vaadin-grid/demo/demo/selection.html

I would fix this in a different PR, make those links absolute (maybe using cdn links) or just remove those links, and just say that there is a demo about that

</blockquote></details>

Yes, that was my point. Since the links don’t work (in both cases), I would prefer not adding them at all. Why would we merge something that doesn't work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by tomivirkki** [comment]
*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemLdLgT1kqRepIulDV:b-mfd4lg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Yes, that was my point. Since the links don’t work (in both cases), I would prefer not adding them at all. Why would we merge something that doesn't work?
</blockquote></details>

Perhaps they will later fix how webcomponents.org demo links work and then we can add the links. Currently it just looks bad if we have broken links in the documentation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by platosha** [comment]
Review status: 29 of 30 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid.html, line 155 at r8](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787#-KeiO6JEa7nfgytu3ig2:-KemQOudKn8sn5K_EGcg:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/919db6520f12885c7cd3ea63346606fb13df3afa/vaadin-grid.html#L155)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Perhaps they will later fix how webcomponents.org demo links work and then we can add the links. Currently it just looks bad if we have broken links in the documentation.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r23.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/787)*

**Pull request merged**
