### PR TITLE
feat(cell-click-mixin): stop `click` events propagation

### LINKED ISSUE #797: Should not change Active Item when clicking on row details
Can be reproduced here: https://cdn.vaadin.com/vaadin-grid/2.0.0-alpha4/demo/row-details.html#expanding-items-without-data-binding

The mouse click on row details should not close the row details.
 
Actual result (left click on row details closing row details):

recorded

Expected result: click on row details does not close the row details

### PR DESCRIPTION
**Pull request by limonte**
Fixes #797

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1263)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[src/vaadin-grid.html, line 418 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263#-L8bOlo75DXCQRn5gNNa:-L8bOlo75DXCQRn5gNNb:b-halaev) ([raw file](https://github.com/vaadin/vaadin-grid/blob/010f0dd3655989b5b8781b8f5cca3d9d9867ccce/src/vaadin-grid.html#L418)):*
> ```HTML
>               this._a11ySetRowDetailsCell(row, detailsCell);
>               detailsCell._vacant = false;
>               detailsCell.addEventListener('click', e => e.stopPropagation()); // #797
> ```

It's kind of strange that clicks in other cells bubble a click event but not in details cells (might even be breaking for someone). Would be a cleaner fix to ignore click that originate from details cells in `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263)*

**Comment by tomivirkki** [comment]
*[src/vaadin-grid.html, line 418 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263#-L8bOlo75DXCQRn5gNNa:-L8bQce-3CxWqsW-b9jl:b-6h8jhg) ([raw file](https://github.com/vaadin/vaadin-grid/blob/010f0dd3655989b5b8781b8f5cca3d9d9867ccce/src/vaadin-grid.html#L418)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

It's kind of strange that clicks in other cells bubble a click event but not in details cells (might even be breaking for someone). Would be a cleaner fix to ignore click that originate from details cells in `
</blockquote></details>

Ok reviewable messed up my comment. But it was supposed to say `

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263)*

**Comment by limonte** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/vaadin-grid.html, line 418 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263#-L8bOlo75DXCQRn5gNNa:-L8bQh5ZBwyHL0_HzF4X:b32vin) ([raw file](https://github.com/vaadin/vaadin-grid/blob/010f0dd3655989b5b8781b8f5cca3d9d9867ccce/src/vaadin-grid.html#L418)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Ok reviewable messed up my comment. But it was supposed to say `
</blockquote></details>

:D

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263)*

**Comment by tomivirkki** [comment]
*[src/vaadin-grid.html, line 418 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263#-L8bOlo75DXCQRn5gNNa:-L8bQm7PDabXe3tvLQTQ:b3ya4m2) ([raw file](https://github.com/vaadin/vaadin-grid/blob/010f0dd3655989b5b8781b8f5cca3d9d9867ccce/src/vaadin-grid.html#L418)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

:D
</blockquote></details>

Haha, what's happening: vaadin-grid-cell-click-mixin.html

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-grid/1263)*

**Comment by tomivirkki** [comment]
Closed in favour of https://github.com/vaadin/vaadin-grid/pull/1276

**Pull request closed without merging**
