### PR TITLE
2.0 keyboard navigation editing

### LINKED ISSUE #601: Keyboard navigation - Cell Editing mode
- Make cell contents accessible by keyboard
- Visual feedback to differentiate navigation and editing mode
- Don't implement "optional" stuff from the wai aria practices
- Cell editing mode should activate also when tapping inside a cell
- User should be able to tab "over" the grid without going through all the cells
- Tabbing outside the currently focused cell to the next one should also move the focus to the next cell

After #487 and #600

### PR DESCRIPTION
**Pull request by Saulis**
Fixes #601

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/668)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Doesn't seem to work (hitting enter to interact) on FF & IE at least

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbFvc3WBsBeJ3xc19Lv:b-92e77t)*

**Comment by tomivirkki** [comment]
Ooh, I'll take that back (was probably testing a wrong branch). Works fine on FF. On IE I still can't focus the grid by clicking a body cell.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbJPmaqndJVfmm_GXz2:b-n2oshq)*

**Comment by manolo** [comment]
Reviewed 1 of 5 files at r1, 1 of 4 files at r2.
Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[package.json, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMKiI6gADYrm6bTZJ7:-KbMKiI6gADYrm6bTZJ8:b-9u4jg6) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/package.json#L34)):*
> ```JSON
>     "stylelint-config-vaadin": "github:vaadin/stylelint-config-vaadin",
>     "systemjs": "^0.19.27",
>     "wct-random-output": "^0.1.0",
> ```

This package needs a README in npm to explain what it does. I could figure out by reading the source, but other readers could not want to dive into them.

---

*[vaadin-grid-keyboard-navigation-behavior.html, line 426 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMZ4-L2O7Ey4Il9DOL:-KbMZ4-L2O7Ey4Il9DOM:bvnin7x) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/vaadin-grid-keyboard-navigation-behavior.html#L426)):*
> ```HTML
>     },
> 
>     _focusOnFocusTarget: function() {
> ```

This method name sounds very weird, at least the `On` part which suggest that there were a `focus-target` . I would suggest `_moveFocusToFocustarget`

---

*[vaadin-grid.html, line 82 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMHBAdNjEBeqfTuer5:-KbMHBAdNjEBeqfTuer6:b-2z363f) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/vaadin-grid.html#L82)):*
> ```HTML
> <kbd>Enter</kbd> or <kbd>F2</kbd> | Activates the interaction mode for the focused cell
> 
> #### in Interaction mode
> ```

Interaction is a noun, you should use an adjective with `mode`, so this should read `in Interactive move`

---

*[vaadin-grid.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMHTvWVJC3DJgcjCb2:-KbMHTvWVJC3DJgcjCb3:bxtfpye) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/vaadin-grid.html#L85)):*
> ```HTML
> Key | Action
> ----|--------
> <kbd>F2</kbd> or <kbd>ESC</kbd> | Deactivates the interaction mode
> ```

same here,  replace all 'interaction' occurrences with 'interactive'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668)*

**Comment by manolo** [comment]
It's not related with this PR, but to me it is odd that I have to click on the table and then push any arrow to make the cell take the focus. Any focusable element should take the focus on click, in the FW grid it happens in this way. Should we fix this behaviour ?.

---

Review status: 2 of 7 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbOEHXPcj7tlFaaeED6:b-gr9q0r)*

**Comment by Saulis** [comment]
@manolo the click focus behavior is intentional – we want to make the keyboard focus visible only after the user has actually used the keyboard.

---

Review status: 0 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[package.json, line 34 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMKiI6gADYrm6bTZJ7:-KbOi7IwOWUe9xgXV24M:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/package.json#L34)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This package needs a README in npm to explain what it does. I could figure out by reading the source, but other readers could not want to dive into them.
</blockquote></details>

Done.

---

*[vaadin-grid-keyboard-navigation-behavior.html, line 426 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMZ4-L2O7Ey4Il9DOL:-KbOiNySm-ZVaMfembit:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/vaadin-grid-keyboard-navigation-behavior.html#L426)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

This method name sounds very weird, at least the `On` part which suggest that there were a `focus-target` . I would suggest `_moveFocusToFocustarget`
</blockquote></details>

Done.

---

*[vaadin-grid.html, line 82 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMHBAdNjEBeqfTuer5:-KbOidYl14vTLWsu0mVF:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/vaadin-grid.html#L82)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

Interaction is a noun, you should use an adjective with `mode`, so this should read `in Interactive move`
</blockquote></details>

Done.

---

*[vaadin-grid.html, line 85 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-KbMHTvWVJC3DJgcjCb2:-KbOidvEFCauarE9qHJr:b-896fix) ([raw file](https://github.com/vaadin/vaadin-grid/blob/b7b9a68f9aea3e046869b1b66a814e362b4597e9/vaadin-grid.html#L85)):*
<details><summary><i>Previously, manolo (Manuel Carrasco Moñino) wrote…</i></summary><blockquote>

same here,  replace all 'interaction' occurrences with 'interactive'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbOj2v7_I9jj3zQQLst:bpjdnuz)*

**Comment by Saulis** [comment]
IE11 issue should be fixed now

---

Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbP0X8IGlRy1zapySgi:b-3qty8c)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 5 files at r1, 2 of 4 files at r2, 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbP20ct5gNN3moeWCdz:bnfp4nl)*

**Comment by manolo** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668#-:-KbPFgrZ7zbm-fVVbbD3:bg7igkv)*

**Comment by manolo** [comment]
Reviewed 2 of 5 files at r1, 2 of 4 files at r2, 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/668)*

**Pull request merged**
