### PR TITLE
Moving JSInterop namespace vaadin -> vaadin.components

### PR DESCRIPTION
**Pull request by manolo**
connects to #189

[Review on Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/202)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[java/src/main/java/com/vaadin/components/grid/data/GridDataSource.java, line 16 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202#-K0PpTvuhFCQAjqGoL4g)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a8b34bd5dc65c0198b3e219f25916a0fea188f12/java/src/main/java/com/vaadin/components/grid/data/GridDataSource.java#L16)):</sup>
Should it say _api?


---

<sup>**[tasks/gwt.js, line 101 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202#-K0Pq5nECqOwCHgJ1g95)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a8b34bd5dc65c0198b3e219f25916a0fea188f12/tasks/gwt.js#L101)):</sup>
How about commenting this out so it doesn't end up in the namespace but is still picked up by the Gulp script?


---

<sup>**[vaadin-grid.html, line 668 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202#-K0Pppvvda5mnlR74h4c)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a8b34bd5dc65c0198b3e219f25916a0fea188f12/vaadin-grid.html#L668)):</sup>
Is this intentionally here or by accident?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202)

**Comment by manolo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

<sup>**[java/src/main/java/com/vaadin/components/grid/data/GridDataSource.java, line 16 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202#-K0PpTvuhFCQAjqGoL4g)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a8b34bd5dc65c0198b3e219f25916a0fea188f12/java/src/main/java/com/vaadin/components/grid/data/GridDataSource.java#L16)):</sup>
done


---

<sup>**[tasks/gwt.js, line 101 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202#-K0Pq5nECqOwCHgJ1g95)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a8b34bd5dc65c0198b3e219f25916a0fea188f12/tasks/gwt.js#L101)):</sup>
done


---

<sup>**[vaadin-grid.html, line 668 \[r2\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202#-K0Pppvvda5mnlR74h4c)** ([raw file](https://github.com/vaadin/vaadin-grid/blob/a8b34bd5dc65c0198b3e219f25916a0fea188f12/vaadin-grid.html#L668)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202)

**Comment by Saulis** [comment]
Calling `grid.clearCache()` seems to fail because the object returned by `grid._grid.getDataSource()` does not seem to export `clearCache` or any of the other public functions...

From my Chrome console: 
```
grid._grid.getDataSource()
> xI {r: sv, f: sv, n: li, o: li, e: Rv…}
```

Patch could also be rebased on top of master to have the latest test fixes.


---

Review status: 0 of 12 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202)

**Comment by Saulis** [comment]
Reviewed 1 of 3 files at r1, 6 of 11 files at r2, 2 of 4 files at r3, 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/vaadin/vaadin-grid/202)

**Pull request merged**
