### PR TITLE
Column reordering styles aligned with visual design and docs added

### PR DESCRIPTION
**Pull request by jouni**
Connects to #181

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/421)

### CODE REVIEW

**Comment by jouni** [comment]
Since @magi42 is currently on vacation, we need to review the documentation internally in the @vaadin/vaadin-elements team.

**Comment by tehapo** [comment]
Reviewed 1 of 2 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/vaadin-grid-columns.adoc, line 168 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421#-KPSEXdanuka3qlC6zeb:-KPSEXdanuka3qlC6zec:b-7j209c) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d3b3622ec68da4c85a44e01a64c2b7671632355c/docs/vaadin-grid-columns.adoc#L168)):*
> ```AsciiDoc
> [[vaadin-grid.columns.reordering]]
> == Column Reordering
> Non-frozen columns can be reordered by the end users by dragging the header cells.
> ```

Repeating the word "by" twice looks like it could be reworded somehow. Perhaps something like:
"The end users can reorder non-frozen columns by dragging the header cells."

If you change this, remember to also do the same fix for `columns.html` file.

---

*[docs/vaadin-grid-columns.adoc, line 169 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421#-KPSE61nT_X1dDG43Rx_:-KPSE61oJRFd1B_CQOry:b-n3rvo4) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d3b3622ec68da4c85a44e01a64c2b7671632355c/docs/vaadin-grid-columns.adoc#L169)):*
> ```AsciiDoc
> == Column Reordering
> Non-frozen columns can be reordered by the end users by dragging the header cells.
> By default, column reordering is disabled, and can be enabled by setting the [propertyname]#columnReorderingAllowed# property to true.
> ```

Maybe the word "and" is here a bit weird. Would it be better to say:
"...reordering is disabled, *but* can be enabled..."

If you change this, remember to also do the same fix for `columns.html` file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421)*

**Comment by jouni** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docs/vaadin-grid-columns.adoc, line 168 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421#-KPSEXdanuka3qlC6zeb:-KPX8gdnSdK-Dr5KVkue:bjws3ei) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d3b3622ec68da4c85a44e01a64c2b7671632355c/docs/vaadin-grid-columns.adoc#L168)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> Repeating the word "by" twice looks like it could be reworded somehow. Perhaps something like:
> "The end users can reorder non-frozen columns by dragging the header cells."
> 
> If you change this, remember to also do the same fix for `columns.html` file.
</details>
Done. Much better, thanks!

---

*[docs/vaadin-grid-columns.adoc, line 169 \[r3\]](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421#-KPSE61nT_X1dDG43Rx_:-KPX8j2TwMjZJPHq1SJe:b-3a0wo3) ([raw file](https://github.com/vaadin/vaadin-grid/blob/d3b3622ec68da4c85a44e01a64c2b7671632355c/docs/vaadin-grid-columns.adoc#L169)):*
<details><summary><i>Previously, tehapo (Teemu Pöntelin) wrote…</i></summary>
> Maybe the word "and" is here a bit weird. Would it be better to say:
> "...reordering is disabled, *but* can be enabled..."
> 
> If you change this, remember to also do the same fix for `columns.html` file.
</details>
Updated also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421)*

**Comment by tehapo** [comment]
:lgtm:

---

Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421#-:-KPXPmJG_i20xRYUhwNJ:bnfp4nl)*

**Comment by tehapo** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421)*

**Comment by tehapo** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/421)*

**Pull request merged**
