### PR TITLE
Fix focus trap styling

### PR DESCRIPTION
**Pull request by Saulis**
Prevents Chrome from scrolling the footer trap to scroll top when tabbing into
it.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/835)

### CODE REVIEW

**Comment by tomivirkki** [comment]
*[vaadin-grid-table-focus-trap.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/835#-KgOkQHXL8IwArV6By7p:-KgOkQHXL8IwArV6By7q:b-syexot) ([raw file](https://github.com/vaadin/vaadin-grid/blob/271bf3d6f491c1a429cfc4c618816e54816787fc/vaadin-grid-table-focus-trap.html#L8)):*
> ```HTML
>      :host {
>        position: absolute;
>        z-index: 1;
> ```

Does this need to have `z-index: 1`? It makes the traps render on top of the header. `z-index: -3` seems to be enough to force the traps beneath the header.

Also, footer focus trap seems to overflow below the grid so you can click it (right below the bottom left corner of grid). Adding `top: 0`might fix that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/835)*

**Comment by Saulis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vaadin-grid-table-focus-trap.html, line 8 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/835#-KgOkQHXL8IwArV6By7p:-KgOqx36HzkvN7RREAs6:b4zax4z) ([raw file](https://github.com/vaadin/vaadin-grid/blob/271bf3d6f491c1a429cfc4c618816e54816787fc/vaadin-grid-table-focus-trap.html#L8)):*
<details><summary><i>Previously, tomivirkki (Tomi Virkki) wrote…</i></summary><blockquote>

Does this need to have `z-index: 1`? It makes the traps render on top of the header. `z-index: -3` seems to be enough to force the traps beneath the header.

Also, footer focus trap seems to overflow below the grid so you can click it (right below the bottom left corner of grid). Adding `top: 0`might fix that.
</blockquote></details>

Changed `z-index` to `-3`, added `bottom: 0` for the footer

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/835)*

**Comment by tomivirkki** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/835#-:-KgOuJMwuXg1Wtzln-H-:bnfp4nl)*

**Comment by tomivirkki** [comment]
Reviewed 9 of 9 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/835)*

**Pull request merged**
