### PR TITLE
Fix/update releases

### LINKED ISSUE #347: Grid does not compiles with latest vaadin & gwt
In order to debug and fix issues for the angular integration we need the grid compilation and debug fully working with latest vaadin & gwt.

### PR DESCRIPTION
**Pull request by manolo**
Fixes #347

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/348)

### CODE REVIEW

**Comment by tomivirkki** [comment]
Is there a reason we should upgrade Vaadin version and switch from using a fixed snapshot version of GWT to changing/unstable snapshot?

Why now and not only when we need the new Vaadin FW features and/or when GWT releases a stable version of 2.8?

**Comment by manolo** [comment]
Well, frozen version of gwt-user-2.8.0.VC-SNAPSHOT we were using in master does not compiles anymore.
I didn't want to investigate the reasons, and just went with 2.8.0-SNAPSHOT which does not have the issues that made us to freeze the version. 
Related with Vaadin I think it's better to be aligned with it as well.

I guess it's better to work with master components, and they should use latest versions, but it's just my opinion.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFE26DrWIWqPCCQN34Y:258406737)*

**Comment by tomivirkki** [comment]
Since we haven't updated any of our other dependencies, the current master version _should_ compile. The only snapshot we're depending on currently is gQuery so the problem must come from there. Should we instead freeze gQuery version?

I was kind of hoping to postpone Vaadin update until https://dev.vaadin.com/review/#/c/12091/ is merged so we could drop our fork of Escalator.java.

Since the Escalator.java changes of this PR are also in review at the FW PR above, reviewing it here is redundant effort and we at least shouldn't merge this until #12091 is merged in the core.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFE3fRZGU921aDbNQHG:116010410)*

**Comment by manolo** [comment]
Seems not a problem in gQuery:

[INFO] Compiling module com.vaadin.elements.grid.VaadinGrid
[INFO]    [ERROR] Errors in 'jar:file:/Users/manolo/.m2/repository/com/google/gwt/gwt-user/2.8.0.VC-SNAPSHOT/gwt-user-2.8.0.VC-SNAPSHOT.jar!/com/google/gwt/emul/java/lang/Double.java'
[INFO]       [ERROR] Line 207: The method getInfinity() is undefined for the type JsUtils
[INFO]       [ERROR] Line 207: The method getInfinity() is undefined for the type JsUtils

Could you try in your computer?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFE88EGM8JPRq4kSukB:172799058)*

**Comment by tomivirkki** [comment]
I get the same error message. I think JsUtils is in gQuery? 

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFEBLuxdraGFNekpaHn:-105798592)*

**Comment by tomivirkki** [comment]
Oh, that's probably not referring to the gQuery version of JsUtils. Then what can break our build if nothing in our dependencies has changed?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFECFmAk3ypvlI9FlWW:618794876)*

**Comment by manolo** [comment]
That seems not being gQuery's com.google.gwt.query.client.js.JsUtils but  com.google.gwt.dev.js.JsUtils

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFEEb669UpkrYaAcH1o:-1301910795)*

**Comment by manolo** [comment]
A bit of investigation reveals that the problem is in master we are using the new JsInterop mode syntax which is not working in the frozen version of gwt we are using in 1.0.0. 

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIUe9h2_zsVFugaHwM:-1877705901)*

**Comment by tomivirkki** [comment]
Hmm...it must have worked at some point. Otherwise it wouldn't have never been merged to master, right?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIVZIctRKm12BH2bXH:-1413115519)*

**Comment by manolo** [comment]
Removed vaadin modifications, now only gwt versions updates in this patch which makes the build work

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIWAIlXvhvNoxXPoih:322461895)*

**Comment by tomivirkki** [comment]
Thx, much easier to review now.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIWaazk1Jpwljysbfh:-1848270532)*

**Comment by manolo** [comment]
Yes it should work in some point, but since we are committing .min.js file it could be generated with different versions. I dont know

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIWX3W0s1usvjfzgnt:-1833698806)*

**Comment by tomivirkki** [comment]
Do you think depending on a snapshot in our master is better than just updating the frozen "2.8.0.VC-SNAPSOT" to most current one?

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIXVpWFZKsaWwfAO1D:-477408068)*

**Comment by manolo** [comment]
We have to create a new one version otherwise vaadin-grid-1.0.0 will not compile anymore

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFIktcH_ss7IgsUuZ6_:-1489469848)*

**Comment by tomivirkki** [comment]
So....do you think depending on a snapshot in our master is better than creating a new frozen vc-snapshot from most current gwt snapshot?

Consider a situation where the team is working on vaadin-grid and all of a sudden one morning the master doesn't work anymore. Everyone has to put their work on hold and wait for someone (in worst case the gwt compiler team) to fix the issue.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFNSETaD4sfOibRBDJR:-717380480)*

**Comment by manolo** [comment]
Well, creating a snapshot now, or any morning is the same effort. But yes, fixing that now so as we are prepared.

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFO1RTZW0q4JgfS8_v0:-320940458)*

**Comment by tomivirkki** [comment]
:lgtm: Please fix the patch "last java commit d0885e1c2c4beef2defa1bf192637bc834378771 does not match js version"

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348#-:-KFODPD1vPRbILUE5QW1:-642738015)*

**Comment by manolo** [comment]
Reviewed 1 of 1 files at r7.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348)*

**Comment by manolo** [comment]
Reviewed 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/348)*

**Pull request merged**
