### PR TITLE
Add stylelint for automatically CSS linting

### PR DESCRIPTION
**Pull request by limonte**
Related to: https://github.com/vaadin/vaadin-element-skeleton/issues/6

This PR is to be discussed. Since whole Elements team has a good sense for CSS code, there's a small number of caught errors which aren't so important. 

Probably CSS linter is an overhead, probably not.
I'd like to hear any feedback.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/612)

### CODE REVIEW

**Comment by manolo** [comment]
I'm ok having this linter here :+1:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/612#-:-K_0OT_VRZzr6qSIl9_r:b-dn17zl)*

**Comment by jouni** [comment]
+1 from me as well. What’s the overhead here? Having to fix your code again before it’s merged? Slower build?

**Comment by limonte** [comment]
> What’s the overhead here?

Maybe "overhead" isn't the right term here. What I meant is that we'll have another one dev-dependency and each dependency should be maintained. 

---

Also, I created [stylelint-config-vaadin](https://github.com/vaadin/stylelint-config-vaadin), now there's no need to copy-paste all rules to each component and `.stylelintrc` looks as simple as:

```js
{
  "extends": "stylelint-config-vaadin"
}
```

**Comment by platosha** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/612#-:-K_dqkJ2WcV3E6ck98rf:bnfp4nl)*

**Pull request merged**
