### PR TITLE
Add issue template

### LINKED ISSUE #1086: Add an issue template
I think adding an issue template that has a ready to go jsbin/fiddle would be excellent.

Something like Polymer's: https://github.com/Polymer/polymer/blob/master/.github/ISSUE_TEMPLATE.md

with the baseUrl switched to 
```html
<base href="https://polygit.org/polymer+:master/webcomponents+:master/shadycss+webcomponents+:master/vaadin*+vaadin+:master/components/">
```

then referencing Vaadin components is just `vaadin-grid/vaadin-grid.html`

### PR DESCRIPTION
**Pull request by web-padawan**
Fixes #1086

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-grid/1118)

### CODE REVIEW

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ISSUE_TEMPLATE.md, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118#-KzTLGbSWHNUooPb4lND:-KzTLGbTniDPs-xg1YcX:bqbhlkk) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ba7dad4040fc45bb565bc571132561f8eb63a612/ISSUE_TEMPLATE.md#L11)):*
> ```Markdown
> 
> ### Live Demo
> 
> ```

Caret dependencies simply do not work this way in Polygit. It ends up taking a fixed version number anyway.

See: https://polygit.org/vaadin-grid+vaadin+%5E4.0.0/iron-ajax+:master/components/vaadin-grid/package.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118)*

**Comment by limonte** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ISSUE_TEMPLATE.md, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118#-KzTLGbSWHNUooPb4lND:-KzTM6rdeZpgDEfchDuG:byy7i45) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ba7dad4040fc45bb565bc571132561f8eb63a612/ISSUE_TEMPLATE.md#L11)):*
<details><summary><i>Previously, platosha (Anton Platonov) wrote…</i></summary><blockquote>

Caret dependencies simply do not work this way in Polygit. It ends up taking a fixed version number anyway.

See: https://polygit.org/vaadin-grid+vaadin+%5E4.0.0/iron-ajax+:master/components/vaadin-grid/package.json
</blockquote></details>

It works just perfectly:

- https://polygit.org/vaadin-grid+vaadin+%5E3.0.0/iron-ajax+:master/components/vaadin-grid/package.json
- https://polygit.org/vaadin-grid+vaadin+3.0.0/iron-ajax+:master/components/vaadin-grid/package.json

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118)*

**Comment by platosha** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ISSUE_TEMPLATE.md, line 11 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118#-KzTLGbSWHNUooPb4lND:-KzTaXx-9E2uHMGO1lC5:bc994lr) ([raw file](https://github.com/vaadin/vaadin-grid/blob/ba7dad4040fc45bb565bc571132561f8eb63a612/ISSUE_TEMPLATE.md#L11)):*
<details><summary><i>Previously, limonte (Limon Monte) wrote…</i></summary><blockquote>

It works just perfectly:

- https://polygit.org/vaadin-grid+vaadin+%5E3.0.0/iron-ajax+:master/components/vaadin-grid/package.json
- https://polygit.org/vaadin-grid+vaadin+3.0.0/iron-ajax+:master/components/vaadin-grid/package.json
</blockquote></details>

Wow, Right. I was wrong.

Sorry, false alarm!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118)*

**Comment by platosha** [comment]
Maybe add `[skip ci]` to the commit title, so that we don’t run the build for this branch/PR. Nothing to test here anyway.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118#-:-KzTaw1fv6VGL2F2zqCM:bk42394)*

**Comment by web-padawan** [comment]
Rebased and added `[skip ci]`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118#-:-KzTdJwFXOGqdVgcS0X4:b2zacch)*

**Comment by limonte** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-grid/1118#-:-KzTdiOcnc3iBmill9hV:bnfp4nl)*

**Pull request merged**
